"""Chase credit card catalog — captured from creditcards.chase.com (2026-09-22 snapshot).

Each entry mirrors the all-credit-cards listing plus the card detail pages
(offer, at-a-glance, APR, annual fee, earning categories, benefits).
Generated from the build-time scrape; committed so the seed is reproducible.
"""

CARDS = [
    {
        'slug': "freedom-flex",
        'name': "Chase Freedom Flex® Credit Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["cash-back", "no-annual-fee", "intro-apr"],
        'offer': "Earn a $200 Strike through $250 bonus Earn a $250 bonus after you spend $500 on purchases in the first 3 months from account opening.",
        'glance': "Earn cash back for every purchase. Earn 5% cash back on up to $1,500 on combined purchases in bonus categories each quarter you activate. Plus, earn 5% cash back on travel purchased through Chase TravelSM, 3% on dining and drugstores, and 1% on all other purchases.",
        'apr': "0% intro APR for 15 months from account opening on purchases and balance transfers.† After the intro period, a variable APR of 18.24%–27.74%.† Balance transfer fee applies, see pricing and terms for more details.†",
        'intro_apr': "0% intro APR for 15 months from account opening on purchases and balance transfers.",
        'fee_text': "$0†",
        'fee_value': 0,
        'card_art': "cards/freedom_flex_card.png",
        'pt_code': "LGC65280",
        'earn_rewards': ["Earn 5% cash back on up to $1,500 on combined purchases in bonus categories each quarter you activate.", "Earn 5% cash back on travel purchased through Chase Travel.", "Earn 3% cash back on dining at restaurants, including takeout and eligible delivery services.", "Earn 3% cash back on drugstore purchases.", "Earn 1% cash back on all other purchases."],
        'benefits': ["No foreign transaction fees", "Cash back rewards do not expire as long as your account is open", "Chase Offers", "Chase Pay Over Time"],
        'stat_value': "$250",
        'stat_label': "bonus offer*",
    },
    {
        'slug': "freedom-unlimited",
        'name': "Chase Freedom Unlimited® Credit Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["cash-back", "no-annual-fee", "intro-apr"],
        'offer': "Earn a $200 bonus Earn a $200 bonus after you spend $500 on purchases in the first 3 months from account opening.",
        'glance': "Unlimited 1.5% cash back is just the beginning. Earn unlimited 1.5% cash back or more on all purchases, like 3% on dining and drugstores and 5% on travel purchased through Chase TravelSM.",
        'apr': "0% intro APR for 15 months from account opening on purchases and balance transfers.† After the intro period, a variable APR of 18.24%–27.74%.† Balance transfer fee applies, see pricing and terms for more details.†",
        'intro_apr': "0% intro APR for 15 months from account opening on purchases and balance transfers.",
        'fee_text': "$0†",
        'fee_value': 0,
        'card_art': "cards/freedom_unlimited_card_alt.png",
        'pt_code': "LGC61498",
        'earn_rewards': ["Earn 5% cash back on travel purchased through Chase Travel.", "Earn 3% on dining at restaurants, including takeout and eligible delivery services.", "Earn 3% on drugstore purchases.", "Earn unlimited 1.5% cash back on all other purchases."],
        'benefits': ["Cash back rewards do not expire as long as your account is open", "Chase Offers", "Chase Pay Over Time"],
        'stat_value': "$200",
        'stat_label': "bonus offer*",
    },
    {
        'slug': "freedom-rise",
        'name': "Chase Freedom Rise® Credit Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["cash-back", "no-annual-fee"],
        'offer': "Establish Credit and earn 1.5% cash back on all purchases",
        'glance': "Best for New to Credit & Students Having at least $250 in Chase checking or savings accounts increases your chances of being approved.",
        'apr': "18.24%–27.74% variable APR.†",
        'intro_apr': "",
        'fee_text': "$0†",
        'fee_value': 0,
        'card_art': "cards/freedom_rise_alt_card2.png",
        'pt_code': "LGC65397",
        'earn_rewards': ["Earn 1.5% cash back on all purchases.", "Earn a $25 statement credit when you sign up for automatic payments within the first three months of opening your account and remain enrolled for at least 90 days.", "Cash Back rewards do not expire as long as your account is open, and there is no minimum to redeem for cash back."],
        'benefits': ["Automatically evaluated each year to upgrade to Chase Freedom Unlimited", "Chase Credit Journey credit building tool", "Chase Offers"],
        'stat_value': "1.5%",
        'stat_label': "cash back*",
    },
    {
        'slug': "sapphire-preferred",
        'name': "Chase Sapphire Preferred® Credit Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["rewards"],
        'offer': "Earn 75,000 points after you spend $5,000 on purchases in the first 3 months from account opening.",
        'glance': "Earn 5x points on Chase TravelSM purchases and 2x points on all other travel.",
        'apr': "19.24%–27.49% variable APR.†",
        'intro_apr': "",
        'fee_text': "$95 annual fee†",
        'fee_value': 95,
        'card_art': "cards/sapphire-preferredcard2026.png",
        'pt_code': "LGC65222",
        'earn_rewards': ["Earn 5x points on Chase Travel.", "Earn 3x points on dining.", "Earn 3x points on gas stations, EV charging, and vacation homes at top brands.", "Earn 3x points on top streaming services and online grocery, exclusions apply.", "Earn 2x points on all other travel, and 1x points on all other purchases."],
        'benefits': ["$100 Chase Travel Hotel Credit each account anniversary year", "Global Entry or TSA PreCheck or NEXUS application fee credit of up to $120 every four years", "A year of complimentary Apple TV when activated by December 31, 2026", "Complimentary DashPass membership for 12 months when activated by 12/31/27", "Trip cancellation/interruption insurance", "Purchase protection", "No foreign transaction fees"],
        'stat_value': "75,000",
        'stat_label': "points bonus*",
    },
    {
        'slug': "sapphire-reserve",
        'name': "Chase Sapphire Reserve® Credit Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["rewards"],
        'offer': "Earn 100,000 points after you spend $6,000 on purchases in the first 3 months from account opening.",
        'glance': "Access $5,000+ in value the first year. Plus, earn 8x points on Chase Travel purchases and 4x points on flights and hotels booked direct.",
        'apr': "19.49%–27.99% variable APR.†",
        'intro_apr': "",
        'fee_text': "$795 annual fee†  ; $195 for each authorized user†",
        'fee_value': 795,
        'card_art': "cards/sapphire_reserve_card_Halo.png",
        'pt_code': "LGC64842",
        'earn_rewards': ["Earn 8x points on Chase Travel purchases.", "Earn 4x points on flights, hotel stays, car rentals, cruises and other qualifying travel purchased through Chase Travel after earning the annual $300 travel credit.", "Earn 8x points on concerts, sporting events and other eligible Chase Live events.", "Earn 4x points on dining worldwide, including takeout and eligible delivery services.", "Earn 3x points on phone plans and select streaming services.", "Earn 1x points on all other purchases."],
        'benefits': ["$300 annual travel credit", "$120 in Lyft credits plus 5x points on Lyft rides", "$120 in Peloton credits plus 10x points on Peloton bikes and accessories", "Priority Pass, Delta Sky Club and Chase Sapphire Lounge access", "Trip cancellation/interruption insurance", "Primary car rental insurance", "No foreign transaction fees"],
        'stat_value': "100,000",
        'stat_label': "points bonus*",
    },
    {
        'slug': "slate",
        'name': "Slate® Credit Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["balance-transfer", "no-annual-fee", "intro-apr"],
        'offer': "Save on interest with a low intro APR for 21 months Enjoy a low intro APR on purchases and balance transfers for 21 months from account opening.†",
        'glance': "Zero Liability Protection Zero Liability Protection means you won't be held responsible for unauthorized charges made with your card. If you see an unauthorized charge, simply call the number on the back of your card.",
        'apr': "for 21 months Enjoy a low intro APR on purchases and balance transfers for 21 months from account opening.† AT A GLANCE Zero Liability Protection Zero Liability Protection means you won't be held responsible for unauthorized charges made with your card. If you see an unauthorized charge, simply call the number on the back of your card. APR 0% intro APR for 21 months from account opening on purchases and balance transfers.† After the intro period, a variable APR of 18.24% to 28.24%.† Balance transfer fee applies, see pricing and terms for more details.",
        'intro_apr': "0% intro APR for 21 months from account opening on purchases and balance transfers.",
        'fee_text': "$0.†",
        'fee_value': 0,
        'card_art': "cards/slate_dagger_card.png",
        'pt_code': "LGC63300",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "",
        'stat_label': "",
    },
    {
        'slug': "slate-edge",
        'name': "Slate Edge® Credit Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["credit-building", "no-annual-fee"],
        'offer': "",
        'glance': "Get the credit you need with Slate Edge®.",
        'apr': "28.99% variable APR.†",
        'intro_apr': "",
        'fee_text': "$0.†",
        'fee_value': 0,
        'card_art': "cards/slate_edge_card_alt.png",
        'pt_code': "LGC64148",
        'earn_rewards': ["No rewards program; built for paying down balances and building credit.", "0% intro APR on balance transfers for 12 months from account opening.", "Automatically evaluated for a credit line increase every 6 months or sooner."],
        'benefits': ["No annual fee", "Chase Credit Journey with personalized plans from Experian", "Zero Liability Protection", "Automatic credit line increase reviews every 6 months"],
        'stat_value': "",
        'stat_label': "",
    },
    {
        'slug': "united-explorer",
        'name': "UnitedSM Explorer Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["travel", "no-annual-fee", "airline"],
        'offer': "Earn up to 60,000 bonus miles after qualifying activities.",
        'glance': "Free first checked bag, 2 United ClubSM one-time passes per year, priority boarding and over $500 in annual partner credits.",
        'apr': "19.74%–28.24% variable APR.†",
        'intro_apr': "",
        'fee_text': "$0 intro annual fee for the first year, then $150†",
        'fee_value': 0,
        'card_art': "cards/united_explorer_card.png",
        'pt_code': "LGC62176",
        'earn_rewards': ["Earn 9x total miles on eligible United flights (6x miles on the Primary Cardmember's fare as a MileagePlus member, plus 3x miles on the entire United purchase).", "Earn 3x miles on all other eligible United purchases.", "Earn 2x miles on hotel stays when booked with the hotel.", "Earn 2x miles on dining including eligible delivery services.", "Earn 1x mile on all other purchases."],
        'benefits': ["Free first and second checked bags for the primary Cardmember and one companion", "Two United Club one-time passes after account opening and each anniversary", "25% back on United in-flight purchases"],
        'stat_value': "60,000",
        'stat_label': "miles bonus*",
    },
    {
        'slug': "united-quest",
        'name': "United QuestSM Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["travel", "airline"],
        'offer': "Earn up to 70,000 bonus miles + 500 Premier qualifying points (PQP) after qualifying activities.",
        'glance': "$200 United travel credit, annual 10,000-mile award flight discount, 2 free checked bags, and priority boarding.",
        'apr': "19.74%–28.24% variable APR.†",
        'intro_apr': "",
        'fee_text': "$350†",
        'fee_value': 350,
        'card_art': "cards/united_quest_card.png",
        'pt_code': "LGC62257",
        'earn_rewards': ["Earn 10x total miles on eligible United flights (6x miles on the Primary Cardmember's fare as a MileagePlus member, plus 4x miles on the entire United purchase).", "Earn 4x miles on all other eligible United purchases.", "Earn 5x miles on hotel stays when you prepay directly through Renowned Hotels and Resorts for United Cardmembers.", "Earn 2x miles on all other travel including airfare, trains, local transit, cruise lines, hotels, car rentals, taxicabs, resorts, ride share services and tolls.", "Earn 2x miles on dining including eligible delivery services.", "Earn 2x miles on select streaming services.", "Earn 1x mile on all other purchases."],
        'benefits': ["Free first and second checked bags for the primary Cardmember and one companion", "$100 United travel credit each year", "Earn 2 global Economy Plus seat upgrades after spending $40,000 each calendar year", "10,000-mile award flight discount each anniversary"],
        'stat_value': "70,000",
        'stat_label': "miles bonus*",
    },
    {
        'slug': "united-gateway",
        'name': "United GatewaySM Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["travel", "no-annual-fee", "intro-apr", "airline"],
        'offer': "Earn up to 40,000 bonus miles after qualifying activities.",
        'glance': "Earn 2 checked bags each year, receive 25% back on United inflight and Club premium drink purchases, and earn unlimited miles with no annual fee.†",
        'apr': "0% intro APR for 12 months from account opening on purchases.† After the intro period, a variable APR of 19.74%–28.24%,† see pricing and terms for more details.†",
        'intro_apr': "0% intro APR for 12 months from account opening on purchases.",
        'fee_text': "$0†",
        'fee_value': 0,
        'card_art': "cards/unitedgateway-ribbon2026.png",
        'pt_code': "LGC60660",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "40,000",
        'stat_label': "miles bonus*",
    },
    {
        'slug': "united-club-infinite",
        'name': "United ClubSM Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["travel", "airline"],
        'offer': "Earn up to 90,000 bonus miles after qualifying activities.",
        'glance': "United ClubSM access, 2 free checked bags, Premier Access travel services, and over $875 in annual partner credits.",
        'apr': "19.74%–28.24% variable APR.†",
        'intro_apr': "",
        'fee_text': "$695†",
        'fee_value': 695,
        'card_art': "cards/united_club_infinite_card.png",
        'pt_code': "LGC64324",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "90,000",
        'stat_label': "miles bonus*",
    },
    {
        'slug': "southwest-plus",
        'name': "Southwest Rapid Rewards® Plus Credit Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["travel"],
        'offer': "Earn 50,000 bonus points after you spend $1,000 on purchases in the first 3 months from account opening.",
        'glance': "First checked bag free. 3,000 anniversary points each year. Plus, earn 2X points on Southwest Airlines® purchases.",
        'apr': "19.24%–27.74% variable APR.† Opens pricing and terms in new window",
        'intro_apr': "",
        'fee_text': "$99 applied to first billing statement.†",
        'fee_value': 99,
        'card_art': "cards/swa_plus_card_New.png",
        'pt_code': "LGC63968",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "50,000",
        'stat_label': "points bonus*",
    },
    {
        'slug': "southwest-priority",
        'name': "Southwest Rapid Rewards® Priority Credit Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["travel"],
        'offer': "Earn 60,000 bonus points after you spend $2,000 on purchases in the first 3 months from account opening.",
        'glance': "First checked bag free. 7,500 anniversary points each year. Plus, earn 4X points on Southwest Airlines® purchases and 2X points at gas stations and restaurants.",
        'apr': "19.24%–27.74% variable APR.†",
        'intro_apr': "",
        'fee_text': "$229 applied to first billing statement.†",
        'fee_value': 229,
        'card_art': "cards/swa_priority_card-2.png",
        'pt_code': "LGC64006",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "60,000",
        'stat_label': "points bonus*",
    },
    {
        'slug': "southwest-premier",
        'name': "Southwest Rapid Rewards® Premier Credit Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["travel"],
        'offer': "Earn 55,000 bonus points after you spend $1,500 on purchases in the first 3 months from account opening",
        'glance': "First checked bag free. 6,000 anniversary points each year. Plus, earn 3X points on Southwest Airlines® purchases.",
        'apr': "19.24%–27.74% variable APR.†",
        'intro_apr': "",
        'fee_text': "$149 applied to first billing statement.†",
        'fee_value': 149,
        'card_art': "cards/swa_premier_card.png",
        'pt_code': "LGC63993",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "55,000",
        'stat_label': "points bonus*",
    },
    {
        'slug': "marriott-bonvoy-boundless",
        'name': "Marriott Bonvoy Boundless® Credit Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["travel", "hotel"],
        'offer': "Earn 3 Free Night Awards Earn 3 Free Night Awards after spending $3,000 on eligible purchases within 3 months of account opening with the Marriott Bonvoy Boundless® Credit Card. Redeem your Free Night Awards for a one-night stay at properties with a redemption level up to 50,000 points per night. Certain hotels have resort fees. Special Offer through 6/30/2027: Get up to $100 in statement credits after spending $500 on eligible airline purchases. That's $50 in statement credits semi-annually.",
        'glance': "Earn up to 17X total points per $1 spent at hotels participating in Marriott Bonvoy®. Enjoy a Free Night Award each account anniversary, automatic Silver Elite Status, and 15 Elite Night Credits towards the next level of Marriott Bonvoy® Elite Status.",
        'apr': "19.24%–27.74% variable APR.†",
        'intro_apr': "",
        'fee_text': "$95†",
        'fee_value': 95,
        'card_art': "cards/marriott-bonvoy-boundless-card.png",
        'pt_code': "LGC65195",
        'earn_rewards': ["Earn 6x points for every $1 spent at over 7,000 hotels participating in Marriott Bonvoy, plus up to 10x points from Marriott Bonvoy for being a member, and up to 1x point with Silver Elite Status.", "Earn 3x points for every $1 on the first $6,000 spent in combined purchases annually on grocery stores, gas stations, and dining.", "Earn 2x points for every $1 you spend on all other purchases; points don't expire as long as you make purchases every 24 months.", "Earn a Free Night Award every year after your account anniversary, valid at properties with a redemption level up to 35,000 points."],
        'benefits': ["Automatic Silver Elite Status each calendar year", "15 Elite Night Credits each calendar year", "Path to Gold Status when you spend $35,000 on purchases each calendar year", "No foreign transaction fees"],
        'stat_value': "3",
        'stat_label': "free night awards bonus*",
    },
    {
        'slug': "marriott-bonvoy-bountiful",
        'name': "Marriott Bonvoy Bountiful® Credit Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["travel", "hotel"],
        'offer': "85,000 Bonus Points Earn 85,000 Bonus Points after you spend $4,000 in purchases in your first 3 months from your account opening.",
        'glance': "Earn Unlimited Marriott Bonvoy® points and get free stays faster. Earn points on every purchase and up to 18.5X total points per $1 spent at hotels participating in Marriott Bonvoy®.",
        'apr': "19.24%–27.74% variable APR.†",
        'intro_apr': "",
        'fee_text': "$250†",
        'fee_value': 250,
        'card_art': "cards/marriott_bonvoy_bountiful_card.png",
        'pt_code': "LGC61472",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "18.5x",
        'stat_label': "points*",
    },
    {
        'slug': "marriott-bonvoy-bold",
        'name': "Marriott Bonvoy Bold® Credit Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["travel", "no-annual-fee", "hotel"],
        'offer': "45,000 Bonus Points Earn 45,000 Bonus Points after spending $1,000 on eligible purchases within 3 months of account opening with the Marriott Bonvoy Bold® Credit Card.",
        'glance': "Earn up to 14X total points per $1 spent at hotels participating in Marriott Bonvoy®. Enjoy automatic Silver Elite Status and 5 Elite Night Credits towards the next level of Marriott Bonvoy® Elite Status. You can also redeem your Marriott Bonvoy® points for a statement credit to cover qualifying travel purchases.",
        'apr': "19.24%–27.74% variable APR.†",
        'intro_apr': "",
        'fee_text': "$0†",
        'fee_value': 0,
        'card_art': "cards/marriott_bonvoy_bold_card_NAF.png",
        'pt_code': "LGC65105",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "14x",
        'stat_label': "points*",
    },
    {
        'slug': "ihg-one-premier",
        'name': "IHG One Rewards Premier Credit Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["travel", "hotel"],
        'offer': "Earn 140,000 Bonus Points after you spend $3,000 on purchases in the first 3 months from account opening.",
        'glance': "Earn IHG One Rewards points on every purchase. Up to 26X points total per $1 spent when you stay at IHG® Hotels and Resorts.",
        'apr': "19.24%–27.74% variable APR.† Opens pricing and terms in new window",
        'intro_apr': "",
        'fee_text': "$99†",
        'fee_value': 99,
        'card_art': "cards/ihg_premier_card.png",
        'pt_code': "LGC60778",
        'earn_rewards': ["Earn up to 26x total points at IHG Hotels and Resorts: 10x points with this card, up to 10x points from IHG for being an IHG One Rewards member, and up to 6x points with Platinum Elite Status.", "Earn 5x total points on travel, dining, and at gas stations.", "Earn 3x points per $1 spent on all other purchases.", "Earn an Anniversary Free Night each account anniversary year with a current point redemption cap of 40,000 points."],
        'benefits': ["Automatic Platinum Elite Status as long as you remain a cardmember", "$100 statement credit and 10,000 bonus points after spending $20,000 each calendar year", "No foreign transaction fees"],
        'stat_value': "26x",
        'stat_label': "points*",
    },
    {
        'slug': "ihg-one-traveler",
        'name': "IHG One Rewards Traveler Credit Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["travel", "no-annual-fee", "hotel"],
        'offer': "Earn 80,000 Bonus Points after you spend $2,000 on purchases in the first 3 months from account opening.",
        'glance': "Earn IHG One Rewards points on every purchase. Up to 17X points total per $1 spent when you stay at IHG® Hotels and Resorts.",
        'apr': "19.24%–27.74% variable APR.† Opens pricing and terms in new window",
        'intro_apr': "",
        'fee_text': "$0†",
        'fee_value': 0,
        'card_art': "cards/ihg-traveler-card.png",
        'pt_code': "LGC62162",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "17x",
        'stat_label': "points*",
    },
    {
        'slug': "world-of-hyatt",
        'name': "World of Hyatt Credit Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["travel", "hotel"],
        'offer': "Earn up to 60,000 Bonus Points after qualifying purchases",
        'glance': "Turn purchases into free nights by earning up to 9X total points per $1 at Hyatt hotels and resorts. Plus, get 1 free night and 5 tier qualifying nights credits toward status each year just for being a cardmember.",
        'apr': "19.24%–27.74% variable APR.† Opens pricing and terms in new window",
        'intro_apr': "",
        'fee_text': "$95.†",
        'fee_value': 95,
        'card_art': "cards/world_of_hyatt_card.png",
        'pt_code': "LGC61032",
        'earn_rewards': ["Earn 4 Bonus Points per $1 spent on qualifying purchases at Hyatt Hotels, plus up to 5 Base Points from Hyatt per eligible $1 spent as a World of Hyatt member (up to 9 total points per $1).", "Earn unlimited 2x Bonus Points per $1 spent at restaurants, on airline tickets purchased directly from airlines, on local transit and commuting, and on fitness club and gym memberships.", "Earn 1 Bonus Point per $1 spent on all other purchases; points don't expire as long as your account is open."],
        'benefits': ["Automatic Discoverist status for as long as your account is open", "Up to 10x total points at Hyatt hotels", "No foreign transaction fees"],
        'stat_value': "9x",
        'stat_label': "points*",
    },
    {
        'slug': "disney-inspire",
        'name': "Disney® Inspire Visa® Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["rewards"],
        'offer': "$500 Offer Get a $300 Disney Gift Card eGift to use today upon approval + earn a $200 statement credit after you spend $1,000 on purchases in the first 3 months from account opening.",
        'glance': "Elevate your Disney experience. Introducing the NEW Disney Inspire Visa Card. Earn 10% in Disney Rewards Dollars on purchases made directly at DisneyPlus.com, Hulu.com or Stream.ESPN.com, 3% on card purchases at gas stations and most other U.S Disney locations, 2% on card purchases at grocery stores and restaurants, and 1% on all other card purchases. Enjoy 10% merchandise and dining savings at select Disney locations and 0% promo",
        'apr': "on select Disney vacation packages. APR 18.24%–27.74% variable APR.† 0% promotional APR for 6 months on select Disney vacation packages from the date of purchase, after that a variable APR of 18.24%–27.74%.†",
        'intro_apr': "",
        'fee_text': "$149†",
        'fee_value': 149,
        'card_art': "cards/disney-inspire.png",
        'pt_code': "LGC64083",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "$200",
        'stat_label': "bonus offer*",
    },
    {
        'slug': "disney-premier",
        'name': "Disney® Premier Visa® Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["rewards"],
        'offer': "$300 Offer Get a $200 Disney Gift Card eGift to use today upon approval + earn a $100 statement credit after you spend $500 on purchases in the first 3 months from account opening.",
        'glance': "Dream bigger with the Disney Premier Visa Card from Chase. Earn 5% in Disney Rewards Dollars on purchases made directly at DisneyPlus.com, Hulu.com or Stream.ESPN.com. Earn 2% on select card purchases and 1% on all other card purchases. Redeem toward most anything Disney at most Disney U.S. locations and for a statement credit toward airline purchases. Enjoy special Disney vacation financing and Disney shopping savings. Terms apply.",
        'apr': "18.24%–27.74% variable APR.† 0% promotional APR for 6 months on select Disney vacation packages from the date of purchase, after that a variable APR of 18.24%–27.74%.†",
        'intro_apr': "",
        'fee_text': "$49†",
        'fee_value': 49,
        'card_art': "cards/disney_sleeping_beauty_premier_vs_Jan_2026.png",
        'pt_code': "LGC63172",
        'earn_rewards': ["Earn 5% on card purchases made directly at DisneyPlus.com, Hulu.com or Stream.ESPN.com.", "Earn 2% on card purchases at gas stations and most Disney U.S. locations.", "Earn 2% on card purchases at grocery stores and restaurants.", "Earn 1% on all other card purchases.", "Save 10% on select purchases at DisneyStore.com and select merchandise and dining locations at the Disneyland Resort and Walt Disney World Resort."],
        'benefits': ["$200 Disney Gift Card eGift upon approval plus a $100 statement credit after you spend $500 in the first 3 months", "0% promotional APR for 6 months on select Disney vacation packages", "Choose from more than a dozen Disney card designs"],
        'stat_value': "$100",
        'stat_label': "bonus offer*",
    },
    {
        'slug': "disney-rewards",
        'name': "Disney® Visa® Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["rewards", "no-annual-fee"],
        'offer': "$150 Offer Get a $100 Disney Gift Card eGift to use today upon approval + earn a $50 statement credit after you spend $500 on purchases in the first 3 months from account opening.",
        'glance': "Reward yourself with the Disney Visa Card from Chase. Redeem Disney Rewards Dollars toward your favorite Disney experiences such as Disney Theme Park Tickets, Resort stays, shopping, dining, and more in the U.S. There are no block-out dates when redeeming Rewards Dollars.",
        'apr': "18.24%–27.74% variable APR.† 0% promotional APR for 6 months on select Disney vacation packages from the date of purchase, after that a variable APR of 18.24%–27.74%.†",
        'intro_apr': "",
        'fee_text': "$0†",
        'fee_value': 0,
        'card_art': "cards/disney_vintage_mickey_Jan_2026.png",
        'pt_code': "LGC63171",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "$50",
        'stat_label': "bonus offer*",
    },
    {
        'slug': "aeroplan",
        'name': "Air Canada Aeroplan® Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["travel", "airline"],
        'offer': "Earn up to 60,000 Strike through 115,000 bonus points. Earn 75,000 bonus points after you spend $4,000 on purchases in the first 3 months your account is open. Plus, 40,000 bonus points after you spend $20,000 on purchases in the first 12 months.",
        'glance': "Enjoy automatic Aeroplan Elite Status. Earn up to 5X total points on purchases made directly with Air Canada and 3X points on travel purchases. Plus, up to $100 in annual Air Canada statement credits.",
        'apr': "19.74%–28.24% variable APR.† Opens pricing and terms in new window",
        'intro_apr': "",
        'fee_text': "$195†",
        'fee_value': 195,
        'card_art': "cards/AirCanada_Aeroplan_cardart.png",
        'pt_code': "LGC65070",
        'earn_rewards': ["Earn up to 5x total points per $1 spent on Air Canada purchases, including 3x points with your card plus an additional 2x points from Air Canada when traveling as an Aeroplan 25K member.", "Earn 3x points per $1 spent on travel purchases.", "Earn 2x points per $1 spent at grocery stores, dining including takeout and eligible delivery services, and at gas stations.", "Earn 1x point per $1 spent on all other purchases."],
        'benefits': ["Automatic Aeroplan 25K Status as a new cardmember", "Up to $100 in Air Canada statement credits annually", "Free first checked bags for cardmembers and up to eight travelers on the same reservation"],
        'stat_value': "115,000",
        'stat_label': "points bonus*",
    },
    {
        'slug': "british-airways",
        'name': "British Airways Visa Signature® Credit Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["travel", "airline"],
        'offer': "Earn 75,000 Avios Earn 75,000 Avios after you spend $5,000 on purchases within the first 3 months of account opening.",
        'glance': "Take your dream vacation getaway sooner In addition to the bonus, cardmembers earn 3 Avios for every $1 spent on British Airways, Aer Lingus, and Iberia flight purchases, and 2 Avios for every $1 spent on hotel accommodations when purchased. Earn 1 Avios for every $1 spent on all other purchases. Terms apply.",
        'apr': "19.24%–27.74% variable APR.†",
        'intro_apr': "",
        'fee_text': "$95†",
        'fee_value': 95,
        'card_art': "cards/british-airways.png",
        'pt_code': "LGC61716",
        'earn_rewards': ["Earn 3 Avios for every $1 spent on British Airways, Aer Lingus, and Iberia flight purchases.", "Earn 2 Avios for every $1 spent on hotel accommodations booked directly with the hotel.", "Earn 1 Avios for every $1 spent on all other purchases.", "Earn a Travel Together Ticket every calendar year you make $30,000 in purchases."],
        'benefits': ["Up to $600 Reward Flight statement credits each year", "Travel Together Ticket each calendar year you make $30,000 in purchases", "No foreign transaction fees"],
        'stat_value': "75,000",
        'stat_label': "avios bonus*",
    },
    {
        'slug': "aer-lingus",
        'name': "Aer Lingus Visa Signature® Credit Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["travel", "airline"],
        'offer': "Earn 75,000 Bonus Avios Earn 75,000 Avios after you spend $5,000 on purchases within the first 3 months of account opening.",
        'glance': "Take your dream vacation getaway sooner In addition to the bonus, cardmembers earn 3 Avios for every $1 spent on Aer Lingus, British Airways, and Iberia flight purchases, and 2 Avios for every $1 spent on hotel accommodations when purchased directly with the hotel. Earn 1 Avios for every $1 spent on all other purchases. Terms apply.",
        'apr': "19.24%–27.74% variable APR.†",
        'intro_apr': "",
        'fee_text': "$95.†",
        'fee_value': 95,
        'card_art': "cards/aer_lingus_card.png",
        'pt_code': "LGC61785",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "75,000",
        'stat_label': "avios bonus*",
    },
    {
        'slug': "iberia",
        'name': "Iberia Visa Signature® Credit Card",
        'network': "Visa",
        'audience': "personal",
        'categories': ["travel", "airline"],
        'offer': "Earn 75,000 Bonus Avios Earn 75,000 Avios after you spend $5,000 on purchases within the first 3 months of account opening.",
        'glance': "Take your dream vacation getaway sooner In addition to the bonus, cardmembers earn 3 Avios for every $1 spent on Iberia, British Airways, and Aer Lingus flight purchases, 2 Avios for every $1 spent on hotel accommodations when purchased directly with the hotel. Earn 1 Avios for every $1 spent on all other purchases. Terms apply.",
        'apr': "19.24%–27.74% variable APR.†",
        'intro_apr': "",
        'fee_text': "$95†",
        'fee_value': 95,
        'card_art': "cards/iberia_card.png",
        'pt_code': "LGC61715",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "75,000",
        'stat_label': "avios bonus*",
    },
    {
        'slug': "prime-visa",
        'name': "Prime Visa",
        'network': "Visa",
        'audience': "personal",
        'categories': ["cash-back", "no-annual-fee"],
        'offer': "$150 Amazon Gift Card Prime members, get a $150 Amazon Gift Card instantly loaded into your Amazon account's Gift Card Balance on approval of your credit card application.",
        'glance': "Earn rewards on all your purchases with no annual card fee† Earn unlimited 5% back at Amazon.com, Audible.com, Whole Foods Market, and on Chase Travel purchases with an eligible Prime membership, unlimited 2% back at gas stations, restaurants, and on local transit and commuting (including rideshare), and unlimited 1% back on all other purchases.",
        'apr': "18.74%–27.49% variable APR†",
        'intro_apr': "",
        'fee_text': "",
        'fee_value': 0,
        'card_art': "cards/prime-visa.png",
        'pt_code': "LGC59329",
        'earn_rewards': ["Earn unlimited 5% back at Amazon.com, Audible.com, Whole Foods Market, and on Chase Travel purchases with an eligible Prime membership.", "Earn unlimited 2% back at gas stations, restaurants, and on local transit and commuting (including rideshare).", "Earn unlimited 1% back on all other purchases anywhere Visa is accepted.", "Eligible Prime cardmembers earn 10% back or more on a rotating selection of items and categories on Amazon.com."],
        'benefits': ["No annual fee with an eligible Prime membership", "No foreign transaction fees"],
        'stat_value': "5%",
        'stat_label': "rewards rate*",
    },
    {
        'slug': "amazon-visa",
        'name': "Amazon Visa",
        'network': "Visa",
        'audience': "personal",
        'categories': ["cash-back", "no-annual-fee"],
        'offer': "$50 Amazon Gift Card Get a $50 Amazon Gift Card instantly loaded into your Amazon account's Gift Card Balance on approval of your credit card application.",
        'glance': "Earn rewards on all your purchases with no annual card fee† Opens pricing and terms in new window Earn unlimited 3% back at Amazon.com, Audible.com, Whole Foods Market, and on Chase Travel purchases, unlimited 2% back at gas stations, restaurants, and on local transit and commuting (including rideshare), and unlimited 1% back on all other purchases.",
        'apr': "18.74%–27.49% variable APR†",
        'intro_apr': "",
        'fee_text': "",
        'fee_value': 0,
        'card_art': "cards/amazon-visa.png",
        'pt_code': "LGC59318",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "3%",
        'stat_label': "rewards rate*",
    },
    {
        'slug': "doordash-rewards-mastercard",
        'name': "DoorDash Rewards Mastercard®",
        'network': "Mastercard",
        'audience': "personal",
        'categories': ["cash-back", "no-annual-fee"],
        'offer': "Approved applicants receive a free year of DashPass that will auto-renew at $96/yr. Cancel anytime.",
        'glance': "No annual card fee, just cash back on every purchase. Earn 4% cash back on DoorDash and Caviar orders, 3% cash back on dining when purchased directly from a restaurant, 2% cash back on grocery stores online or in-store and 1% on all other purchases.",
        'apr': "18.24%–27.74% variable APR.†",
        'intro_apr': "",
        'fee_text': "",
        'fee_value': 0,
        'card_art': "cards/doordash_card.png",
        'pt_code': "LGC61934",
        'earn_rewards': ["Earn 4% cash back on DoorDash and Caviar orders, including restaurants, groceries, pet supplies, retail items and more, with no earning caps.", "Earn 3% cash back on dining when purchased directly from a restaurant.", "Earn 2% cash back at grocery stores online or in-store.", "Earn 1% cash back on all other purchases."],
        'benefits': ["Free DashPass ($96 value) for a year upon account opening", "No foreign transaction fees", "Contactless payments"],
        'stat_value': "4%",
        'stat_label': "cash back*",
    },
    {
        'slug': "instacart-mastercard",
        'name': "Instacart Mastercard®",
        'network': "Mastercard",
        'audience': "personal",
        'categories': ["cash-back", "no-annual-fee"],
        'offer': "Get a $50 Instacart credit automatically upon approval",
        'glance': "Turn everyday shopping into everyday rewards. Earn 5% cash back on qualifying Instacart purchases on your first $6,000 spent annually, 5% cash back on Chase Travel purchases, and 2% cash back at restaurants, gas stations, and on select streaming services.",
        'apr': "18.24%–27.74% variable APR.†",
        'intro_apr': "",
        'fee_text': "",
        'fee_value': 0,
        'card_art': "cards/instacart_card.png",
        'pt_code': "LGC60680",
        'earn_rewards': ["Earn 5% cash back on qualifying Instacart.com and Instacart app purchases on your first $6,000 spent annually.", "Earn 5% cash back on Chase Travel purchases, including flights, hotels and more.", "Earn 2% cash back at restaurants, including orders on Instacart powered by Uber Eats, gas stations, and on select streaming services.", "Earn 1% cash back on all other purchases."],
        'benefits': ["$50 Instacart credit automatically upon approval", "No foreign transaction fees", "Chase Pay Over Time"],
        'stat_value': "5%",
        'stat_label': "cash back*",
    },
    {
        'slug': "ink-business-unlimited",
        'name': "Ink Business Unlimited® Credit Card",
        'network': "Visa",
        'audience': "business",
        'categories': ["business", "no-annual-fee", "intro-apr"],
        'offer': "Earn $750 cash back after you spend $6,000 on purchases in the first 3 months after account opening.",
        'glance': "Unlimited 1.5% cash back on every purchase.",
        'apr': "0% intro APR for 12 months from account opening on purchases.† Opens pricing and terms in new window After that, 16.74%–24.74% variable APR.† Opens pricing and terms in new window",
        'intro_apr': "0% intro APR for 12 months from account opening on purchases.",
        'fee_text': "$0†",
        'fee_value': 0,
        'card_art': "cards/ink_unlimited_card.png",
        'pt_code': "LGC63749",
        'earn_rewards': ["Earn unlimited 1.5% cash back on every purchase made for your business.", "Earn a total of 5% cash back on Lyft rides through September 30, 2027.", "Redeem rewards for cash back, gift cards, travel and more through Chase Ultimate Rewards."],
        'benefits': ["Employee cards at no additional cost", "Complimentary three-month Instacart+ membership", "Chase Pay Over Time"],
        'stat_value': "1.5%",
        'stat_label': "cash back*",
    },
    {
        'slug': "ink-business-cash",
        'name': "Ink Business Cash® Credit Card",
        'network': "Visa",
        'audience': "business",
        'categories': ["business", "no-annual-fee", "intro-apr"],
        'offer': "Earn $750 cash back after you spend $6,000 on purchases in the first 3 months after account opening.",
        'glance': "5% Cash Back on Business Essentials on $25K max combined spend.",
        'apr': "0% intro APR for 12 months from account opening on purchases.† After that, 16.74%–24.74% variable APR.†",
        'intro_apr': "0% intro APR for 12 months from account opening on purchases.",
        'fee_text': "$0†",
        'fee_value': 0,
        'card_art': "cards/ink_cash_card.png",
        'pt_code': "LGC63827",
        'earn_rewards': ["Earn 5% cash back on the first $25,000 spent in combined purchases at office supply stores and on internet, cable and phone services each account anniversary year.", "Earn 2% cash back on the first $25,000 spent in combined purchases at gas stations and restaurants each account anniversary year.", "Earn 1% cash back on all other purchases, with no limit to the amount you can earn.", "Earn a total of 5% cash back on Lyft rides through September 30, 2027."],
        'benefits': ["Employee cards at no additional cost", "Complimentary three-month Instacart+ membership", "Chase Pay Over Time"],
        'stat_value': "5%",
        'stat_label': "cash back*",
    },
    {
        'slug': "ink-business-preferred",
        'name': "Ink Business Preferred® Credit Card",
        'network': "Visa",
        'audience': "business",
        'categories': ["business"],
        'offer': "Earn 100,000 bonus points after you spend $8,000 on purchases in the first 3 months after account opening.",
        'glance': "3X on Travel and Business categories on $150K combined spend.",
        'apr': "17.74%–26.74% variable APR.†",
        'intro_apr': "",
        'fee_text': "$95†",
        'fee_value': 95,
        'card_art': "cards/ink_preferred_card.png",
        'pt_code': "LGC63764",
        'earn_rewards': ["Earn 3 points per $1 on the first $150,000 spent in combined purchases each account anniversary year on shipping purchases, advertising purchases made with social media sites and search engines, internet, cable and phone services, and travel.", "Earn 1 point per $1 on all other purchases, with no limit to the amount you can earn.", "Earn a total of 5x points on Lyft rides through September 30, 2027."],
        'benefits': ["Complimentary access to DashPass for a minimum of one year when activated by December 31, 2027", "Employee cards at no additional cost", "No foreign transaction fees"],
        'stat_value': "100,000",
        'stat_label': "points bonus*",
    },
    {
        'slug': "ink-business-premier",
        'name': "Ink Business Premier® Credit Card",
        'network': "Visa",
        'audience': "business",
        'categories': ["business"],
        'offer': "Earn $1,000 bonus cash back after you spend $10,000 on purchases in your first 3 months from account opening.",
        'glance': "Unlimited 2.5% Cash Back on large purchases.",
        'apr': "Flex for Business variable APR: 17.74%–28.49%.†",
        'intro_apr': "",
        'fee_text': "$195†",
        'fee_value': 195,
        'card_art': "cards/ink_business_premier_card.png",
        'pt_code': "LGC63834",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "$1,000",
        'stat_label': "bonus offer*",
    },
    {
        'slug': "sapphire-reserve-business",
        'name': "Sapphire Reserve for BusinessSM Credit Card",
        'network': "Visa",
        'audience': "business",
        'categories': ["business"],
        'offer': "Earn 150,000 strike through 200,000 bonus points after you spend $30,000 on purchases in your first 6 months from account opening.",
        'glance': "Access award winning lounge network. Plus, $7,000+ in value your first year.",
        'apr': "Flex for Business variable APR: 17.74%–28.49%.†",
        'intro_apr': "",
        'fee_text': "$795†  ; Employee Cards at no additional cost",
        'fee_value': 795,
        'card_art': "cards/sapphire_reserve_biz_card.png",
        'pt_code': "LGC64346",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "200,000",
        'stat_label': "points bonus*",
    },
    {
        'slug': "united-business",
        'name': "UnitedSM Business Card",
        'network': "Visa",
        'audience': "business",
        'categories': ["business", "airline"],
        'offer': "Earn up to 110,000 bonus miles + 2,000 Premier qualifying points (PQP) after qualifying activities.",
        'glance': "2 United ClubSM one-time passes each year, a free first checked bag, and over $600 in annual partner credits.",
        'apr': "19.74%–28.24% variable APR.†",
        'intro_apr': "",
        'fee_text': "$150 Annual Fee†",
        'fee_value': 150,
        'card_art': "cards/united_biz_card.png",
        'pt_code': "LGC62231",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "110,000",
        'stat_label': "miles bonus*",
    },
    {
        'slug': "united-club-business",
        'name': "United ClubSM Business Card",
        'network': "Visa",
        'audience': "business",
        'categories': ["business", "airline"],
        'offer': "Earn up to 110,000 bonus miles + 2,000 Premier qualifying points (PQP) after qualifying activities.",
        'glance': "United ClubSM access, Premier Access travel services, and over $925 in annual partner credits.",
        'apr': "19.74%–28.24% variable APR.†",
        'intro_apr': "",
        'fee_text': "$695†",
        'fee_value': 695,
        'card_art': "cards/united_club_biz_card.png",
        'pt_code': "LGC63542",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "110,000",
        'stat_label': "miles bonus*",
    },
    {
        'slug': "southwest-performance-business",
        'name': "Southwest Rapid Rewards® Performance Business Credit Card",
        'network': "Visa",
        'audience': "business",
        'categories': ["business"],
        'offer': "Earn 80,000 points after you spend $5,000 on purchases in the first 3 months from account opening.",
        'glance': "Complimentary Preferred seat selection at booking and Extra Legroom seat upgrades 48 hs. prior to departure, when available. Plus, free first checked bag.",
        'apr': "19.24%–27.74% variable APR.†",
        'intro_apr': "",
        'fee_text': "$299 applied to first billing statement.†",
        'fee_value': 299,
        'card_art': "cards/swa_performance_biz_card.png",
        'pt_code': "LGC61809",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "80,000",
        'stat_label': "points bonus*",
    },
    {
        'slug': "southwest-premier-business",
        'name': "Southwest Rapid Rewards® Premier Business Credit Card",
        'network': "Visa",
        'audience': "business",
        'categories': ["business"],
        'offer': "Earn 60,000 Strike through 80,000 points after you spend $3,000 on purchases in the first 3 months from account opening.",
        'glance': "Free first checked bag, select a Standard or Preferred seat within 48 hours prior to departure, when available, and a boarding benefit. Plus, 6,000 anniversary points each year.",
        'apr': "19.24%–27.74% variable APR.†",
        'intro_apr': "",
        'fee_text': "$149 applied to first billing statement.†",
        'fee_value': 149,
        'card_art': "cards/swa_premier_biz_card.png",
        'pt_code': "LGC65025",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "80,000",
        'stat_label': "points bonus*",
    },
    {
        'slug': "ihg-one-premier-business",
        'name': "IHG One Rewards Premier Business Credit Card",
        'network': "Visa",
        'audience': "business",
        'categories': ["business", "hotel"],
        'offer': "Earn 140,000 Bonus Points after spending $4,000 in the first 3 months from account opening.",
        'glance': "Earn IHG One Rewards points on every purchase. Up to 26X total points per $1 spent when you stay at IHG® Hotels and Resorts.",
        'apr': "19.24%–27.74% variable APR.†",
        'intro_apr': "",
        'fee_text': "$99†",
        'fee_value': 99,
        'card_art': "cards/IHG_One_Premier_Biz_card_alt.png",
        'pt_code': "LGC60353",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "26x",
        'stat_label': "points*",
    },
    {
        'slug': "world-of-hyatt-business",
        'name': "World of Hyatt Business Credit Card",
        'network': "Visa",
        'audience': "business",
        'categories': ["business", "hotel"],
        'offer': "Earn 70,000 Bonus Points after you spend $7,000 on purchases within the first 3 months of account opening.",
        'glance': "Make the most of your small business spending with accelerated earning wherever you spend the most. Earn 2 Bonus Points total per $1 spent in your top three spend categories each quarter.",
        'apr': "19.24%–27.74% variable APR.†",
        'intro_apr': "",
        'fee_text': "$199†",
        'fee_value': 199,
        'card_art': "cards/world_hyatt_biz_card.png",
        'pt_code': "LGC65087",
        'earn_rewards': [],
        'benefits': [],
        'stat_value': "",
        'stat_label': "",
    },
]
