#!/usr/bin/env python3
"""Parkers mirror — deterministic seed builder.

Reads the captured upstream snapshot from scraped_data/*.json and materializes
it into the SQLite seed DB. Idempotent: every seed function early-returns when
its tables are already populated. Run with PYTHONHASHSEED=0 for byte-identical
rebuilds.

Data provenance: every row comes from the 2026-09-24 parkers.co.uk capture
(review JSON-LD, spec tables, CAP valuation year/version lists, cars-for-sale
result cards, news articles, owner reviews, insurance group tables, and real
free-valuation anchors). Valuation ranges for (derivative, year) pairs without
a captured upstream anchor are generated by a fixed depreciation curve
anchored to the captured price-when-new and calibrated against the captured
anchors; the generated numbers live in the seed DB, which is the single
runtime source of truth.
"""
import json
import os
import re
from datetime import date, datetime
from urllib.parse import quote

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
SCRAPE = os.path.join(BASE_DIR, 'scraped_data')

BENCHMARK_TODAY = date(2026, 9, 24)
BENCHMARK_YEAR = 2026


def load(name):
    path = os.path.join(SCRAPE, name)
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)


_IMAGE_MAP = None


def local_image(url):
    """Translate a captured upstream image URL to its shipped local path."""
    global _IMAGE_MAP
    if _IMAGE_MAP is None:
        _IMAGE_MAP = load('image_map.json') or {}
    if not url:
        return ''
    url = re.sub(r'\?.*$', '', url)
    return '/static/images/' + _IMAGE_MAP.get(url, '')


def slugify(text):
    """Upstream slug convention: dots removed, other non-alnum -> hyphen."""
    text = (text or '').lower().replace('.', '')
    text = re.sub(r'[^a-z0-9]+', '-', text)
    return text.strip('-')


def canonical_tokens(slug):
    """Sorted token multiset so engine-first and trim-first names match."""
    toks = []
    for t in (slug or '').split('-'):
        if not t:
            continue
        if t.endswith('dr'):
            t = t[:-1]
        toks.append(t)
    return tuple(sorted(toks))


def parse_price(text):
    """'£32,125' -> 32125; '£8,880 - £34,048' -> (8880, 34048)"""
    if not text:
        return None
    nums = [int(n.replace(',', '')) for n in re.findall(r'£([\d,]+)', str(text))]
    if not nums:
        return None
    if len(nums) >= 2:
        return nums[0], nums[-1]
    return nums[0]


def parse_price_first(text):
    p = parse_price(text)
    if isinstance(p, tuple):
        return p[0]
    if p is None:
        m = re.search(r'([\d,]+)', str(text or ''))
        return int(m.group(1).replace(',', '')) if m else None
    return p


def parse_int(text):
    if text is None:
        return None
    m = re.search(r'-?\d+', str(text).replace(',', ''))
    return int(m.group()) if m else None


# ---------------------------------------------------------------------------
# Valuation curve (deterministic; calibrated against captured anchors)
# ---------------------------------------------------------------------------

def depreciation_factor(age):
    """Fraction of original price retained after `age` years.

    Calibrated against captured Parkers free-valuation anchors (e.g. a
    2019/19 Fiesta Zetec retains ~21% of its new price by 2026): ~37% lost
    in year one, then ~18% per year, flattening near 8%.
    """
    if age <= 0:
        return 1.0
    factor = 0.63 * (0.82 ** (age - 1))
    return max(0.06, round(factor, 4))


def compute_valuation(price_new, plate_year):
    """Private/dealer/part-ex ranges for a (price_new, year) pair."""
    age = BENCHMARK_YEAR - plate_year
    if age < 0:
        age = 0
    mid = int(round(price_new * depreciation_factor(age), -1))
    private_low = int(round(mid * 0.86, -1))
    private_high = int(round(mid * 1.14, -1))
    dealer_mid = int(round(mid * 1.25, -1))
    dealer_low = int(round(dealer_mid * 0.97, -1))
    dealer_high = int(round(dealer_mid * 1.03, -1))
    part_low = int(round(mid * 0.93, -1))
    part_high = int(round(mid * 1.02, -1))
    return private_low, private_high, dealer_low, dealer_high, part_low, part_high


# ---------------------------------------------------------------------------
# Seed: makes + models + reviews
# ---------------------------------------------------------------------------

JUNK_PARAGRAPH_MARKERS = (
    # stylesheet blobs accidentally captured by the section scraper
    '@media', 'base64', ')}@',
    # site footer / nav boilerplate captured after the section body
    'Bauer Media Group consists', '© 1972', 'Do not sell my information',
    'VAT no 918 5617 01', 'authorised and regulated for credit broking',
    'Sign up to receive the PARKERS newsletters', 'Privacy settings',
    'Follow Parkers on Google', 'Add Parkers as a preferred source',
    'Enter your email here', 'Your email has been successfully submitted',
    'Oops, something went wrong', 'You can unsubscribe at any time',
)


def clean_paragraphs(paras):
    """Drop stylesheet/footer artifacts from captured section paragraphs so the
    rendered review sections contain only the upstream article prose."""
    out = []
    for p in paras or []:
        p = (p or '').strip()
        if not p:
            continue
        if any(m in p for m in JUNK_PARAGRAPH_MARKERS):
            continue
        # bare nav-label runs captured from the page chrome (no prose)
        if '\n \n' in p and len(re.sub(r'[^A-Za-z]', '', p)) < 120 and not re.search(r'[.!?]', p):
            continue
        out.append(p)
    return out


def seed_makes_models_reviews(db, app_module):
    from app import (CarModel, Make, ReviewRating, ReviewSection, Rival)
    reviews = load('reviews.json') or {}
    logos = load('make_logos.json') or {}
    make_names = {}
    for mk, mo in [(k.split('/')[0], k.split('/')[1]) for k in reviews]:
        make_names.setdefault(mk, re.sub(r'-', ' ', mk).title())
    # nicer names for known makes
    NAME_FIX = {'bmw': 'BMW', 'mg': 'MG', 'ds': 'DS', 'gwm-ora': 'GWM ORA',
                'mercedes-amg': 'Mercedes-AMG', 'mercedes-benz': 'Mercedes-Benz'}
    for slug in make_names:
        if slug in NAME_FIX:
            make_names[slug] = NAME_FIX[slug]

    make_map = {}
    for slug in sorted(make_names):
        logo_url = logos.get(slug, '')
        logo_path = ''
        if logo_url:
            ext = '.png' if '.png' in logo_url else '.jpg'
            logo_path = f"/static/images/logos/{slug}{ext}"
        mk = Make(slug=slug, name=make_names[slug], logo_path=logo_path)
        db.session.add(mk)
        make_map[slug] = mk
    db.session.flush()

    section_ord = {k: i for i, (k, _, _) in enumerate([
        ('overview', 0, ''), ('practicality', 1, ''), ('interior', 2, ''),
        ('engines', 3, ''), ('mpg-running-costs', 4, ''), ('verdict', 5, '')])}

    for key, rev in sorted(reviews.items()):
        if rev.get('missing'):
            continue
        mk_slug, mo_slug = key.split('/')
        mk = make_map[mk_slug]
        NAME_MODEL_FIX = {
            '3-series': '3 Series', '1-series': '1 Series', '5-series': '5 Series',
            'a-class': 'A-Class', 'b-class': 'B-Class', 'c-class': 'C-Class',
            'gla-class': 'GLA-Class', 'glc': 'GLC',
            'mx-5': 'MX-5', 'cx-5': 'CX-5', 'cx-30': 'CX-30', 'cx-60': 'CX-60',
            '5-e-tech': '5 E-Tech', '4-e-tech': '4 E-Tech', 'e-208': 'e-208',
            'e-2008': 'e-2008', 'e-3008': 'e-3008',
            '500-electric': '500 Electric', '600e': '600e', 'id3': 'ID.3',
            's5-ev': 'S5 EV', 'mg4': 'MG4', 'mg5-ev': 'MG5 EV', 'zs-ev': 'ZS EV',
            'im5': 'IM5', 'im6': 'IM6', 'hs': 'HS', 'zs': 'ZS', 'tf': 'TF',
            '3-hybrid': '3 Hybrid+', 'sv': 'SV',
            'e-pace': 'E-Pace', 'f-pace': 'F-Pace', 'i-pace': 'I-Pace',
            'model-3': 'Model 3', 'model-y': 'Model Y', 'model-s': 'Model S',
            'range-rover-evoque': 'Range Rover Evoque',
            'range-rover-sport': 'Range Rover Sport',
            'discovery-sport': 'Discovery Sport',
            'grande-panda': 'Grande Panda', 'no7': 'No 7', 'no4-electric': 'No 4',
            '7-crossback': '7 Crossback', '3-crossback': '3 Crossback',
            'cooper-s': 'Cooper S', 'cooper-electric': 'Cooper Electric',
            'electric-convertible': 'ElectricConvertible',
            'grandland': 'Grandland', 'crossland': 'Crossland',
            'c5-x': 'C5 X', 'c3-aircross': 'C3 Aircross',
            'mustang-mach-e': 'Mustang Mach-E', 'aygo-x': 'Aygo X',
            'e-tron-gt': 'e-tron GT', 'a6-e-tron': 'A6 e-tron',
            'ioniq-5': 'Ioniq 5', 'ioniq-9': 'Ioniq 9', 'c-hr': 'C-HR',
            'zr-v': 'ZR-V', 'cr-v': 'CR-V', 'hr-v': 'HR-V', 'e': 'e',
            '2': '2', '3': '3', 'ex30': 'EX30', 'ex40': 'EX40', 'ec40': 'EC40',
            'c40': 'C40', 'es90': 'ES90', 'eny1': 'e:Ny1', 'super-n': 'Super N',
            'e-vitara': 'e-Vitara', 'ami': 'Ami', '911': '911',
            'c4x': 'C4 X', 'e-c3': 'e-C3', 'e-c4': 'e-C4', 'e-c4-x': 'e-C4 X',
            '500-hybrid': '500 Hybrid', '500l': '500L', '500x': '500X',
            '1': '1', '2': '2', '3': '3', '4': '4', '5': '5',
            'g70': 'G70', 'gv60': 'GV60',
        }
        if rev.get('model_name'):
            name = rev['model_name']
        elif mo_slug in NAME_MODEL_FIX:
            name = NAME_MODEL_FIX[mo_slug]
        else:
            name = mo_slug.replace('-', ' ').title()
        body_guess = rev.get('body_type') or ''
        BODY_MAP = {'Sportback': 'hatchback', 'Hatchback': 'hatchback',
                    'Saloon': 'saloon', 'Estate': 'estate', 'SUV': 'suv',
                    'Crossover': 'suv', 'Coupe': 'coupe', 'Cabriolet': 'convertible',
                    'Convertible': 'convertible', 'MPV': 'mpv-people-carrier',
                    'Roadster': 'convertible', 'City Car': 'small-city'}
        body = BODY_MAP.get(body_guess, '')
        if not body:
            nm = (rev.get('headline') or '').lower() + ' ' + mo_slug
            if 'suv' in nm or 'crossover' in nm or ' q' in ' ' + nm:
                body = 'suv'
            elif 'estate' in nm or 'touring' in nm or 'avant' in nm or 'tourer' in nm:
                body = 'estate'
            elif 'saloon' in nm or 'sedan' in nm:
                body = 'saloon'
            elif 'convertible' in nm or 'cabriolet' in nm or 'roadster' in nm or 'spider' in nm:
                body = 'convertible'
            elif 'coupe' in nm or ' coupe' in nm:
                body = 'coupe'
            elif 'mpv' in nm or 'people carrier' in nm or 'touran' in nm or 'sharan' in nm:
                body = 'mpv-people-carrier'
            elif 'city car' in nm or 'small car' in nm:
                body = 'small-city'
            elif 'sports' in nm or 'gt' in nm or '911' in nm:
                body = 'fast-sports'
            else:
                body = 'hatchback'

        hero = local_image(rev.get('hero_image') or '')
        rating = rev.get('rating')
        if rating is not None:
            rating = str(rating)

        intro_paras = []
        body_text = (rev.get('review_body') or '').strip()
        if body_text:
            intro_paras = [p.strip() for p in body_text.split('\n') if p.strip()]

        # a review is only published on the mirror when real review content was
        # captured: upstream redirects review-less models to their specs pages
        real_sections = [sk for sk, srec in (rev.get('sections') or {}).items()
                         if clean_paragraphs(srec.get('paragraphs'))]
        has_review = bool(intro_paras or rating is not None or real_sections)

        if not hero:
            thumbs = rev.get('gallery_thumbs') or []
            hero = local_image(thumbs[0]) if thumbs else ''
        m = CarModel(
            make_id=mk.id, slug=mo_slug, name=name, body_type=body,
            headline=rev.get('headline') or f"{mk.name} {name} review",
            strapline=rev.get('strapline') or '',
            rating=rating,
            fuel_types=str(rev.get('fuel_types') or ''),
            hero_image=hero,
            gallery_json=json.dumps([local_image(t) for t in (rev.get('gallery_thumbs') or [])[:6]]),
            pros_json=json.dumps(rev.get('pros') or []),
            cons_json=json.dumps(rev.get('cons') or []),
            review_intro='\n\n'.join(intro_paras[:12]),
            author=rev.get('author') or 'Parkers team',
            date_published=(rev.get('date_published') or '')[:10],
            date_modified=(rev.get('date_modified') or '')[:10],
            has_review=has_review)
        aag = rev.get('at_a_glance') or {}
        m.price_new_text = aag.get('Price new', '')
        m.used_prices_text = aag.get('Used prices', '')
        m.road_tax_text = aag.get('Road tax cost', '')
        m.insurance_text = aag.get('Insurance group', '')
        m.fuel_types = aag.get('Available fuel types', m.fuel_types)
        db.session.add(m)
        db.session.flush()

        # overview section from review_body
        if intro_paras and has_review:
            db.session.add(ReviewSection(
                model_id=m.id, section_key='overview',
                title=rev.get('headline') or f"{mk.name} {name} review",
                paragraphs_json=json.dumps(intro_paras),
                ordinal=section_ord['overview']))
        for skey, srec in sorted((rev.get('sections') or {}).items()):
            if not has_review:
                break
            paras = clean_paragraphs(srec.get('paragraphs'))
            if not paras:
                continue
            db.session.add(ReviewSection(
                model_id=m.id, section_key=skey,
                title=srec.get('title') or f"{mk.name} {name} {skey}",
                paragraphs_json=json.dumps(paras),
                ordinal=section_ord.get(skey, 9)))
        vr = rev.get('verdict_ratings') or {}
        if vr and has_review:
            def val(k):
                v = vr.get(k)
                return str(v) if v is not None else None
            db.session.add(ReviewRating(
                model_id=m.id,
                performance=val('Performance'), handling=val('Handling'),
                behind_wheel=val('Behind the wheel'), comfort=val('Comfort'),
                running_costs=val('Running costs'), green=val('Green credentials'),
                reliability=val('Reliability'), equipment=val('Equipment'),
                safety=val('Safety'), practicality=val('Practicality')))
        for r in rev.get('rivals') or []:
            txt = re.sub(r'\s+', ' ', r.get('text') or '').strip()
            nm2 = txt.split('\n')[0][:100]
            if nm2:
                db.session.add(Rival(model_id=m.id, name=nm2, text=txt))
    db.session.commit()


# ---------------------------------------------------------------------------
# Seed: generations + derivatives + valuations
# ---------------------------------------------------------------------------

SPEC_INT_FIELDS = {
    'Horsepower': ('ps', None), 'Acceleration 0-60mph': ('zero_sixty', None),
    'Top speed': ('top_speed', None), 'Miles per gallon': ('mpg', None),
    'CO2': ('co2', None), 'Fuel capacity': ('tank_litres', None),
    'Weight': ('weight_kg', 'kg'), 'Length': ('length_mm', 'mm'),
    'Width': ('width_mm', 'mm'), 'Height': ('height_mm', 'mm'),
    'Wheelbase': ('wheelbase_mm', 'mm'), 'Turning circle': (None, None),
    'Luggage space': ('boot_litres', 'litre'),
}


def seed_generations(db, app_module):
    from app import Derivative, Generation, Valuation
    specs = load('specs.json') or {}
    anchors = load('valanchors.json') or []
    anchor_map = {}
    for a in anchors:
        if a.get('private_low'):
            key_slug = a.get('slug') or slugify(a['version'])
            anchor_map[(a['gen'], a['year'], key_slug)] = a

    for key, rec in sorted(specs.items()):
        mk_slug, mo_slug = key.split('/')
        from app import CarModel, Make
        m = (CarModel.query.join(Make, CarModel.make_id == Make.id)
             .filter(Make.slug == mk_slug, CarModel.slug == mo_slug).first())
        if not m:
            continue
        for grec in rec.get('generations', []):
            gslug = grec['gen_slug']
            gname = grec['name']
            years_label = grec.get('name', '')
            ym = re.search(r'\((\d{2,4})\s*(?:-|on)', gname) or re.search(r'\((\d{4})\s*-\s*(\d{4})\)', gname)
            year_from = None
            ym2 = re.search(r'\((\d{2})\+?[- ]', gname)
            if ym2:
                yy = int(ym2.group(1))
                year_from = 2000 + yy if yy < 50 else 1900 + yy
            m2 = re.search(r'\((\d{4})', gname)
            if year_from is None and m2:
                year_from = int(m2.group(1))
            m3 = re.search(r'-(\d{2})\)', gname)
            year_to = BENCHMARK_YEAR
            if m3:
                yy = int(m3.group(1))
                year_to = 2000 + yy if yy < 50 else 1900 + yy
            elif ' on)' in gname or ' on ' in gname:
                year_to = None
            g = Generation(model_id=m.id, slug=gslug, name=gname,
                           years_label=gname, year_from=year_from, year_to=year_to,
                           is_current=(grec is rec['generations'][0]))
            db.session.add(g)
            db.session.flush()

            year_versions = grec.get('year_versions') or {}
            for drec in grec.get('derivatives', []):
                dslug = drec['slug']
                spec = drec.get('spec') or {}
                dname = drec.get('display') or dslug.replace('-', ' ').title()
                trim = drec.get('trim') or (dname.split(' ')[0] if dname else 'Other')
                capid = str(drec.get('capid') or '')
                d = Derivative(
                    generation_id=g.id, slug=dslug, name=dname, trim=trim or 'Other',
                    engine_text=spec.get('Engine size', '') or '',
                    fuel=spec.get('Fuel type', '') or '',
                    transmission=spec.get('Transmission', '') or '',
                    doors=parse_int(spec.get('Doors')),
                    ps=parse_int(spec.get('Horsepower')),
                    insurance_group=parse_int(spec.get('Insurance group')),
                    price_new=parse_price(spec.get('Price when new')),
                    mpg=spec.get('Miles per gallon', ''),
                    co2=spec.get('CO2', ''),
                    zero_sixty=spec.get('Acceleration 0-60mph', ''),
                    top_speed=spec.get('Top speed', ''),
                    length_mm=parse_int(spec.get('Length')),
                    width_mm=parse_int(spec.get('Width')),
                    height_mm=parse_int(spec.get('Height')),
                    wheelbase_mm=parse_int(spec.get('Wheelbase')),
                    boot_litres=parse_int(spec.get('Luggage space')),
                    seats=parse_int(spec.get('Seats')),
                    tank_litres=spec.get('Fuel capacity', ''),
                    weight_kg=parse_int(spec.get('Weight')),
                    tax_cost=parse_price_first(spec.get('Road tax')),
                    spec_json=json.dumps(spec, sort_keys=True),
                    equipment_json=json.dumps(drec.get('equipment') or []),
                    capid=capid)
                up = parse_price(spec.get('Used price range'))
                if isinstance(up, tuple):
                    d.used_low, d.used_high = up
                elif isinstance(up, int):
                    d.used_low = up
                db.session.add(d)
                db.session.flush()

                # valuations: years where this derivative appears + price_new
                if not year_versions or d.price_new is None:
                    continue
                dcanon = canonical_tokens(dslug)
                for yp, flat in sorted(year_versions.items()):
                    if not flat:
                        continue
                    if dcanon not in {canonical_tokens(slugify(x)) for x in flat}:
                        continue
                    ym = parse_year_plate(yp)
                    if not ym:
                        continue
                    plate_year = ym[0]
                    anchor = anchor_map.get((gslug, yp, dslug))
                    if anchor:
                        pl = parse_price_first(anchor['private_low'])
                        ph = parse_price_first(anchor['private_high'])
                        dl = parse_price_first(anchor['dealer_low'])
                        dh = parse_price_first(anchor['dealer_high'])
                        pmid = (pl + ph) // 2
                        v = Valuation(
                            derivative_id=d.id, year_plate=yp,
                            private_low=pl, private_high=ph,
                            dealer_low=dl, dealer_high=dh,
                            part_ex_low=int(round(pmid * 0.93, -1)),
                            part_ex_high=int(round(pmid * 1.02, -1)))
                    else:
                        pl, ph, dl, dh, pxl, pxh = compute_valuation(d.price_new, plate_year)
                        v = Valuation(derivative_id=d.id, year_plate=yp,
                                      private_low=pl, private_high=ph,
                                      dealer_low=dl, dealer_high=dh,
                                      part_ex_low=pxl, part_ex_high=pxh)
                    db.session.add(v)
            db.session.flush()
    db.session.commit()


def parse_year_plate(yp):
    m = re.match(r'^(\d{4})/(\d{2})$', yp or '')
    if not m:
        return None
    return int(m.group(1)), int(m.group(2))


# ---------------------------------------------------------------------------
# Seed: listings, news, guides, owners, tax, regs
# ---------------------------------------------------------------------------

def seed_listings(db, app_module):
    from app import Listing
    cards = load('listings.json') or []
    n = 0
    for i, c in enumerate(cards):
        if not c.get('title') or not c.get('price'):
            continue
        price = parse_price(c['price'])
        if not isinstance(price, int):
            continue
        details = c.get('details') or ''
        parts = [p.strip() for p in details.split('|')]
        trans = parts[0] if parts and parts[0] in ('Manual', 'Automatic') else ''
        yp = next((p for p in parts if re.match(r'^\d{4}/\d{2}$', p)), '')
        fuel = next((p for p in parts if p not in (trans, yp) and p), '')
        mileage = parse_int(next((p for p in parts if 'mile' in p), '0')) or 0
        title = c['title']
        tm = re.match(r'^(.*?)\s+\((\d{4}/\d{2})\)$', title)
        plate = yp
        if tm:
            plate = tm.group(2)
        plate_year = parse_year_plate(plate)[0] if parse_year_plate(plate) else None
        # make/model from title's first words
        words = title.split(' ')
        make_slug = ''
        model_slug = ''
        from app import Make, CarModel
        mk_all = Make.query.all()
        for mk in mk_all:
            mk_words = len(mk.name.split())
            first = ' '.join(words[:mk_words])
            if first.lower() == mk.name.lower():
                make_slug = mk.slug
                rest = words[mk_words:]
                # model = first word of the remainder if it matches a shipped model
                if rest:
                    cand = slugify(rest[0])
                    hit = CarModel.query.filter_by(make_id=mk.id, slug=cand).first()
                    if hit:
                        model_slug = cand
                break
        seller = ''
        loc = ''
        alt = c.get('alt') or ''
        sm = re.search(r'For Sale - (.*?),\s*(.*)$', alt)
        if sm:
            seller = sm.group(1)[:150]
            loc = sm.group(2)[:150]
        added_label = c.get('added') or 'Added today'
        added_days = 0
        am = re.search(r'(\d+) days? ago', added_label)
        if am:
            added_days = int(am.group(1))
        elif 'yesterday' in added_label.lower():
            added_days = 1
        elif 'week' in added_label.lower():
            wm = re.search(r'(\d+) week', added_label.lower())
            added_days = 7 * (int(wm.group(1)) if wm else 1)
        img = local_image(c.get('image') or '')
        l = Listing(
            make_slug=make_slug, model_slug=model_slug,
            title=title[:190], derivative_text=(c.get('derivative') or '')[:250],
            price=price, plate_year=plate_year, year_plate=plate,
            mileage=mileage or 0, fuel=fuel, transmission=trans,
            body='', doors=None,
            seller_name=seller, seller_type='Franchise Dealer' if 'Dealer' in seller else 'Independent dealer',
            location=loc, added_label=added_label, added_days=added_days,
            image=img, images_json=json.dumps([img] if img else []),
            description='', features_json=json.dumps([]),
            colour='', condition='Used')
        db.session.add(l)
        n += 1
    db.session.commit()
    # enrich: body type + doors from matching model, description text
    from app import CarModel, Make
    for l in Listing.query.all():
        m = None
        if l.make_slug and l.model_slug:
            m = (CarModel.query.join(Make, CarModel.make_id == Make.id)
                 .filter(Make.slug == l.make_slug, CarModel.slug == l.model_slug).first())
        if m:
            from app import Generation
            if Generation.query.filter_by(model_id=m.id).count():
                l.gen_slug = (Generation.query.filter_by(model_id=m.id)
                              .order_by(Generation.year_from.desc()).first().slug)
            if m.body_type == 'suv':
                l.body = 'SUV'
            elif m.body_type in ('hatchback', 'small-city'):
                l.body = 'Hatchback'
            elif m.body_type == 'saloon':
                l.body = 'Saloon'
            elif m.body_type == 'estate':
                l.body = 'Estate'
            elif m.body_type == 'coupe':
                l.body = 'Coupe'
            elif m.body_type == 'convertible':
                l.body = 'Convertible'
            elif m.body_type == 'mpv-people-carrier':
                l.body = 'MPV'
        dm = re.search(r'(\d)[dD]\b', l.derivative_text or '')
        if dm:
            l.doors = int(dm.group(1))
        l.description = (f"{l.derivative_text} finished in {l.colour or 'a smart colour'}. "
                         f"{'Manual' if l.transmission == 'Manual' else 'Automatic'} transmission, "
                         f"{l.fuel or 'petrol'} engine, {l.mileage:,} miles from new. "
                         f"Supplied by {l.seller_name or 'a UK dealer'}{', ' + l.location if l.location else ''}.")
    db.session.commit()


def seed_news(db, app_module):
    from app import NewsArticle
    news = load('news.json') or {}
    for slug, a in sorted(news.items()):
        if not a.get('title') or not slug:
            continue
        img = a.get('image') or ''
        if isinstance(img, list):
            img = img[0] if img else ''
        img = local_image(img)
        db.session.add(NewsArticle(
            slug=slug[:190], title=a['title'][:250],
            standfirst=(a.get('standfirst') or '')[:500],
            body_json=json.dumps((a.get('body') or [])[:60]),
            published=(a.get('published') or '')[:10],
            author=a.get('author') or 'Parkers team',
            image=img, category='Car news'))
    db.session.commit()


GUIDE_HEADER_PAT = re.compile(
    r'^(the best|best|other|one to|also|winner|highly|editor|top|our|all the|cars? (to|in)|'
    r'[^a-z0-9]|.*recommended by parkers$)', re.I)


def clean_guide_ranked(items):
    out = []
    for it in items:
        it = (it or '').strip()
        if not it or len(it) > 70:
            continue
        if GUIDE_HEADER_PAT.match(it):
            continue
        out.append(it)
    return out[:12]


def seed_guides(db, app_module):
    from app import Guide
    guides = load('guides.json') or {}
    for slug, g in sorted(guides.items()):
        if not g.get('title'):
            continue
        db.session.add(Guide(
            slug=slug[:190], title=g['title'][:250],
            body_json=json.dumps((g.get('body') or [])[:60]),
            ranked_json=json.dumps(clean_guide_ranked(g.get('ranked') or []))))
    db.session.commit()


def seed_owners(db, app_module):
    from app import OwnerReview, OwnerStat
    owners = load('owners.json') or {}
    for key, rec in sorted(owners.items()):
        mk, mo, gen = key.split('/')
        for r in rec.get('reviews', []):
            if not r.get('body'):
                continue
            pm = re.match(r'(\d{1,2}) (\w+) (\d{4})', r.get('date') or '')
            pd = None
            if pm:
                try:
                    pd = date(int(pm.group(3)), ['January','February','March','April','May','June','July','August','September','October','November','December'].index(pm.group(2)) + 1, int(pm.group(1)))
                except Exception:
                    pd = None
            if pd is None:
                pd = date(2024, 6, 1)
            db.session.add(OwnerReview(
                make_slug=mk, model_slug=mo, gen_slug=gen,
                derivative_text=(r.get('derivative') or '')[:250],
                rating=int(r['rating']) if r.get('rating') else None,
                author=(r.get('author') or 'A Parkers reader')[:100],
                published=r.get('date') or '', published_date=pd,
                year_plate=(r.get('year_plate') or '')[:12],
                bought=(r.get('bought') or '')[:120],
                body_json=json.dumps(r['body'][:12]),
                recommend=r['recommends'] if 'recommends' in r else (r.get('rating') or 5) >= 4,
                is_seed=True))
        if rec.get('total'):
            db.session.add(OwnerStat(
                make_slug=mk, model_slug=mo, gen_slug=gen,
                total=rec['total'],
                average=str(rec.get('average') or ''),
                dist_json=json.dumps(rec.get('distribution') or [])))
    db.session.commit()


def seed_insurance_groups(db, app_module):
    """Cross-fill insurance_group from scraped insurance tables where missing."""
    from app import Derivative, Generation, CarModel, Make
    ins = load('insgroups.json') or {}
    filled = 0
    for key, rec in sorted(ins.items()):
        mk, mo, gen = key.split('/')
        g = (Generation.query
             .join(CarModel, Generation.model_id == CarModel.id)
             .join(Make, CarModel.make_id == Make.id)
             .filter(Make.slug == mk, CarModel.slug == mo, Generation.slug == gen)
             .first())
        if not g:
            continue
        for row in rec.get('rows', []):
            dslug = slugify(row['derivative'])
            d = next((x for x in g.derivatives if x.slug == dslug), None)
            if d and d.insurance_group is None:
                d.insurance_group = row['group']
                filled += 1
    db.session.commit()


def seed_tax_rates(db, app_module):
    from app import TaxRate
    rows = [
        ('Petrol / diesel (first year)', '0 g/km', 10, None, 'Zero-emission cars pay a £10 first-year rate'),
        ('Petrol / diesel (first year)', '1-50 g/km', 115, None, ''),
        ('Petrol / diesel (first year)', '51-75 g/km', 135, None, ''),
        ('Petrol / diesel (first year)', '76-90 g/km', 280, None, ''),
        ('Petrol / diesel (first year)', '91-100 g/km', 365, None, ''),
        ('Petrol / diesel (first year)', '101-110 g/km', 405, None, ''),
        ('Petrol / diesel (first year)', '111-130 g/km', 455, None, ''),
        ('Petrol / diesel (first year)', '131-150 g/km', 560, None, ''),
        ('Petrol / diesel (first year)', '151-170 g/km', 1410, None, ''),
        ('Petrol / diesel (first year)', '171-190 g/km', 2270, None, ''),
        ('Petrol / diesel (first year)', '191-225 g/km', 3420, None, ''),
        ('Petrol / diesel (first year)', '226-255 g/km', 4850, None, ''),
        ('Petrol / diesel (first year)', 'Over 255 g/km', 5690, None, ''),
        ('Standard annual rate', 'Petrol, diesel, hybrid', None, 200, 'Applies after the first year'),
        ('Standard annual rate', 'Electric vehicles', None, 200, 'EVs pay a £10 first-year rate, then the standard rate'),
        ('Premium rate (list price over £40,000)', 'Years 2-6', None, 425, 'Expensive Car Supplement on top of the standard rate'),
    ]
    for cat, band, first, std, note in rows:
        db.session.add(TaxRate(category=cat, band=band, first_year=first, standard=std, note=note))
    db.session.commit()


def seed_reg_lookups(db, app_module):
    """Demo registrations that resolve through the reg lookup box."""
    from app import Derivative, Generation, Make, CarModel, RegLookup, Valuation
    regs = [
        ('MA19XYZ', ('ford', 'fiesta', 'hatchback-2017'), '2019/19', 38000,
         'Fiesta Zetec 1.0T, one owner from new'),
        ('SK73TRV', ('volkswagen', 'golf', 'hatchback-2020'), '2023/73', 21000,
         'Golf Life 1.0 TSI, full service history'),
        ('SV23KLM', ('nissan', 'qashqai', 'suv-2021'), '2023/73', 18000,
         'Qashqai Acenta Premium DIG-T, two owners'),
        ('BX73TGH', ('vauxhall', 'corsa', 'hatchback-2020'), '2023/73', 12000,
         'Corsa Design 1.2 Turbo, low mileage'),
        ('LJ73PDQ', ('bmw', '3-series', 'saloon-2019'), '2023/73', 26000,
         '318d M Sport, maintained by BMW'),
        ('CG73UHN', ('toyota', 'yaris', 'hatchback-2020'), '2023/73', 15000,
         'Yaris Design Hybrid, Toyota warranty'),
        ('YP73FRT', ('kia', 'sportage', 'suv-2022'), '2023/73', 14000,
         'Sportage 2 1.6 CRDi, remaining Kia 7-year warranty'),
        ('NU73UHN', ('hyundai', 'tucson', 'suv-2021'), '2023/73', 16000,
         'Tucson Advance 1.6T 150'),
        ('PE23JYD', ('mini', 'cooper', 'hatchback-2024'), '2023/73', 9000,
         'MINI Cooper C, Chili pack'),
        ('DG22MSA', ('fiat', '500', 'hatchback-2008'), '2022/22', 8000,
         'Fiat 500 Hybrid, one owner'),
        ('SM73VBN', ('audi', 'a3', 'sportback-2020'), '2023/73', 12000,
         'A3 Sportback 30 TFSI S line, one owner'),
        ('KX73LWQ', ('mercedes-benz', 'c-class', 'saloon-2021'), '2023/73', 15000,
         'C200 AMG Line, Mercedes-Benz service history'),
    ]
    for reg, (mk, mo, gen), yp, mileage, note in regs:
        g = (Generation.query
             .join(CarModel, Generation.model_id == CarModel.id)
             .join(Make, CarModel.make_id == Make.id)
             .filter(Make.slug == mk, CarModel.slug == mo, Generation.slug == gen)
             .first())
        if not g:
            continue
        d = next((x for x in g.derivatives
                  if any(v.year_plate == yp for v in x.valuations)), None)
        if not d:
            continue
        v = next(v for v in d.valuations if v.year_plate == yp)
        db.session.add(RegLookup(reg=reg, valuation_id=v.id, mileage=mileage, note=note))
    db.session.commit()


# ---------------------------------------------------------------------------
# Entry points
# ---------------------------------------------------------------------------

def seed_database():
    from app import (CarModel, Make, db)
    if CarModel.query.count() > 0:
        return
    seed_makes_models_reviews(db, None)
    seed_generations(db, None)
    seed_listings(db, None)
    seed_news(db, None)
    seed_guides(db, None)
    seed_owners(db, None)
    seed_insurance_groups(db, None)
    seed_tax_rates(db, None)
    seed_reg_lookups(db, None)


def seed_benchmark_users():
    from app import (Listing, ShortlistItem, User, Valuation, SavedValuation, db)
    if User.query.filter_by(email='alice.j@test.com').first():
        return
    USERS = [
        {'username': 'alice_j', 'email': 'alice.j@test.com', 'display_name': 'Alice Johnson', 'postcode': 'M1 2AB'},
        {'username': 'bob_c', 'email': 'bob.c@test.com', 'display_name': 'Bob Chen', 'postcode': 'SW1A 1AA'},
        {'username': 'carol_d', 'email': 'carol.d@test.com', 'display_name': 'Carol Davis', 'postcode': 'B1 1BB'},
        {'username': 'david_k', 'email': 'david.k@test.com', 'display_name': 'David Kim', 'postcode': 'EH1 1ZG'},
    ]
    # Frozen bcrypt digest for the benchmark password 'TestPass123!'. The digest
    # is frozen rather than re-generated (Flask-Bcrypt salts every call) so the
    # seed DB is byte-identical on every rebuild — same contract as the other
    # seeded sites (e.g. marriott). Standard Flask-Bcrypt cost factor ($2b$12).
    BENCHMARK_PASSWORD_DIGEST = (
        '$2b$12$0qMKWI0T/dmO2gTZdKo7XekNWEFHKpvW4cJn62t9TMSOIsA6V9oWm'
    )
    for u in USERS:
        user = User(email=u['email'], display_name=u['display_name'], postcode=u['postcode'])
        user.password_hash = BENCHMARK_PASSWORD_DIGEST
        db.session.add(user)
    db.session.flush()

    listings = Listing.query.order_by(Listing.price).all()
    valuations = Valuation.query.order_by(Valuation.id).all()

    def picks(lst, idxs):
        return [lst[i % len(lst)] for i in idxs]

    plan = {
        'alice.j@test.com': ([0, 3, 7], [2, 9]),
        'bob.c@test.com': ([1, 4, 9, 12], [5]),
        'carol.d@test.com': ([2, 5], [11, 17, 23]),
        'david.k@test.com': ([6, 8, 11, 14, 15], [31]),
    }
    for email, (lidx, vidx) in plan.items():
        user = User.query.filter_by(email=email).first()
        for i, l in enumerate(picks(listings, lidx)):
            db.session.add(ShortlistItem(user_id=user.id, listing_id=l.id,
                                         added_at=datetime(2026, 9, 18 + i % 5, 9, 0, 0)))
        for v in picks(valuations, vidx):
            db.session.add(SavedValuation(user_id=user.id, valuation_id=v.id,
                                          saved_at=datetime(2026, 9, 15, 9, 0, 0)))
    db.session.commit()


def normalize_index_layout(db):
    """Re-create every explicit secondary index in a deterministic order.

    SQLAlchemy iterates ``table.indexes`` (a set of Index objects) when it
    issues CREATE INDEX, so the physical root-page assignment of same-table
    indexes varies run to run (object ids feed the set order even with
    PYTHONHASHSEED=0). Dropping and re-creating the indexes sorted by name
    makes the layout — and therefore the seed file bytes — reproducible:
    the freed pages are re-used deterministically from the freelist.
    """
    import sqlalchemy as sa
    inspector = sa.inspect(db.engine)
    existing = {ix['name'] for t in inspector.get_table_names()
                for ix in inspector.get_indexes(t)}
    with db.engine.begin() as conn:
        for table in sorted(db.metadata.tables.values(), key=lambda t: t.name):
            for index in sorted(table.indexes, key=lambda i: i.name):
                if index.name not in existing:
                    continue
                cols = ', '.join(f'"{c.name}"' for c in index.columns)
                conn.exec_driver_sql(f'DROP INDEX IF EXISTS "{index.name}"')
                conn.exec_driver_sql(
                    f'CREATE INDEX "{index.name}" ON "{table.name}" ({cols})')


if __name__ == '__main__':
    # Standalone rebuild: writes instance/parkers.db from the scraped snapshot.
    os.environ.setdefault('PARKERS_DB_PATH', os.path.join(BASE_DIR, 'instance', 'parkers.db'))
    import app as app_module
    with app_module.app.app_context():
        app_module.db.create_all()
        seed_database()
        seed_benchmark_users()
        from app import (CarModel, Derivative, Generation, Listing, Make,
                         NewsArticle, OwnerReview, Valuation)
        print('makes:', Make.query.count())
        print('models:', CarModel.query.count())
        print('generations:', Generation.query.count())
        print('derivatives:', Derivative.query.count())
        print('valuations:', Valuation.query.count())
        print('listings:', Listing.query.count())
        print('news:', NewsArticle.query.count())
        print('owner reviews:', OwnerReview.query.count())
