"""Condition catalog, part B (H–V). Same sourcing rules as part A."""

CONDITIONS_B = [
    {
        "name": "Hyperthyroidism (Overactive Thyroid)", "slug": "hyperthyroidism", "letter": "H",
        "overview": "Hyperthyroidism occurs when the thyroid gland makes more thyroid hormone than the body needs, speeding up metabolism. About 1 in 100 Americans over age 12 have it, women far more often than men.",
        "symptoms": "Unintended weight loss despite normal or increased appetite, rapid or irregular heartbeat, palpitations, nervousness and irritability, tremor, sweating and heat intolerance, more frequent bowel movements, trouble sleeping, and in Graves' disease, bulging eyes.",
        "causes": "Graves' disease (an autoimmune condition) is the most common cause, followed by overactive thyroid nodules, thyroid inflammation (thyroiditis), and taking too much thyroid hormone medicine.",
        "treatments": "Antithyroid medicines (methimazole), radioactive iodine to shrink the gland, or surgery, plus beta-blockers such as atenolol or metoprolol to control racing heartbeat and tremor while hormone levels normalize. Many treated patients eventually need levothyroxine for the resulting underactive thyroid.",
        "related_drug_slugs": ["atenolol", "metoprolol", "levothyroxine"],
        "symptom_slugs": ["weight-loss", "palpitations", "irritability", "trouble-sleeping", "night-sweats"],
    },
    {
        "name": "Hypothyroidism (Underactive Thyroid)", "slug": "hypothyroidism", "letter": "H",
        "overview": "Hypothyroidism means the thyroid gland doesn't make enough thyroid hormone, slowing the body's metabolism. It affects nearly 5 in 100 Americans age 12 and older, most commonly women and people over 60, and is easily treated once found.",
        "symptoms": "Fatigue, weight gain, cold intolerance, constipation, dry skin and hair, hoarseness, muscle weakness and aches, depression, memory problems, heavy or irregular periods, and a slowed heart rate — developing so gradually they're often missed for years.",
        "causes": "Hashimoto's thyroiditis (autoimmune attack on the thyroid) is the leading cause in the U.S. Others: thyroid surgery, radioactive iodine treatment, radiation to the neck, certain medicines (lithium, amiodarone), and iodine imbalance.",
        "treatments": "Daily levothyroxine restores normal hormone levels and reverses symptoms; the dose is fine-tuned with TSH blood tests every 6 to 8 weeks at first, then annually. Take it consistently on an empty stomach, separated from calcium, iron, and antacids by four hours.",
        "related_drug_slugs": ["levothyroxine"],
        "symptom_slugs": ["fatigue", "weight-gain", "constipation", "low-mood", "muscle-aches"],
    },
    {
        "name": "Influenza (Flu)", "slug": "influenza", "letter": "I",
        "overview": "Influenza is a contagious respiratory illness caused by influenza viruses that infect the nose, throat, and lungs. Unlike a cold, flu hits suddenly and hard, and each year in the U.S. it causes millions of illnesses and thousands of deaths, mostly among older adults.",
        "symptoms": "Abrupt fever and chills, body aches, headache, dry cough, sore throat, runny or stuffy nose, marked fatigue, and sometimes vomiting or diarrhea (more common in children). Most people recover in under two weeks; pneumonia is the chief serious complication.",
        "causes": "Influenza A and B viruses spread mainly by respiratory droplets from coughs and sneezes, and by touching contaminated surfaces. People are contagious from a day before symptoms until about 5 to 7 days after onset. Seasonal epidemics peak between December and February.",
        "treatments": "Annual vaccination is the best prevention for everyone 6 months and older. Antiviral drugs (oseltamivir) shorten illness when started within 48 hours and matter most for high-risk patients. Otherwise: rest, fluids, and acetaminophen or ibuprofen for fever and aches — never aspirin for children.",
        "related_drug_slugs": ["acetaminophen", "ibuprofen"],
        "symptom_slugs": ["fever", "muscle-aches", "cough", "fatigue", "headache", "sore-throat"],
    },
    {
        "name": "Insomnia", "slug": "insomnia", "letter": "I",
        "overview": "Insomnia is persistent difficulty falling asleep, staying asleep, or waking too early despite adequate opportunity to sleep, with daytime consequences. About one-third of adults report insomnia symptoms; roughly 10 percent meet criteria for chronic insomnia disorder.",
        "symptoms": "Lying awake 30 minutes or more at bedtime, repeated night awakenings, early-morning waking, unrefreshing sleep, plus daytime fatigue, irritability, poor concentration, and worry about sleep itself.",
        "causes": "Stress, irregular schedules, caffeine, alcohol, and screens at night; medical conditions (pain, reflux, sleep apnea, restless legs), mental health conditions (anxiety, depression), and medicines including some antidepressants, steroids like prednisone, and decongestants.",
        "treatments": "Cognitive behavioral therapy for insomnia (CBT-I) is the recommended first-line treatment and beats pills long-term. Consistent wake times, limiting time in bed awake, and cutting late caffeine and alcohol help. Short-term medication options include low-dose trazodone and other prescription sleep aids; diphenhydramine is discouraged for regular use, especially in older adults.",
        "related_drug_slugs": ["trazodone", "diphenhydramine"],
        "symptom_slugs": ["trouble-sleeping", "fatigue", "irritability"],
    },
    {
        "name": "Irritable Bowel Syndrome (IBS)", "slug": "irritable-bowel-syndrome", "letter": "I",
        "overview": "IBS is a common disorder of gut-brain interaction affecting an estimated 10 to 15 percent of U.S. adults, producing abdominal pain with altered bowel habits. It does not damage the bowel or raise cancer risk, but it can significantly disrupt daily life.",
        "symptoms": "Crampy abdominal pain related to bowel movements, bloating, gas, and diarrhea (IBS-D), constipation (IBS-C), or both alternating (IBS-M). Symptoms often flare with stress or certain meals; blood in stool, weight loss, or nighttime symptoms are NOT typical and warrant evaluation.",
        "causes": "Altered gut-brain signaling, visceral hypersensitivity, changes in gut microbes, and prior gastrointestinal infections. Food intolerances (often fermentable carbohydrates called FODMAPs) and psychological stress amplify symptoms.",
        "treatments": "Dietary strategies — soluble fiber for constipation-type, a dietitian-guided low-FODMAP trial, smaller regular meals — plus stress management and exercise. Loperamide helps diarrhea episodes; laxatives or prescription agents treat IBS-C; antispasmodics and low-dose antidepressants reduce pain signaling.",
        "related_drug_slugs": ["loperamide"],
        "symptom_slugs": ["abdominal-pain", "bloating", "diarrhea", "constipation"],
    },
    {
        "name": "Kidney Stones", "slug": "kidney-stones", "letter": "K",
        "overview": "Kidney stones are hard mineral and salt deposits that form in concentrated urine and can cause excruciating pain when they move into the ureter. About 1 in 10 people will have one, and after a first stone, the 5-year recurrence risk approaches 50 percent without prevention.",
        "symptoms": "Sudden severe pain in the side and back below the ribs that radiates to the lower abdomen and groin and comes in waves, pink or red urine, nausea and vomiting, painful or frequent urination, and fever with chills if infection complicates the blockage.",
        "causes": "Low fluid intake is the biggest factor. Calcium oxalate stones (the most common type) are promoted by high sodium and oxalate intake; uric acid stones by gout and purine-rich diets. Obesity, certain bowel diseases, and family history raise risk.",
        "treatments": "Stones under about 5 mm usually pass with vigorous hydration, NSAIDs such as ibuprofen for pain, and tamsulosin to relax the ureter and speed passage. Larger or stuck stones need shock-wave lithotripsy or ureteroscopy. Prevention: 2.5 to 3 liters of fluid daily, less sodium, normal dietary calcium.",
        "related_drug_slugs": ["ibuprofen", "tamsulosin"],
        "symptom_slugs": ["back-pain", "painful-urination", "nausea", "frequent-urination", "abdominal-pain"],
    },
    {
        "name": "Lactose Intolerance", "slug": "lactose-intolerance", "letter": "L",
        "overview": "Lactose intolerance is the inability to fully digest lactose, the sugar in milk, because the small intestine makes too little of the enzyme lactase. About 36 percent of Americans have some degree of lactose malabsorption; it is uncomfortable but not dangerous.",
        "symptoms": "Bloating, gas, diarrhea, abdominal cramps, and stomach rumbling beginning 30 minutes to 2 hours after consuming dairy. Severity tracks with how much lactose was eaten and how much lactase the person still makes.",
        "causes": "Most commonly a genetically programmed decline in lactase after childhood (especially in people of East Asian, West African, Arab, Jewish, Greek, and Italian descent). It can also appear temporarily after gut infections or with celiac and Crohn's disease.",
        "treatments": "Most people tolerate some dairy: hard cheeses and yogurt are naturally low in lactose, and lactose-free milk works well. Lactase enzyme tablets taken with dairy help, and calcium plus vitamin D from other sources protects bone health.",
        "related_drug_slugs": [],
        "symptom_slugs": ["bloating", "diarrhea", "abdominal-pain"],
    },
    {
        "name": "Migraine", "slug": "migraine", "letter": "M",
        "overview": "Migraine is a neurological disease producing recurrent attacks of moderate-to-severe headache with nausea and sensitivity to light and sound. It affects about 39 million Americans — women three times as often as men — and ranks among the world's leading causes of disability.",
        "symptoms": "Throbbing, often one-sided head pain lasting 4 to 72 hours, worsened by activity, with nausea, vomiting, and light/sound sensitivity. About 1 in 4 people get an 'aura' first — shimmering zigzag lights, blind spots, or tingling. Prodrome symptoms (yawning, food cravings, neck stiffness) can precede attacks by a day.",
        "causes": "A genetically influenced hyperexcitable brain; attacks involve waves of neural activity and release of pain-signaling peptides like CGRP. Common triggers: stress and stress let-down, skipped meals, poor or irregular sleep, hormonal shifts around menstruation, alcohol (especially red wine), aged cheeses, and weather changes.",
        "treatments": "For attacks: NSAIDs such as ibuprofen or naproxen for milder episodes, and triptans like sumatriptan for moderate-to-severe ones, taken early. For frequent migraine: preventive daily medicines (beta-blockers such as metoprolol, certain antidepressants and anticonvulsants) or newer CGRP-targeting drugs, plus regular sleep, meals, hydration, and a headache diary — limit acute medicines to under 10 days per month to avoid rebound headache.",
        "related_drug_slugs": ["sumatriptan", "ibuprofen", "naproxen", "metoprolol"],
        "symptom_slugs": ["headache", "nausea", "vomiting", "blurred-vision", "dizziness"],
    },
    {
        "name": "Obstructive Sleep Apnea", "slug": "sleep-apnea", "letter": "O",
        "overview": "Obstructive sleep apnea (OSA) causes breathing to repeatedly stop and restart during sleep because throat muscles relax and block the airway — sometimes hundreds of times a night. An estimated 25 to 30 million U.S. adults have it, most undiagnosed, and untreated OSA raises risks of hypertension, atrial fibrillation, and daytime accidents.",
        "symptoms": "Loud snoring, witnessed pauses in breathing, gasping or choking awakenings, unrefreshing sleep, morning headaches, dry mouth, excessive daytime sleepiness, irritability, and poor concentration.",
        "causes": "Airway collapse during sleep, promoted by excess weight (the strongest factor), a thick neck, small jaw or large tonsils, male sex, age, alcohol and sedatives before bed, smoking, and nasal congestion. It runs in families.",
        "treatments": "CPAP — a mask delivering gentle air pressure — is the gold-standard treatment and reverses daytime symptoms and blood-pressure effects. Alternatives include custom oral appliances, weight loss (which can be curative), positional therapy, avoiding evening alcohol, and surgery or implanted nerve stimulators for selected patients.",
        "related_drug_slugs": [],
        "symptom_slugs": ["trouble-sleeping", "fatigue", "headache", "irritability"],
    },
    {
        "name": "Osteoarthritis", "slug": "osteoarthritis", "letter": "O",
        "overview": "Osteoarthritis (OA) is the most common form of arthritis, affecting over 32 million U.S. adults. Cartilage cushioning the ends of bones gradually breaks down — most often in the knees, hips, hands, and spine — causing pain and stiffness that worsen over years.",
        "symptoms": "Joint pain during or after movement, stiffness after waking or inactivity that eases within about 30 minutes, tenderness, loss of flexibility, grating sensations, bony enlargements of finger joints, and swelling.",
        "causes": "Age-related wear plus joint injury, repetitive stress, obesity (each extra pound adds about four pounds of knee load), genetics, bone deformities, and female sex. It is a disease of the whole joint, including bone and the joint lining, not just cartilage.",
        "treatments": "Exercise and weight loss are the most effective long-term treatments. Acetaminophen or oral NSAIDs (ibuprofen, naproxen, meloxicam) and topical NSAID gels relieve pain; duloxetine helps chronic OA pain; corticosteroid injections give temporary relief. Joint replacement is highly successful for end-stage hips and knees.",
        "related_drug_slugs": ["acetaminophen", "ibuprofen", "naproxen", "meloxicam", "duloxetine"],
        "symptom_slugs": ["joint-pain", "joint-stiffness", "swelling"],
    },
    {
        "name": "Osteoporosis", "slug": "osteoporosis", "letter": "O",
        "overview": "Osteoporosis silently weakens bones until they break from minor falls or even everyday stresses — most often at the hip, spine, and wrist. About 10 million Americans have it (80 percent women), and one in two women over 50 will suffer an osteoporosis-related fracture.",
        "symptoms": "None until a bone breaks. Clues of spinal compression fractures include gradual height loss (more than an inch), a stooped posture, and sudden back pain. Bone density (DXA) screening is how it's actually found.",
        "causes": "Bone loss outpacing bone formation with age, accelerated by menopausal estrogen decline, low calcium and vitamin D, inactivity, smoking, heavy alcohol use, small body frame, family history, and long-term use of corticosteroids such as prednisone.",
        "treatments": "Weight-bearing and resistance exercise, 1,000 to 1,200 mg calcium and 600 to 800 IU vitamin D daily, fall-proofing the home, and quitting smoking. Bisphosphonate drugs are first-line to cut fracture risk; denosumab and bone-building agents serve higher-risk patients. DXA screening for all women 65+ and younger people with risk factors.",
        "related_drug_slugs": ["prednisone"],
        "symptom_slugs": ["back-pain"],
    },
    {
        "name": "Panic Disorder", "slug": "panic-disorder", "letter": "P",
        "overview": "Panic disorder involves recurrent, unexpected panic attacks — sudden surges of intense fear peaking within minutes — followed by persistent worry about further attacks or avoidance of situations that might trigger them. It affects about 2 to 3 percent of U.S. adults yearly.",
        "symptoms": "During an attack: pounding heart, sweating, trembling, shortness of breath, chest pain, choking sensation, nausea, dizziness, chills or heat, numbness, feelings of unreality, and fear of dying or losing control. Attacks are so physical that many people first go to the ER convinced it's a heart attack.",
        "causes": "Genetics, an overly sensitive threat-detection system (amygdala), major life stress, and temperament. Caffeine, stimulants, and some medical conditions (thyroid disease, heart rhythm problems) can mimic or provoke attacks and should be ruled out.",
        "treatments": "CBT with interoceptive exposure — deliberately practicing the feared body sensations — is highly effective. SSRIs (sertraline, fluoxetine, escitalopram) and SNRIs (venlafaxine) prevent attacks; benzodiazepines such as alprazolam act fast but are limited to short-term use because of dependence. Limiting caffeine and learning slow-breathing techniques help.",
        "related_drug_slugs": ["sertraline", "fluoxetine", "escitalopram", "venlafaxine", "alprazolam", "lorazepam"],
        "symptom_slugs": ["palpitations", "chest-pain", "shortness-of-breath", "dizziness", "excessive-worry"],
    },
    {
        "name": "Peptic Ulcer Disease", "slug": "peptic-ulcer-disease", "letter": "P",
        "overview": "Peptic ulcers are open sores in the lining of the stomach or the first part of the small intestine (duodenum). Roughly 1 in 10 people develops one during their lifetime — and contrary to old belief, stress and spicy food don't cause them; bacteria and pain relievers do.",
        "symptoms": "Burning or gnawing stomach pain between the breastbone and navel — often on an empty stomach and relieved (duodenal) or worsened (gastric) by eating — plus bloating, heartburn, and nausea. Black tarry stools, vomiting blood, or severe sudden pain signal bleeding or perforation: emergencies.",
        "causes": "Helicobacter pylori infection and regular use of NSAIDs such as ibuprofen, naproxen, and aspirin account for the vast majority. Smoking and heavy alcohol impair healing; rare acid-hypersecretion syndromes cause the rest.",
        "treatments": "Proton pump inhibitors such as omeprazole or pantoprazole heal most ulcers in 4 to 8 weeks. H. pylori, when present, is eradicated with a 14-day combination of a PPI plus antibiotics (commonly amoxicillin and clarithromycin), confirmed by follow-up testing. Stop NSAIDs where possible; famotidine is an alternative acid reducer.",
        "related_drug_slugs": ["omeprazole", "pantoprazole", "famotidine", "amoxicillin"],
        "symptom_slugs": ["abdominal-pain", "heartburn", "nausea", "bloating"],
    },
    {
        "name": "Plantar Fasciitis", "slug": "plantar-fasciitis", "letter": "P",
        "overview": "Plantar fasciitis is inflammation and degeneration of the thick band of tissue (plantar fascia) running along the bottom of the foot from heel to toes. It is the most common cause of heel pain, producing about a million doctor visits per year, and usually resolves with conservative care — though often over months.",
        "symptoms": "Stabbing pain at the bottom of the heel with the first steps after waking or after sitting, easing as you move, then returning after long standing or exercise. Tenderness where the fascia meets the heel bone.",
        "causes": "Repetitive strain on the fascia from running, prolonged standing on hard surfaces, tight calf muscles, high arches or flat feet, unsupportive footwear, obesity, and age 40 to 60.",
        "treatments": "Calf and plantar-fascia stretching several times daily is the core treatment, plus supportive shoes or over-the-counter arch supports, activity modification, ice massage, and NSAIDs such as ibuprofen or naproxen for pain. Night splints, physical therapy, and corticosteroid injections help stubborn cases; more than 90 percent recover without surgery.",
        "related_drug_slugs": ["ibuprofen", "naproxen"],
        "symptom_slugs": ["joint-pain", "muscle-aches"],
    },
    {
        "name": "Pneumonia", "slug": "pneumonia", "letter": "P",
        "overview": "Pneumonia is an infection that inflames the air sacs of one or both lungs, which may fill with fluid or pus. Severity ranges from mild to life-threatening; it is most dangerous for infants, adults over 65, and people with weakened immune systems or chronic disease.",
        "symptoms": "Cough with phlegm, fever, chills, and shortness of breath, plus chest pain that sharpens with breathing or coughing, fatigue, and in older adults sometimes confusion with a lower-than-normal temperature instead of fever.",
        "causes": "Bacteria (Streptococcus pneumoniae is the classic culprit), viruses including influenza, RSV, and COVID-19, and less often fungi. Risk rises with smoking, recent viral illness, chronic lung or heart disease, and swallowing problems.",
        "treatments": "Bacterial pneumonia is treated with antibiotics — commonly amoxicillin, doxycycline, or azithromycin for outpatient community-acquired cases — plus rest, fluids, and fever control with acetaminophen or ibuprofen. Hospital care with oxygen for severe cases. Pneumococcal and flu vaccines prevent many cases.",
        "related_drug_slugs": ["amoxicillin", "azithromycin", "doxycycline", "acetaminophen"],
        "symptom_slugs": ["cough", "fever", "shortness-of-breath", "chest-pain", "fatigue"],
    },
    {
        "name": "Psoriasis", "slug": "psoriasis", "letter": "P",
        "overview": "Psoriasis is a chronic immune-mediated disease that speeds skin cell turnover from weeks to days, piling cells into thick scaly plaques. It affects more than 7.5 million U.S. adults, is not contagious, and up to 30 percent of patients also develop psoriatic arthritis.",
        "symptoms": "Raised red patches covered with silvery-white scale — classically on the elbows, knees, scalp, and lower back — itching or burning, thickened or pitted nails, and cyclical flares. Joint pain, stiffness, and swelling suggest psoriatic arthritis.",
        "causes": "An overactive immune response (involving T cells and cytokines like TNF and IL-17/23) in genetically predisposed people. Flares are triggered by stress, skin injury, strep throat, cold dry weather, smoking, heavy alcohol, and certain medicines including lithium and beta-blockers.",
        "treatments": "Topical corticosteroids and vitamin D analogs for limited disease; phototherapy for wider involvement; and for moderate-to-severe psoriasis, systemic agents — methotrexate, apremilast, and highly effective biologic injections targeting TNF or IL-17/23. Moisturizers, stress management, and trigger avoidance support all stages.",
        "related_drug_slugs": [],
        "symptom_slugs": ["rash", "itching", "joint-pain"],
    },
    {
        "name": "Restless Legs Syndrome", "slug": "restless-legs-syndrome", "letter": "R",
        "overview": "Restless legs syndrome (RLS) is a neurological disorder causing an irresistible urge to move the legs, usually with uncomfortable crawling or pulling sensations, worse in the evening and at rest. It affects up to 7 to 10 percent of Americans and is a major hidden cause of insomnia.",
        "symptoms": "An urge to move the legs with creeping, tingling, or aching sensations that begin during rest, are worse at night, and are relieved — temporarily — by movement such as walking or stretching. Most patients also have involuntary leg kicks during sleep.",
        "causes": "Dysfunction in brain dopamine signaling and brain iron handling; it runs strongly in families. Iron deficiency, pregnancy, kidney failure, and certain drugs — including many antidepressants and sedating antihistamines like diphenhydramine — can cause or worsen it.",
        "treatments": "Check and replenish iron stores (ferritin) first. Regular moderate exercise, leg massage, warm baths, and consistent sleep help mild cases. For persistent RLS, gabapentinoids such as gabapentin or pregabalin are now preferred first-line medicines; dopamine agonists work but can worsen symptoms over time (augmentation).",
        "related_drug_slugs": ["gabapentin", "pregabalin"],
        "symptom_slugs": ["trouble-sleeping", "numbness-tingling", "muscle-aches"],
    },
    {
        "name": "Rheumatoid Arthritis", "slug": "rheumatoid-arthritis", "letter": "R",
        "overview": "Rheumatoid arthritis (RA) is a chronic autoimmune disease in which the immune system attacks the lining of the joints, causing painful swelling that can erode bone and deform joints — typically symmetrically, in the small joints of the hands and feet. About 1.3 million U.S. adults have RA; early aggressive treatment prevents most joint damage.",
        "symptoms": "Tender, warm, swollen joints on both sides of the body, morning stiffness lasting an hour or more (a key difference from osteoarthritis), fatigue, low-grade fever, and loss of appetite. RA can also affect the skin, eyes, lungs, heart, and blood vessels.",
        "causes": "Autoimmunity in genetically susceptible people (HLA gene variants), with smoking the strongest modifiable risk factor. Women are affected two to three times as often; onset is most common in middle age. Hormonal factors and gum disease bacteria are under study.",
        "treatments": "Disease-modifying antirheumatic drugs (DMARDs) — methotrexate first — started early, escalating to biologics or JAK inhibitors as needed to reach remission. NSAIDs such as naproxen or meloxicam and short prednisone courses bridge symptom control while DMARDs take effect. Regular monitoring, exercise, and joint protection round out care.",
        "related_drug_slugs": ["naproxen", "meloxicam", "prednisone", "ibuprofen"],
        "symptom_slugs": ["joint-pain", "joint-stiffness", "swelling", "fatigue", "fever"],
    },
    {
        "name": "Rosacea", "slug": "rosacea", "letter": "R",
        "overview": "Rosacea is a common chronic skin condition causing facial redness, flushing, and acne-like bumps, typically starting between ages 30 and 50 in fair-skinned adults. An estimated 14 million Americans have it; it cannot be cured but is very manageable.",
        "symptoms": "Persistent redness across the cheeks, nose, chin, and forehead, easy flushing, visible small blood vessels, red bumps and pus-filled pimples without blackheads, burning or stinging skin, eye irritation (ocular rosacea), and in advanced cases a thickened bumpy nose (rhinophyma).",
        "causes": "Not fully known: an overreactive facial blood-vessel and innate-immune response, Demodex skin mites, and genetics all contribute. Classic flare triggers include sun, heat, wind, hot beverages, spicy food, alcohol (especially red wine), exercise, stress, and some skin products.",
        "treatments": "Daily broad-spectrum sunscreen and gentle skin care, plus a personal trigger diary. Prescription topical treatments (metronidazole, azelaic acid, ivermectin) control bumps; low-dose oral doxycycline treats moderate-to-severe papules; vessel-targeting laser therapy reduces persistent redness.",
        "related_drug_slugs": ["doxycycline"],
        "symptom_slugs": ["rash", "itching"],
    },
    {
        "name": "Shingles (Herpes Zoster)", "slug": "shingles", "letter": "S",
        "overview": "Shingles is a painful blistering rash caused by reactivation of the varicella-zoster virus — the same virus that causes chickenpox — which lies dormant in nerve cells for decades. About 1 in 3 Americans will get shingles; the risk and severity climb sharply after age 50.",
        "symptoms": "Burning, tingling, or stabbing pain in a band on one side of the body or face, followed in days by a stripe of fluid-filled blisters that crust over within 7 to 10 days. Fever, headache, and fatigue may accompany it. Pain persisting months after the rash — postherpetic neuralgia — is the most common complication.",
        "causes": "Reactivation of dormant chickenpox virus when immunity wanes with age, stress, or immune-suppressing illness or medicines. You cannot catch shingles, but someone with active blisters can give chickenpox to a non-immune person.",
        "treatments": "Antiviral drugs (valacyclovir or acyclovir) started within 72 hours of the rash speed healing and reduce complications. Pain control ranges from acetaminophen and NSAIDs to gabapentin for nerve pain; postherpetic neuralgia is treated with gabapentin, pregabalin, or duloxetine. The Shingrix vaccine (two doses, adults 50+) is over 90 percent effective at prevention.",
        "related_drug_slugs": ["gabapentin", "pregabalin", "acetaminophen", "duloxetine"],
        "symptom_slugs": ["rash", "numbness-tingling", "fever", "headache", "itching"],
    },
    {
        "name": "Sinusitis (Sinus Infection)", "slug": "sinusitis", "letter": "S",
        "overview": "Sinusitis is inflammation of the tissue lining the sinuses, usually following a cold, that blocks drainage and traps mucus. Acute sinusitis affects millions of Americans yearly; most cases are viral and clear on their own within 10 days.",
        "symptoms": "Facial pressure or pain around the cheeks, eyes, and forehead that worsens when bending forward, thick yellow-green nasal discharge, congestion, reduced smell, post-nasal drip, cough, headache, tooth pressure, and fatigue.",
        "causes": "Viral upper respiratory infections cause the great majority; bacteria are suspected only when symptoms last more than 10 days, are unusually severe, or improve and then worsen again ('double sickening'). Allergies, nasal polyps, and a deviated septum predispose to blockage; chronic sinusitis lasts 12 weeks or more.",
        "treatments": "Saline rinses, steam, hydration, intranasal steroid sprays such as fluticasone, and pain relief with acetaminophen or ibuprofen manage most cases. Amoxicillin-based antibiotics are reserved for likely bacterial infections. Chronic sinusitis needs steroid sprays long-term, allergy management, and sometimes endoscopic surgery.",
        "related_drug_slugs": ["fluticasone-nasal", "acetaminophen", "ibuprofen", "amoxicillin"],
        "symptom_slugs": ["nasal-congestion", "headache", "runny-nose", "cough", "fever"],
    },
    {
        "name": "Strep Throat", "slug": "strep-throat", "letter": "S",
        "overview": "Strep throat is a bacterial infection of the throat and tonsils caused by group A Streptococcus. It is most common in children 5 to 15 but affects adults too, and unlike viral sore throats it warrants antibiotics — both to speed recovery and to prevent rheumatic fever.",
        "symptoms": "Sudden severe sore throat with pain on swallowing, fever, red swollen tonsils often with white patches or streaks, tiny red spots on the roof of the mouth, swollen tender neck glands, and headache. Notably absent: cough and runny nose, which point to a virus instead.",
        "causes": "Group A strep bacteria spread through respiratory droplets and shared food or drinks. It spreads readily in schools and households; untreated people are contagious for two to three weeks.",
        "treatments": "Diagnosis by rapid strep test or throat culture, then a 10-day course of penicillin or amoxicillin (azithromycin or cephalexin for penicillin-allergic patients). Acetaminophen or ibuprofen ease pain and fever; salt-water gargles and cold liquids soothe. Patients stop being contagious about 24 hours after starting antibiotics.",
        "related_drug_slugs": ["amoxicillin", "azithromycin", "cephalexin", "acetaminophen", "ibuprofen"],
        "symptom_slugs": ["sore-throat", "fever", "headache"],
    },
    {
        "name": "Stroke", "slug": "stroke", "letter": "S",
        "overview": "A stroke happens when blood flow to part of the brain is cut off — by a clot (ischemic, about 87 percent of cases) or a burst vessel (hemorrhagic) — and brain cells begin dying within minutes. Someone in the U.S. has a stroke every 40 seconds; fast treatment dramatically improves outcomes, so every minute counts.",
        "symptoms": "Remember F.A.S.T.: Face drooping, Arm weakness, Speech difficulty, Time to call 911. Other sudden signs: numbness on one side, confusion, trouble seeing, dizziness or loss of balance, and severe headache with no known cause. A 'mini-stroke' (TIA) with symptoms that resolve is an urgent warning, not a relief.",
        "causes": "Ischemic strokes arise from atherosclerosis and from heart clots — atrial fibrillation is a major source. Key risk factors: high blood pressure (the biggest), smoking, diabetes, high cholesterol, obesity, inactivity, and heavy drinking. Hemorrhagic strokes stem from uncontrolled hypertension and aneurysms.",
        "treatments": "Emergency clot-busting drugs (tPA within 4.5 hours) or mechanical clot removal for ischemic stroke — which is why calling 911 immediately matters. Prevention afterward: blood pressure control (lisinopril, amlodipine), statins such as atorvastatin, antiplatelets (aspirin, clopidogrel) or anticoagulants (apixaban, warfarin) for AFib, plus rehabilitation therapy to recover function.",
        "related_drug_slugs": ["aspirin", "clopidogrel", "apixaban", "warfarin", "atorvastatin", "lisinopril"],
        "symptom_slugs": ["numbness-tingling", "dizziness", "headache", "blurred-vision"],
    },
    {
        "name": "Tension Headache", "slug": "tension-headache", "letter": "T",
        "overview": "Tension-type headache is the most common headache disorder — most people experience one at some point. It produces mild-to-moderate, pressing pain without the nausea and disabling qualities of migraine, and is usually managed with simple measures.",
        "symptoms": "Dull, aching head pain with a sensation of tightness or pressure like a band across the forehead or around the back of the head and neck, tenderness of the scalp and shoulder muscles, and no more than mild sensitivity to light or noise. Unlike migraine, routine activity doesn't worsen it.",
        "causes": "Not fully understood: heightened sensitivity of pain pathways plus muscle tension. Common contributors are stress, poor posture and long screen sessions, skipped meals, dehydration, eye strain, jaw clenching, and irregular sleep.",
        "treatments": "OTC pain relievers — ibuprofen, acetaminophen, naproxen, or aspirin — work for episodic attacks, but limit them to fewer than 10 to 15 days a month to avoid medication-overuse headache. Prevention: regular exercise, stress management, posture breaks, consistent sleep and meals; frequent sufferers may benefit from low-dose amitriptyline and relaxation training.",
        "related_drug_slugs": ["ibuprofen", "acetaminophen", "naproxen", "aspirin"],
        "symptom_slugs": ["headache", "muscle-aches"],
    },
    {
        "name": "Ulcerative Colitis", "slug": "ulcerative-colitis", "letter": "U",
        "overview": "Ulcerative colitis (UC) is a chronic inflammatory bowel disease causing continuous inflammation and open sores in the innermost lining of the colon and rectum. Like Crohn's disease it cycles through flares and remissions, but it is limited to the colon — which also means surgery can be curative.",
        "symptoms": "Diarrhea, often with blood or pus, abdominal cramping, rectal pain and urgency, feeling unable to empty the bowel, fatigue, weight loss, and fever during flares. Long-standing extensive colitis raises colon cancer risk, so surveillance colonoscopies are scheduled.",
        "causes": "An abnormal immune response against colon lining and gut microbes in genetically predisposed people; up to 20 percent of patients have an affected close relative. Diet and stress can aggravate flares but do not cause the disease. Curiously, it is more common in ex-smokers.",
        "treatments": "Aminosalicylates (mesalamine) induce and maintain remission in mild-to-moderate UC; corticosteroids such as prednisone quiet flares but aren't for maintenance; biologics and JAK inhibitors treat moderate-to-severe disease. Removing the colon cures refractory or precancerous cases. Loperamide is used cautiously and never during severe flares.",
        "related_drug_slugs": ["prednisone", "loperamide"],
        "symptom_slugs": ["diarrhea", "abdominal-pain", "fatigue", "weight-loss", "fever"],
    },
    {
        "name": "Urinary Tract Infection (UTI)", "slug": "urinary-tract-infection", "letter": "U",
        "overview": "A urinary tract infection is a bacterial infection anywhere in the urinary system, most commonly the bladder (cystitis). UTIs drive over 8 million U.S. medical visits annually; more than half of women will have at least one, and prompt treatment keeps infections from reaching the kidneys.",
        "symptoms": "Burning with urination, frequent urges to urinate with little output, cloudy, strong-smelling, or pink-tinged urine, and pelvic pressure. Fever, chills, back or flank pain, and nausea suggest a kidney infection — see a clinician urgently. Older adults may show only new confusion.",
        "causes": "Bacteria — usually E. coli from the digestive tract — entering the urethra and multiplying in the bladder. Risk factors include female anatomy (a short urethra), sexual activity, certain contraceptives (spermicides, diaphragms), menopause, catheters, kidney stones, enlarged prostate, and diabetes.",
        "treatments": "Short antibiotic courses cure uncomplicated bladder infections — first-line agents include nitrofurantoin and trimethoprim-sulfamethoxazole; ciprofloxacin is reserved for complicated cases. Drink plenty of water, and use acetaminophen or ibuprofen for discomfort. For frequent recurrences: hydration, urinating after sex, and preventive strategies discussed with your clinician.",
        "related_drug_slugs": ["ciprofloxacin", "acetaminophen", "ibuprofen"],
        "symptom_slugs": ["painful-urination", "frequent-urination", "fever", "back-pain", "abdominal-pain"],
    },
    {
        "name": "Vertigo (BPPV)", "slug": "vertigo-bppv", "letter": "V",
        "overview": "Benign paroxysmal positional vertigo (BPPV) is the most common cause of vertigo — brief, intense spinning sensations set off by changes in head position, such as rolling over in bed or looking up. It is unpleasant but usually harmless and highly fixable with simple repositioning maneuvers.",
        "symptoms": "Spinning dizziness lasting under a minute triggered by moving the head, unsteadiness, nausea and occasionally vomiting, and jerking eye movements during episodes. Hearing loss, persistent vertigo, weakness, or trouble speaking are NOT typical of BPPV and need medical evaluation.",
        "causes": "Tiny calcium carbonate crystals (otoconia) dislodge from their normal spot in the inner ear and tumble into a semicircular canal, sending false motion signals. Head trauma, age-related degeneration, prolonged lying down, and inner-ear disorders can set it off.",
        "treatments": "The Epley maneuver — a guided sequence of head positions that steers the crystals back where they belong — cures most cases in one to three sessions and can be taught for home use. Anti-nausea medicine such as ondansetron or an antihistamine helps short-term; vestibular suppressants are avoided long-term because they delay natural compensation.",
        "related_drug_slugs": ["ondansetron", "diphenhydramine"],
        "symptom_slugs": ["dizziness", "nausea", "vomiting"],
    },
]
