"""Drug catalog, part B (thyroid, GI, mental health, allergy/respiratory,
neurology, men's health).

Same sourcing rules as part A: structured facts from openFDA labeling
(public domain, snapshots in scraped_data/openfda/), original prose.
"""

DRUGS_B = [
    {
        "name": "Levothyroxine", "slug": "levothyroxine",
        "generic_name": "levothyroxine sodium",
        "brand_names": "Synthroid, Levoxyl, Unithroid",
        "drug_class": "Thyroid Hormone Replacement",
        "category": "Hormones & Thyroid",
        "uses": "Replaces the hormone your thyroid gland no longer makes enough of, treating hypothyroidism, and suppresses TSH in certain thyroid cancers and goiters. It restores normal energy, metabolism, and body temperature regulation.",
        "dosage": "Individualized by TSH blood tests; full replacement in adults is about 1.6 mcg/kg once daily (roughly 100 to 125 mcg for many adults). Take on an empty stomach with water, 30 to 60 minutes before breakfast, at the same time every day.",
        "side_effects_common": "At the correct dose, few — hair thinning may occur in the first months. Symptoms of over-replacement include palpitations, weight loss, tremor, insomnia, and heat intolerance.",
        "side_effects_serious": "Chest pain or irregular heart rhythm from excessive dosing, and bone density loss with long-term over-replacement.",
        "interactions": "Calcium, iron, antacids, and proton pump inhibitors such as omeprazole reduce absorption — separate by 4 hours. Soy, coffee, and high-fiber meals also interfere. Warfarin effect may increase as thyroid levels normalize.",
        "warnings": "Boxed warning: thyroid hormone is not a weight-loss drug and is dangerous when used for that purpose. Doses look tiny (micrograms) but small changes matter — never switch brands or skip blood tests without telling your doctor.",
    },
    {
        "name": "Omeprazole", "slug": "omeprazole",
        "generic_name": "omeprazole",
        "brand_names": "Prilosec, Prilosec OTC",
        "drug_class": "Proton Pump Inhibitor (PPI)",
        "category": "Digestive Health",
        "uses": "Treats frequent heartburn, gastroesophageal reflux disease (GERD), erosive esophagitis, and stomach and duodenal ulcers, and is part of regimens to eradicate H. pylori. It shuts down the stomach's acid-producing pumps.",
        "dosage": "For frequent heartburn (OTC): 20 mg once daily before breakfast for 14 days; the course may be repeated every 4 months. Prescription GERD dosing is 20 to 40 mg daily for 4 to 8 weeks. Swallow whole — do not crush or chew delayed-release forms.",
        "side_effects_common": "Headache, abdominal pain, nausea, diarrhea, and gas.",
        "side_effects_serious": "Low magnesium with long-term use, vitamin B12 deficiency, increased risk of C. difficile infection, bone fractures with high-dose long-term therapy, and kidney inflammation.",
        "interactions": "Clopidogrel (omeprazole blunts its antiplatelet effect — a clinically important combination to avoid), methotrexate, diazepam, and drugs needing stomach acid to absorb, such as certain antifungals.",
        "warnings": "OTC use is limited to a 14-day course up to three times a year — see a doctor if heartburn persists, or if you have alarm symptoms like trouble swallowing, vomiting blood, or unintended weight loss.",
    },
    {
        "name": "Esomeprazole", "slug": "esomeprazole",
        "generic_name": "esomeprazole magnesium",
        "brand_names": "Nexium, Nexium 24HR",
        "drug_class": "Proton Pump Inhibitor (PPI)",
        "category": "Digestive Health",
        "uses": "Treats GERD, heals erosive esophagitis, reduces the risk of NSAID-associated stomach ulcers, and is used with antibiotics for H. pylori. It is the S-isomer of omeprazole.",
        "dosage": "Adults with GERD: 20 to 40 mg once daily for 4 to 8 weeks, taken at least one hour before a meal. The OTC 20 mg product follows the same 14-day-course rules as omeprazole.",
        "side_effects_common": "Headache, diarrhea, nausea, gas, and dry mouth.",
        "side_effects_serious": "Same class risks as other PPIs: low magnesium, B12 deficiency, C. difficile diarrhea, fracture risk with prolonged high-dose use, and acute kidney inflammation.",
        "interactions": "Clopidogrel (reduced activation — avoid combining), certain HIV drugs such as rilpivirine (contraindicated), methotrexate, and warfarin.",
        "warnings": "Long-term users should periodically review with a doctor whether continued acid suppression is needed, and report muscle spasms, tremor, or irregular heartbeat, which can signal low magnesium.",
    },
    {
        "name": "Pantoprazole", "slug": "pantoprazole",
        "generic_name": "pantoprazole sodium",
        "brand_names": "Protonix",
        "drug_class": "Proton Pump Inhibitor (PPI)",
        "category": "Digestive Health",
        "uses": "Treats erosive esophagitis associated with GERD and conditions of excess stomach acid such as Zollinger-Ellison syndrome. Because it interferes less with clopidogrel than omeprazole does, it is often the PPI chosen for heart patients.",
        "dosage": "Adults: 40 mg once daily for up to 8 weeks for erosive esophagitis, taken with or without food. Tablets must be swallowed whole.",
        "side_effects_common": "Headache, diarrhea, nausea, abdominal pain, and joint pain.",
        "side_effects_serious": "Low magnesium, C. difficile-associated diarrhea, kidney inflammation, lupus-like reactions, and fracture risk with long-term high-dose use.",
        "interactions": "Methotrexate, warfarin, and drugs that need stomach acid for absorption (ketoconazole, iron salts, certain HIV medicines). Minimal interaction with clopidogrel compared with omeprazole.",
        "warnings": "Tell your doctor about persistent watery stools, new joint pain with rash on sun-exposed skin, or symptoms of low magnesium such as muscle cramps and palpitations.",
    },
    {
        "name": "Famotidine", "slug": "famotidine",
        "generic_name": "famotidine",
        "brand_names": "Pepcid, Pepcid AC",
        "drug_class": "Histamine-2 (H2) Receptor Blocker",
        "category": "Digestive Health",
        "uses": "Relieves and prevents heartburn from acid indigestion, and at prescription doses treats ulcers and GERD. It works faster than PPIs (within an hour) but suppresses acid less profoundly, making it a good option for occasional symptoms.",
        "dosage": "OTC for heartburn: 10 to 20 mg once or twice daily, taken 15 to 60 minutes before food or drink that causes symptoms; maximum 2 tablets in 24 hours. Prescription ulcer dosing is typically 20 mg twice daily or 40 mg at bedtime.",
        "side_effects_common": "Headache, dizziness, constipation, and diarrhea.",
        "side_effects_serious": "Confusion or agitation in elderly patients and those with kidney impairment, irregular heart rhythm at high IV doses, and rare blood-cell effects.",
        "interactions": "Drugs requiring stomach acid for absorption such as certain antifungals and the HIV drug atazanavir; otherwise few significant interactions — one reason it is preferred over older H2 blockers.",
        "warnings": "Doses must be lowered in kidney disease. See a doctor if heartburn persists beyond 14 days of self-treatment or comes with trouble swallowing, chest pain spreading to the arm, or black stools.",
    },
    {
        "name": "Ondansetron", "slug": "ondansetron",
        "generic_name": "ondansetron hydrochloride",
        "brand_names": "Zofran, Zofran ODT",
        "drug_class": "Serotonin-3 (5-HT3) Receptor Antagonist",
        "category": "Digestive Health",
        "uses": "Prevents nausea and vomiting caused by chemotherapy, radiation therapy, and surgery. It blocks serotonin signals in the gut and brain that trigger the vomiting reflex.",
        "dosage": "Adults: 8 mg by mouth 30 minutes before chemotherapy, repeated 8 hours later, then 8 mg every 12 hours for 1 to 2 days. For post-surgical nausea: 16 mg one hour before anesthesia. Orally disintegrating tablets dissolve on the tongue without water.",
        "side_effects_common": "Headache, constipation, fatigue, and dizziness.",
        "side_effects_serious": "QT-interval prolongation with risk of a dangerous heart rhythm (torsades de pointes), serotonin syndrome when combined with serotonergic drugs, and allergic reactions.",
        "interactions": "Other QT-prolonging drugs (azithromycin, certain antipsychotics), serotonergic antidepressants such as sertraline and venlafaxine, apomorphine (contraindicated), and tramadol (reduced effect of both).",
        "warnings": "People with congenital long QT syndrome should not use ondansetron. Tell your doctor about heart disease, low potassium or magnesium, or any fainting episodes before taking it.",
    },
    {
        "name": "Loperamide", "slug": "loperamide",
        "generic_name": "loperamide hydrochloride",
        "brand_names": "Imodium A-D",
        "drug_class": "Antidiarrheal (Mu-Opioid Agonist, Peripheral)",
        "category": "Digestive Health",
        "uses": "Controls the symptoms of acute diarrhea, including traveler's diarrhea, and reduces the number of ostomy discharges. It slows intestinal movement so the body can absorb more fluid.",
        "dosage": "Adults: 4 mg (two 2 mg caplets) after the first loose stool, then 2 mg after each subsequent loose stool. Do not exceed 8 mg in 24 hours for OTC use (16 mg under a doctor's direction). Drink plenty of clear fluids to prevent dehydration.",
        "side_effects_common": "Constipation, dizziness, abdominal cramps, and nausea.",
        "side_effects_serious": "At doses far above the label — often from misuse — life-threatening heart rhythm problems including torsades de pointes and cardiac arrest; also toxic megacolon in colitis.",
        "interactions": "Drugs that raise loperamide levels such as ritonavir, quinidine, and itraconazole, and other QT-prolonging medicines.",
        "warnings": "Boxed warning: taking more than directed can cause serious heart problems and death. Do not use with bloody or black stools or a fever over 101°F — these suggest an infection needing medical care.",
    },
    {
        "name": "Sertraline", "slug": "sertraline",
        "generic_name": "sertraline hydrochloride",
        "brand_names": "Zoloft",
        "drug_class": "Selective Serotonin Reuptake Inhibitor (SSRI)",
        "category": "Mental Health",
        "uses": "Treats major depressive disorder, panic disorder, obsessive-compulsive disorder, post-traumatic stress disorder, social anxiety disorder, and premenstrual dysphoric disorder. One of the most widely prescribed antidepressants in the United States.",
        "dosage": "Adults with depression: started at 50 mg once daily, adjustable in 25 to 50 mg steps at intervals of at least one week, up to 200 mg daily. Panic disorder often starts at 25 mg. Full effect typically takes 4 to 6 weeks.",
        "side_effects_common": "Nausea, diarrhea, insomnia or drowsiness, dry mouth, increased sweating, tremor, and sexual side effects.",
        "side_effects_serious": "Serotonin syndrome, increased bleeding risk (especially with NSAIDs or blood thinners), low sodium in older adults, activation of mania, and worsening suicidal thoughts in people under 25 early in treatment.",
        "interactions": "MAO inhibitors (contraindicated — 14-day washout required), tramadol and triptans such as sumatriptan (serotonin syndrome risk), NSAIDs and warfarin (bleeding), and pimozide (contraindicated).",
        "warnings": "Boxed warning: antidepressants increase the risk of suicidal thinking in children, adolescents, and young adults — watch closely for mood changes early in treatment. Do not stop abruptly; taper to avoid discontinuation symptoms.",
    },
    {
        "name": "Fluoxetine", "slug": "fluoxetine",
        "generic_name": "fluoxetine hydrochloride",
        "brand_names": "Prozac",
        "drug_class": "Selective Serotonin Reuptake Inhibitor (SSRI)",
        "category": "Mental Health",
        "uses": "Treats major depression, obsessive-compulsive disorder, bulimia nervosa, and panic disorder. Its very long half-life makes missed doses more forgiving and abrupt discontinuation symptoms milder than other SSRIs.",
        "dosage": "Adults with depression: 20 mg every morning to start, up to 80 mg daily. Because the drug and its active metabolite stay in the body for weeks, dose changes are spaced at least 1 to 2 weeks apart.",
        "side_effects_common": "Insomnia, nausea, nervousness or anxiety, headache, decreased appetite, and sexual side effects.",
        "side_effects_serious": "Serotonin syndrome, severe rash or allergic events, low sodium, QT prolongation at high doses, activation of mania, and increased suicidal thoughts in young people.",
        "interactions": "MAO inhibitors (contraindicated, with a 5-week washout after stopping fluoxetine), thioridazine and pimozide (contraindicated), tramadol, triptans, NSAIDs and blood thinners, and drugs metabolized by CYP2D6 such as metoprolol.",
        "warnings": "Carries the SSRI boxed warning for suicidality in patients under 25. Because it lingers in the body, interactions can occur weeks after the last dose — tell any new prescriber you recently took fluoxetine.",
    },
    {
        "name": "Escitalopram", "slug": "escitalopram",
        "generic_name": "escitalopram oxalate",
        "brand_names": "Lexapro",
        "drug_class": "Selective Serotonin Reuptake Inhibitor (SSRI)",
        "category": "Mental Health",
        "uses": "Treats major depressive disorder and generalized anxiety disorder. It is the purified active isomer of citalopram and is often chosen for its relatively clean interaction profile and tolerability.",
        "dosage": "Adults: 10 mg once daily, morning or evening, which may be increased to a maximum of 20 mg daily after at least one week. Older adults and those with liver impairment should stay at 10 mg.",
        "side_effects_common": "Nausea, insomnia or sleepiness, increased sweating, fatigue, and sexual side effects.",
        "side_effects_serious": "Serotonin syndrome, dose-dependent QT-interval prolongation, low sodium in older adults, abnormal bleeding, and increased suicidal thinking in young people.",
        "interactions": "MAO inhibitors and pimozide (contraindicated), other QT-prolonging drugs such as ondansetron, tramadol and triptans, and NSAIDs or anticoagulants.",
        "warnings": "Carries the SSRI boxed warning for suicidality under age 25. Report fainting, palpitations, or a personal or family history of long QT syndrome before starting.",
    },
    {
        "name": "Bupropion", "slug": "bupropion",
        "generic_name": "bupropion hydrochloride",
        "brand_names": "Wellbutrin XL, Wellbutrin SR, Zyban",
        "drug_class": "Norepinephrine-Dopamine Reuptake Inhibitor (Aminoketone Antidepressant)",
        "category": "Mental Health",
        "uses": "Treats major depression and seasonal affective disorder, and helps people quit smoking (as Zyban). Unlike SSRIs it rarely causes sexual side effects or weight gain, and tends to be energizing.",
        "dosage": "Extended-release (XL): 150 mg once each morning, increased to 300 mg daily after at least 4 days. Sustained-release (SR): 150 mg once daily, then twice daily, with doses at least 8 hours apart. Maximum 450 mg per day.",
        "side_effects_common": "Dry mouth, insomnia, headache, agitation, nausea, tremor, and decreased appetite.",
        "side_effects_serious": "Seizures (dose-related — the key class risk), elevated blood pressure, activation of mania, angle-closure glaucoma, and neuropsychiatric symptoms during smoking cessation.",
        "interactions": "MAO inhibitors (contraindicated), other seizure-threshold-lowering drugs, and CYP2D6-metabolized drugs such as metoprolol and certain antidepressants whose levels it raises.",
        "warnings": "Do not use if you have a seizure disorder, a current or prior eating disorder (anorexia or bulimia), or are abruptly stopping alcohol or sedatives — these sharply raise seizure risk. Never double up doses.",
    },
    {
        "name": "Duloxetine", "slug": "duloxetine",
        "generic_name": "duloxetine hydrochloride",
        "brand_names": "Cymbalta",
        "drug_class": "Serotonin-Norepinephrine Reuptake Inhibitor (SNRI)",
        "category": "Mental Health",
        "uses": "Treats major depression and generalized anxiety disorder, and — unusually for an antidepressant — is also approved for nerve pain from diabetes, fibromyalgia, and chronic musculoskeletal pain such as osteoarthritis and low back pain.",
        "dosage": "Depression: 40 to 60 mg per day (once daily or divided). Diabetic nerve pain and fibromyalgia: 60 mg once daily; fibromyalgia may start at 30 mg for a week. Maximum studied benefit is generally at 60 mg daily. Swallow capsules whole.",
        "side_effects_common": "Nausea, dry mouth, sleepiness, constipation, decreased appetite, and increased sweating.",
        "side_effects_serious": "Liver injury (avoid in heavy alcohol use), serotonin syndrome, severe skin reactions, orthostatic drops in blood pressure, urinary retention, and suicidality in young people.",
        "interactions": "MAO inhibitors (contraindicated), strong CYP1A2 inhibitors such as ciprofloxacin (raise duloxetine levels — avoid), tramadol and triptans, NSAIDs and anticoagulants, and thioridazine.",
        "warnings": "Carries the antidepressant boxed warning for suicidality under 25. Do not stop abruptly — dizziness, irritability, and 'brain zaps' are common with sudden discontinuation; taper gradually.",
    },
    {
        "name": "Venlafaxine", "slug": "venlafaxine",
        "generic_name": "venlafaxine hydrochloride",
        "brand_names": "Effexor XR",
        "drug_class": "Serotonin-Norepinephrine Reuptake Inhibitor (SNRI)",
        "category": "Mental Health",
        "uses": "Treats major depression, generalized anxiety disorder, social anxiety disorder, and panic disorder. At higher doses it adds norepinephrine effects on top of its serotonin action.",
        "dosage": "Extended-release: 75 mg once daily with food (may start at 37.5 mg for a week), increased in 75 mg steps every 4 or more days to a maximum of 225 mg daily for depression.",
        "side_effects_common": "Nausea, dizziness, insomnia, dry mouth, sweating, and sexual side effects.",
        "side_effects_serious": "Sustained increases in blood pressure (dose-related — monitor regularly), serotonin syndrome, low sodium, abnormal bleeding, and suicidality in young people.",
        "interactions": "MAO inhibitors (contraindicated), tramadol, triptans such as sumatriptan, other serotonergic drugs, NSAIDs and anticoagulants, and drugs affecting CYP2D6.",
        "warnings": "Among antidepressants, venlafaxine has notably prominent discontinuation symptoms — never stop suddenly; taper over weeks. Have your blood pressure checked regularly, especially at doses above 150 mg.",
    },
    {
        "name": "Trazodone", "slug": "trazodone",
        "generic_name": "trazodone hydrochloride",
        "brand_names": "Desyrel (discontinued brand)",
        "drug_class": "Serotonin Receptor Antagonist and Reuptake Inhibitor (SARI)",
        "category": "Mental Health",
        "uses": "Approved for major depression, but in modern practice most often prescribed at low doses off-label to help with insomnia because it is sedating and not habit-forming.",
        "dosage": "For depression: started at 150 mg per day in divided doses, up to 400 mg daily in outpatients. For off-label sleep: commonly 25 to 100 mg at bedtime. Take shortly after a meal or light snack.",
        "side_effects_common": "Drowsiness, dizziness, dry mouth, blurred vision, and headache.",
        "side_effects_serious": "Priapism (a painful erection lasting more than 4 hours — a medical emergency), orthostatic hypotension with fainting, heart rhythm changes, and serotonin syndrome.",
        "interactions": "MAO inhibitors, other serotonergic drugs (SSRIs, tramadol, triptans), CYP3A4 inhibitors such as ketoconazole and ritonavir, digoxin, and phenytoin. Alcohol intensifies sedation.",
        "warnings": "Carries the antidepressant boxed warning for suicidality in young people. Rise slowly from sitting or lying down, especially at night, to avoid falls from sudden blood pressure drops.",
    },
    {
        "name": "Alprazolam", "slug": "alprazolam",
        "generic_name": "alprazolam",
        "brand_names": "Xanax, Xanax XR",
        "drug_class": "Benzodiazepine",
        "category": "Mental Health",
        "uses": "Treats generalized anxiety disorder and panic disorder. It enhances the calming neurotransmitter GABA and works within an hour, but is intended for short-term or intermittent use because tolerance and dependence develop.",
        "dosage": "Anxiety: 0.25 to 0.5 mg three times daily, up to 4 mg per day. Panic disorder may require higher divided doses. The dose must be tapered gradually — typically no faster than 0.5 mg every 3 days — when stopping.",
        "side_effects_common": "Drowsiness, light-headedness, memory problems, poor coordination, and slurred speech.",
        "side_effects_serious": "Dangerous breathing suppression when combined with opioids or alcohol, dependence and withdrawal seizures with abrupt discontinuation, and paradoxical agitation.",
        "interactions": "Opioids such as tramadol (boxed warning — profound sedation and death), alcohol, other sedatives, and strong CYP3A4 inhibitors including ketoconazole and itraconazole (contraindicated).",
        "warnings": "Boxed warnings for risks of combined opioid use, and for abuse, misuse, addiction, dependence, and withdrawal reactions. Never stop suddenly after regular use — withdrawal can include life-threatening seizures.",
    },
    {
        "name": "Lorazepam", "slug": "lorazepam",
        "generic_name": "lorazepam",
        "brand_names": "Ativan",
        "drug_class": "Benzodiazepine",
        "category": "Mental Health",
        "uses": "Treats anxiety disorders and anxiety associated with depression, and is used in hospitals for status epilepticus and pre-procedure sedation. Its metabolism is simpler than alprazolam's, making it steadier in liver disease and older adults.",
        "dosage": "Anxiety: 2 to 3 mg per day given two or three times daily, with a usual range of 1 to 6 mg daily; insomnia from anxiety may use 2 to 4 mg at bedtime. Use the lowest effective dose for the shortest time.",
        "side_effects_common": "Sedation, dizziness, weakness, and unsteadiness.",
        "side_effects_serious": "Respiratory depression with opioids or alcohol, dependence and withdrawal (including seizures), and worsening depression.",
        "interactions": "Opioids (boxed warning), alcohol, other CNS depressants, clozapine, and valproate (raises lorazepam levels).",
        "warnings": "Boxed warnings for opioid co-use and for abuse, dependence, and withdrawal. Avoid driving until you know its effect. Older adults are more sensitive and fall risk increases.",
    },
    {
        "name": "Gabapentin", "slug": "gabapentin",
        "generic_name": "gabapentin",
        "brand_names": "Neurontin, Gralise",
        "drug_class": "Gabapentinoid (Anticonvulsant)",
        "category": "Neurology & Sleep",
        "uses": "Treats nerve pain following shingles (postherpetic neuralgia) and partial seizures, and is widely used off-label for other nerve pain and restless legs syndrome.",
        "dosage": "For postherpetic neuralgia: 300 mg on day 1, 300 mg twice daily on day 2, 300 mg three times daily on day 3, then titrated as needed up to 1,800 mg per day in three divided doses. Kidney impairment requires substantial dose reductions.",
        "side_effects_common": "Dizziness, sleepiness, swelling of the legs, unsteadiness, and weight gain.",
        "side_effects_serious": "Serious breathing problems when combined with opioids or in people with lung disease, severe allergic reactions with fever and swollen lymph nodes (DRESS), and mood changes with suicidal thoughts.",
        "interactions": "Opioids (respiratory depression), alcohol and other sedatives, and aluminum/magnesium antacids (take gabapentin at least 2 hours after them).",
        "warnings": "Do not stop suddenly if you take it for seizures — taper over at least a week. Report new or worsening depression or unusual mood changes; anticonvulsants carry a suicidality warning.",
    },
    {
        "name": "Pregabalin", "slug": "pregabalin",
        "generic_name": "pregabalin",
        "brand_names": "Lyrica",
        "drug_class": "Gabapentinoid (Anticonvulsant)",
        "category": "Neurology & Sleep",
        "uses": "Treats nerve pain from diabetes, shingles, and spinal cord injury, fibromyalgia, and partial-onset seizures. It binds the same calcium-channel site as gabapentin but absorbs more predictably.",
        "dosage": "Diabetic nerve pain: 50 mg three times daily, up to 300 mg per day within one week. Fibromyalgia: 300 to 450 mg per day in divided doses. Reduce doses in kidney impairment.",
        "side_effects_common": "Dizziness, sleepiness, dry mouth, swelling of hands and feet, blurred vision, weight gain, and difficulty concentrating.",
        "side_effects_serious": "Angioedema, serious breathing suppression with opioids, mood changes with suicidal thoughts, and muscle pain with fever (possible myopathy).",
        "interactions": "Opioids and other CNS depressants, alcohol, and pioglitazone-type diabetes drugs (additive swelling and weight gain).",
        "warnings": "A controlled substance (Schedule V) with some misuse potential. Do not stop abruptly — taper over at least a week to avoid insomnia, nausea, headache, and, in epilepsy, increased seizures.",
    },
    {
        "name": "Sumatriptan", "slug": "sumatriptan",
        "generic_name": "sumatriptan succinate",
        "brand_names": "Imitrex",
        "drug_class": "Serotonin 5-HT1B/1D Receptor Agonist (Triptan)",
        "category": "Neurology & Sleep",
        "uses": "Treats migraine attacks with or without aura, and (in injection form) cluster headache. It narrows swollen blood vessels around the brain and blocks pain-signal release — it treats attacks but does not prevent them.",
        "dosage": "Tablets: 25, 50, or 100 mg at the first sign of migraine; if the headache returns, a second dose may be taken at least 2 hours after the first. Maximum 200 mg in 24 hours. Nasal spray and injection forms act faster.",
        "side_effects_common": "Tingling, warmth or flushing, pressure or tightness in the chest, neck, or jaw, dizziness, and drowsiness.",
        "side_effects_serious": "Heart attack and serious arrhythmias in people with coronary disease, medication-overuse headache with frequent use, serotonin syndrome with serotonergic antidepressants, and blood-vessel spasm elsewhere in the body.",
        "interactions": "Ergotamine-type migraine drugs and other triptans within 24 hours (contraindicated), MAO inhibitors, and SSRIs/SNRIs such as sertraline and venlafaxine (serotonin syndrome — usually manageable but watch for symptoms).",
        "warnings": "Not for people with coronary artery disease, uncontrolled blood pressure, or prior stroke. Using acute migraine medicines on 10 or more days per month can itself cause chronic daily headache.",
    },
    {
        "name": "Cetirizine", "slug": "cetirizine",
        "generic_name": "cetirizine hydrochloride",
        "brand_names": "Zyrtec",
        "drug_class": "Second-Generation Antihistamine",
        "category": "Allergy & Respiratory",
        "uses": "Relieves runny nose, sneezing, itchy and watery eyes, and itchy throat or nose from hay fever and other respiratory allergies, and treats chronic hives. Among second-generation antihistamines it is fast-acting but slightly more sedating than loratadine or fexofenadine.",
        "dosage": "Adults and children 6 years and over: 10 mg once daily; 5 mg may be enough for milder symptoms. Adults 65 and over should ask a doctor before use.",
        "side_effects_common": "Drowsiness (in roughly 1 in 10 people), dry mouth, and fatigue.",
        "side_effects_serious": "Rare allergic reactions; intense itching has been reported after stopping long-term daily use.",
        "interactions": "Alcohol and sedatives amplify drowsiness; theophylline may slightly reduce its clearance. Otherwise few significant interactions.",
        "warnings": "Do not drive or operate machinery until you know whether it makes you drowsy. Use with a doctor's advice in kidney or liver disease, which slow its elimination.",
    },
    {
        "name": "Loratadine", "slug": "loratadine",
        "generic_name": "loratadine",
        "brand_names": "Claritin, Alavert",
        "drug_class": "Second-Generation Antihistamine",
        "category": "Allergy & Respiratory",
        "uses": "Relieves sneezing, runny nose, and itchy, watery eyes from hay fever and other upper respiratory allergies, and treats chronic hives. Marketed as non-drowsy because very little crosses into the brain at the labeled dose.",
        "dosage": "Adults and children 6 years and over: 10 mg once daily. Do not take more than one dose in 24 hours — extra doses add drowsiness without extra relief.",
        "side_effects_common": "Headache, fatigue, and dry mouth; drowsiness is uncommon at the recommended dose.",
        "side_effects_serious": "Rare allergic reactions and, very rarely, rapid heartbeat.",
        "interactions": "Ketoconazole, erythromycin, and cimetidine raise loratadine blood levels, though this rarely matters clinically. Alcohol may still add mild sedation.",
        "warnings": "Ask a doctor before use if you have liver or kidney disease. If symptoms don't improve within a week of daily use, see a clinician to confirm allergies are the cause.",
    },
    {
        "name": "Fexofenadine", "slug": "fexofenadine",
        "generic_name": "fexofenadine hydrochloride",
        "brand_names": "Allegra",
        "drug_class": "Second-Generation Antihistamine",
        "category": "Allergy & Respiratory",
        "uses": "Relieves seasonal allergy symptoms — sneezing, runny nose, itchy nose or throat, and itchy watery eyes — and treats chronic hives. It is the least sedating of the common second-generation antihistamines.",
        "dosage": "Adults and children 12 and over: 180 mg once daily or 60 mg twice daily, taken with water only.",
        "side_effects_common": "Headache, nausea, and occasionally dizziness; drowsiness rates are similar to placebo.",
        "side_effects_serious": "Rare hypersensitivity reactions with rash and swelling.",
        "interactions": "Fruit juices (orange, apple, grapefruit) markedly cut its absorption — take with water and avoid juice within 4 hours. Aluminum/magnesium antacids also reduce absorption; separate by 2 hours. Ketoconazole and erythromycin raise its levels.",
        "warnings": "Take with water, not juice — this is the most common reason it 'doesn't work.' Ask a doctor before use if you have kidney disease.",
    },
    {
        "name": "Diphenhydramine", "slug": "diphenhydramine",
        "generic_name": "diphenhydramine hydrochloride",
        "brand_names": "Benadryl, ZzzQuil",
        "drug_class": "First-Generation Antihistamine",
        "category": "Allergy & Respiratory",
        "uses": "Relieves allergy and cold symptoms including sneezing, runny nose, and itchy watery eyes, treats hives and itching, helps motion sickness, and is used as a nighttime sleep aid because of its strong sedative effect.",
        "dosage": "Adults for allergies: 25 to 50 mg every 4 to 6 hours, not exceeding 300 mg in 24 hours. As a sleep aid: 50 mg at bedtime. Effects last 4 to 6 hours.",
        "side_effects_common": "Marked drowsiness, dry mouth, dizziness, blurred vision, constipation, and urinary retention.",
        "side_effects_serious": "Confusion and falls in older adults, rapid or irregular heartbeat, seizures in overdose, and paradoxical excitation in children.",
        "interactions": "Alcohol, sedatives, opioids, MAO inhibitors, and other anticholinergic drugs (additive confusion, constipation, and urinary retention).",
        "warnings": "Not recommended for adults 65 and older for routine use — its anticholinergic load is linked to confusion and falls. Do not use to make a child sleepy. Avoid driving after a dose.",
    },
    {
        "name": "Montelukast", "slug": "montelukast",
        "generic_name": "montelukast sodium",
        "brand_names": "Singulair",
        "drug_class": "Leukotriene Receptor Antagonist",
        "category": "Allergy & Respiratory",
        "uses": "Prevents asthma attacks (not for rescue during an attack), prevents exercise-induced airway narrowing, and relieves allergic rhinitis symptoms when antihistamines are not enough.",
        "dosage": "Adults and adolescents 15 and over: 10 mg once daily in the evening. For exercise-induced symptoms: 10 mg at least 2 hours before exercise, with no second dose within 24 hours.",
        "side_effects_common": "Headache, abdominal pain, and upper respiratory infection symptoms.",
        "side_effects_serious": "Neuropsychiatric events — agitation, depression, sleep disturbances, nightmares, and suicidal thoughts — plus rare allergic inflammation of blood vessels.",
        "interactions": "Phenobarbital and rifampin reduce its levels; otherwise interaction burden is low.",
        "warnings": "Boxed warning for serious mental health side effects — because of this, it is reserved for allergic rhinitis patients who cannot use other treatments. Report mood or behavior changes immediately, and keep a rescue inhaler for asthma attacks.",
    },
    {
        "name": "Albuterol", "slug": "albuterol",
        "generic_name": "albuterol sulfate",
        "brand_names": "ProAir HFA, Ventolin HFA, Proventil HFA",
        "drug_class": "Short-Acting Beta-2 Agonist (SABA) Bronchodilator",
        "category": "Allergy & Respiratory",
        "uses": "The standard rescue inhaler: rapidly relaxes airway muscles to relieve wheezing, chest tightness, and shortness of breath in asthma and COPD, and prevents exercise-induced bronchospasm.",
        "dosage": "Inhalation aerosol: 2 puffs every 4 to 6 hours as needed for symptoms; 2 puffs 15 to 30 minutes before exercise for prevention. Shake well before each use and rinse the mouthpiece weekly.",
        "side_effects_common": "Tremor, nervousness, rapid heartbeat, headache, and throat irritation.",
        "side_effects_serious": "Paradoxical bronchospasm (breathing suddenly worsens right after a dose), significant heart rhythm changes, low potassium at high doses, and allergic reactions.",
        "interactions": "Beta-blockers such as metoprolol and atenolol blunt its effect, diuretics add to potassium loss, and MAO inhibitors or tricyclic antidepressants can amplify cardiovascular effects.",
        "warnings": "Needing your rescue inhaler more than two days a week (outside exercise) means your asthma is not controlled — see your doctor about a daily controller medicine rather than using more albuterol.",
    },
    {
        "name": "Fluticasone Nasal", "slug": "fluticasone-nasal",
        "generic_name": "fluticasone propionate (nasal spray)",
        "brand_names": "Flonase Allergy Relief",
        "drug_class": "Intranasal Corticosteroid",
        "category": "Allergy & Respiratory",
        "uses": "Relieves the full set of nasal allergy symptoms — congestion, runny nose, sneezing, and itchy nose — plus itchy, watery eyes. Steroid sprays are the single most effective drug class for nasal allergy congestion.",
        "dosage": "Adults: 2 sprays in each nostril once daily for the first week, then 1 to 2 sprays daily as needed. Full effect builds over several days of regular use. Aim slightly away from the nasal septum.",
        "side_effects_common": "Nasal dryness or burning, nosebleeds, headache, and an unpleasant taste.",
        "side_effects_serious": "Nasal septum perforation (rare, usually from poor spray technique), glaucoma or cataracts with long-term use, and slowed growth in children.",
        "interactions": "Strong CYP3A4 inhibitors such as ritonavir and ketoconazole can raise systemic steroid levels — tell your doctor if you take these.",
        "warnings": "Point the spray toward the outer wall of the nostril, not the center, to prevent nosebleeds and septum damage. See a doctor if you have frequent nosebleeds, eye pain, or vision changes.",
    },
    {
        "name": "Prednisone", "slug": "prednisone",
        "generic_name": "prednisone",
        "brand_names": "Deltasone (discontinued brand), Rayos",
        "drug_class": "Systemic Corticosteroid",
        "category": "Hormones & Thyroid",
        "uses": "A powerful anti-inflammatory and immune suppressant used for asthma and COPD flare-ups, severe allergic reactions, rheumatoid arthritis, lupus, inflammatory bowel disease, and many other inflammatory and autoimmune conditions.",
        "dosage": "Highly condition-dependent, from 5 mg to 60 mg per day. Short 'burst' courses (for example 40 mg daily for 5 days) can stop abruptly, but courses longer than about 2 to 3 weeks must be tapered gradually. Take in the morning with food.",
        "side_effects_common": "Increased appetite and weight gain, insomnia, mood changes, fluid retention, elevated blood sugar, and indigestion.",
        "side_effects_serious": "Adrenal suppression, serious infections, stomach ulcers and bleeding (especially with NSAIDs), osteoporosis and fractures, cataracts and glaucoma, and psychiatric reactions.",
        "interactions": "NSAIDs (ulcer and bleeding risk), warfarin, diabetes medicines (steroids raise blood sugar), live vaccines (avoid during significant doses), and CYP3A4 inducers/inhibitors like rifampin and ketoconazole.",
        "warnings": "Never stop long-term prednisone suddenly — your adrenal glands need time to resume cortisol production; abrupt withdrawal can cause a crisis. Carry a steroid card if on prolonged therapy.",
    },
    {
        "name": "Tamsulosin", "slug": "tamsulosin",
        "generic_name": "tamsulosin hydrochloride",
        "brand_names": "Flomax",
        "drug_class": "Alpha-1A Adrenergic Blocker",
        "category": "Men's Health",
        "uses": "Improves urinary symptoms of an enlarged prostate (benign prostatic hyperplasia) — weak stream, hesitancy, and nighttime urination — by relaxing muscle in the prostate and bladder neck. Also used off-label to help pass kidney stones.",
        "dosage": "Adults: 0.4 mg once daily, taken about 30 minutes after the same meal each day. May be increased to 0.8 mg daily after 2 to 4 weeks if needed. Do not crush, chew, or open capsules.",
        "side_effects_common": "Dizziness, runny nose, abnormal ejaculation, and headache.",
        "side_effects_serious": "First-dose fainting from a sudden blood pressure drop, priapism (rare), and intraoperative floppy iris syndrome during cataract surgery.",
        "interactions": "Other alpha-blockers, strong CYP3A4 inhibitors such as ketoconazole (avoid), cimetidine, and erectile dysfunction drugs like sildenafil (additive blood pressure lowering).",
        "warnings": "Tell your eye surgeon you take or have ever taken tamsulosin before cataract or glaucoma surgery. Rise slowly for the first days of treatment and after dose increases.",
    },
    {
        "name": "Sildenafil", "slug": "sildenafil",
        "generic_name": "sildenafil citrate",
        "brand_names": "Viagra, Revatio",
        "drug_class": "Phosphodiesterase-5 (PDE5) Inhibitor",
        "category": "Men's Health",
        "uses": "Treats erectile dysfunction by increasing blood flow to the penis during sexual stimulation; the same molecule at lower doses (Revatio) treats pulmonary arterial hypertension.",
        "dosage": "For ED: 50 mg taken about one hour before sexual activity, adjustable between 25 mg and 100 mg based on response. Maximum one dose per day. High-fat meals delay its onset.",
        "side_effects_common": "Headache, flushing, indigestion, nasal congestion, and a temporary bluish tinge to vision.",
        "side_effects_serious": "Dangerous blood pressure drops with nitrates, priapism (erection lasting over 4 hours), sudden vision loss in one or both eyes (NAION), and sudden hearing loss.",
        "interactions": "Nitrates such as nitroglycerin (absolutely contraindicated — life-threatening hypotension), riociguat, alpha-blockers such as tamsulosin (separate timing, use low doses), and strong CYP3A4 inhibitors like ritonavir and ketoconazole.",
        "warnings": "Never combine with any nitrate medicine, including recreational 'poppers.' Seek immediate care for an erection lasting more than 4 hours or any sudden loss of vision or hearing.",
    },
]
