"""Drug catalog, part A (pain, antibiotics, cardiovascular, diabetes).

Facts (generic/brand names, drug classes, standard adult dosages, side-effect
and interaction profiles) are sourced from openFDA drug labeling (public
domain; harvested snapshots in scraped_data/openfda/). All sentences are
original prose written for this mirror — nothing is copied from webmd.com or
any other site.
"""

DRUGS_A = [
    {
        "name": "Ibuprofen", "slug": "ibuprofen",
        "generic_name": "ibuprofen",
        "brand_names": "Advil, Motrin IB",
        "drug_class": "Nonsteroidal Anti-inflammatory Drug (NSAID)",
        "category": "Pain & Inflammation",
        "uses": "Relieves minor aches and pains from headache, toothache, backache, menstrual cramps, muscle aches, and minor arthritis, and temporarily reduces fever. It works by blocking cyclooxygenase (COX) enzymes, which lowers the production of prostaglandins that drive pain and inflammation.",
        "dosage": "Adults and children 12 years and over: 200 mg every 4 to 6 hours while symptoms persist. If pain or fever does not respond, 400 mg may be used. Do not exceed 1,200 mg in 24 hours unless directed by a doctor. Take with food or milk if stomach upset occurs.",
        "side_effects_common": "Upset stomach, heartburn, nausea, mild dizziness, and headache.",
        "side_effects_serious": "Stomach bleeding or ulcers (black or bloody stools, vomiting blood), allergic reactions (hives, facial swelling, wheezing), chest pain, slurred speech, swelling of the ankles, or changes in urination signaling kidney problems.",
        "interactions": "Avoid combining with aspirin, other NSAIDs such as naproxen, blood thinners such as warfarin or apixaban, and corticosteroids such as prednisone, all of which raise bleeding risk. Ibuprofen can also reduce the effect of blood pressure medicines including lisinopril and diuretics.",
        "warnings": "NSAIDs increase the risk of heart attack, stroke, and stomach bleeding, especially with longer use, higher doses, or in people over 60. Do not use in the last 3 months of pregnancy. Do not take for more than 10 days for pain unless directed by a doctor.",
    },
    {
        "name": "Acetaminophen", "slug": "acetaminophen",
        "generic_name": "acetaminophen",
        "brand_names": "Tylenol, Tylenol Extra Strength",
        "drug_class": "Analgesic / Antipyretic",
        "category": "Pain & Inflammation",
        "uses": "Temporarily relieves minor aches and pains from headache, muscle aches, backache, arthritis, colds, and toothache, and reduces fever. Unlike NSAIDs, it does not reduce inflammation, but it is gentler on the stomach.",
        "dosage": "Adults and children 12 years and over: 650 mg (two 325 mg tablets) every 4 to 6 hours, or 1,000 mg of extra-strength every 6 hours. Do not exceed 3,000 to 4,000 mg in 24 hours depending on the product; follow the specific label.",
        "side_effects_common": "Generally well tolerated at recommended doses. Occasional nausea or rash may occur.",
        "side_effects_serious": "Liver damage with overdose or heavy alcohol use (symptoms include yellowing skin or eyes, dark urine, and right-upper abdominal pain), and rare severe skin reactions such as Stevens-Johnson syndrome.",
        "interactions": "Warfarin (may raise INR with regular use), isoniazid, and other combination cold or pain products that also contain acetaminophen — stacking products is the most common cause of accidental overdose.",
        "warnings": "Severe liver damage may occur if you take more than the maximum daily dose, take it with other acetaminophen-containing products, or have 3 or more alcoholic drinks daily. Overdose requires immediate medical attention even without symptoms.",
    },
    {
        "name": "Aspirin", "slug": "aspirin",
        "generic_name": "aspirin",
        "brand_names": "Bayer Aspirin, Ecotrin",
        "drug_class": "Nonsteroidal Anti-inflammatory Drug (NSAID) / Antiplatelet",
        "category": "Pain & Inflammation",
        "uses": "Relieves minor aches, pains, and fever, and at low doses (81 mg) is used under a doctor's direction to lower the risk of heart attack and clot-related stroke in people with established cardiovascular disease. It permanently inhibits platelets, which keeps blood from clotting as easily.",
        "dosage": "For pain or fever in adults: 325 to 650 mg every 4 hours as needed, not to exceed 4,000 mg in 24 hours. For heart protection: 81 mg once daily, only when recommended by a doctor.",
        "side_effects_common": "Heartburn, upset stomach, nausea, and easy bruising.",
        "side_effects_serious": "Gastrointestinal bleeding, ringing in the ears (a sign of overdose), allergic reactions including asthma attacks in aspirin-sensitive people, and hemorrhagic stroke.",
        "interactions": "Warfarin, apixaban, clopidogrel, and other NSAIDs such as ibuprofen (increased bleeding risk); ibuprofen can also blunt aspirin's heart-protective antiplatelet effect if taken at the same time. Also interacts with methotrexate.",
        "warnings": "Children and teenagers recovering from chickenpox or flu-like symptoms should never take aspirin because of the risk of Reye's syndrome, a rare but serious illness. Stop use and ask a doctor if you notice ringing in the ears or bleeding that does not stop.",
    },
    {
        "name": "Naproxen", "slug": "naproxen",
        "generic_name": "naproxen sodium",
        "brand_names": "Aleve, Naprosyn",
        "drug_class": "Nonsteroidal Anti-inflammatory Drug (NSAID)",
        "category": "Pain & Inflammation",
        "uses": "Relieves minor aches and pains from arthritis, muscle aches, backache, menstrual cramps, headache, and toothache, and reduces fever. Its longer duration of action means fewer doses per day than ibuprofen.",
        "dosage": "Adults: 220 mg every 8 to 12 hours while symptoms last. For the first dose you may take 440 mg within the first hour. Do not exceed 660 mg in 24 hours unless directed by a doctor.",
        "side_effects_common": "Heartburn, stomach pain, nausea, headache, dizziness, and drowsiness.",
        "side_effects_serious": "Stomach ulcers and bleeding, fluid retention with swelling, elevated blood pressure, kidney injury, and severe allergic reactions.",
        "interactions": "Other NSAIDs and aspirin, blood thinners (warfarin, apixaban, clopidogrel), corticosteroids, lithium, methotrexate, and blood pressure medicines such as lisinopril and hydrochlorothiazide.",
        "warnings": "Like other NSAIDs, naproxen carries a boxed warning for increased risk of heart attack, stroke, and serious gastrointestinal bleeding. Use the lowest effective dose for the shortest duration, and avoid in late pregnancy.",
    },
    {
        "name": "Meloxicam", "slug": "meloxicam",
        "generic_name": "meloxicam",
        "brand_names": "Mobic",
        "drug_class": "Nonsteroidal Anti-inflammatory Drug (NSAID)",
        "category": "Pain & Inflammation",
        "uses": "A prescription NSAID for the relief of pain, tenderness, swelling, and stiffness caused by osteoarthritis and rheumatoid arthritis. Its once-daily dosing makes it convenient for chronic joint pain.",
        "dosage": "Adults: 7.5 mg once daily, which may be increased to a maximum of 15 mg once daily. Take at the same time each day, with or without food.",
        "side_effects_common": "Diarrhea, indigestion, nausea, dizziness, and cold or flu-like symptoms.",
        "side_effects_serious": "Gastrointestinal bleeding or perforation, heart attack, stroke, kidney injury, liver problems, and serious skin reactions.",
        "interactions": "Aspirin and other NSAIDs, warfarin and other anticoagulants, ACE inhibitors such as lisinopril, diuretics, lithium, and methotrexate.",
        "warnings": "Carries the NSAID boxed warning for cardiovascular and gastrointestinal risk. Do not use for pain before or after coronary artery bypass surgery. Avoid after 30 weeks of pregnancy.",
    },
    {
        "name": "Tramadol", "slug": "tramadol",
        "generic_name": "tramadol hydrochloride",
        "brand_names": "Ultram, ConZip",
        "drug_class": "Opioid Analgesic",
        "category": "Pain & Inflammation",
        "uses": "A prescription pain medicine for adults with pain severe enough to require an opioid when other treatments have not worked or cannot be tolerated. It acts on opioid receptors and also affects serotonin and norepinephrine signaling.",
        "dosage": "Adults: 50 to 100 mg every 4 to 6 hours as needed for pain, not to exceed 400 mg per day. Extended-release forms are dosed once daily. Doses should be reduced in older adults and in kidney or liver disease.",
        "side_effects_common": "Dizziness, nausea, constipation, headache, drowsiness, and dry mouth.",
        "side_effects_serious": "Slowed or stopped breathing, seizures, serotonin syndrome (agitation, fever, rapid heartbeat, muscle twitching), severe low blood pressure, and dependence or addiction.",
        "interactions": "Other opioids, benzodiazepines such as alprazolam and lorazepam (dangerous sedation and breathing suppression), alcohol, and serotonergic antidepressants such as sertraline, fluoxetine, and duloxetine (serotonin syndrome risk).",
        "warnings": "Boxed warnings for addiction, abuse, misuse, life-threatening respiratory depression, and fatal overdose in children. Do not drink alcohol while taking tramadol. Do not stop suddenly after long-term use — taper under medical supervision.",
    },
    {
        "name": "Cyclobenzaprine", "slug": "cyclobenzaprine",
        "generic_name": "cyclobenzaprine hydrochloride",
        "brand_names": "Flexeril, Amrix",
        "drug_class": "Skeletal Muscle Relaxant",
        "category": "Pain & Inflammation",
        "uses": "Relieves muscle spasm associated with acute, painful musculoskeletal conditions, used together with rest and physical therapy. It is intended for short courses, typically two to three weeks.",
        "dosage": "Adults: 5 mg three times a day, which may be increased to 10 mg three times a day if needed. Extended-release capsules are taken as 15 to 30 mg once daily. Not recommended for use longer than 3 weeks.",
        "side_effects_common": "Drowsiness, dry mouth, dizziness, and fatigue.",
        "side_effects_serious": "Irregular heart rhythms, serotonin syndrome when combined with serotonergic drugs, confusion or hallucinations (especially in older adults), and severe allergic reactions.",
        "interactions": "MAO inhibitors (contraindicated), alcohol and other sedatives, tramadol, and serotonergic antidepressants such as sertraline, duloxetine, and venlafaxine.",
        "warnings": "Causes significant drowsiness — do not drive or operate machinery until you know how it affects you. Not recommended for older adults or people with heart rhythm problems, recent heart attack, or hyperthyroidism.",
    },
    {
        "name": "Amoxicillin", "slug": "amoxicillin",
        "generic_name": "amoxicillin",
        "brand_names": "Amoxil",
        "drug_class": "Penicillin-class Antibacterial",
        "category": "Antibiotics",
        "uses": "Treats bacterial infections of the ear, nose, throat, lungs, skin, and urinary tract, including strep throat, middle-ear infections, and sinusitis. It is also part of combination regimens that eliminate Helicobacter pylori in peptic ulcer disease. It does not work for viral illnesses like colds or flu.",
        "dosage": "Adults: 250 to 500 mg every 8 hours, or 500 to 875 mg every 12 hours, depending on the infection. A typical course runs 7 to 10 days. Finish the full course even if you feel better sooner.",
        "side_effects_common": "Nausea, diarrhea, vomiting, and rash.",
        "side_effects_serious": "Severe allergic reactions (anaphylaxis, hives, swelling of the face and throat), Clostridioides difficile-associated diarrhea, and rare severe skin reactions.",
        "interactions": "Probenecid (raises amoxicillin levels), allopurinol (higher chance of rash), warfarin (may enhance its effect), and certain other antibiotics.",
        "warnings": "Do not take if you have ever had an allergic reaction to penicillin or cephalosporin antibiotics. Watery or bloody diarrhea during or up to two months after treatment should be reported to a doctor.",
    },
    {
        "name": "Azithromycin", "slug": "azithromycin",
        "generic_name": "azithromycin",
        "brand_names": "Zithromax, Z-Pak",
        "drug_class": "Macrolide Antibacterial",
        "category": "Antibiotics",
        "uses": "Treats community-acquired pneumonia, bronchitis flare-ups, sinus infections, strep throat in penicillin-allergic patients, skin infections, and certain sexually transmitted infections such as chlamydia.",
        "dosage": "The common 5-day 'Z-Pak' regimen for adults: 500 mg as a single dose on day 1, followed by 250 mg once daily on days 2 through 5. Some infections use 500 mg daily for 3 days or a single 1 g dose.",
        "side_effects_common": "Diarrhea, nausea, abdominal pain, and headache.",
        "side_effects_serious": "QT-interval prolongation with abnormal heart rhythms, liver injury, severe allergic and skin reactions, and C. difficile diarrhea.",
        "interactions": "Antacids containing aluminum or magnesium (reduce absorption — separate doses), warfarin, and other QT-prolonging drugs such as ondansetron and citalopram-type antidepressants.",
        "warnings": "People with known heart rhythm problems, low potassium, or a slow baseline heart rate should use azithromycin cautiously because of the risk of a dangerous arrhythmia called torsades de pointes.",
    },
    {
        "name": "Ciprofloxacin", "slug": "ciprofloxacin",
        "generic_name": "ciprofloxacin hydrochloride",
        "brand_names": "Cipro",
        "drug_class": "Fluoroquinolone Antibacterial",
        "category": "Antibiotics",
        "uses": "Treats urinary tract infections, some types of infectious diarrhea, bone and joint infections, and certain abdominal and skin infections caused by susceptible bacteria. Because of its side-effect profile, it is generally reserved for infections without safer alternatives.",
        "dosage": "Adults: 250 to 750 mg every 12 hours depending on infection type and severity; uncomplicated UTIs are often treated with 250 mg twice daily for 3 days. Drink plenty of fluids while taking it.",
        "side_effects_common": "Nausea, diarrhea, headache, and dizziness.",
        "side_effects_serious": "Tendinitis and tendon rupture (especially the Achilles tendon), peripheral neuropathy, central nervous system effects including seizures and confusion, aortic aneurysm or dissection, and severe blood sugar drops.",
        "interactions": "Dairy products, calcium, iron, zinc, and antacids block its absorption — separate by at least 2 hours. Also interacts with theophylline, warfarin, tizanidine (contraindicated), and caffeine.",
        "warnings": "Boxed warning for disabling and potentially irreversible reactions involving tendons, muscles, joints, and nerves. Stop at the first sign of tendon pain or swelling. Avoid in people with myasthenia gravis.",
    },
    {
        "name": "Doxycycline", "slug": "doxycycline",
        "generic_name": "doxycycline hyclate",
        "brand_names": "Vibramycin, Doryx",
        "drug_class": "Tetracycline-class Antibacterial",
        "category": "Antibiotics",
        "uses": "Treats respiratory infections, moderate-to-severe acne, rosacea, Lyme disease, Rocky Mountain spotted fever, chlamydia, and is used to prevent malaria in travelers.",
        "dosage": "Adults: 100 mg every 12 hours on day one, then 100 mg once or twice daily depending on the infection. For malaria prevention: 100 mg once daily starting 1 to 2 days before travel. Take with a full glass of water and remain upright for 30 minutes.",
        "side_effects_common": "Nausea, vomiting, diarrhea, and sensitivity of the skin to sunlight.",
        "side_effects_serious": "Severe sunburn reactions, esophageal ulceration if the capsule lodges in the throat, intracranial hypertension (severe headache and vision changes), and C. difficile diarrhea.",
        "interactions": "Antacids, calcium, iron, and magnesium supplements markedly reduce absorption — separate by 2 to 3 hours. Also interacts with warfarin, penicillin antibiotics, and seizure medicines like carbamazepine.",
        "warnings": "Not for children under 8 or during pregnancy because it can permanently stain developing teeth and affect bone growth. Use sunscreen and protective clothing — exaggerated sunburn can occur quickly.",
    },
    {
        "name": "Cephalexin", "slug": "cephalexin",
        "generic_name": "cephalexin",
        "brand_names": "Keflex",
        "drug_class": "Cephalosporin Antibacterial",
        "category": "Antibiotics",
        "uses": "Treats skin and soft-tissue infections, strep throat, bone infections, uncomplicated urinary tract infections, and respiratory infections caused by susceptible bacteria.",
        "dosage": "Adults: 250 to 500 mg every 6 to 12 hours, typically 500 mg twice daily for skin infections. Usual course is 7 to 14 days. May be taken with or without food.",
        "side_effects_common": "Diarrhea, nausea, indigestion, and abdominal pain.",
        "side_effects_serious": "Allergic reactions ranging from rash to anaphylaxis (higher risk in people with penicillin allergy), C. difficile diarrhea, and rare kidney or liver effects.",
        "interactions": "Metformin (cephalexin can raise its levels), probenecid, and zinc supplements (reduce absorption — separate doses by at least 3 hours).",
        "warnings": "Tell your doctor about any previous allergic reaction to penicillins or cephalosporins before starting. Complete the entire prescribed course to prevent the infection from returning.",
    },
    {
        "name": "Lisinopril", "slug": "lisinopril",
        "generic_name": "lisinopril",
        "brand_names": "Prinivil, Zestril",
        "drug_class": "Angiotensin-Converting Enzyme (ACE) Inhibitor",
        "category": "Heart & Blood Pressure",
        "uses": "Lowers high blood pressure, treats heart failure, and improves survival when started after a heart attack. Controlling blood pressure lowers the risk of stroke, heart attack, and kidney damage.",
        "dosage": "Adults with hypertension: usually started at 10 mg once daily, with a typical maintenance range of 20 to 40 mg once daily. Heart failure is often started at 2.5 to 5 mg daily. Take at the same time each day.",
        "side_effects_common": "A persistent dry cough, dizziness (especially after the first dose), headache, and fatigue.",
        "side_effects_serious": "Angioedema (sudden swelling of the face, lips, tongue, or throat — a medical emergency), high potassium levels, kidney function decline, and very low blood pressure.",
        "interactions": "Potassium supplements and potassium-sparing diuretics (risk of high potassium), NSAIDs such as ibuprofen and naproxen (blunt its effect and stress the kidneys), lithium, and other blood pressure medicines.",
        "warnings": "Boxed warning: can cause injury or death to a developing fetus — stop as soon as pregnancy is detected. Seek emergency care immediately for any swelling of the face, tongue, or throat.",
    },
    {
        "name": "Amlodipine", "slug": "amlodipine",
        "generic_name": "amlodipine besylate",
        "brand_names": "Norvasc",
        "drug_class": "Calcium Channel Blocker (Dihydropyridine)",
        "category": "Heart & Blood Pressure",
        "uses": "Treats high blood pressure and chronic stable or vasospastic angina (chest pain). It relaxes the walls of blood vessels so blood flows more easily and the heart works less hard.",
        "dosage": "Adults: usually started at 5 mg once daily, with a maximum of 10 mg once daily. Small, fragile, or elderly patients may start at 2.5 mg. Effects build over one to two weeks.",
        "side_effects_common": "Swelling of the ankles and feet, flushing, dizziness, fatigue, and palpitations.",
        "side_effects_serious": "Worsening chest pain or heart attack when starting or increasing the dose (rare), severe low blood pressure, and allergic reactions.",
        "interactions": "Simvastatin (limit simvastatin to 20 mg daily when combined), grapefruit juice in large amounts, and strong CYP3A4 inhibitors such as clarithromycin and ketoconazole, which raise amlodipine levels.",
        "warnings": "Ankle swelling is dose-related and more common in women; tell your doctor if it becomes bothersome rather than stopping on your own. Do not stop abruptly if you take it for angina.",
    },
    {
        "name": "Losartan", "slug": "losartan",
        "generic_name": "losartan potassium",
        "brand_names": "Cozaar",
        "drug_class": "Angiotensin II Receptor Blocker (ARB)",
        "category": "Heart & Blood Pressure",
        "uses": "Treats high blood pressure, protects the kidneys in people with type 2 diabetes and protein in the urine, and lowers stroke risk in patients with hypertension and an enlarged heart. Often chosen for people who develop a cough on ACE inhibitors.",
        "dosage": "Adults: usually started at 50 mg once daily, with a range of 25 to 100 mg daily taken in one or two doses. Patients on diuretics or with liver impairment may start at 25 mg.",
        "side_effects_common": "Dizziness, stuffy nose, back pain, and fatigue.",
        "side_effects_serious": "High potassium levels, kidney function decline, very low blood pressure, and rare angioedema.",
        "interactions": "Potassium supplements and salt substitutes containing potassium, NSAIDs such as ibuprofen (reduce effectiveness and stress kidneys), lithium, and rifampin.",
        "warnings": "Boxed warning: can cause fetal injury or death — discontinue as soon as pregnancy is detected. Have kidney function and potassium checked periodically while taking losartan.",
    },
    {
        "name": "Metoprolol", "slug": "metoprolol",
        "generic_name": "metoprolol tartrate / metoprolol succinate",
        "brand_names": "Lopressor, Toprol-XL",
        "drug_class": "Beta-1 Selective Beta-Blocker",
        "category": "Heart & Blood Pressure",
        "uses": "Treats high blood pressure, angina, and heart failure (extended-release form), and improves survival after a heart attack. It slows the heart rate and reduces the heart's workload. It is also commonly used to control heart rate in atrial fibrillation.",
        "dosage": "Immediate-release (tartrate): typically 50 mg twice daily for hypertension, adjustable to 100 to 450 mg per day in divided doses. Extended-release (succinate): 25 to 200 mg once daily. Take with or immediately after a meal for the tartrate form.",
        "side_effects_common": "Tiredness, dizziness, slow heartbeat, depression, and cold hands and feet.",
        "side_effects_serious": "Very slow heart rate or heart block, worsening heart failure, severe low blood pressure, and masking of low blood sugar symptoms in diabetes.",
        "interactions": "Other heart-rate-lowering drugs (verapamil, diltiazem, digoxin), clonidine, strong CYP2D6 inhibitors such as fluoxetine and bupropion (raise metoprolol levels), and insulin or oral diabetes medicines.",
        "warnings": "Never stop a beta-blocker abruptly — sudden withdrawal can trigger chest pain or heart attack; the dose should be tapered over one to two weeks. Use caution in asthma, as higher doses can trigger wheezing.",
    },
    {
        "name": "Atenolol", "slug": "atenolol",
        "generic_name": "atenolol",
        "brand_names": "Tenormin",
        "drug_class": "Beta-1 Selective Beta-Blocker",
        "category": "Heart & Blood Pressure",
        "uses": "Treats high blood pressure and angina, and is used after heart attack to improve survival. Compared with metoprolol it is longer-acting and excreted by the kidneys rather than the liver.",
        "dosage": "Adults with hypertension: 25 to 50 mg once daily initially, up to 100 mg once daily. Doses must be reduced in significant kidney impairment.",
        "side_effects_common": "Fatigue, dizziness, slow heart rate, cold extremities, and vivid dreams.",
        "side_effects_serious": "Severe bradycardia, heart block, worsening heart failure, and bronchospasm in people with asthma.",
        "interactions": "Verapamil and diltiazem (additive heart-rate slowing), clonidine, NSAIDs (reduce blood-pressure effect), and diabetes medicines whose hypoglycemia warning signs it can mask.",
        "warnings": "Do not stop suddenly; taper under medical supervision to avoid rebound chest pain or heart attack. Tell your doctor if you have asthma, diabetes, or kidney disease before starting.",
    },
    {
        "name": "Hydrochlorothiazide", "slug": "hydrochlorothiazide",
        "generic_name": "hydrochlorothiazide",
        "brand_names": "Microzide",
        "drug_class": "Thiazide Diuretic",
        "category": "Heart & Blood Pressure",
        "uses": "Treats high blood pressure and fluid retention (edema) caused by heart failure, liver disease, or kidney disorders. As a 'water pill' it helps the kidneys remove extra salt and water.",
        "dosage": "Adults with hypertension: 12.5 to 25 mg once daily, up to 50 mg daily. Take in the morning to avoid nighttime urination.",
        "side_effects_common": "Increased urination, dizziness, low potassium, muscle cramps, and increased blood sugar or uric acid.",
        "side_effects_serious": "Severe electrolyte imbalance (weakness, confusion, irregular heartbeat), gout flares, acute eye pain from angle-closure glaucoma (rare), and severe skin reactions with sun exposure.",
        "interactions": "Lithium (levels rise dangerously), digoxin (low potassium raises toxicity risk), NSAIDs (blunt the diuretic effect), corticosteroids, and diabetes medicines.",
        "warnings": "Tell your doctor if you are allergic to sulfonamide drugs. Have electrolytes checked periodically, eat potassium-rich foods unless told otherwise, and use sun protection because of photosensitivity.",
    },
    {
        "name": "Atorvastatin", "slug": "atorvastatin",
        "generic_name": "atorvastatin calcium",
        "brand_names": "Lipitor",
        "drug_class": "HMG-CoA Reductase Inhibitor (Statin)",
        "category": "Cholesterol",
        "uses": "Lowers LDL ('bad') cholesterol and triglycerides, raises HDL ('good') cholesterol, and reduces the risk of heart attack and stroke in people with cardiovascular risk factors. One of the two most potent statins available.",
        "dosage": "Adults: 10 to 80 mg once daily, at any time of day, with or without food. A common starting dose is 10 or 20 mg; high-intensity therapy after a heart attack is 40 to 80 mg.",
        "side_effects_common": "Muscle aches, joint pain, diarrhea, and mild elevations in liver enzymes.",
        "side_effects_serious": "Rhabdomyolysis (severe muscle breakdown with dark urine and weakness), liver injury, and new-onset diabetes in predisposed people.",
        "interactions": "Grapefruit juice in large quantities, clarithromycin, itraconazole, cyclosporine, and gemfibrozil all raise atorvastatin levels and muscle-injury risk. Also interacts with digoxin and some HIV medicines.",
        "warnings": "Report unexplained muscle pain, tenderness, or weakness promptly, especially with fever or dark urine. Do not use during pregnancy or while breastfeeding.",
    },
    {
        "name": "Simvastatin", "slug": "simvastatin",
        "generic_name": "simvastatin",
        "brand_names": "Zocor",
        "drug_class": "HMG-CoA Reductase Inhibitor (Statin)",
        "category": "Cholesterol",
        "uses": "Lowers LDL cholesterol and triglycerides and reduces cardiovascular events in people with heart disease or diabetes. An older statin with more drug-interaction limits than atorvastatin or rosuvastatin.",
        "dosage": "Adults: 10 to 40 mg once daily in the evening — evening dosing matters because the body makes most cholesterol at night. The 80 mg dose is restricted to patients who have tolerated it long-term.",
        "side_effects_common": "Headache, muscle aches, constipation, and nausea.",
        "side_effects_serious": "Myopathy and rhabdomyolysis (risk rises sharply with interacting drugs and the 80 mg dose), and liver injury.",
        "interactions": "Contraindicated with clarithromycin, erythromycin, itraconazole, ketoconazole, gemfibrozil, and cyclosporine. Limit to 20 mg daily with amlodipine and 10 mg daily with verapamil or diltiazem. Avoid grapefruit juice.",
        "warnings": "Because of muscle toxicity risk, never exceed your prescribed dose, and review every new medicine — including antibiotics — with your pharmacist. Report muscle pain or weakness right away.",
    },
    {
        "name": "Rosuvastatin", "slug": "rosuvastatin",
        "generic_name": "rosuvastatin calcium",
        "brand_names": "Crestor",
        "drug_class": "HMG-CoA Reductase Inhibitor (Statin)",
        "category": "Cholesterol",
        "uses": "Lowers LDL cholesterol, raises HDL, slows the progression of atherosclerosis, and reduces the risk of heart attack and stroke. Milligram for milligram it is the most potent statin.",
        "dosage": "Adults: 5 to 40 mg once daily, at any time of day. Common starting doses are 10 to 20 mg; the 40 mg dose is reserved for patients not reaching their LDL goal on 20 mg. Asian patients often start at 5 mg because blood levels run higher.",
        "side_effects_common": "Headache, muscle aches, abdominal pain, and nausea.",
        "side_effects_serious": "Myopathy and rhabdomyolysis, liver enzyme elevations, and protein or blood in the urine at the highest dose.",
        "interactions": "Cyclosporine, gemfibrozil, certain HIV and hepatitis C antivirals, and warfarin (monitor INR). Antacids containing aluminum or magnesium should be taken at least 2 hours after rosuvastatin.",
        "warnings": "Report unexplained muscle pain or weakness, especially with fever. Not for use in pregnancy. Periodic liver enzyme and cholesterol checks are standard while on therapy.",
    },
    {
        "name": "Warfarin", "slug": "warfarin",
        "generic_name": "warfarin sodium",
        "brand_names": "Coumadin, Jantoven",
        "drug_class": "Vitamin K Antagonist Anticoagulant",
        "category": "Blood Thinners",
        "uses": "Prevents and treats blood clots in the legs (DVT) and lungs (pulmonary embolism), and prevents stroke in people with atrial fibrillation or mechanical heart valves. It blocks vitamin K-dependent clotting factors.",
        "dosage": "Highly individualized: typically started at 2 to 5 mg once daily and adjusted based on INR blood tests, with most patients targeting an INR of 2.0 to 3.0. Take at the same time each evening.",
        "side_effects_common": "Easy bruising and minor bleeding from gums or small cuts.",
        "side_effects_serious": "Major bleeding (gastrointestinal, urinary, or into the brain), skin necrosis early in therapy, and purple toe syndrome.",
        "interactions": "One of the most interaction-prone drugs in medicine: NSAIDs, aspirin, many antibiotics (including ciprofloxacin, azithromycin, and amoxicillin), amiodarone, and even acetaminophen at regular high doses can raise bleeding risk, while vitamin K-rich foods and rifampin reduce its effect.",
        "warnings": "Boxed warning for major or fatal bleeding — regular INR monitoring is essential. Keep vitamin K intake (leafy greens) consistent rather than avoiding it entirely, and tell every prescriber and dentist you take warfarin.",
    },
    {
        "name": "Clopidogrel", "slug": "clopidogrel",
        "generic_name": "clopidogrel bisulfate",
        "brand_names": "Plavix",
        "drug_class": "P2Y12 Platelet Inhibitor",
        "category": "Blood Thinners",
        "uses": "Reduces the risk of heart attack and stroke in people with recent heart attack, recent stroke, peripheral artery disease, or acute coronary syndrome, and keeps coronary stents from clotting, usually combined with low-dose aspirin for a defined period.",
        "dosage": "Adults: 75 mg once daily, with or without food. A one-time loading dose of 300 to 600 mg is often given at the start of treatment for acute coronary syndrome or stenting.",
        "side_effects_common": "Bruising, minor bleeding, itching, and diarrhea.",
        "side_effects_serious": "Major bleeding, and a rare but life-threatening blood disorder called thrombotic thrombocytopenic purpura (TTP), usually within the first two weeks.",
        "interactions": "Omeprazole and esomeprazole reduce its activation and should be avoided (pantoprazole or famotidine are alternatives); NSAIDs and warfarin add bleeding risk.",
        "warnings": "Boxed warning: poor metabolizers of CYP2C19 get less benefit — genetic testing is available. Never stop clopidogrel after a stent without talking to your cardiologist, even before dental work or surgery.",
    },
    {
        "name": "Apixaban", "slug": "apixaban",
        "generic_name": "apixaban",
        "brand_names": "Eliquis",
        "drug_class": "Factor Xa Inhibitor Anticoagulant",
        "category": "Blood Thinners",
        "uses": "Prevents stroke in nonvalvular atrial fibrillation, treats and prevents deep vein thrombosis and pulmonary embolism, and prevents clots after hip or knee replacement — without the routine blood-test monitoring warfarin requires.",
        "dosage": "For atrial fibrillation: 5 mg twice daily, reduced to 2.5 mg twice daily in patients with at least two of: age 80 or older, body weight 60 kg or less, or elevated creatinine. DVT treatment starts at 10 mg twice daily for 7 days, then 5 mg twice daily.",
        "side_effects_common": "Easy bruising and minor bleeding; nausea is uncommon.",
        "side_effects_serious": "Major bleeding including gastrointestinal and intracranial hemorrhage, and spinal hematomas after epidural procedures.",
        "interactions": "Strong dual CYP3A4/P-gp inhibitors (ketoconazole, ritonavir) raise levels; rifampin, carbamazepine, and St. John's wort lower them. Aspirin, NSAIDs, and other blood thinners add bleeding risk.",
        "warnings": "Boxed warnings: stopping apixaban early increases clot and stroke risk, and spinal punctures during therapy can cause paralysis-causing hematomas. Do not miss doses — its protection fades within a day.",
    },
    {
        "name": "Metformin", "slug": "metformin",
        "generic_name": "metformin hydrochloride",
        "brand_names": "Glucophage, Glucophage XR",
        "drug_class": "Biguanide Antidiabetic",
        "category": "Diabetes",
        "uses": "The first-choice medicine for type 2 diabetes: it lowers blood sugar by reducing the liver's glucose production and improving the body's sensitivity to insulin. It does not cause weight gain and rarely causes low blood sugar on its own.",
        "dosage": "Adults: usually started at 500 mg once or twice daily with meals, increased gradually to a typical maintenance dose of 1,000 mg twice daily. Maximum 2,550 mg per day (immediate-release). Extended-release forms are taken once daily with the evening meal.",
        "side_effects_common": "Diarrhea, nausea, gas, abdominal discomfort, and a metallic taste — usually improving after the first weeks.",
        "side_effects_serious": "Lactic acidosis (very rare but life-threatening: deep rapid breathing, severe weakness, unusual muscle pain), and vitamin B12 deficiency with long-term use.",
        "interactions": "Iodinated contrast dye (hold metformin around imaging procedures), heavy alcohol use, carbonic anhydrase inhibitors like topiramate, and cimetidine.",
        "warnings": "Boxed warning for lactic acidosis — risk rises with kidney impairment, liver disease, heavy drinking, and dehydration. Your doctor will check kidney function before and during treatment.",
    },
    {
        "name": "Glipizide", "slug": "glipizide",
        "generic_name": "glipizide",
        "brand_names": "Glucotrol, Glucotrol XL",
        "drug_class": "Sulfonylurea Antidiabetic",
        "category": "Diabetes",
        "uses": "Lowers blood sugar in type 2 diabetes by stimulating the pancreas to release more insulin. Often added when metformin alone is not enough.",
        "dosage": "Adults: started at 5 mg once daily taken 30 minutes before breakfast, adjusted up to 40 mg per day (immediate-release, divided) or 20 mg once daily (extended-release).",
        "side_effects_common": "Low blood sugar (shakiness, sweating, hunger, confusion), dizziness, and modest weight gain.",
        "side_effects_serious": "Severe or prolonged hypoglycemia, especially in older adults or with missed meals, and rare liver or blood-cell effects.",
        "interactions": "Alcohol (can trigger both hypoglycemia and flushing), beta-blockers such as metoprolol (mask low-sugar warning signs), fluconazole, and NSAIDs.",
        "warnings": "Always carry a fast-acting sugar source. Do not skip meals after taking a dose. Tell your doctor before periods of fasting, illness, or increased exercise, which change your insulin needs.",
    },
    {
        "name": "Insulin Glargine", "slug": "insulin-glargine",
        "generic_name": "insulin glargine",
        "brand_names": "Lantus, Basaglar, Toujeo",
        "drug_class": "Long-Acting Insulin Analog",
        "category": "Diabetes",
        "uses": "A once-daily basal insulin that provides a steady background level of insulin over about 24 hours to control blood sugar in type 1 and type 2 diabetes. It is injected under the skin and is not used to correct sudden sugar spikes.",
        "dosage": "Individualized by a clinician: type 2 diabetes commonly starts at 10 units (or 0.2 units/kg) once daily at the same time each day, then is titrated based on fasting glucose readings. Rotate injection sites on the abdomen, thigh, or upper arm.",
        "side_effects_common": "Low blood sugar, injection-site redness or thickened skin, and weight gain.",
        "side_effects_serious": "Severe hypoglycemia with confusion, seizures, or loss of consciousness; low potassium; and serious allergic reactions.",
        "interactions": "Other diabetes medicines (additive sugar lowering), beta-blockers (mask hypoglycemia symptoms), thiazolidinediones (fluid retention and heart failure risk), and alcohol.",
        "warnings": "Never share pens or needles, even with family. Do not dilute or mix glargine with other insulins in the same syringe. Learn the symptoms of low blood sugar and keep glucose tablets or juice on hand.",
    },
    {
        "name": "Sitagliptin", "slug": "sitagliptin",
        "generic_name": "sitagliptin",
        "brand_names": "Januvia",
        "drug_class": "Dipeptidyl Peptidase-4 (DPP-4) Inhibitor",
        "category": "Diabetes",
        "uses": "Improves blood sugar control in adults with type 2 diabetes by boosting the body's own incretin hormones, which increase insulin release after meals and reduce the liver's sugar output. Weight-neutral with a low risk of hypoglycemia when used alone.",
        "dosage": "Adults: 100 mg once daily, with or without food. The dose is lowered to 50 mg daily in moderate kidney impairment and 25 mg daily in severe kidney impairment.",
        "side_effects_common": "Stuffy or runny nose, sore throat, headache, and upper respiratory infections.",
        "side_effects_serious": "Pancreatitis (severe persistent abdominal pain radiating to the back), serious allergic reactions, severe disabling joint pain, and worsening heart failure in some patients.",
        "interactions": "Insulin and sulfonylureas such as glipizide (their doses may need lowering to avoid hypoglycemia); digoxin levels rise slightly.",
        "warnings": "Stop the drug and seek care for severe abdominal pain that will not ease — pancreatitis has been reported. Tell your doctor about any history of pancreatitis, kidney disease, or heart failure.",
    },
    {
        "name": "Pravastatin", "slug": "pravastatin",
        "generic_name": "pravastatin sodium",
        "brand_names": "Pravachol",
        "drug_class": "HMG-CoA Reductase Inhibitor (Statin)",
        "category": "Cholesterol",
        "uses": "Lowers LDL ('bad') cholesterol and reduces cardiovascular risk. A lower-intensity statin than atorvastatin or rosuvastatin, it is often chosen when a higher-intensity statin caused muscle aches, or when a patient takes interacting medicines, because it is cleared without the liver enzymes most statins depend on.",
        "dosage": "Adults: 40 mg once daily to start, adjustable between 10 and 80 mg daily. Can be taken at any time of day, with or without food.",
        "side_effects_common": "Muscle or joint aches, nausea, headache, and cold-like symptoms.",
        "side_effects_serious": "Muscle breakdown (rhabdomyolysis) with dark urine and severe muscle pain, and liver injury (rare).",
        "interactions": "Fewer than most statins because it bypasses CYP3A4 metabolism: cyclosporine and clarithromycin still raise its levels, and combining with gemfibrozil raises muscle-injury risk.",
        "warnings": "Do not use during pregnancy. Report unexplained muscle pain, tenderness, or weakness promptly, especially with fever or dark urine.",
    },
    {
        "name": "Lovastatin", "slug": "lovastatin",
        "generic_name": "lovastatin",
        "brand_names": "Mevacor (discontinued brand), Altoprev",
        "drug_class": "HMG-CoA Reductase Inhibitor (Statin)",
        "category": "Cholesterol",
        "uses": "The first statin approved in the United States, used to lower LDL cholesterol and slow coronary artery disease. Its LDL-lowering is more modest than atorvastatin or rosuvastatin, so it now serves mainly patients who need moderate-intensity therapy and tolerate it well.",
        "dosage": "Adults: 20 mg once daily with the evening meal to start; range 10 to 80 mg daily. Immediate-release tablets absorb best with food, unlike most other statins.",
        "side_effects_common": "Muscle aches, constipation, stomach upset, and headache.",
        "side_effects_serious": "Rhabdomyolysis with kidney failure (risk rises sharply with interacting drugs), and liver enzyme elevations.",
        "interactions": "Strong CYP3A4 inhibitors — clarithromycin, itraconazole, protease inhibitors, and grapefruit juice in quantity — are contraindicated. Amiodarone, diltiazem, and verapamil require dose caps.",
        "warnings": "Avoid grapefruit juice. Do not use during pregnancy or with the contraindicated antibiotics and antifungals listed above — switch statins instead of risking the combination.",
    },
    {
        "name": "Allopurinol", "slug": "allopurinol",
        "generic_name": "allopurinol",
        "brand_names": "Zyloprim, Aloprim",
        "drug_class": "Xanthine Oxidase Inhibitor",
        "category": "Pain & Inflammation",
        "uses": "The first-choice daily medicine for preventing gout attacks: it lowers the body's production of uric acid so crystals stop forming in joints. Also used for kidney stones caused by uric acid and for high urate from cancer treatment. It does not relieve an attack already underway.",
        "dosage": "Start low — 100 mg once daily (50 mg in kidney disease) — and increase every 2 to 5 weeks until blood uric acid falls below 6 mg/dL; typical maintenance is 300 mg daily, maximum 800 mg. Take after meals with plenty of water.",
        "side_effects_common": "Rash, stomach upset, drowsiness, and a temporary increase in gout flares during the first months (often covered with low-dose colchicine).",
        "side_effects_serious": "Severe hypersensitivity syndrome with fever, widespread rash, and liver and kidney injury — stop at the first sign of rash. Risk is higher in people with the HLA-B*58:01 gene variant.",
        "interactions": "Azathioprine and mercaptopurine (dangerous accumulation — doses must be cut), warfarin (enhanced effect), amoxicillin (higher rash rates), and thiazide diuretics (higher hypersensitivity risk).",
        "warnings": "Do not stop during a gout flare if already taking it, and do not start during one. Stay well hydrated, and report any rash immediately.",
    },
    {
        "name": "Colchicine", "slug": "colchicine",
        "generic_name": "colchicine",
        "brand_names": "Colcrys, Mitigare",
        "drug_class": "Anti-Gout Anti-Inflammatory",
        "category": "Pain & Inflammation",
        "uses": "Treats and prevents gout flares by calming the inflammatory response to urate crystals, and treats the crystal arthritis of pseudogout. Low doses are also used long-term while urate-lowering therapy is being started.",
        "dosage": "For a gout flare: 1.2 mg at the first sign, then 0.6 mg one hour later (1.8 mg total), started within 24 hours of onset. For prevention: 0.6 mg once or twice daily. Doses must be reduced with kidney or liver impairment.",
        "side_effects_common": "Diarrhea, nausea, cramping, and vomiting — often the first sign the dose is too high.",
        "side_effects_serious": "Life-threatening toxicity in overdose or with interacting drugs: muscle damage, bone marrow suppression, and multi-organ failure.",
        "interactions": "Clarithromycin, itraconazole, cyclosporine, and other strong CYP3A4/P-glycoprotein inhibitors can make standard doses toxic — combinations are contraindicated in kidney or liver disease. Statins raise muscle-injury risk.",
        "warnings": "Narrow margin between effective and toxic doses — never take extra to 'finish off' a flare. Keep away from children; overdose is a medical emergency.",
    },
]
