"""Condition catalog, part A (A–H), plus the master symptom list.

Medical facts (symptom profiles, causes, standard treatments) follow
MedlinePlus / NIH public-domain health-topic data; all prose is original.
"""

# Master symptom list for the symptom checker. Each condition below links
# 3-6 of these via symptom_slugs.
SYMPTOMS = [
    ("Fatigue", "fatigue"),
    ("Headache", "headache"),
    ("Fever", "fever"),
    ("Cough", "cough"),
    ("Shortness of breath", "shortness-of-breath"),
    ("Wheezing", "wheezing"),
    ("Chest pain", "chest-pain"),
    ("Heart palpitations", "palpitations"),
    ("Dizziness", "dizziness"),
    ("Nausea", "nausea"),
    ("Vomiting", "vomiting"),
    ("Diarrhea", "diarrhea"),
    ("Constipation", "constipation"),
    ("Abdominal pain", "abdominal-pain"),
    ("Heartburn", "heartburn"),
    ("Bloating", "bloating"),
    ("Joint pain", "joint-pain"),
    ("Joint stiffness", "joint-stiffness"),
    ("Muscle aches", "muscle-aches"),
    ("Back pain", "back-pain"),
    ("Swelling in legs or feet", "swelling"),
    ("Skin rash", "rash"),
    ("Itching", "itching"),
    ("Sore throat", "sore-throat"),
    ("Runny nose", "runny-nose"),
    ("Nasal congestion", "nasal-congestion"),
    ("Sneezing", "sneezing"),
    ("Frequent urination", "frequent-urination"),
    ("Painful urination", "painful-urination"),
    ("Increased thirst", "increased-thirst"),
    ("Unintended weight loss", "weight-loss"),
    ("Weight gain", "weight-gain"),
    ("Blurred vision", "blurred-vision"),
    ("Numbness or tingling", "numbness-tingling"),
    ("Trouble sleeping", "trouble-sleeping"),
    ("Persistent sadness or low mood", "low-mood"),
    ("Irritability", "irritability"),
    ("Excessive worry", "excessive-worry"),
    ("Night sweats", "night-sweats"),
    ("Loss of appetite", "loss-of-appetite"),
]

CONDITIONS_A = [
    {
        "name": "Acne", "slug": "acne", "letter": "A",
        "overview": "Acne is the most common skin condition in the United States, occurring when hair follicles become clogged with oil and dead skin cells. It typically appears on the face, chest, upper back, and shoulders, and while most common in teenagers, it affects people of all ages.",
        "symptoms": "Whiteheads, blackheads, small red tender bumps (papules), pus-filled pimples, and — in more severe forms — painful lumps beneath the skin (nodules and cysts) that can scar.",
        "causes": "Four factors drive acne: excess oil (sebum) production, clogged follicles, Cutibacterium acnes bacteria, and inflammation. Hormonal changes during puberty, menstrual cycles, and pregnancy, certain medications such as corticosteroids, and genetics all contribute.",
        "treatments": "Mild acne responds to over-the-counter benzoyl peroxide, salicylic acid, and adapalene gel. Moderate to severe cases may need prescription topical retinoids, oral antibiotics such as doxycycline, hormonal therapy, or isotretinoin for resistant nodular acne.",
        "related_drug_slugs": ["doxycycline"],
        "symptom_slugs": ["rash", "itching"],
    },
    {
        "name": "Allergic Rhinitis (Hay Fever)", "slug": "allergic-rhinitis", "letter": "A",
        "overview": "Allergic rhinitis is an allergic response of the nasal passages to airborne substances such as pollen, dust mites, mold, or pet dander. Seasonal forms flare with pollen seasons, while perennial forms cause year-round symptoms.",
        "symptoms": "Sneezing fits, runny nose with clear discharge, nasal congestion, itchy nose, throat, and eyes, watery eyes, and post-nasal drip. Many people also feel tired during heavy allergy periods.",
        "causes": "The immune system mistakes a harmless airborne protein for a threat and releases histamine and other chemicals. Common triggers are tree, grass, and ragweed pollens, dust mites, cockroach droppings, mold spores, and animal dander. A family history of allergies raises risk.",
        "treatments": "Intranasal corticosteroid sprays such as fluticasone are the most effective single therapy. Oral second-generation antihistamines (cetirizine, loratadine, fexofenadine) relieve sneezing and itching, montelukast is an option when other treatments fail, and allergen immunotherapy can retrain the immune system.",
        "related_drug_slugs": ["fluticasone-nasal", "cetirizine", "loratadine", "fexofenadine", "montelukast"],
        "symptom_slugs": ["sneezing", "runny-nose", "nasal-congestion", "itching"],
    },
    {
        "name": "Anemia (Iron-Deficiency)", "slug": "iron-deficiency-anemia", "letter": "A",
        "overview": "Iron-deficiency anemia develops when the body lacks enough iron to make hemoglobin, the protein that lets red blood cells carry oxygen. It is the most common type of anemia worldwide and is especially frequent in menstruating and pregnant women.",
        "symptoms": "Fatigue, weakness, pale skin, shortness of breath with activity, dizziness, cold hands and feet, brittle nails, and sometimes unusual cravings for ice or dirt (pica).",
        "causes": "Blood loss (heavy periods, gastrointestinal bleeding from ulcers or NSAID use), poor dietary iron intake, impaired absorption from celiac disease or gastric surgery, and the increased iron demands of pregnancy.",
        "treatments": "Oral iron supplements taken on an empty stomach or with vitamin C for better absorption, treating the underlying source of blood loss, iron-rich foods (lean meat, beans, fortified cereals), and intravenous iron or transfusion for severe cases.",
        "related_drug_slugs": [],
        "symptom_slugs": ["fatigue", "dizziness", "shortness-of-breath", "headache"],
    },
    {
        "name": "Anxiety (Generalized Anxiety Disorder)", "slug": "generalized-anxiety-disorder", "letter": "A",
        "overview": "Generalized anxiety disorder (GAD) is marked by persistent, excessive worry about everyday matters that is difficult to control and lasts six months or longer. It affects roughly 3 percent of U.S. adults in a given year and often coexists with depression.",
        "symptoms": "Constant worry out of proportion to events, restlessness or feeling on edge, fatigue, difficulty concentrating, irritability, muscle tension, and sleep problems.",
        "causes": "A combination of genetics, brain chemistry involving serotonin and norepinephrine, personality traits, and life experiences including chronic stress or trauma. Medical conditions such as thyroid disease and stimulants like caffeine can mimic or worsen it.",
        "treatments": "Cognitive behavioral therapy (CBT) and SSRI or SNRI antidepressants such as escitalopram, sertraline, duloxetine, and venlafaxine are first-line. Benzodiazepines like lorazepam or alprazolam may be used briefly for severe episodes but carry dependence risk. Regular exercise and limiting caffeine help.",
        "related_drug_slugs": ["escitalopram", "sertraline", "duloxetine", "venlafaxine", "lorazepam", "alprazolam"],
        "symptom_slugs": ["excessive-worry", "irritability", "trouble-sleeping", "fatigue", "muscle-aches"],
    },
    {
        "name": "Asthma", "slug": "asthma", "letter": "A",
        "overview": "Asthma is a chronic disease in which the airways become inflamed, narrow, and produce extra mucus, making breathing difficult. About 25 million Americans have asthma, and while it cannot be cured, modern treatment lets most people live fully active lives.",
        "symptoms": "Wheezing (a whistling sound when breathing out), shortness of breath, chest tightness, and coughing that is often worse at night, early in the morning, or after exercise. Symptoms flare episodically as 'attacks.'",
        "causes": "A mix of genetic predisposition and environmental exposures. Common triggers include airborne allergens (pollen, dust mites, pet dander), respiratory infections, cold air, exercise, smoke, air pollution, strong odors, and stress. Aspirin and NSAIDs trigger attacks in some people.",
        "treatments": "Daily inhaled corticosteroids form the foundation of control, with a short-acting rescue inhaler such as albuterol for quick relief of attacks. Add-on options include long-acting bronchodilators and montelukast, plus an asthma action plan and trigger avoidance. Oral prednisone treats severe flare-ups.",
        "related_drug_slugs": ["albuterol", "montelukast", "prednisone"],
        "symptom_slugs": ["wheezing", "shortness-of-breath", "cough", "chest-pain"],
    },
    {
        "name": "Atrial Fibrillation", "slug": "atrial-fibrillation", "letter": "A",
        "overview": "Atrial fibrillation (AFib) is the most common serious heart rhythm disorder, in which the heart's upper chambers quiver chaotically instead of beating effectively. It matters chiefly because pooled blood can clot and cause a stroke — AFib raises stroke risk about fivefold.",
        "symptoms": "A racing, fluttering, or irregular heartbeat, fatigue, reduced exercise capacity, shortness of breath, light-headedness, and chest discomfort. Some people have no symptoms and are diagnosed incidentally.",
        "causes": "High blood pressure, coronary artery disease, heart valve problems, heart failure, overactive thyroid, sleep apnea, obesity, heavy alcohol use, and advancing age. Episodes may be triggered by binge drinking, stimulants, or acute illness.",
        "treatments": "Two pillars: stroke prevention with anticoagulants such as apixaban or warfarin, and rhythm or rate control with beta-blockers like metoprolol, antiarrhythmic drugs, cardioversion, or catheter ablation. Treating sleep apnea, alcohol reduction, and weight loss reduce recurrences.",
        "related_drug_slugs": ["apixaban", "warfarin", "metoprolol", "atenolol"],
        "symptom_slugs": ["palpitations", "fatigue", "shortness-of-breath", "dizziness", "chest-pain"],
    },
    {
        "name": "Back Pain (Low Back Pain)", "slug": "low-back-pain", "letter": "B",
        "overview": "Low back pain is one of the most common reasons for doctor visits, affecting about 80 percent of adults at some point. Most episodes are 'nonspecific' — arising from muscles, ligaments, discs, and joints — and improve within a few weeks.",
        "symptoms": "Aching or stabbing pain in the lower back, stiffness, muscle spasm, and pain that may radiate into the buttock or down the leg (sciatica) when a nerve root is irritated. Red flags such as numbness in the groin, loss of bladder control, or fever warrant urgent care.",
        "causes": "Muscle or ligament strain from lifting or awkward movement, degenerated or herniated discs, arthritis of the spinal joints, spinal stenosis, osteoporosis-related fractures, and poor conditioning. Prolonged sitting, obesity, and smoking raise risk.",
        "treatments": "Stay active — bed rest slows recovery. Short-term NSAIDs such as ibuprofen or naproxen, heat, and gentle stretching help most episodes; muscle relaxants like cyclobenzaprine may be added briefly for spasm. Physical therapy and core strengthening prevent recurrences; duloxetine helps some chronic cases.",
        "related_drug_slugs": ["ibuprofen", "naproxen", "cyclobenzaprine", "duloxetine", "acetaminophen"],
        "symptom_slugs": ["back-pain", "muscle-aches", "numbness-tingling"],
    },
    {
        "name": "Bipolar Disorder", "slug": "bipolar-disorder", "letter": "B",
        "overview": "Bipolar disorder causes dramatic shifts in mood, energy, and activity — from emotional highs (mania or hypomania) to lows (depression). Episodes may last days to months, and with consistent treatment most people achieve long stretches of stability.",
        "symptoms": "Manic periods bring elevated or irritable mood, racing thoughts, decreased need for sleep, grandiosity, rapid speech, and risky behavior; depressive periods bring persistent sadness, loss of interest, fatigue, sleep and appetite changes, and thoughts of death.",
        "causes": "Strong genetic influence — having a first-degree relative with bipolar disorder is the biggest risk factor — combined with differences in brain structure and neurotransmitter signaling. Stress, sleep disruption, and substance use can trigger episodes.",
        "treatments": "Mood stabilizers (lithium, valproate, lamotrigine) and certain antipsychotics form the core of treatment, alongside psychotherapy and strict sleep routines. Antidepressants alone can flip a person into mania and are used cautiously if at all.",
        "related_drug_slugs": [],
        "symptom_slugs": ["low-mood", "irritability", "trouble-sleeping", "fatigue"],
    },
    {
        "name": "Bronchitis (Acute)", "slug": "acute-bronchitis", "letter": "B",
        "overview": "Acute bronchitis — often called a chest cold — is short-term inflammation of the bronchial tubes, usually following an upper respiratory infection. The hallmark cough typically lasts two to three weeks and resolves on its own.",
        "symptoms": "Persistent cough that may bring up clear, white, or yellow-green mucus, chest soreness from coughing, mild shortness of breath or wheezing, fatigue, sore throat, and sometimes low-grade fever.",
        "causes": "Viruses cause more than 90 percent of cases — the same viruses behind colds and flu — so antibiotics rarely help. Smoke, dust, and fumes can also inflame the airways.",
        "treatments": "Rest, fluids, honey for cough, and humidified air. Ibuprofen or acetaminophen ease chest soreness and fever. An albuterol inhaler helps if there is wheezing. See a doctor for fever over 100.4°F lasting days, bloody mucus, or a cough beyond three weeks.",
        "related_drug_slugs": ["ibuprofen", "acetaminophen", "albuterol"],
        "symptom_slugs": ["cough", "fatigue", "sore-throat", "wheezing", "fever"],
    },
    {
        "name": "Carpal Tunnel Syndrome", "slug": "carpal-tunnel-syndrome", "letter": "C",
        "overview": "Carpal tunnel syndrome occurs when the median nerve is compressed as it passes through the narrow carpal tunnel at the wrist. It is the most common nerve-entrapment condition, and early treatment usually prevents permanent nerve damage.",
        "symptoms": "Numbness, tingling, or burning in the thumb, index, middle, and half of the ring finger — classically waking people at night — plus hand weakness, dropping objects, and an electric-shock feeling shooting into the fingers.",
        "causes": "Anything that crowds the tunnel: wrist anatomy, repetitive hand use and prolonged awkward wrist positions, pregnancy-related fluid retention, hypothyroidism, diabetes, rheumatoid arthritis, and obesity.",
        "treatments": "A neutral-position wrist splint worn at night is the first step, along with activity modification. Corticosteroid injections reduce swelling around the nerve; NSAIDs help short-term pain. Surgery to release the ligament is highly effective when numbness persists or muscles weaken.",
        "related_drug_slugs": ["ibuprofen", "naproxen"],
        "symptom_slugs": ["numbness-tingling", "muscle-aches"],
    },
    {
        "name": "Celiac Disease", "slug": "celiac-disease", "letter": "C",
        "overview": "Celiac disease is an autoimmune disorder in which eating gluten — a protein in wheat, barley, and rye — triggers an immune attack on the small intestine's lining. About 1 in 100 people worldwide are affected, many undiagnosed.",
        "symptoms": "Diarrhea, bloating, gas, abdominal pain, fatigue, weight loss, and iron-deficiency anemia. Adults may have non-digestive signs: an itchy blistering rash (dermatitis herpetiformis), bone loss, mouth ulcers, and numbness in the hands and feet.",
        "causes": "A genetic immune reaction to gluten: nearly all patients carry HLA-DQ2 or HLA-DQ8 genes. Family history, type 1 diabetes, and autoimmune thyroid disease raise risk. Onset can occur at any age.",
        "treatments": "A strict, lifelong gluten-free diet is the only treatment — the intestinal lining then heals over months. Dietitian guidance, vitamin and mineral repletion (iron, B12, vitamin D), and follow-up antibody testing to confirm dietary control.",
        "related_drug_slugs": [],
        "symptom_slugs": ["diarrhea", "bloating", "abdominal-pain", "fatigue", "weight-loss"],
    },
    {
        "name": "Chronic Kidney Disease", "slug": "chronic-kidney-disease", "letter": "C",
        "overview": "Chronic kidney disease (CKD) means the kidneys are damaged and gradually losing their ability to filter blood, over months to years. It affects an estimated 1 in 7 U.S. adults, most of whom don't know they have it because early stages are silent.",
        "symptoms": "Usually none until late stages, then fatigue, swelling in the legs and around the eyes, foamy urine, increased or decreased urination, nausea, loss of appetite, itching, muscle cramps, and trouble concentrating.",
        "causes": "Diabetes and high blood pressure cause about two-thirds of cases. Other causes include glomerulonephritis, polycystic kidney disease, repeated kidney infections, prolonged urinary blockage, and long-term heavy NSAID use.",
        "treatments": "Control the drivers: blood pressure with ACE inhibitors or ARBs (lisinopril, losartan — which also protect kidneys), blood sugar in diabetes, and cholesterol with statins. Avoid NSAIDs, moderate protein and salt intake, and plan for dialysis or transplant in advanced disease.",
        "related_drug_slugs": ["lisinopril", "losartan", "atorvastatin"],
        "symptom_slugs": ["fatigue", "swelling", "nausea", "itching", "loss-of-appetite"],
    },
    {
        "name": "Common Cold", "slug": "common-cold", "letter": "C",
        "overview": "The common cold is a mild viral infection of the nose and throat. Adults average two to three colds per year, each lasting about 7 to 10 days; children get them even more often. Colds are the leading reason for missed work and school.",
        "symptoms": "Runny or stuffy nose, sneezing, sore or scratchy throat, cough, mild body aches, low-grade fever (more common in children), and watery eyes. Nasal discharge often thickens and turns yellow-green as the cold runs its course — that alone doesn't mean a bacterial infection.",
        "causes": "More than 200 viruses, most often rhinoviruses, spread by droplets and by hands touching contaminated surfaces then the eyes, nose, or mouth. Colds circulate most in fall and winter, largely because people gather indoors.",
        "treatments": "No cure — antibiotics do nothing against cold viruses. Rest, fluids, saline rinses, honey for cough, and symptom relievers: acetaminophen or ibuprofen for aches, an antihistamine such as diphenhydramine at night, and decongestants for short-term stuffiness.",
        "related_drug_slugs": ["acetaminophen", "ibuprofen", "diphenhydramine"],
        "symptom_slugs": ["runny-nose", "sneezing", "sore-throat", "cough", "nasal-congestion"],
    },
    {
        "name": "COPD (Chronic Obstructive Pulmonary Disease)", "slug": "copd", "letter": "C",
        "overview": "COPD is a progressive lung disease — encompassing emphysema and chronic bronchitis — that obstructs airflow and makes breathing increasingly difficult. It affects about 16 million diagnosed Americans and is a leading cause of death, yet it is largely preventable.",
        "symptoms": "Shortness of breath that worsens with activity, chronic cough with mucus ('smoker's cough'), wheezing, chest tightness, frequent respiratory infections, fatigue, and in later stages unintended weight loss.",
        "causes": "Cigarette smoking causes as many as 8 in 10 cases. Long-term exposure to secondhand smoke, air pollution, occupational dusts and fumes, and a rare genetic deficiency of alpha-1 antitrypsin account for the rest.",
        "treatments": "Quitting smoking is the single most important step at any stage. Bronchodilator inhalers (including albuterol for rescue), inhaled corticosteroids for frequent flare-ups, pulmonary rehabilitation, vaccinations, oxygen therapy for low blood oxygen, and prednisone plus antibiotics for exacerbations.",
        "related_drug_slugs": ["albuterol", "prednisone", "azithromycin"],
        "symptom_slugs": ["shortness-of-breath", "cough", "wheezing", "fatigue", "chest-pain"],
    },
    {
        "name": "Coronary Artery Disease", "slug": "coronary-artery-disease", "letter": "C",
        "overview": "Coronary artery disease (CAD) — the most common form of heart disease — develops when cholesterol-laden plaque builds up in the arteries supplying the heart muscle. It is the leading cause of death in the United States, and a ruptured plaque is what causes most heart attacks.",
        "symptoms": "Chest pain or pressure (angina) brought on by exertion or stress and relieved by rest, shortness of breath, and fatigue. A heart attack adds crushing chest pain, pain spreading to the arm, jaw, or back, sweating, and nausea — call 911 immediately.",
        "causes": "Atherosclerosis driven by high LDL cholesterol, high blood pressure, smoking, diabetes, obesity, physical inactivity, unhealthy diet, and family history. Risk climbs with age, and inflammation plays a central role.",
        "treatments": "Statins such as atorvastatin or rosuvastatin to lower LDL, low-dose aspirin or clopidogrel to prevent clots, beta-blockers like metoprolol and ACE inhibitors like lisinopril to protect the heart, nitroglycerin for angina, plus stenting or bypass surgery for severe blockages. Diet, exercise, and smoking cessation are foundational.",
        "related_drug_slugs": ["atorvastatin", "rosuvastatin", "aspirin", "clopidogrel", "metoprolol", "lisinopril"],
        "symptom_slugs": ["chest-pain", "shortness-of-breath", "fatigue"],
    },
    {
        "name": "Crohn's Disease", "slug": "crohns-disease", "letter": "C",
        "overview": "Crohn's disease is a chronic inflammatory bowel disease (IBD) that can inflame any part of the digestive tract — most often the end of the small intestine — in patches that penetrate deep into the bowel wall. It follows a relapsing-remitting course of flares and quiet periods.",
        "symptoms": "Persistent diarrhea, crampy abdominal pain (often right lower abdomen), urgency, weight loss, fatigue, low-grade fever, and mouth sores. Complications include strictures, fistulas, and abscesses; joints, skin, and eyes can also be affected.",
        "causes": "An inappropriate immune response to gut microbes in genetically susceptible people. Smoking doubles the risk and worsens the course. Onset most often occurs between ages 15 and 35. Diet and stress aggravate but do not cause it.",
        "treatments": "Corticosteroids such as prednisone calm flares; immunomodulators and biologic drugs (anti-TNF and newer agents) maintain remission and heal the bowel lining. Surgery removes damaged segments when medicines fail. Smoking cessation and nutritional support are essential.",
        "related_drug_slugs": ["prednisone", "loperamide"],
        "symptom_slugs": ["diarrhea", "abdominal-pain", "weight-loss", "fatigue", "fever"],
    },
    {
        "name": "Depression (Major Depressive Disorder)", "slug": "depression", "letter": "D",
        "overview": "Major depression is a common and serious mood disorder that affects how you feel, think, and function daily. About 8 percent of U.S. adults experience a major depressive episode in a given year; it is highly treatable, yet many people never seek care.",
        "symptoms": "Persistent sad, empty, or hopeless mood, loss of interest or pleasure in activities, sleep and appetite changes, fatigue, trouble concentrating, feelings of worthlessness or guilt, slowed movement or restlessness, and recurring thoughts of death or suicide, lasting most of the day for at least two weeks.",
        "causes": "An interplay of brain chemistry, genetics, hormones, and life circumstances. Risk rises with family history, major stress or loss, chronic illness, certain medications, and substance use. It can occur at any age and affects women about twice as often as men.",
        "treatments": "Psychotherapy (especially CBT) and antidepressants — SSRIs such as sertraline, fluoxetine, and escitalopram, SNRIs such as duloxetine and venlafaxine, or bupropion — work best combined. Exercise, sleep regularity, and social support help; treatment-resistant cases have options including esketamine and TMS. Crisis help: call or text 988.",
        "related_drug_slugs": ["sertraline", "fluoxetine", "escitalopram", "duloxetine", "venlafaxine", "bupropion", "trazodone"],
        "symptom_slugs": ["low-mood", "fatigue", "trouble-sleeping", "loss-of-appetite", "irritability"],
    },
    {
        "name": "Diabetes, Type 1", "slug": "type-1-diabetes", "letter": "D",
        "overview": "Type 1 diabetes is an autoimmune disease in which the immune system destroys the insulin-producing beta cells of the pancreas, leaving the body unable to make insulin. It accounts for about 5 to 10 percent of all diabetes and most often begins in childhood or young adulthood, though it can start at any age.",
        "symptoms": "Increased thirst, frequent urination, extreme hunger, unintended weight loss, fatigue, blurred vision, and irritability — often developing quickly over weeks. Untreated, it can progress to diabetic ketoacidosis with nausea, vomiting, fruity breath, and confusion.",
        "causes": "Autoimmune destruction of beta cells in genetically susceptible people, possibly triggered by viral infections or other environmental factors. It is not caused by diet or lifestyle and cannot currently be prevented.",
        "treatments": "Lifelong insulin — typically a long-acting basal insulin such as insulin glargine plus rapid-acting insulin at meals, or an insulin pump — paired with carbohydrate counting, frequent glucose monitoring or a continuous glucose monitor, and regular screening for eye, kidney, and nerve complications.",
        "related_drug_slugs": ["insulin-glargine"],
        "symptom_slugs": ["increased-thirst", "frequent-urination", "weight-loss", "fatigue", "blurred-vision"],
    },
    {
        "name": "Diabetes, Type 2", "slug": "type-2-diabetes", "letter": "D",
        "overview": "Type 2 diabetes is a chronic condition in which the body resists insulin's effects and gradually loses the ability to make enough of it, causing high blood sugar. It accounts for 90 to 95 percent of diabetes, affects more than 35 million Americans, and is closely tied to weight, activity, and genetics.",
        "symptoms": "Often none for years. When present: increased thirst, frequent urination, increased hunger, fatigue, blurred vision, slow-healing sores, frequent infections, and darkened skin in the armpits and neck (acanthosis nigricans).",
        "causes": "Insulin resistance driven by excess weight (especially abdominal fat), physical inactivity, genetics, and age, with strong family and ethnic risk patterns. Prediabetes almost always precedes it — a window where progression can be prevented.",
        "treatments": "Lifestyle change (weight loss, diet quality, 150 minutes of weekly activity) plus metformin as the usual first medicine. Additional options include sitagliptin, glipizide, newer injectable agents, and insulin glargine when needed, alongside blood pressure and cholesterol control to prevent heart, kidney, eye, and nerve complications.",
        "related_drug_slugs": ["metformin", "sitagliptin", "glipizide", "insulin-glargine"],
        "symptom_slugs": ["increased-thirst", "frequent-urination", "fatigue", "blurred-vision", "weight-gain"],
    },
    {
        "name": "Diverticulitis", "slug": "diverticulitis", "letter": "D",
        "overview": "Diverticulitis is inflammation or infection of small pouches (diverticula) that form in the wall of the colon, most often the lower left portion. The pouches themselves (diverticulosis) are common and harmless — about half of people over 60 have them — but roughly 5 percent develop diverticulitis.",
        "symptoms": "Constant pain in the lower left abdomen, fever, nausea, and a change in bowel habits (constipation more often than diarrhea). Severe cases can cause abscess, perforation, or bleeding.",
        "causes": "Pouches form where the colon wall is weak, under pressure; inflammation follows when a pouch tears or becomes blocked. Low-fiber diets, obesity, smoking, inactivity, and regular NSAID use raise risk. Nuts and seeds are no longer thought to trigger attacks.",
        "treatments": "Mild cases: rest, a clear-liquid then low-fiber diet during the attack, and acetaminophen for pain (NSAIDs can worsen bleeding risk); antibiotics for complicated or higher-risk cases. Afterward, a high-fiber diet prevents recurrences. Surgery is reserved for complications or repeated attacks.",
        "related_drug_slugs": ["acetaminophen", "ciprofloxacin"],
        "symptom_slugs": ["abdominal-pain", "fever", "nausea", "constipation"],
    },
    {
        "name": "Eczema (Atopic Dermatitis)", "slug": "eczema", "letter": "E",
        "overview": "Atopic dermatitis — the most common form of eczema — is a chronic condition that makes skin dry, itchy, and inflamed. It affects up to 20 percent of children and about 10 percent of adults, often alongside asthma and hay fever (the 'atopic triad').",
        "symptoms": "Intense itching (often worse at night), dry sensitive skin, red to brownish-gray patches — classically in the creases of elbows and knees, on hands, and on the face in infants — plus thickened, cracked, or scaly skin from scratching.",
        "causes": "A leaky skin barrier (often from variations in the filaggrin gene) plus immune overactivity. Flares are triggered by dry air, harsh soaps, fragrances, wool, sweat, stress, and allergens. It is not contagious.",
        "treatments": "Daily moisturizing with thick creams or ointments is the cornerstone, plus gentle skin care and trigger avoidance. Topical corticosteroids calm flares; non-steroid creams, antihistamines such as cetirizine for itch, and biologic injections for moderate-to-severe disease. Short lukewarm showers, then moisturize within three minutes.",
        "related_drug_slugs": ["cetirizine", "diphenhydramine"],
        "symptom_slugs": ["itching", "rash"],
    },
    {
        "name": "Enlarged Prostate (BPH)", "slug": "enlarged-prostate", "letter": "E",
        "overview": "Benign prostatic hyperplasia (BPH) is non-cancerous growth of the prostate gland that squeezes the urethra and slows urine flow. It is nearly universal with age — about half of men in their 50s and up to 90 percent of men over 80 have some degree of it — and it is not prostate cancer, nor does it raise cancer risk.",
        "symptoms": "A weak or interrupted urine stream, hesitancy getting started, dribbling at the end, a feeling the bladder never fully empties, urgency, and waking several times a night to urinate. Sudden inability to urinate at all is an emergency.",
        "causes": "Prostate growth driven by age-related hormonal shifts, particularly dihydrotestosterone (DHT). Family history, obesity, diabetes, and heart disease are associated with faster symptom progression; the symptom burden depends less on gland size than on where the growth presses.",
        "treatments": "Mild symptoms may need only watchful waiting and evening fluid timing. Alpha-blockers such as tamsulosin, alfuzosin, or silodosin relax the bladder outlet within days; 5-alpha reductase inhibitors (finasteride, dutasteride) shrink larger glands over months and can be combined with an alpha-blocker. Minimally invasive procedures and surgery (TURP) treat retention or failed drug therapy.",
        "related_drug_slugs": ["tamsulosin", "alfuzosin", "silodosin", "finasteride", "dutasteride"],
        "symptom_slugs": ["frequent-urination"],
    },
    {
        "name": "Fibromyalgia", "slug": "fibromyalgia", "letter": "F",
        "overview": "Fibromyalgia is a chronic disorder of widespread musculoskeletal pain accompanied by fatigue, sleep, memory, and mood problems, believed to arise from amplified pain processing in the central nervous system. It affects about 4 million U.S. adults, most of them women.",
        "symptoms": "Widespread aching on both sides of the body lasting three months or more, profound fatigue, unrefreshing sleep, 'fibro fog' (trouble focusing and remembering), headaches, and heightened sensitivity to pressure, noise, and temperature.",
        "causes": "Not fully understood: abnormal pain amplification involving brain and spinal cord signaling, often set off by physical trauma, infection, or significant stress. Genetics contribute, and it frequently coexists with IBS, migraine, and mood disorders.",
        "treatments": "Exercise — gradual, regular aerobic activity — is the best-proven therapy. FDA-approved medicines include pregabalin and duloxetine; low-dose amitriptyline and cyclobenzaprine at night can improve sleep and pain. CBT, stress management, and sleep hygiene round out care; opioids are not recommended.",
        "related_drug_slugs": ["pregabalin", "duloxetine", "cyclobenzaprine"],
        "symptom_slugs": ["muscle-aches", "fatigue", "trouble-sleeping", "headache", "joint-pain"],
    },
    {
        "name": "GERD (Acid Reflux)", "slug": "gerd", "letter": "G",
        "overview": "Gastroesophageal reflux disease (GERD) is chronic acid reflux — stomach contents flowing back into the esophagus at least weekly — caused by a weakened lower esophageal sphincter. About 20 percent of U.S. adults have it; untreated, it can damage the esophagus lining.",
        "symptoms": "Heartburn (burning behind the breastbone, often after meals or at night), regurgitation of sour liquid, difficulty swallowing, chest discomfort, chronic cough, hoarseness, and a lump-in-the-throat sensation.",
        "causes": "A weak or inappropriately relaxing lower esophageal sphincter, hiatal hernia, obesity, pregnancy, smoking, and delayed stomach emptying. Trigger foods include fatty and fried food, chocolate, peppermint, coffee, alcohol, and large late-night meals.",
        "treatments": "Weight loss, smaller earlier dinners, elevating the head of the bed, and trigger avoidance. Famotidine for milder or occasional symptoms; proton pump inhibitors such as omeprazole, esomeprazole, or pantoprazole for frequent GERD and to heal esophagitis. Surgery (fundoplication) is an option for refractory cases.",
        "related_drug_slugs": ["omeprazole", "esomeprazole", "pantoprazole", "famotidine"],
        "symptom_slugs": ["heartburn", "chest-pain", "cough", "nausea"],
    },
    {
        "name": "Gout", "slug": "gout", "letter": "G",
        "overview": "Gout is a painful form of inflammatory arthritis caused by uric acid crystals depositing in a joint, classically the base of the big toe. It affects about 4 percent of U.S. adults and has become more common; between flares it is silent, but untreated it can permanently damage joints.",
        "symptoms": "Sudden, severe joint pain often starting at night — the joint becomes hot, swollen, red, and exquisitely tender (even a bedsheet hurts). Attacks peak within 12 to 24 hours and subside over days to two weeks. Chronic gout can form visible crystal lumps (tophi).",
        "causes": "High blood uric acid from the body making too much or the kidneys clearing too little. Risk factors: red meat and organ meats, shellfish, beer and spirits, sugary drinks (fructose), obesity, kidney disease, and diuretics such as hydrochlorothiazide.",
        "treatments": "For flares: NSAIDs such as naproxen or ibuprofen, colchicine, or prednisone, started as early as possible. For prevention: daily urate-lowering therapy (allopurinol first-line) targeting uric acid below 6 mg/dL, plus limiting alcohol, sugary drinks, and purine-rich foods.",
        "related_drug_slugs": ["naproxen", "ibuprofen", "prednisone", "colchicine", "allopurinol"],
        "symptom_slugs": ["joint-pain", "swelling", "fever"],
    },
    {
        "name": "Heart Failure", "slug": "heart-failure", "letter": "H",
        "overview": "Heart failure means the heart cannot pump blood well enough to meet the body's needs — it does not mean the heart has stopped. About 6.7 million U.S. adults live with it, and modern drug therapy substantially improves both symptoms and survival.",
        "symptoms": "Shortness of breath with activity or when lying flat, waking at night gasping, swelling in the legs, ankles, and abdomen, rapid weight gain from fluid, fatigue, reduced exercise tolerance, persistent cough or wheezing, and rapid or irregular heartbeat.",
        "causes": "Most often the end result of coronary artery disease, prior heart attack, or long-standing high blood pressure. Other causes include faulty heart valves, cardiomyopathy, arrhythmias like atrial fibrillation, diabetes, alcohol excess, and certain chemotherapies.",
        "treatments": "Guideline therapy combines an ACE inhibitor or ARB (lisinopril, losartan), a beta-blocker such as metoprolol succinate, a mineralocorticoid antagonist, and newer SGLT2 inhibitors; diuretics like hydrochlorothiazide or furosemide control fluid. Daily weights, salt moderation, and cardiac rehab are key; devices and transplant serve advanced disease.",
        "related_drug_slugs": ["lisinopril", "losartan", "metoprolol", "hydrochlorothiazide"],
        "symptom_slugs": ["shortness-of-breath", "swelling", "fatigue", "weight-gain", "cough"],
    },
    {
        "name": "Hemorrhoids", "slug": "hemorrhoids", "letter": "H",
        "overview": "Hemorrhoids are swollen veins in the lower rectum and anus, similar to varicose veins. They are extremely common — about half of adults over 50 have had them — and while uncomfortable, they are rarely dangerous.",
        "symptoms": "Painless bright-red bleeding with bowel movements, itching and irritation around the anus, discomfort or swelling, and — with external hemorrhoids that clot — sudden severe pain and a tender lump.",
        "causes": "Increased pressure in the rectal veins from straining during bowel movements, chronic constipation or diarrhea, prolonged sitting on the toilet, pregnancy, obesity, heavy lifting, and a low-fiber diet.",
        "treatments": "Fiber (25 to 35 grams daily) and fluids to soften stools, warm sitz baths, over-the-counter creams and witch hazel pads, and not delaying or straining on the toilet. Persistent internal hemorrhoids respond to office procedures like rubber-band ligation; surgery is for large or thrombosed cases. Rectal bleeding should be checked at least once by a clinician.",
        "related_drug_slugs": [],
        "symptom_slugs": ["itching", "constipation"],
    },
    {
        "name": "High Cholesterol", "slug": "high-cholesterol", "letter": "H",
        "overview": "High cholesterol — particularly high LDL ('bad') cholesterol — silently drives plaque buildup in arteries, setting the stage for heart attack and stroke. Nearly 2 in 5 U.S. adults have elevated cholesterol, and it produces no symptoms; only a blood test reveals it.",
        "symptoms": "None. Very high inherited levels can cause visible cholesterol deposits (xanthomas) on tendons or yellowish patches around the eyes, but for most people the first 'symptom' is a cardiovascular event.",
        "causes": "Diets high in saturated and trans fats, excess weight, inactivity, smoking, and genetics — familial hypercholesterolemia affects about 1 in 250 people. Diabetes, hypothyroidism, kidney disease, and some medicines also raise levels.",
        "treatments": "A heart-healthy diet (less saturated fat, more soluble fiber), exercise, and weight management first. Statins — atorvastatin, rosuvastatin, simvastatin, or gentler options such as pravastatin and lovastatin — are the mainstay medicines, lowering LDL 30 to 55 percent; ezetimibe and PCSK9 inhibitors are added when statins aren't enough. Screening every 4 to 6 years for healthy adults, more often with risk factors.",
        "related_drug_slugs": ["atorvastatin", "rosuvastatin", "simvastatin", "pravastatin", "lovastatin"],
        "symptom_slugs": [],
    },
    {
        "name": "Hypertension (High Blood Pressure)", "slug": "hypertension", "letter": "H",
        "overview": "Hypertension is sustained blood pressure of 130/80 mm Hg or higher. Nearly half of U.S. adults have it, and because it usually causes no symptoms, many don't know — yet it is a leading driver of heart attack, stroke, kidney failure, and dementia.",
        "symptoms": "Usually none — hence the name 'silent killer.' Extremely high readings (180/120 or above) can cause headache, vision changes, chest pain, or shortness of breath and require immediate care.",
        "causes": "Primary hypertension develops gradually from genetics, age, excess salt, obesity, inactivity, and alcohol. Secondary causes include kidney disease, sleep apnea, thyroid or adrenal disorders, and medicines such as NSAIDs and decongestants.",
        "treatments": "The DASH diet, sodium reduction (ideally under 1,500 mg/day), weight loss, exercise, and alcohol moderation lower pressure meaningfully. First-line drugs: thiazide diuretics (hydrochlorothiazide), ACE inhibitors (lisinopril), ARBs (losartan), and calcium channel blockers (amlodipine) — often in combination. Home monitoring improves control.",
        "related_drug_slugs": ["hydrochlorothiazide", "lisinopril", "losartan", "amlodipine", "metoprolol", "atenolol"],
        "symptom_slugs": ["headache", "dizziness", "blurred-vision"],
    },
]
