"""Article catalog, part B: Well-Being and Diet & Weight Management
sections. Same sourcing rules as part A."""

ARTICLES_B = [
    # ------------------------------------------------------------------
    # Section: well-being
    # ------------------------------------------------------------------
    {
        "title": "Sleep Debt Is Real: What a Week of Short Nights Does to Your Body",
        "slug": "sleep-debt-week-short-nights", "section": "well-being",
        "subcategory": "Sleep",
        "summary": "Cutting sleep to six hours feels manageable by day three — that's the trap. Objective performance keeps falling even as you stop noticing.",
        "body_html": "<p>In controlled studies, adults limited to six hours of sleep a night for two weeks performed as poorly on attention tests as people kept awake for two full days — while rating themselves only 'a little' tired. Sleep debt degrades the very self-monitoring you'd use to detect it, which is why chronically short sleepers genuinely believe they've adapted.</p><p>The body keeps a fuller ledger. Within a week of short nights, insulin sensitivity drops measurably, hunger hormones tilt toward appetite (more ghrelin, less leptin), blood pressure runs higher, and immune response weakens — one reason short sleepers catch more colds. Over years, chronic short sleep associates with weight gain, type 2 diabetes, heart disease, and depression.</p><p>Repayment works, but not in one heroic weekend lie-in, which mostly scrambles your body clock. The durable fix is boring: a consistent wake time seven days a week, a bedtime early enough to allow 7 to 9 hours, caffeine cut off by early afternoon, and dim light in the last hour before bed. Give it two weeks — most people are surprised by what 'rested' actually feels like.</p>",
        "author": "elena-vasquez", "reviewer": "karen-shale-md",
        "published": "2024-09-30", "reviewed": "2024-10-04",
    },
    {
        "title": "The 150-Minute Prescription: What Exercise Guidelines Actually Ask of You",
        "slug": "exercise-150-minute-prescription", "section": "well-being",
        "subcategory": "Fitness & Exercise",
        "summary": "The official target is more modest — and more flexible — than most people assume. Here's how to meet it without reorganizing your life.",
        "body_html": "<p>The physical activity guidelines for adults come down to two lines: at least 150 minutes a week of moderate aerobic activity (or 75 vigorous), plus muscle-strengthening work twice a week. Moderate means you can talk but not sing — a brisk walk qualifies. There's no minimum session length; three 10-minute walks count the same as one 30-minute one.</p><p>The payoff curve is steepest at the bottom: going from nothing to even 60 to 90 weekly minutes buys a large share of the mortality benefit, with lower risks of heart disease, type 2 diabetes, several cancers, depression, and dementia accumulating from there. Strength training earns its separate line in the guidelines because muscle mass and bone density quietly erode from our thirties onward — two sessions a week of squats, pushes, pulls, and carries slows the leak.</p><p>Make it survivable: anchor activity to existing routines (walk the first 15 minutes of lunch), count everything (stairs, yard work, hauling groceries), and if you've been sedentary or have heart disease, ramp gradually and clear vigorous plans with your clinician. The best program remains the one still happening in March.</p>",
        "author": "tom-okafor", "reviewer": "karen-shale-md",
        "published": "2024-06-17", "reviewed": "2024-06-21",
    },
    {
        "title": "Chronic Stress and Your Body: The Cortisol Story, Minus the Myths",
        "slug": "chronic-stress-cortisol", "section": "well-being",
        "subcategory": "Stress Management",
        "summary": "Stress isn't just a feeling — it's a hormonal state with measurable downstream costs. But 'adrenal fatigue' isn't one of them.",
        "body_html": "<p>The stress response is a magnificent short-term system: cortisol and adrenaline mobilize fuel, sharpen attention, and prime muscles. The trouble is duration. When the alarm never fully switches off — money strain, caregiving, a hostile workplace — chronically elevated stress signaling associates with higher blood pressure, abdominal weight gain, insulin resistance, disrupted sleep, weakened immunity, and worsened anxiety and depression.</p><p>One myth to retire: 'adrenal fatigue,' the idea that stressed adrenal glands wear out and need supplements, is not a recognized medical diagnosis, and the supplement stacks sold for it range from useless to risky. Real adrenal insufficiency (Addison's disease) exists, is rare, and is diagnosed with blood tests — not symptom quizzes.</p><p>What actually lowers the load has less flash and more evidence: aerobic exercise (as effective as medication for mild anxiety in some trials), adequate sleep, slow-breathing practices and mindfulness (modest but consistent effects), social connection, and — where the stressor is a solvable problem — problem-solving therapy or plain old boundaries. If stress symptoms include panic attacks, persistent insomnia, or hopelessness, that's a clinician conversation, not a willpower project.</p>",
        "author": "elena-vasquez", "reviewer": "grace-okonkwo-md",
        "published": "2024-07-29", "reviewed": "2024-08-02",
    },
    {
        "title": "Strength After 60: Why Muscle Is the Retirement Account You Can Still Fund",
        "slug": "strength-after-60", "section": "well-being",
        "subcategory": "Healthy Aging",
        "summary": "Sarcopenia — age-related muscle loss — is the quiet driver of falls, fractures, and lost independence. It responds to training at every age studied.",
        "body_html": "<p>Adults lose roughly 3 to 8 percent of muscle mass per decade after 30, and the rate accelerates past 60. The consequences read like a geriatrics syllabus: slower walking speed, harder chair rises, worse balance, more falls, and the fractures — especially hip — that end independent living. Yet in trial after trial, including participants in their nineties, progressive resistance training rebuilds strength substantially.</p><p>The program doesn't need to be heroic. Two or three sessions a week hitting the big patterns — sit-to-stands or leg press, step-ups, rows, presses, farmer's carries — at an effort that makes the last two repetitions genuinely hard, progressed slowly, does the job. Add balance work (heel-to-toe walking, single-leg stands near a counter) and you're addressing fall risk from both ends.</p><p>Protein is the co-investment older adults most often shortchange: aging muscle responds less to each meal's protein, so aim for 25 to 30 grams at each meal rather than a token breakfast and a protein-heavy dinner. If you have osteoporosis, heart disease, or joint replacements, get cleared and ideally start with a physical therapist — then keep going, because detraining reverses the gains as reliably as training built them.</p>",
        "author": "leah-sandoval", "reviewer": "karen-shale-md",
        "published": "2024-10-14", "reviewed": "2024-10-18",
    },
    {
        "title": "How to Fall Asleep Faster: What Sleep Medicine Actually Recommends",
        "slug": "fall-asleep-faster", "section": "well-being",
        "subcategory": "Sleep",
        "summary": "Lying in bed trying harder is the one strategy guaranteed to fail. The clinical playbook works differently.",
        "body_html": "<p>Sleep is one of the few biological functions that flees direct pursuit — effort produces arousal, arousal blocks sleep. Sleep medicine's counterintuitive core rule is stimulus control: the bed is for sleep only, and if you're awake beyond about 20 minutes, get up, keep lights dim, do something quiet and dull, and return only when drowsy. Repeated over a couple of weeks, this retrains the bed from 'worry venue' back to 'sleep trigger.'</p><p>The supporting cast: one fixed wake time every day (the single most powerful lever on your body clock), daylight exposure in the first hour after waking, caffeine finished eight or more hours before bed, alcohol not used as a sedative (it fragments the second half of the night), and a wind-down hour with dim light — bright evening screens delay the melatonin rise that opens the sleep gate.</p><p>If trouble sleeping persists three nights a week for three months despite this, that's chronic insomnia, and the first-line treatment is cognitive behavioral therapy for insomnia (CBT-I) — digital versions work too — not a nightly pill. And if loud snoring, gasping awakenings, or crushing daytime sleepiness are part of the picture, ask about sleep apnea testing before treating this as insomnia at all.</p>",
        "author": "elena-vasquez", "reviewer": "miguel-santana-md",
        "published": "2024-11-25", "reviewed": "2024-11-29",
    },
    {
        "title": "Walking 8,000 Steps: What the Step-Count Science Really Shows",
        "slug": "walking-8000-steps", "section": "well-being",
        "subcategory": "Fitness & Exercise",
        "summary": "10,000 steps began as a marketing slogan. The research points somewhere friendlier — and the curve matters more than the target.",
        "body_html": "<p>The 10,000-step target traces to a 1960s Japanese pedometer brand, not to physiology. When researchers actually measured step counts against mortality across large cohorts, the pattern that emerged was a curve: risk falls steeply as daily steps rise from 2,000-3,000 toward 7,000-8,000, then flattens. Older adults appear to capture most of the benefit by around 6,000-8,000; younger adults' curves flatten somewhat higher.</p><p>Two encouraging details hide in the data. First, the biggest gains belong to the least active — moving from 2,500 to 5,000 steps buys more health than moving from 8,000 to 10,500. Second, pace helps but doesn't dominate: total volume matters most, though bouts of brisker walking add cardiovascular benefit on top.</p><p>Practical translation: find your current baseline (a week of phone-tracked normal life), then add 1,000 steps a day for a couple of weeks at a time. Attach walks to fixed anchors — after lunch, during calls, the far end of the parking lot. And if a step counter makes you anxious rather than active, drop it and keep the walks; the health effect lives in the movement, not the measurement.</p>",
        "author": "tom-okafor", "reviewer": "karen-shale-md",
        "published": "2024-05-06", "reviewed": "2024-05-10",
    },
    {
        "title": "Burnout vs. Depression: Different Problems, Different Fixes",
        "slug": "burnout-vs-depression", "section": "well-being",
        "subcategory": "Mental Health",
        "summary": "They share exhaustion and bleakness, and they can coexist — but confusing them sends people to the wrong remedy.",
        "body_html": "<p>Burnout, as researchers define it, is an occupational syndrome with three fingerprints: exhaustion, cynicism or detachment toward the work itself, and a collapsing sense of effectiveness. Its defining feature is context — symptoms track the job and often lift, at least partially, on genuine time away. Depression is context-free: it colonizes weekends, vacations, hobbies, and relationships alike, and adds signatures burnout lacks, such as pervasive guilt or worthlessness, appetite change, and thoughts of death.</p><p>The distinction is imperfect and the conditions can co-occur or convert — sustained burnout is a risk factor for developing depression. The screening question that helps: does anything still bring pleasure? A burned-out teacher may still light up on a hiking weekend; a depressed one usually cannot. Rest treats one but not the other: prescribing a vacation for major depression fails, and prescribing antidepressants for a toxic workload treats the worker while sparing the problem.</p><p>Match the fix to the diagnosis. For burnout: change the exposure — workload negotiation, boundary-setting, role change, and where those are impossible, an exit plan — plus recovery basics of sleep, exercise, and social reconnection. For depression: evidence-based care — psychotherapy, medication such as an SSRI, or both. And for the person who can't tell which they have, a primary care or mental health visit sorts it faster than another month of white-knuckling.</p>",
        "author": "elena-vasquez", "reviewer": "grace-okonkwo-md",
        "published": "2024-08-12", "reviewed": "2024-08-16",
    },
    {
        "title": "Hydration: How Much Water You Actually Need",
        "slug": "hydration-how-much-water", "section": "well-being",
        "subcategory": "Healthy Living",
        "summary": "Eight glasses a day is folklore. Your kidneys run a more sophisticated system — and they publish their status in the toilet bowl.",
        "body_html": "<p>There is no single daily water quota. Adequate-intake estimates — roughly 15.5 cups of total fluids daily for men and 11.5 for women — include the 20 percent that arrives in food and the coffee, tea, and milk that count fully despite the persistent myth that caffeine 'doesn't count.' Needs swing widely with heat, exercise, body size, pregnancy, breastfeeding, and illness.</p><p>The body's own gauges beat any rule: drink when thirsty, and check urine color — pale straw means well hydrated; dark amber says drink more. Groups who shouldn't rely on thirst alone include older adults (the thirst signal dulls with age), people working or exercising hard in heat, and anyone with vomiting, diarrhea, or fever. A few medical situations — kidney stones (2.5 to 3 liters daily is protective), certain heart failure and kidney patients on fluid limits — come with prescriptions that override defaults.</p><p>Overhydration is rarer but real: forcing large volumes rapidly, especially during endurance events, can dilute blood sodium (hyponatremia), which is dangerous. The practical playbook is undramatic — a glass with each meal, water within reach during the day, more around exercise and heat, and let thirst and urine color steer the rest.</p>",
        "author": "sofia-andersson", "reviewer": "karen-shale-md",
        "published": "2024-07-01", "reviewed": "2024-07-05",
    },
    {
        "title": "Loneliness Is a Health Risk, Not a Character Flaw",
        "slug": "loneliness-health-risk", "section": "well-being",
        "subcategory": "Mental Health",
        "summary": "The research linking social disconnection to heart disease, dementia, and early death is strong enough that health agencies now treat it as a public health issue.",
        "body_html": "<p>Loneliness is the gap between the social connection you have and the connection you need — which is why it can flourish in crowded households and marriages, and why solitude isn't the same thing. Chronic loneliness is common (surveys put it at roughly one in three to one in two U.S. adults at least sometimes) and consequential: meta-analyses associate poor social connection with meaningfully higher risks of heart disease, stroke, dementia, depression, and earlier death — effect sizes in the neighborhood of established risk factors like smoking status and inactivity.</p><p>The mechanisms are plausibly boring: chronic stress physiology (higher blood pressure and inflammation), worse sleep, less motivation for self-care, and fewer people to notice when something's wrong. The loneliest stretches of life cluster around transitions — new parenthood, retirement, bereavement, relocation — which is useful to know, because it predicts when to invest deliberately.</p><p>What helps, per actual trials: less about meeting strangers, more about deepening existing threads. Regular scheduled contact beats spontaneous intentions; shared activity (a class, volunteering, a walking group) beats unstructured socializing; and for entrenched loneliness, cognitive approaches that challenge the 'nobody wants me here' filter outperform social-skills training. Start smaller than feels meaningful: one standing weekly call, one recurring commitment. Consistency, not intensity, rebuilds connection.</p>",
        "author": "leah-sandoval", "reviewer": "grace-okonkwo-md",
        "published": "2024-12-09", "reviewed": "2024-12-13",
    },
    {
        "title": "Desk Job, Aching Back: An Ergonomics Reset That Takes 20 Minutes",
        "slug": "desk-ergonomics-reset", "section": "well-being",
        "subcategory": "Healthy Living",
        "summary": "The best posture is the next posture. But a few one-time adjustments make every posture cheaper for your spine.",
        "body_html": "<p>Spines dislike sustained anything — sustained slouching, yes, but also sustained 'perfect' posture. The modern ergonomic view has shifted from finding one correct position to reducing the cost of positions and increasing the frequency of changes. Still, setup matters: a 20-minute reset removes the worst offenders.</p><p>The checklist: screen top at or slightly below eye level, about an arm's length away (laptop users need a stand plus external keyboard — this is the highest-yield fix in the list); elbows near 90 degrees with shoulders relaxed, keyboard and mouse close; feet flat on floor or a footrest; chair supporting the low back's natural curve, hips slightly above knees. Phone habits count too — 'text neck' is a real load, so raise the phone rather than dropping the head.</p><p>Then add movement snacks: stand, stretch, or walk for a couple of minutes every 30 to 45 minutes (calendar reminders work; so does drinking enough water to force trips). Pair with two or three weekly sessions strengthening the back's support system — rows, hip hinges, planks, glute work. For back pain that radiates down a leg, brings numbness, or persists beyond a few weeks despite activity, step past ergonomics and see a clinician.</p>",
        "author": "tom-okafor", "reviewer": "karen-shale-md",
        "published": "2024-04-22", "reviewed": "2024-04-26",
    },
    {
        "title": "Alcohol and Health in 2025: The Sober-Curious Case for Less",
        "slug": "alcohol-health-drinking-less", "section": "well-being",
        "subcategory": "Healthy Living",
        "summary": "The 'red wine is heart-healthy' era is over. Current evidence supports a simpler slogan: less is better, and none is fine.",
        "body_html": "<p>For decades, observational studies seemed to show moderate drinkers outliving abstainers — the famous J-curve. Better methods largely dismantled it: many 'abstainers' in old studies were former drinkers who had quit for health reasons, making nondrinkers look artificially sick. Newer analyses and genetic studies find risk rising more or less continuously with dose. No major health body now recommends starting to drink for your health.</p><p>The costs are better mapped than most drinkers know: alcohol is an established carcinogen linked to at least seven cancers — including breast cancer at levels as low as one daily drink — and contributes to high blood pressure, atrial fibrillation, liver disease, poor sleep (it sedates, then fragments the night), anxiety, and injuries. Current U.S. guidelines cap 'moderate' at two drinks per day for men and one for women — as ceilings, not targets.</p><p>If cutting back appeals, the tactics with evidence: count honestly for two weeks (pours at home run large), schedule alcohol-free days and defend them, stock nonalcoholic alternatives you actually like, and notice what improves — sleep quality usually reports first, within a week or two. Signs that this is more than a habit adjustment — morning drinking, shakiness when stopping, failed attempts to cut down — warrant a medical conversation; withdrawal from heavy daily drinking can be dangerous to attempt alone.</p>",
        "author": "curtis-boone", "reviewer": "karen-shale-md",
        "published": "2024-12-30", "reviewed": "2025-01-03",
    },
    {
        "title": "Meditation for Skeptics: What Mindfulness Can and Can't Do",
        "slug": "meditation-for-skeptics", "section": "well-being",
        "subcategory": "Stress Management",
        "summary": "Strip away the incense and the overselling, and a modest, useful tool remains — with trial evidence for specific problems.",
        "body_html": "<p>Mindfulness meditation, at its mechanical core, is attention training: noticing when the mind wanders and returning it, thousands of repetitions, usually anchored to the breath. Structured programs have been trialed extensively, and honest reading of the evidence shows moderate benefits for anxiety, depression symptoms, and stress — comparable in some analyses to other active treatments — plus smaller effects on chronic pain coping and sleep.</p><p>Equally honest: it is not a cure-all. Effects on blood pressure, immunity, and attention in healthy people are modest and inconsistent; it does not replace therapy or medication for significant depression or anxiety disorders; and a minority of intensive practitioners report unpleasant effects like anxiety spikes or dissociation — worth knowing, especially for trauma histories, where trauma-sensitive instruction matters.</p><p>A skeptic-friendly on-ramp: ten minutes daily for four weeks, guided (any major app or free recordings), treating it like an exercise program — you're not seeking bliss, you're doing attention reps. Judge it at the end not by how sessions felt but by the week's data: Are you sleeping better? Snapping less? Recovering from stress faster? Keep what the data supports; discard the rest without guilt.</p>",
        "author": "elena-vasquez", "reviewer": "grace-okonkwo-md",
        "published": "2024-09-16", "reviewed": "2024-09-20",
    },

    # ------------------------------------------------------------------
    # Section: diet-weight
    # ------------------------------------------------------------------
    {
        "title": "The Mediterranean Diet, Operationalized: A Week One Shopping List",
        "slug": "mediterranean-diet-week-one", "section": "diet-weight",
        "subcategory": "Healthy Eating",
        "summary": "The most consistently recommended eating pattern in medicine is less a diet than a grocery-store strategy. Here's the concrete version.",
        "body_html": "<p>Across major trials and decades of cohort data, the Mediterranean pattern keeps earning its reputation: lower rates of heart attack and stroke, better blood sugar control, and associations with slower cognitive decline. The pattern, not any superfood, does the work — olive oil as the principal fat; vegetables, fruits, beans, nuts, and whole grains daily; fish twice a week; poultry and dairy in moderation; red and processed meat rarely; sweets occasional.</p><p>Week one, buy: extra-virgin olive oil (retire the butter dish to weekends), a jar of nuts for snacking, canned or dried beans and lentils for two dinners, canned or frozen fish (sardines and salmon are the budget route to omega-3s), whatever vegetables you'll honestly eat — frozen counts fully — plus whole-grain bread or farro or oats, plain yogurt, and fruit visible on the counter. That list covers most of the pattern for roughly the cost of the processed foods it replaces.</p><p>Then swap, don't overhaul: olive oil where butter was, beans where half the ground meat was, fruit and yogurt where dessert was, fish where one weekly steak was. The trials that showed benefits weren't testing perfection — adherence scores measure direction, and every swap moves the score. Wine is the one component modern guidance has walked back: if you don't drink, the pattern works without it.</p>",
        "author": "sofia-andersson", "reviewer": "karen-shale-md",
        "published": "2024-06-03", "reviewed": "2024-06-07",
    },
    {
        "title": "Why Diets 'Stop Working': The Biology of the Weight Plateau",
        "slug": "weight-loss-plateau-biology", "section": "diet-weight",
        "subcategory": "Weight Loss",
        "summary": "The plateau isn't failure — it's physiology doing exactly what it evolved to do. Understanding it changes the strategy.",
        "body_html": "<p>Weight loss triggers a coordinated defense. As pounds drop, total energy needs fall — a smaller body costs less to run — and metabolism adapts downward a bit further than size alone predicts. Meanwhile hunger hormones shift: ghrelin rises, satiety signals like leptin fall, and food becomes more salient to the brain. The diet didn't stop working; the body started negotiating harder. Plateaus typically arrive around six months into a successful effort.</p><p>What doesn't help: slashing intake to extremes (unsustainable, muscle-costly) or declaring the effort broken. What does: recalculating — your maintenance calories at the new weight are lower than at the old one; tightening measurement drift (portions creep, tracking lapses, 'bites don't count'); protecting muscle with resistance training and adequate protein, which supports the calorie budget; and adding movement outside workouts, since non-exercise activity often quietly declines during dieting.</p><p>Zoom out on the goal, too. Five to ten percent loss — often achieved by plateau time — already delivers most of the metabolic wins: better blood pressure, blood sugar, and lipids. Some people's best move at plateau is a deliberate maintenance phase: hold the new weight for a few months, let the physiology settle, then resume. Maintenance is not failure; it's the skill the whole project ultimately depends on.</p>",
        "author": "sofia-andersson", "reviewer": "robert-yuen-md",
        "published": "2024-08-26", "reviewed": "2024-08-30",
    },
    {
        "title": "Protein: How Much, When, and Whether the Powder Is Necessary",
        "slug": "protein-how-much", "section": "diet-weight",
        "subcategory": "Nutrition Basics",
        "summary": "The RDA is a floor, not a target — especially if you're older, dieting, or training. But the ceiling arrives sooner than the supplement aisle suggests.",
        "body_html": "<p>The official RDA — 0.8 grams per kilogram of body weight daily — was set to prevent deficiency, not to optimize anything. Evidence supports more for several groups: roughly 1.2 to 1.6 g/kg for older adults (whose muscle responds less to each dose), people losing weight (protein defends muscle and blunts hunger), and recreational athletes; strength athletes may benefit up to about 2.2 g/kg. For a 175-pound adult, 1.2 to 1.6 g/kg is about 95 to 127 grams a day.</p><p>Distribution matters more than timing myths. Muscle building responds best to 25 to 40 grams of protein per meal, several times a day — which indicts the standard American pattern of token breakfast, modest lunch, giant dinner. The fabled 'anabolic window' after workouts turns out to be hours wide; total daily intake and per-meal doses dominate. Food sources bring companions powder lacks — fiber and iron in beans, calcium in dairy, omega-3s in fish.</p><p>Powders are convenience, not magic: reasonable when whole-food logistics fail (they're regulated as supplements, so pick third-party-tested brands), unnecessary otherwise. Cautions: very high intakes are hard on already-diseased kidneys — people with chronic kidney disease need individualized targets, not internet defaults — and protein calories still count; the physique aisle has fueled plenty of weight gain.</p>",
        "author": "sofia-andersson", "reviewer": "karen-shale-md",
        "published": "2024-05-27", "reviewed": "2024-05-31",
    },
    {
        "title": "Ultra-Processed Foods: What the NOVA Debate Means for Your Cart",
        "slug": "ultra-processed-foods-cart", "section": "diet-weight",
        "subcategory": "Healthy Eating",
        "summary": "More than half of U.S. calories now come from ultra-processed foods. The science has nuances; the shopping advice mostly doesn't.",
        "body_html": "<p>'Ultra-processed' (the NOVA classification's fourth category) describes industrial formulations built from refined ingredients and additives — soft drinks, packaged snacks, instant noodles, reconstituted meats, most fast food. Observational studies consistently link higher intake with obesity, type 2 diabetes, and cardiovascular disease, and one landmark inpatient trial found people ate about 500 more calories a day when offered ultra-processed meals versus matched unprocessed ones — eating faster and reporting no more satisfaction.</p><p>The honest caveats: the category is broad and blunt. Whole-grain breads, flavored yogurts, and fortified cereals get lumped with soda and hot dogs, and researchers argue about mechanisms — is it the processing itself, the salt-sugar-fat engineering, the softness and speed of eating, or simply that these foods displace better ones? Probably several at once.</p><p>The cart-level translation doesn't require settling the debate: cook more of what you can, favor foods whose ingredient lists read like recipes rather than chemistry sets, and target the biggest offenders first — sugary drinks and processed meats carry the strongest evidence of harm. No need for purity; a diet that's three-quarters minimally processed leaves room for convenience without surrendering the pattern.</p>",
        "author": "priya-raman", "reviewer": "karen-shale-md",
        "published": "2024-10-07", "reviewed": "2024-10-11",
    },
    {
        "title": "Intermittent Fasting: What Trials Show When the Hype Clears",
        "slug": "intermittent-fasting-trials", "section": "diet-weight",
        "subcategory": "Weight Loss",
        "summary": "Time-restricted eating works about as well as ordinary calorie counting — no better, no worse. That's actually useful information.",
        "body_html": "<p>Intermittent fasting arrived wrapped in mechanistic promise — autophagy, metabolic switching, cellular cleanup. When randomized trials finally compared it head-to-head with conventional calorie restriction, the results were consistent and anticlimactic: similar weight loss, similar changes in blood pressure, lipids, and glucose, when calories end up matched. Fasting's main effect is that a shorter eating window helps some people eat less without counting.</p><p>That reframe clarifies who it suits. Time-restricted eating (say, an 8-hour window) shines for people who prefer clear rules to arithmetic, snack heavily at night, or find that skipping breakfast costs them nothing. It suits poorly those with a history of disordered eating (rigid rules can reignite it), people on diabetes medicines that can cause hypoglycemia — insulin or glipizide require medical guidance before fasting — pregnant women, and anyone whose fasting hours end in compensatory bingeing.</p><p>If you try it: pick a window you can hold socially (10 a.m. to 6 p.m. beats a heroic 4-hour slot you'll abandon), keep the eating window's quality high — fasting forgives nothing nutritionally — and judge the experiment on four weeks of data: weight trend, energy, and whether evenings feel liberated or obsessive. It's one tool among several, and adherence, as always, is the active ingredient.</p>",
        "author": "priya-raman", "reviewer": "robert-yuen-md",
        "published": "2024-07-15", "reviewed": "2024-07-19",
    },
    {
        "title": "Fiber: The Least Glamorous Nutrient Keeps Winning",
        "slug": "fiber-least-glamorous-nutrient", "section": "diet-weight",
        "subcategory": "Nutrition Basics",
        "summary": "Only about 5 percent of Americans hit the fiber target. Meanwhile the outcome data keeps piling up — for hearts, guts, blood sugar, and more.",
        "body_html": "<p>The targets are 25 grams a day for women and 38 for men (or 14 grams per 1,000 calories); the average American eats about half that. The gap matters: umbrella reviews link higher fiber intake with lower rates of heart disease, stroke, type 2 diabetes, and colorectal cancer, with dose-response curves suggesting each additional 8 to 10 grams daily buys measurable risk reduction. Fiber also feeds gut bacteria that produce short-chain fatty acids, remains the first-line management for constipation and much of IBS, and blunts post-meal blood sugar.</p><p>Fiber's varieties divide labor. Soluble fiber (oats, beans, apples, psyllium) forms gels — it's the cholesterol-lowerer and the stool-normalizer, useful in both constipation and diarrhea. Insoluble fiber (wheat bran, vegetables) adds bulk and speeds transit. Food sources beat supplements for the full package, though psyllium has legitimate trial evidence for cholesterol and bowel regularity.</p><p>Getting from 15 grams to 30 without misery is a ramp, not a leap: add 5 grams or so per week and drink more water alongside, letting gut bacteria adapt (gas is the adjustment tax and mostly temporary). The highest-yield swaps: beans or lentils into two dinners a week, a bran-or-oat-based breakfast, fruit instead of juice, and whole-grain versions of whatever bread, rice, and pasta you already eat.</p>",
        "author": "sofia-andersson", "reviewer": "lucia-ferreira-md",
        "published": "2024-09-09", "reviewed": "2024-09-13",
    },
    {
        "title": "Reading a Nutrition Label in 30 Seconds: The Three-Line Method",
        "slug": "nutrition-label-three-lines", "section": "diet-weight",
        "subcategory": "Nutrition Basics",
        "summary": "Ignore the marketing on the front. Three lines on the back settle most packaged-food decisions.",
        "body_html": "<p>Front-of-package claims — natural, multigrain, lightly sweetened, immune support — are marketing with minimal regulation. The Nutrition Facts panel is where the law lives. And for quick decisions, three lines carry most of the signal: serving size (everything below it is per serving, and packages routinely contain several), added sugars, and sodium.</p><p>Calibration for the two big numbers: the daily ceiling for added sugars is 50 grams on a 2,000-calorie diet (the American Heart Association suggests tighter: about 25 g for women, 36 g for men), so a yogurt with 15 grams added is spending a third of the tight budget; sodium's target is under 2,300 mg a day, so a 900 mg frozen entrée is a heavy withdrawal. The percent daily value column does this math for you — 5 percent or less is low, 20 percent or more is high.</p><p>With another ten seconds, add two checks: fiber (3 or more grams per serving earns bread and cereal their place) and the ingredient list's first three entries, which are the product's real identity — 'whole wheat' should lead a whole-wheat bread, and sugar has aliases (cane syrup, dextrose, fruit juice concentrate) that split its ranking. None of this requires perfection at the shelf; it requires that the same two products stop being interchangeable once you've flipped them over.</p>",
        "author": "priya-raman", "reviewer": "karen-shale-md",
        "published": "2024-04-08", "reviewed": "2024-04-12",
    },
    {
        "title": "Emotional Eating: Breaking the Stress-Snack Circuit",
        "slug": "emotional-eating-circuit", "section": "diet-weight",
        "subcategory": "Weight Loss",
        "summary": "Eating for comfort is wired, common, and workable — once you treat it as a signal-reading problem instead of a willpower problem.",
        "body_html": "<p>Stress eating has legitimate physiology behind it: sustained stress hormones increase appetite specifically for energy-dense, sweet-and-fat foods, and those foods genuinely dampen the stress response short-term — the circuit pays out, which is why it persists. Layered on top are learned associations (couch, evening, screen, snack) that fire with no hunger involved. Shame doesn't interrupt any of this; it usually feeds the loop.</p><p>The workable sequence starts with detection: for two weeks, before unplanned eating, pause for one question — 'what am I feeling, and when did I last eat?' Physical hunger builds gradually, accepts many foods, and stops at fullness; emotional hunger arrives suddenly, demands something specific, and ignores fullness. The pause itself, done consistently, weakens automaticity. Next, make the circuit inconvenient: trigger foods out of the house or out of sight, and a competing default ready — a walk, a shower, tea, a two-minute tidy, a text to a friend. The replacement has to be easy, or it loses to the pantry.</p><p>Two structural fixes outrank all tactics: eat enough during the day (under-eating until evening practically schedules a nighttime raid — regular meals with protein and fiber defuse it) and address the actual stressor where possible. If eating episodes feel out of control, involve large amounts with distress, or are followed by compensating, that pattern deserves professional support — binge eating disorder is common, real, and treatable.</p>",
        "author": "elena-vasquez", "reviewer": "grace-okonkwo-md",
        "published": "2024-11-04", "reviewed": "2024-11-08",
    },
    {
        "title": "Sodium: The 70 Percent You Never Salted",
        "slug": "sodium-you-never-salted", "section": "diet-weight",
        "subcategory": "Healthy Eating",
        "summary": "The shaker is a rounding error. Most American sodium is decided before the food reaches your kitchen — which changes where to aim.",
        "body_html": "<p>Average U.S. sodium intake runs about 3,400 mg a day against a guideline of under 2,300 (with 1,500 the tighter goal for many with hypertension). But only about 10 percent comes from the salt shaker; roughly 70 percent is added during commercial processing and restaurant preparation. Bread, cold cuts and cured meats, pizza, soups, sandwiches, cheese, and sauces top the source list — several of which don't even taste salty.</p><p>Why care: sodium is the most consequential dietary lever on blood pressure, and blood pressure is the biggest treatable driver of stroke and heart disease. Trials of sodium reduction show meaningful pressure drops — larger in people who are older, hypertensive, or salt-sensitive — and the DASH diet's famous results came from combining lower sodium with potassium-rich produce, which blunts sodium's effect.</p><p>Aim where the sodium is: compare labels within categories (breads vary twofold; jarred sauces threefold), favor 'no salt added' canned goods or rinse regular ones, treat cured meats and instant soups as occasional, and ask for sauces on the side when eating out — restaurant portions of sauce carry remarkable payloads. At home, salting to taste while cooking real ingredients almost never reproduces processed-food levels, and potassium-based salt substitutes help many people — though anyone with kidney disease or on drugs like lisinopril or losartan should clear those first.</p>",
        "author": "priya-raman", "reviewer": "anil-bhatt-md",
        "published": "2024-06-24", "reviewed": "2024-06-28",
    },
    {
        "title": "The New Weight-Loss Drugs: Where GLP-1s Fit — and Where They Don't",
        "slug": "glp1-weight-loss-drugs-fit", "section": "diet-weight",
        "subcategory": "Weight Loss",
        "summary": "Semaglutide-class medicines produce losses diets rarely match. They also come with costs, side effects, and a regain problem nobody should skip past.",
        "body_html": "<p>GLP-1 receptor agonists — developed for type 2 diabetes and now approved at higher doses for chronic weight management — mimic a gut hormone that slows stomach emptying and quiets appetite signaling in the brain. In trials, semaglutide produced average losses around 15 percent of body weight, and newer dual-hormone agents exceed 20 percent — territory previously reserved for bariatric surgery. Alongside, trials have shown cardiovascular benefit in high-risk patients.</p><p>The unvarnished parts: gastrointestinal side effects (nausea, vomiting, constipation) are common, especially during dose escalation, and a minority discontinue over them; rare but serious risks include pancreatitis and gallbladder disease; cost and supply remain real barriers; and the drugs treat, not cure — stop them and appetite returns, with trials showing most weight regained within a year. Muscle loss travels with rapid weight loss too, making protein and resistance training non-optional companions.</p><p>Where they fit: for people with obesity or weight-related disease who haven't reached health goals with lifestyle change alone, prescribed within ongoing medical care that includes nutrition and strength work — not as a shortcut around them. Where they don't: cosmetic loss for people at healthy weights, compounded knock-offs of uncertain provenance, or anyone unwilling to plan for the long game. The right frame is chronic-disease management, the same way we think about blood pressure medication.</p>",
        "author": "sofia-andersson", "reviewer": "robert-yuen-md",
        "published": "2025-01-06", "reviewed": "2025-01-09",
    },
    {
        "title": "Meal Prep Without Martyrdom: A 90-Minute Sunday System",
        "slug": "meal-prep-90-minute-system", "section": "diet-weight",
        "subcategory": "Food & Recipes",
        "summary": "You don't need matching containers and a photogenic fridge. You need components, not completed meals.",
        "body_html": "<p>Classic meal prep fails on repetition: five identical boxed lunches sound efficient on Sunday and inedible by Wednesday. The system that survives real appetites preps components instead — a protein, a grain, roasted vegetables, a sauce, and washed greens — which recombine all week into bowls, wraps, salads, and skillet dinners that don't feel like reruns.</p><p>The 90-minute run, parallelized: oven on first — two sheet pans of vegetables (whatever's cheap: broccoli, peppers, sweet potatoes, onions) and a tray of chicken thighs or salmon, all roasting while a pot of rice, farro, or quinoa cooks and a dozen eggs boil. Final twenty minutes: one sauce or dressing (a vinaigrette, a yogurt-herb sauce, or peanut-lime), rinse and dry greens, portion nuts or fruit for snacks. Total: one oven cycle, two burners, one cutting board.</p><p>Storage math matters: most cooked components hold 3 to 4 days refrigerated, so prep for the near week and freeze the rest — cooked grains and proteins freeze gracefully. Downstream, assembly beats cooking every weeknight: grain plus protein plus vegetables plus sauce is dinner in six minutes, and the same parts make lunch boxes trivially. The health payoff is indirect but reliable — the biggest predictor of eating well on a Wednesday night is whether eating well requires zero decisions.</p>",
        "author": "sofia-andersson", "reviewer": "danielle-hart-md",
        "published": "2024-08-05", "reviewed": "2024-08-09",
    },
    {
        "title": "Blood Sugar for the Rest of Us: What Non-Diabetics Should Know About Glucose",
        "slug": "blood-sugar-non-diabetics", "section": "diet-weight",
        "subcategory": "Nutrition Basics",
        "summary": "Continuous glucose monitors have gone consumer, and 'glucose hacking' is everywhere. Some of it is physiology; some is theater.",
        "body_html": "<p>The legitimate core: 98 million American adults have prediabetes, most unaware, and the trajectory toward type 2 diabetes is substantially preventable — landmark prevention trials cut progression roughly in half with modest weight loss and regular activity. Knowing your numbers (a fasting glucose or A1C at routine checkups, earlier and more often with family history, higher weight, or a history of gestational diabetes) is genuinely worthwhile.</p><p>The trend part: continuous glucose monitors on people without diabetes mostly confirm textbook physiology — glucose rises after carbohydrate, more when it's refined and eaten alone, less after fiber, protein, fat, or a post-meal walk. Those are fine habits with or without a sensor. What the sensor adds for healthy users is less clear: normal glucose fluctuates, single-food 'spikes' within normal range have no established harm, and early evidence suggests monitoring can push some users toward needless carb-phobia and food anxiety.</p><p>If glucose curiosity motivates better habits, the cheap version needs no subscription: build meals around fiber and protein, keep refined carbs and sugary drinks occasional, walk ten minutes after larger meals, sleep adequately (short sleep measurably worsens next-day glucose handling), and let a clinician check an A1C on schedule. If you have prediabetes, that same list — plus structured support like a diabetes-prevention program — is the actual evidence-based play.</p>",
        "author": "priya-raman", "reviewer": "robert-yuen-md",
        "published": "2024-10-21", "reviewed": "2024-10-25",
    },
]
