"""Frozen per-task fixture specs extracted from the reviewer honest live runs.

Agent_demo trajectory shape; sqlite delta mirroring the site. Task 13 encodes
the post-fix pricing (one-way bag charged once), confirmed live at re-review
against orch/contribute/ryanair @ 733296f9. Specs 8/18 mirror the post-fix
honest runs (remove-card default promotion; phone target +353 85 012 9999).
Auto-generated by the review pipeline; do not hand-edit the values."""

BASE = "http://localhost:40129"

SPECS = {
 "0": {
  "urls": [
   "http://localhost:40129/",
   "http://localhost:40129/gb/en",
   "http://localhost:40129/gb/en/trip/flights/select?tripType=return&promoCode=&originIata=STN&destinationIata=DUB&dateOut=2026-10-13&dateIn=2026-10-20&isReturn=true&adults=2&teens=0&children=0&infants=0",
   "http://localhost:40129/gb/en/trip/flights/select?originIata=STN&destinationIata=DUB&dateOut=2026-10-13&dateIn=2026-10-20&adults=2&teens=0&children=0&infants=0&promoCode=&isReturn=true",
   "http://localhost:40129/gb/en/trip/flights/seats",
   "http://localhost:40129/gb/en/trip/flights/bags",
   "http://localhost:40129/gb/en/trip/flights/extras",
   "http://localhost:40129/gb/en/payment",
   "http://localhost:40129/gb/en/booking/confirmation/4CVM95",
   "http://localhost:40129/gb/en/booking/confirmation/4CVM95"
  ],
  "answer": "Booking reference 4CVM95. Total charged £74.40 (2 adults, Basic fare, London Stansted to Dublin 13 Oct returning 20 Oct, no seats/bags/extras).",
  "sql": [
   "INSERT INTO bookings (booking_ref, user_id, contact_email, contact_phone, fare_type, adults, teens, children, infants, outbound_schedule_id, outbound_date, inbound_schedule_id, inbound_date, promo_code, sms_updates, insurance_key, fast_track_out, fast_track_in, inflight_credit, flights_total, seats_total, bags_total, extras_total, card_fee, total, status, checked_in, created_at) VALUES ('4CVM95', NULL, 'john.smith@example.com', '+44 7700 900999', 'basic', 2, 0, 0, 0, 5040, '2026-10-13', 1902, '2026-10-20', '', 0, '', 0, 0, 0.0, 72.94, 0.0, 0.0, 0.0, 1.46, 74.4, 'confirmed', 0, '2026-09-24 12:00:00.000000')",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Mr', 'John', 'Smith', '', '', 'small-bag', 'small-bag', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Mrs', 'Jane', 'Smith', '', '', 'small-bag', 'small-bag', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO trip_states (token, data) VALUES ('fixturetoken0123456789abcdef', '{}')"
  ]
 },
 "1": {
  "urls": [
   "http://localhost:40129/",
   "http://localhost:40129/gb/en",
   "http://localhost:40129/gb/en/trip/flights/select?tripType=return&promoCode=&originIata=STN&destinationIata=DUB&dateOut=2026-10-13&dateIn=2026-10-20&isReturn=true&adults=1&teens=0&children=0&infants=0",
   "http://localhost:40129/gb/en/trip/flights/select?originIata=STN&destinationIata=DUB&dateOut=2026-10-13&dateIn=2026-10-21&adults=1&teens=0&children=0&infants=0&promoCode=&isReturn=true",
   "http://localhost:40129/gb/en/trip/flights/seats",
   "http://localhost:40129/gb/en/trip/flights/bags",
   "http://localhost:40129/gb/en/trip/flights/extras",
   "http://localhost:40129/gb/en/payment",
   "http://localhost:40129/gb/en/booking/confirmation/25RQ3G",
   "http://localhost:40129/gb/en/booking/confirmation/25RQ3G"
  ],
  "answer": "Cheapest displayed departure day: Tuesday 13 October (£17.98). Cheapest displayed return day: Wednesday 21 October (£14.99). Booked the cheapest return trip for 1 adult on the Basic fare as a guest. Total paid £33.63. Booking reference 25RQ3G.",
  "sql": [
   "INSERT INTO bookings (booking_ref, user_id, contact_email, contact_phone, fare_type, adults, teens, children, infants, outbound_schedule_id, outbound_date, inbound_schedule_id, inbound_date, promo_code, sms_updates, insurance_key, fast_track_out, fast_track_in, inflight_credit, flights_total, seats_total, bags_total, extras_total, card_fee, total, status, checked_in, created_at) VALUES ('25RQ3G', NULL, 'flexible@example.com', '+44 7700 900999', 'basic', 1, 0, 0, 0, 5040, '2026-10-13', 1904, '2026-10-21', '', 0, '', 0, 0, 0.0, 32.97, 0.0, 0.0, 0.0, 0.66, 33.63, 'confirmed', 0, '2026-09-24 12:00:00.000000')",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Mr', 'Flex', 'Traveller', '', '', 'small-bag', 'small-bag', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO trip_states (token, data) VALUES ('fixturetoken0123456789abcdef', '{}')"
  ]
 },
 "2": {
  "urls": [
   "http://localhost:40129/",
   "http://localhost:40129/gb/en",
   "http://localhost:40129/gb/en/trip/flights/select?tripType=return&promoCode=&originIata=LGW&destinationIata=AGP&dateOut=2026-10-09&dateIn=2026-10-16&isReturn=true&adults=2&teens=0&children=0&infants=0",
   "http://localhost:40129/gb/en/trip/flights/select?originIata=LGW&destinationIata=AGP&dateOut=2026-10-09&dateIn=2026-10-16&adults=2&teens=0&children=0&infants=0&promoCode=&isReturn=true",
   "http://localhost:40129/gb/en/trip/flights/seats",
   "http://localhost:40129/gb/en/trip/flights/bags",
   "http://localhost:40129/gb/en/trip/flights/extras",
   "http://localhost:40129/gb/en/payment",
   "http://localhost:40129/gb/en/booking/confirmation/NYASBH",
   "http://localhost:40129/gb/en/booking/confirmation/NYASBH"
  ],
  "answer": "Flexi Plus costs £386.00 more per person for the whole trip than Plus, and Flexi Plus is the bundle that allows flight changes with no fees. Booked the Plus fare for 2 adults (London Gatwick-Malaga, out 9 Oct, back 16 Oct) as a guest. Booking reference NYASBH, total £442.64.",
  "sql": [
   "INSERT INTO bookings (booking_ref, user_id, contact_email, contact_phone, fare_type, adults, teens, children, infants, outbound_schedule_id, outbound_date, inbound_schedule_id, inbound_date, promo_code, sms_updates, insurance_key, fast_track_out, fast_track_in, inflight_credit, flights_total, seats_total, bags_total, extras_total, card_fee, total, status, checked_in, created_at) VALUES ('NYASBH', NULL, 'sally@example.com', '+44 7700 900999', 'plus', 2, 0, 0, 0, 3013, '2026-10-09', 142, '2026-10-16', '', 0, '', 0, 0, 0.0, 433.96, 0.0, 0.0, 0.0, 8.68, 442.64, 'confirmed', 0, '2026-09-24 12:00:00.000000')",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Mrs', 'Sally', 'Brown', '', '', 'small-bag', 'small-bag', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Mr', 'Tom', 'Brown', '', '', 'small-bag', 'small-bag', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO trip_states (token, data) VALUES ('fixturetoken0123456789abcdef', '{}')"
  ]
 },
 "3": {
  "urls": [
   "http://localhost:40129/",
   "http://localhost:40129/gb/en",
   "http://localhost:40129/gb/en/trip/flights/select?tripType=return&promoCode=&originIata=MAN&destinationIata=DUB&dateOut=2026-10-06&dateIn=2026-10-10&isReturn=true&adults=2&teens=0&children=0&infants=0",
   "http://localhost:40129/gb/en/trip/flights/select?originIata=MAN&destinationIata=DUB&dateOut=2026-10-06&dateIn=2026-10-10&adults=2&teens=0&children=0&infants=0&promoCode=&isReturn=true",
   "http://localhost:40129/gb/en/trip/flights/seats",
   "http://localhost:40129/gb/en/trip/flights/bags",
   "http://localhost:40129/gb/en/trip/flights/extras",
   "http://localhost:40129/gb/en/payment",
   "http://localhost:40129/gb/en/booking/confirmation/PDUXTV",
   "http://localhost:40129/gb/en/booking/confirmation/PDUXTV"
  ],
  "answer": "Booked Manchester-Dublin (out 6 Oct, return 10 Oct) for 2 adults on Plus. Outbound window seat in row 1 (1A, £21.50) plus 1C for my daughter; cheapest two seats together on the return (18B/18C, £19.00). The seats added £62.00 to the total. Booking reference PDUXTV, total paid £221.28.",
  "sql": [
   "INSERT INTO bookings (booking_ref, user_id, contact_email, contact_phone, fare_type, adults, teens, children, infants, outbound_schedule_id, outbound_date, inbound_schedule_id, inbound_date, promo_code, sms_updates, insurance_key, fast_track_out, fast_track_in, inflight_credit, flights_total, seats_total, bags_total, extras_total, card_fee, total, status, checked_in, created_at) VALUES ('PDUXTV', NULL, 'mary@example.com', '+44 7700 900999', 'plus', 2, 0, 0, 0, 3682, '2026-10-06', 1863, '2026-10-10', '', 0, '', 0, 0, 0.0, 154.94, 62.0, 0.0, 0.0, 4.34, 221.28, 'confirmed', 0, '2026-09-24 12:00:00.000000')",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Ms', 'Mary', 'Green', '1A', '18B', 'small-bag', 'small-bag', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Ms', 'Lily', 'Green', '1C', '18C', 'small-bag', 'small-bag', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO trip_states (token, data) VALUES ('fixturetoken0123456789abcdef', '{}')"
  ]
 },
 "4": {
  "urls": [
   "http://localhost:40129/",
   "http://localhost:40129/gb/en",
   "http://localhost:40129/gb/en/trip/flights/select?tripType=return&promoCode=&originIata=STN&destinationIata=ALC&dateOut=2026-10-15&dateIn=2026-10-22&isReturn=true&adults=2&teens=0&children=0&infants=0",
   "http://localhost:40129/gb/en/trip/flights/select?originIata=STN&destinationIata=ALC&dateOut=2026-10-15&dateIn=2026-10-22&adults=2&teens=0&children=0&infants=0&promoCode=&isReturn=true",
   "http://localhost:40129/gb/en/trip/flights/seats",
   "http://localhost:40129/gb/en/trip/flights/bags",
   "http://localhost:40129/gb/en/trip/flights/extras",
   "http://localhost:40129/gb/en/payment",
   "http://localhost:40129/gb/en/booking/confirmation/6HS4BL",
   "http://localhost:40129/gb/en/booking/confirmation/6HS4BL"
  ],
  "answer": "Added Priority & 2 Cabin Bags for both passengers on both flights (£64.00) and one 20kg check-in bag for me on both flights (£50.98): the bags added £114.98 compared with travelling with only the free small bags. Final total paid £260.04. Booking reference 6HS4BL.",
  "sql": [
   "INSERT INTO bookings (booking_ref, user_id, contact_email, contact_phone, fare_type, adults, teens, children, infants, outbound_schedule_id, outbound_date, inbound_schedule_id, inbound_date, promo_code, sms_updates, insurance_key, fast_track_out, fast_track_in, inflight_credit, flights_total, seats_total, bags_total, extras_total, card_fee, total, status, checked_in, created_at) VALUES ('6HS4BL', NULL, 'dave@example.com', '+44 7700 900999', 'basic', 2, 0, 0, 0, 4999, '2026-10-15', 315, '2026-10-22', '', 0, '', 0, 0, 0.0, 139.96, 0.0, 114.98, 0.0, 5.1, 260.04, 'confirmed', 0, '2026-09-24 12:00:00.000000')",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Mr', 'Dave', 'White', '', '', 'priority', 'priority', 0, 0, 1, 1, 0, 0)",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Ms', 'Ann', 'White', '', '', 'priority', 'priority', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO trip_states (token, data) VALUES ('fixturetoken0123456789abcdef', '{}')"
  ]
 },
 "5": {
  "urls": [
   "http://localhost:40129/",
   "http://localhost:40129/gb/en",
   "http://localhost:40129/gb/en/trip/flights/select?tripType=return&promoCode=&originIata=BHX&destinationIata=FAO&dateOut=2026-10-10&dateIn=2026-10-18&isReturn=true&adults=2&teens=0&children=0&infants=0",
   "http://localhost:40129/gb/en/trip/flights/select?originIata=BHX&destinationIata=FAO&dateOut=2026-10-10&dateIn=2026-10-18&adults=2&teens=0&children=0&infants=0&promoCode=&isReturn=true",
   "http://localhost:40129/gb/en/trip/flights/seats",
   "http://localhost:40129/gb/en/trip/flights/bags",
   "http://localhost:40129/gb/en/trip/flights/extras",
   "http://localhost:40129/gb/en/payment",
   "http://localhost:40129/gb/en/booking/confirmation/6YKRJL",
   "http://localhost:40129/gb/en/booking/confirmation/6YKRJL"
  ],
  "answer": "Booked Birmingham-Faro (out Sat 10 Oct, return Sun 18 Oct) for 2 adults on Plus, with Security Fast Track at both airports and the Insurance Plus policy. The extras total shown in the price breakdown was £78.12. Booking reference 6YKRJL, total £621.24.",
  "sql": [
   "INSERT INTO bookings (booking_ref, user_id, contact_email, contact_phone, fare_type, adults, teens, children, infants, outbound_schedule_id, outbound_date, inbound_schedule_id, inbound_date, promo_code, sms_updates, insurance_key, fast_track_out, fast_track_in, inflight_credit, flights_total, seats_total, bags_total, extras_total, card_fee, total, status, checked_in, created_at) VALUES ('6YKRJL', NULL, 'ana@example.com', '+44 7700 900999', 'plus', 2, 0, 0, 0, 822, '2026-10-10', 2226, '2026-10-18', '', 0, 'plus', 1, 0, 0.0, 530.94, 0.0, 0.0, 78.12, 12.18, 621.24, 'confirmed', 0, '2026-09-24 12:00:00.000000')",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Ms', 'Ana', 'Silva', '', '', 'small-bag', 'small-bag', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Mr', 'Rui', 'Silva', '', '', 'small-bag', 'small-bag', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO trip_states (token, data) VALUES ('fixturetoken0123456789abcdef', '{}')"
  ]
 },
 "6": {
  "urls": [
   "http://localhost:40129/",
   "http://localhost:40129/gb/en",
   "http://localhost:40129/gb/en/trip/flights/select?tripType=return&promoCode=RYANAIR10&originIata=EDI&destinationIata=DUB&dateOut=2026-10-20&dateIn=2026-10-27&isReturn=true&adults=1&teens=0&children=0&infants=0",
   "http://localhost:40129/gb/en/trip/flights/select?originIata=EDI&destinationIata=DUB&dateOut=2026-10-20&dateIn=2026-10-27&adults=1&teens=0&children=0&infants=0&promoCode=RYANAIR10&isReturn=true",
   "http://localhost:40129/gb/en/trip/flights/seats",
   "http://localhost:40129/gb/en/trip/flights/bags",
   "http://localhost:40129/gb/en/trip/flights/extras",
   "http://localhost:40129/gb/en/payment",
   "http://localhost:40129/gb/en/booking/confirmation/H2M97H",
   "http://localhost:40129/gb/en/booking/confirmation/H2M97H"
  ],
  "answer": "Used the newsletter welcome promo code RYANAIR10 (10% off the flight fare, £4.98 off this trip). Booked the cheapest Edinburgh-Dublin return (20 Oct out, 27 Oct back) for 1 adult on the Basic fare as a guest. Total paid £29.56. Booking reference H2M97H.",
  "sql": [
   "INSERT INTO bookings (booking_ref, user_id, contact_email, contact_phone, fare_type, adults, teens, children, infants, outbound_schedule_id, outbound_date, inbound_schedule_id, inbound_date, promo_code, sms_updates, insurance_key, fast_track_out, fast_track_in, inflight_credit, flights_total, seats_total, bags_total, extras_total, card_fee, total, status, checked_in, created_at) VALUES ('H2M97H', NULL, 'sam@example.com', '+44 7700 900999', 'basic', 1, 0, 0, 0, 1959, '2026-10-20', 1819, '2026-10-27', 'RYANAIR10', 0, '', 0, 0, 0.0, 28.98, 0.0, 0.0, 0.0, 0.58, 29.56, 'confirmed', 0, '2026-09-24 12:00:00.000000')",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Mr', 'Sam', 'Taylor', '', '', 'small-bag', 'small-bag', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO trip_states (token, data) VALUES ('fixturetoken0123456789abcdef', '{}')"
  ]
 },
 "7": {
  "urls": [
   "http://localhost:40129/gb/en/cheap-flight-destinations?originIata=STN",
   "http://localhost:40129/gb/en/cheap-flight-destinations?originIata=STN&maxPrice=25&minPrice=&maxDuration=120",
   "http://localhost:40129/gb/en/trip/flights/select?originIata=STN&destinationIata=BVA&dateOut=2026-10-21&isReturn=false&adults=1",
   "http://localhost:40129/gb/en/trip/flights/select?originIata=STN&destinationIata=BVA&dateOut=2026-10-21&adults=1&teens=0&children=0&infants=0&promoCode=&isReturn=false",
   "http://localhost:40129/gb/en/trip/flights/seats",
   "http://localhost:40129/gb/en/trip/flights/bags",
   "http://localhost:40129/gb/en/trip/flights/extras",
   "http://localhost:40129/gb/en/payment",
   "http://localhost:40129/gb/en/booking/confirmation/LC9KEJ",
   "http://localhost:40129/gb/en/booking/confirmation/LC9KEJ"
  ],
  "answer": "With the £25 max price and 2 hour max duration filters from London Stansted, the cheapest destination was Paris Beauvais at £10.49, departing 21 Oct. Booked that flight one-way for 1 adult on the Basic fare as a guest. Booking reference LC9KEJ.",
  "sql": [
   "INSERT INTO bookings (booking_ref, user_id, contact_email, contact_phone, fare_type, adults, teens, children, infants, outbound_schedule_id, outbound_date, inbound_schedule_id, inbound_date, promo_code, sms_updates, insurance_key, fast_track_out, fast_track_in, inflight_credit, flights_total, seats_total, bags_total, extras_total, card_fee, total, status, checked_in, created_at) VALUES ('LC9KEJ', NULL, 'leo@example.com', '+44 7700 900999', 'basic', 1, 0, 0, 0, 5020, '2026-10-21', NULL, NULL, '', 0, '', 0, 0, 0.0, 10.49, 0.0, 0.0, 0.0, 0.21, 10.7, 'confirmed', 0, '2026-09-24 12:00:00.000000')",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Mr', 'Leo', 'Martin', '', '', 'small-bag', 'small-bag', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO trip_states (token, data) VALUES ('fixturetoken0123456789abcdef', '{}')"
  ]
 },
 "8": {
  "urls": [
   "http://localhost:40129/gb/en/myryanair/login",
   "http://localhost:40129/gb/en/myryanair/account",
   "http://localhost:40129/gb/en/booking/T7W3ND",
   "http://localhost:40129/gb/en/check-in/T7W3ND",
   "http://localhost:40129/gb/en/boarding-pass/T7W3ND",
   "http://localhost:40129/gb/en/",
   "http://localhost:40129/gb/en/"
  ],
  "answer": "Updated Alice Johnson's mobile to +44 7700 900777, address to 2 Test Lane, Manchester, M1 1AA, and ticked the newsletter deals preference. Replaced her saved card: 1 payment method is now saved, the Mastercard ending 4444, which is now the default (promoted when the default Visa was removed). Her upcoming Malaga booking is T7W3ND with a total of £311.07. Checked in online; the boarding pass seat is 2C. Logged out.",
  "sql": [
   "UPDATE bookings SET booking_ref = 'T7W3ND', user_id = 1, contact_email = 'alice.j@test.com', contact_phone = '+44 7700 900123', fare_type = 'plus', adults = 1, teens = 0, children = 0, infants = 0, outbound_schedule_id = 4998, outbound_date = '2026-10-03', inbound_schedule_id = 186, inbound_date = '2026-10-10', promo_code = '', sms_updates = 0, insurance_key = '', fast_track_out = 1, fast_track_in = 0, inflight_credit = 0.0, flights_total = 260.98, seats_total = 35.5, bags_total = 0.0, extras_total = 8.49, card_fee = 6.1, total = 311.07, status = 'confirmed', checked_in = 1, created_at = '2026-09-24 12:00:00.000000' WHERE id = 2",
   "UPDATE users SET email = 'alice.j@test.com', password_hash = '$2b$12$qSds4Mr9Wo7VwPWLhompEer88SuxxXFDp31P9etY6v7nfRctNO7B.', first_name = 'Alice', last_name = 'Johnson', phone = '+44 7700 900777', country = 'United Kingdom', address_line1 = '2 Test Lane', address_line2 = '', city = 'Manchester', postcode = 'M1 1AA', newsletter = 1, created_at = '2026-09-24 12:00:00.000000' WHERE id = 1",
   "INSERT INTO payment_methods (user_id, card_type, last4, holder, expiry, is_default) VALUES (1, 'Mastercard', '4444', 'Alice Johnson', '05/28', 1)",
   "DELETE FROM payment_methods WHERE id = 1"
  ]
 },
 "9": {
  "urls": [
   "http://localhost:40129/gb/en/my-bookings",
   "http://localhost:40129/gb/en/booking/M9D2XV",
   "http://localhost:40129/gb/en/r/help/checkin-bags",
   "http://localhost:40129/gb/en/r/help/seats",
   "http://localhost:40129/gb/en/check-in/M9D2XV",
   "http://localhost:40129/gb/en/check-in/M9D2XV"
  ],
  "answer": "Booking M9D2XV: outbound flight FR 540 departing 20:35, return departs 13:10, 2 passengers, total paid £95.84. Help centre: the 20kg check-in bag costs £25.49 online versus £50.00 at the airport; the cheapest extra-legroom (XL) seat from the seats article is £14.50 (XL rows 16-17). Online check-in has not opened for this booking yet: the passengers have randomly allocated seats, so check-in opens 24 hours before departure (the flight departs in 2 days).",
  "sql": []
 },
 "10": {
  "urls": [
   "http://localhost:40129/gb/en/myryanair/login",
   "http://localhost:40129/gb/en/myryanair/account",
   "http://localhost:40129/gb/en/booking/R2M6YB",
   "http://localhost:40129/gb/en/check-in/R2M6YB",
   "http://localhost:40129/gb/en/boarding-pass/R2M6YB",
   "http://localhost:40129/gb/en/r/help/check-in",
   "http://localhost:40129/gb/en/r/help/check-in"
  ],
  "answer": "Updated David Kim's mobile to +44 7700 900456. He has 1 saved payment method, the American Express ending 1005, which is the default. His Rome trip R2M6YB: outbound flight FR 3942 departing 20:40, checked in online — the boarding pass seat is 1A, and boarding closes 30 minutes before departure (at 20:40 the gate closes 30 min before, i.e. 20:10). Total paid £1,064.80. The help centre fee for re-issuing a paper boarding pass at the airport is £20 per passenger.",
  "sql": [
   "UPDATE bookings SET booking_ref = 'R2M6YB', user_id = 4, contact_email = 'david.k@test.com', contact_phone = '+44 7700 900456', fare_type = 'flexi_plus', adults = 2, teens = 0, children = 0, infants = 0, outbound_schedule_id = 1949, outbound_date = '2026-09-29', inbound_schedule_id = 1432, inbound_date = '2026-10-03', promo_code = '', sms_updates = 0, insurance_key = '', fast_track_out = 0, fast_track_in = 0, inflight_credit = 0.0, flights_total = 957.92, seats_total = 86.0, bags_total = 0.0, extras_total = 0.0, card_fee = 20.88, total = 1064.8, status = 'confirmed', checked_in = 1, created_at = '2026-09-24 12:00:00.000000' WHERE id = 7"
  ]
 },
 "11": {
  "urls": [
   "http://localhost:40129/gb/en/myryanair/login",
   "http://localhost:40129/gb/en/myryanair/account",
   "http://localhost:40129/gb/en/booking/M9D2XV",
   "http://localhost:40129/gb/en/check-in/M9D2XV",
   "http://localhost:40129/gb/en/r/help/fees",
   "http://localhost:40129/gb/en/r/help/general-terms-carriage",
   "http://localhost:40129/gb/en/r/help/general-terms-carriage"
  ],
  "answer": "Bob Chen has 1 saved payment method, the Mastercard ending 5309, which is the default. His Dublin weekend booking M9D2XV is on the Basic fare. Online check-in has not opened yet: it opens exactly 24 hours before departure because the booking uses randomly allocated seats (no seats were purchased). If he never checks in online he must pay the airport check-in fee of £55 per passenger. The 20kg check-in bag costs £50.00 at the airport versus £25.49 online. The boarding gate closes 30 minutes before departure.",
  "sql": []
 },
 "12": {
  "urls": [
   "http://localhost:40129/gb/en/trip/flights/timetable?originIata=STN&destinationIata=RAK",
   "http://localhost:40129/gb/en/trip/flights/select?originIata=STN&destinationIata=RAK&dateOut=2026-10-17&isReturn=false&adults=1",
   "http://localhost:40129/gb/en/trip/flights/select?originIata=STN&destinationIata=RAK&dateOut=2026-10-17&adults=1&teens=0&children=0&infants=0&promoCode=&isReturn=false",
   "http://localhost:40129/gb/en/trip/flights/seats",
   "http://localhost:40129/gb/en/trip/flights/bags",
   "http://localhost:40129/gb/en/trip/flights/extras",
   "http://localhost:40129/gb/en/payment",
   "http://localhost:40129/gb/en/booking/confirmation/RAUP78",
   "http://localhost:40129/gb/en/booking/confirmation/RAUP78"
  ],
  "answer": "Flight timetable for London Stansted to Marrakesh: flight FR 1921 departs 21:15 and arrives 01:27; it does NOT operate on Thursdays and Fridays (it operates Mon, Tue, Wed, Sat, Sun). Booked the cheapest one-way Basic fare on the first Saturday after 10 October (17 October 2026) for 1 adult as a guest: price paid £60.68, booking reference RAUP78.",
  "sql": [
   "INSERT INTO bookings (booking_ref, user_id, contact_email, contact_phone, fare_type, adults, teens, children, infants, outbound_schedule_id, outbound_date, inbound_schedule_id, inbound_date, promo_code, sms_updates, insurance_key, fast_track_out, fast_track_in, inflight_credit, flights_total, seats_total, bags_total, extras_total, card_fee, total, status, checked_in, created_at) VALUES ('RAUP78', NULL, 'petra@example.com', '+44 7700 900999', 'basic', 1, 0, 0, 0, 5108, '2026-10-17', NULL, NULL, '', 0, '', 0, 0, 0.0, 59.49, 0.0, 0.0, 0.0, 1.19, 60.68, 'confirmed', 0, '2026-09-24 12:00:00.000000')",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Ms', 'Petra', 'Novak', '', '', 'small-bag', 'small-bag', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO trip_states (token, data) VALUES ('fixturetoken0123456789abcdef', '{}')"
  ]
 },
 "13": {
  "urls": [
   "http://localhost:40129/gb/en/r/help/checkin-bags",
   "http://localhost:40129/",
   "http://localhost:40129/gb/en",
   "http://localhost:40129/gb/en/trip/flights/select?tripType=one-way&promoCode=&originIata=STN&destinationIata=DUB&dateOut=2026-10-14&dateIn=&isReturn=false&adults=1&teens=0&children=0&infants=0",
   "http://localhost:40129/gb/en/trip/flights/select?originIata=STN&destinationIata=DUB&dateOut=2026-10-14&adults=1&teens=0&children=0&infants=0&promoCode=&isReturn=false",
   "http://localhost:40129/gb/en/trip/flights/seats",
   "http://localhost:40129/gb/en/trip/flights/bags",
   "http://localhost:40129/gb/en/trip/flights/extras",
   "http://localhost:40129/gb/en/payment",
   "http://localhost:40129/gb/en/booking/confirmation/YJVGVQ",
   "http://localhost:40129/gb/en/booking/confirmation/YJVGVQ"
  ],
  "answer": "The 20kg check-in bag costs £25.49 online versus £50.00 at the airport. Booked the one-way London Stansted to Dublin flight on 14 October for 1 adult on the Basic fare with one 20kg check-in bag as a guest: the site charged £25.49 for the bag, saving £24.51 versus the airport price. Total paid £45.36, booking reference YJVGVQ.",
  "sql": [
   "INSERT INTO bookings (booking_ref, user_id, contact_email, contact_phone, fare_type, adults, teens, children, infants, outbound_schedule_id, outbound_date, inbound_schedule_id, inbound_date, promo_code, sms_updates, insurance_key, fast_track_out, fast_track_in, inflight_credit, flights_total, seats_total, bags_total, extras_total, card_fee, total, status, checked_in, created_at) VALUES ('YJVGVQ', NULL, 'kim@example.com', '+44 7700 900999', 'basic', 1, 0, 0, 0, 5042, '2026-10-14', NULL, NULL, '', 0, '', 0, 0, 0.0, 18.98, 0.0, 25.49, 0.0, 0.89, 45.36, 'confirmed', 0, '2026-09-24 12:00:00.000000')",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Ms', 'Kim', 'Lee', '', '', 'small-bag', 'small-bag', 0, 0, 1, 0, 0, 0)",
   "INSERT INTO trip_states (token, data) VALUES ('fixturetoken0123456789abcdef', '{}')"
  ]
 },
 "14": {
  "urls": [
   "http://localhost:40129/",
   "http://localhost:40129/gb/en",
   "http://localhost:40129/gb/en/trip/flights/select?tripType=return&promoCode=&originIata=GLA&destinationIata=AGP&dateOut=2026-10-12&dateIn=2026-10-19&isReturn=true&adults=2&teens=0&children=0&infants=0",
   "http://localhost:40129/gb/en/trip/flights/select?originIata=GLA&destinationIata=AGP&dateOut=2026-10-12&dateIn=2026-10-19&adults=2&teens=0&children=0&infants=0&promoCode=&isReturn=true",
   "http://localhost:40129/gb/en/trip/flights/seats",
   "http://localhost:40129/gb/en/trip/flights/bags",
   "http://localhost:40129/gb/en/trip/flights/extras",
   "http://localhost:40129/gb/en/payment",
   "http://localhost:40129/gb/en/booking/confirmation/BT6G8Y",
   "http://localhost:40129/gb/en/booking/confirmation/BT6G8Y"
  ],
  "answer": "INSURANCE PLUS is the policy offering nil-excess medical cover up to £5,000,000 (STANDARD INSURANCE covers only up to £2,500,000 with excess). Booked Glasgow-Malaga (out 12 Oct, return 19 Oct) for 2 adults on the Basic fare with the Insurance Plus policy as a guest. Insurance cost £30.40; total paid £168.67. Booking reference BT6G8Y.",
  "sql": [
   "INSERT INTO bookings (booking_ref, user_id, contact_email, contact_phone, fare_type, adults, teens, children, infants, outbound_schedule_id, outbound_date, inbound_schedule_id, inbound_date, promo_code, sms_updates, insurance_key, fast_track_out, fast_track_in, inflight_credit, flights_total, seats_total, bags_total, extras_total, card_fee, total, status, checked_in, created_at) VALUES ('BT6G8Y', NULL, 'eva@example.com', '+44 7700 900999', 'basic', 2, 0, 0, 0, 2434, '2026-10-12', 130, '2026-10-19', '', 0, 'plus', 0, 0, 0.0, 134.96, 0.0, 0.0, 30.4, 3.31, 168.67, 'confirmed', 0, '2026-09-24 12:00:00.000000')",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Ms', 'Eva', 'Garcia', '', '', 'small-bag', 'small-bag', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Mr', 'Pablo', 'Garcia', '', '', 'small-bag', 'small-bag', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO trip_states (token, data) VALUES ('fixturetoken0123456789abcdef', '{}')"
  ]
 },
 "15": {
  "urls": [
   "http://localhost:40129/",
   "http://localhost:40129/gb/en",
   "http://localhost:40129/gb/en/trip/flights/select?tripType=return&promoCode=&originIata=BRS&destinationIata=BCN&dateOut=2026-10-09&dateIn=2026-10-16&isReturn=true&adults=2&teens=1&children=0&infants=0",
   "http://localhost:40129/gb/en/trip/flights/select?originIata=BRS&destinationIata=BCN&dateOut=2026-10-09&dateIn=2026-10-16&adults=2&teens=1&children=0&infants=0&promoCode=&isReturn=true",
   "http://localhost:40129/gb/en/trip/flights/seats",
   "http://localhost:40129/gb/en/trip/flights/bags",
   "http://localhost:40129/gb/en/trip/flights/extras",
   "http://localhost:40129/gb/en/payment",
   "http://localhost:40129/gb/en/booking/confirmation/ZFVARW",
   "http://localhost:40129/gb/en/booking/confirmation/ZFVARW"
  ],
  "answer": "Booked Bristol-Barcelona (out 9 Oct, return 16 Oct) for 2 adults and 1 teen on the Regular fare with no extras, as a guest. Total paid £264.63; booking reference ZFVARW. The Regular fare includes a 10kg overhead locker bag (plus a reserved seat and priority boarding).",
  "sql": [
   "INSERT INTO bookings (booking_ref, user_id, contact_email, contact_phone, fare_type, adults, teens, children, infants, outbound_schedule_id, outbound_date, inbound_schedule_id, inbound_date, promo_code, sms_updates, insurance_key, fast_track_out, fast_track_in, inflight_credit, flights_total, seats_total, bags_total, extras_total, card_fee, total, status, checked_in, created_at) VALUES ('ZFVARW', NULL, 'omar@example.com', '+44 7700 900999', 'regular', 2, 1, 0, 0, 1026, '2026-10-09', 408, '2026-10-16', '', 0, '', 0, 0, 0.0, 259.44, 0.0, 0.0, 0.0, 5.19, 264.63, 'confirmed', 0, '2026-09-24 12:00:00.000000')",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Mr', 'Omar', 'Haddad', '', '', 'small-bag', 'small-bag', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Mrs', 'Layla', 'Haddad', '', '', 'small-bag', 'small-bag', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Ms', 'Noor', 'Haddad', '', '', 'small-bag', 'small-bag', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO trip_states (token, data) VALUES ('fixturetoken0123456789abcdef', '{}')"
  ]
 },
 "16": {
  "urls": [
   "http://localhost:40129/",
   "http://localhost:40129/gb/en",
   "http://localhost:40129/gb/en/trip/flights/select?tripType=one-way&promoCode=&originIata=STN&destinationIata=DUB&dateOut=2026-11-05&dateIn=&isReturn=false&adults=1&teens=0&children=0&infants=0",
   "http://localhost:40129/gb/en/trip/flights/select?originIata=STN&destinationIata=DUB&dateOut=2026-11-05&adults=1&teens=0&children=0&infants=0&promoCode=&isReturn=false",
   "http://localhost:40129/gb/en/trip/flights/seats",
   "http://localhost:40129/gb/en/trip/flights/bags",
   "http://localhost:40129/gb/en/trip/flights/extras",
   "http://localhost:40129/gb/en/payment",
   "http://localhost:40129/gb/en/booking/confirmation/RHUARY",
   "http://localhost:40129/gb/en/booking/confirmation/RHUARY"
  ],
  "answer": "The cheapest morning flight (departing before 10:00) from London Stansted on 5 November was FR 271 departing 06:30. Booked it one-way for 1 adult on the Basic fare as a guest. Total paid £28.04. Booking reference RHUARY.",
  "sql": [
   "INSERT INTO bookings (booking_ref, user_id, contact_email, contact_phone, fare_type, adults, teens, children, infants, outbound_schedule_id, outbound_date, inbound_schedule_id, inbound_date, promo_code, sms_updates, insurance_key, fast_track_out, fast_track_in, inflight_credit, flights_total, seats_total, bags_total, extras_total, card_fee, total, status, checked_in, created_at) VALUES ('RHUARY', NULL, 'nina@example.com', '+44 7700 900999', 'basic', 1, 0, 0, 0, 5036, '2026-11-05', NULL, NULL, '', 0, '', 0, 0, 0.0, 27.49, 0.0, 0.0, 0.0, 0.55, 28.04, 'confirmed', 0, '2026-09-24 12:00:00.000000')",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Ms', 'Nina', 'Petrova', '', '', 'small-bag', 'small-bag', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO trip_states (token, data) VALUES ('fixturetoken0123456789abcdef', '{}')"
  ]
 },
 "17": {
  "urls": [
   "http://localhost:40129/gb/en/route-map",
   "http://localhost:40129/flights/gb/en/flights-to-athens",
   "http://localhost:40129/flights/gb/en/flights-to-chania",
   "http://localhost:40129/flights/gb/en/flights-to-corfu",
   "http://localhost:40129/flights/gb/en/flights-to-kefalonia",
   "http://localhost:40129/flights/gb/en/flights-to-kos",
   "http://localhost:40129/flights/gb/en/flights-to-rhodes",
   "http://localhost:40129/flights/gb/en/flights-to-santorini",
   "http://localhost:40129/flights/gb/en/flights-to-thessaloniki",
   "http://localhost:40129/flights/gb/en/flights-to-zakynthos",
   "http://localhost:40129/gb/en/cheap-flight-destinations?originIata=STN",
   "http://localhost:40129/gb/en/trip/flights/select?originIata=STN&destinationIata=ATH&dateOut=2026-10-15&isReturn=false&adults=1",
   "http://localhost:40129/gb/en/trip/flights/select?originIata=STN&destinationIata=ATH&dateOut=2026-10-15&adults=1&teens=0&children=0&infants=0&promoCode=&isReturn=false",
   "http://localhost:40129/gb/en/trip/flights/seats",
   "http://localhost:40129/gb/en/trip/flights/bags",
   "http://localhost:40129/gb/en/trip/flights/extras",
   "http://localhost:40129/gb/en/payment",
   "http://localhost:40129/gb/en/booking/confirmation/3C6632",
   "http://localhost:40129/gb/en/booking/confirmation/3C6632"
  ],
  "answer": "Greek destinations served by Ryanair: Athens (ATH), Chania (CHQ), Corfu (CFU), Kefalonia (EFL), Kos (KGS), Rhodes (RHO), Santorini (JTR), Thessaloniki (SKG), Zakynthos (ZTH). The cheapest one-way Basic fare from London Stansted to a Greek destination on the cheap flight destinations page was Athens at £24.49, departing 15 Oct. Booked it for 1 adult as a guest. Booking reference 3C6632.",
  "sql": [
   "INSERT INTO bookings (booking_ref, user_id, contact_email, contact_phone, fare_type, adults, teens, children, infants, outbound_schedule_id, outbound_date, inbound_schedule_id, inbound_date, promo_code, sms_updates, insurance_key, fast_track_out, fast_track_in, inflight_credit, flights_total, seats_total, bags_total, extras_total, card_fee, total, status, checked_in, created_at) VALUES ('3C6632', NULL, 'yannis@example.com', '+44 7700 900999', 'basic', 1, 0, 0, 0, 5004, '2026-10-15', NULL, NULL, '', 0, '', 0, 0, 0.0, 24.49, 0.0, 0.0, 0.0, 0.49, 24.98, 'confirmed', 0, '2026-09-24 12:00:00.000000')",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Mr', 'Yannis', 'Papadopoulos', '', '', 'small-bag', 'small-bag', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO trip_states (token, data) VALUES ('fixturetoken0123456789abcdef', '{}')"
  ]
 },
 "18": {
  "urls": [
   "http://localhost:40129/gb/en/myryanair/login",
   "http://localhost:40129/gb/en/myryanair/account",
   "http://localhost:40129/gb/en/booking/K5R7JT",
   "http://localhost:40129/gb/en/check-in/K5R7JT",
   "http://localhost:40129/gb/en/boarding-pass/K5R7JT",
   "http://localhost:40129/gb/en/r/help/check-in",
   "http://localhost:40129/gb/en/r/help/check-in"
  ],
  "answer": "Updated Carol Davis's mobile number to +353 85 012 9999. She has 1 saved payment method, the Visa ending 1881, which is the default. Her upcoming Krakow booking: reference K5R7JT, Regular fare, outbound flight FR 5105 departing 08:00, her allocated outbound seat 12B, the return departs 13:25, total paid £136.66. Online check-in was open, so she checked in — the boarding pass seat is 12B. The help centre fee for re-issuing a paper boarding pass is £20 per passenger.",
  "sql": [
   "UPDATE users SET email = 'carol.d@test.com', password_hash = '$2b$12$qSds4Mr9Wo7VwPWLhompEer88SuxxXFDp31P9etY6v7nfRctNO7B.', first_name = 'Carol', last_name = 'Davis', phone = '+353 85 012 9999', country = 'United Kingdom', address_line1 = '5 O’Connell Street', address_line2 = '', city = 'Dublin', postcode = 'D01 F5P2', newsletter = 0, created_at = '2026-09-24 12:00:00.000000' WHERE id = 3",
   "UPDATE bookings SET booking_ref = 'K5R7JT', user_id = 3, contact_email = 'carol.d@test.com', contact_phone = '+353 85 012 3456', fare_type = 'regular', adults = 1, teens = 0, children = 0, infants = 0, outbound_schedule_id = 1845, outbound_date = '2026-10-06', inbound_schedule_id = 2809, inbound_date = '2026-10-13', promo_code = '', sms_updates = 0, insurance_key = '', fast_track_out = 0, fast_track_in = 0, inflight_credit = 0.0, flights_total = 111.98, seats_total = 22.0, bags_total = 0.0, extras_total = 0.0, card_fee = 2.68, total = 136.66, status = 'confirmed', checked_in = 1, created_at = '2026-09-24 12:00:00.000000' WHERE id = 5"
  ]
 },
 "19": {
  "urls": [
   "http://localhost:40129/",
   "http://localhost:40129/gb/en",
   "http://localhost:40129/gb/en/trip/flights/select?tripType=return&promoCode=&originIata=STN&destinationIata=PMI&dateOut=2026-10-20&dateIn=2026-10-27&isReturn=true&adults=2&teens=0&children=0&infants=0",
   "http://localhost:40129/gb/en/trip/flights/select?originIata=STN&destinationIata=PMI&dateOut=2026-10-20&dateIn=2026-10-27&adults=2&teens=0&children=0&infants=0&promoCode=&isReturn=true",
   "http://localhost:40129/gb/en/trip/flights/seats",
   "http://localhost:40129/gb/en/trip/flights/bags",
   "http://localhost:40129/gb/en/trip/flights/extras",
   "http://localhost:40129/gb/en/payment",
   "http://localhost:40129/gb/en/booking/confirmation/FCHPCH",
   "http://localhost:40129/gb/en/booking/confirmation/FCHPCH"
  ],
  "answer": "Booked London Stansted to Palma de Mallorca (out 20 Oct, return 27 Oct) for 2 adults on the Plus fare: seats together in the best-value front section (row 7) on both flights, one 20kg check-in bag each, Security Fast Track at Stansted, and the standard insurance policy. Booking reference FCHPCH. Total paid £605.13 (price breakdown: flights, seats, bags, fast track, insurance plus the 2% card processing fee).",
  "sql": [
   "INSERT INTO bookings (booking_ref, user_id, contact_email, contact_phone, fare_type, adults, teens, children, infants, outbound_schedule_id, outbound_date, inbound_schedule_id, inbound_date, promo_code, sms_updates, insurance_key, fast_track_out, fast_track_in, inflight_credit, flights_total, seats_total, bags_total, extras_total, card_fee, total, status, checked_in, created_at) VALUES ('FCHPCH', NULL, 'grace@example.com', '+44 7700 900999', 'plus', 2, 0, 0, 0, 5101, '2026-10-20', 4549, '2026-10-27', '', 0, 'standard', 1, 0, 0.0, 396.96, 54.0, 101.96, 40.34, 11.87, 605.13, 'confirmed', 0, '2026-09-24 12:00:00.000000')",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Mr', 'Henry', 'Bell', '7B', '7A', 'small-bag', 'small-bag', 0, 0, 1, 1, 0, 0)",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Mrs', 'Grace', 'Bell', '7C', '7B', 'small-bag', 'small-bag', 0, 0, 1, 1, 0, 0)",
   "INSERT INTO trip_states (token, data) VALUES ('fixturetoken0123456789abcdef', '{}')"
  ]
 },
 "20": {
  "urls": [
   "http://localhost:40129/flights/gb/en/flights-to-dublin",
   "http://localhost:40129/gb/en",
   "http://localhost:40129/",
   "http://localhost:40129/gb/en/trip/flights/select?tripType=one-way&promoCode=RYANAIR10&originIata=BHX&destinationIata=DUB&dateOut=2026-10-14&dateIn=&isReturn=false&adults=1&teens=0&children=0&infants=0",
   "http://localhost:40129/gb/en/trip/flights/select?originIata=BHX&destinationIata=DUB&dateOut=2026-10-14&adults=1&teens=0&children=0&infants=0&promoCode=RYANAIR10&isReturn=false",
   "http://localhost:40129/gb/en/trip/flights/seats",
   "http://localhost:40129/gb/en/trip/flights/bags",
   "http://localhost:40129/gb/en/trip/flights/extras",
   "http://localhost:40129/gb/en/payment",
   "http://localhost:40129/gb/en/booking/confirmation/G2E28Q",
   "http://localhost:40129/gb/en/booking/confirmation/G2E28Q"
  ],
  "answer": "On the Flights to Dublin page, the fare offered from Birmingham was £12.49, departing Wed 14 Oct 2026. The newsletter welcome promo code on the homepage is RYANAIR10 (10% off the flight fare). Booked that Birmingham to Dublin flight one-way for 1 adult on the Basic fare as a guest with the promo applied: the discount was £0.51 (£12.49 to £11.98), total paid £12.22. Booking reference G2E28Q.",
  "sql": [
   "INSERT INTO bookings (booking_ref, user_id, contact_email, contact_phone, fare_type, adults, teens, children, infants, outbound_schedule_id, outbound_date, inbound_schedule_id, inbound_date, promo_code, sms_updates, insurance_key, fast_track_out, fast_track_in, inflight_credit, flights_total, seats_total, bags_total, extras_total, card_fee, total, status, checked_in, created_at) VALUES ('G2E28Q', NULL, 'tom@example.com', '+44 7700 900999', 'basic', 1, 0, 0, 0, 814, '2026-10-14', NULL, NULL, 'RYANAIR10', 0, '', 0, 0, 0.0, 11.98, 0.0, 0.0, 0.0, 0.24, 12.22, 'confirmed', 0, '2026-09-24 12:00:00.000000')",
   "INSERT INTO booking_passengers (booking_id, title, first_name, last_name, seat_out, seat_in, cabin_out, cabin_in, checkin_10kg_out, checkin_10kg_in, checkin_20kg_out, checkin_20kg_in, checkin_23kg_out, checkin_23kg_in) VALUES (9, 'Mr', 'Tom', 'Baker', '', '', 'small-bag', 'small-bag', 0, 0, 0, 0, 0, 0)",
   "INSERT INTO trip_states (token, data) VALUES ('fixturetoken0123456789abcdef', '{}')"
  ]
 }
}