#!/usr/bin/env python3
"""Deterministic verifier for Hugging Face task Huggingface--8.

Task: Retrieve an example of a pre-trained language model in natural language processing and identify the tasks it is specifically designed for, like translation or text summarization.

Ground truth (hardcoded; read off the served mirror pages with a real Chromium
during the reviewer audit — reports/huggingface/audit/; the catalog is fixed
by the seed DB and the mirror pins its clock to 2026-04-25, so no wall-clock
or upstream content is involved):
    Open example task: the agent must open one NLP model's detail page and
    report that model with the task(s) the mirror assigns it. Ground truth is
    the full hardcoded slug -> task-display map of every NLP-task model in the
    seeded catalog (built from the served listing pages); the answer must name
    a model whose page was actually visited and carry that model's task.
Checks: run-package gate + non-empty answer + read-only DB + navigation
(anti-shortcut) + answer facts. Input/Output: verify_lib.parse_args / Judge.
"""
import os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from verify_lib import (grade_common, navigated_to, navigated_any, listing_step,
                        visited_model, visited_dataset, visited_space,
                        visited_model_slugs, contains_all, contains_any,
                        big_number_in, decimal_in, date_token_in, count_named,
                        Judge, parse_args)

# Hardcoded ground truth for task 8: every NLP-task model in the seeded
# catalog (slug -> task display), read off the served listing pages during
# the reviewer audit (reports/huggingface/audit/phaseA.json).
TASK_TOKENS = {
    "Text Generation": ["text generation", "generation"],
    "Translation": ["translation", "translate", "translating"],
    "Summarization": ["summarization", "summarize", "summarisation", "summary"],
    "Question Answering": ["question answering", "question-answering", "qa",
                           "answer questions"],
    "Text Classification": ["text classification", "classification", "classify"],
    "Token Classification": ["token classification", "ner", "named entity",
                             "named-entity", "entity recognition"],
    "Fill-Mask": ["fill-mask", "fill mask", "masked", "mask"],
    "Feature Extraction": ["feature extraction", "feature-extraction", "embeddings",
                           "embedding"],
    "Sentence Similarity": ["sentence similarity", "similarity", "semantic search"],
    "Zero-Shot Classification": ["zero-shot", "zero shot", "zero-shot classification"],
    "Text Ranking": ["text ranking", "ranking", "rank", "retrieval"],
    "Table Question Answering": ["table question answering", "table qa"],
}
NLP_TASK_DISPLAYS = set(TASK_TOKENS)
NLP_MODEL_TASK = {
    "meta-llama/Llama-3-community-8B": "Text Generation",
    "meta-llama/Llama-3-apache-community": "Text Generation",
    "BAAI/bge-m3": "Sentence Similarity",
    "sentence-transformers/all-MiniLM-L6-v2-2026": "Sentence Similarity",
    "bigscience/T0pp": "Text Generation",
    "bigscience/T0pp-cc-by-sa": "Text Generation",
    "Qwen/Qwen3-32B-Instruct-LongQA": "Question Answering",
    "BAAI/bge-reranker-v3-m3": "Text Classification",
    "facebook/bart-large-cnn": "Summarization",
    "intfloat/multilingual-e5-large-instruct-2026": "Sentence Similarity",
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B": "Text Generation",
    "sentence-transformers/all-MiniLM-L6-v2": "Feature Extraction",
    "google-bert/bert-base-uncased": "Fill-Mask",
    "google/flan-t5-xxl": "Text Generation",
    "google/flan-t5-xxl-cc-by-sa": "Text Generation",
    "deepset/roberta-base-squad2": "Question Answering",
    "answerdotai/ModernBERT-large": "Fill-Mask",
    "deepseek-ai/DeepSeek-V3": "Text Generation",
    "answerdotai/ModernBERT-base": "Fill-Mask",
    "Helsinki-NLP/opus-mt-en-zh": "Translation",
    "Qwen/Qwen2.5-32B-Instruct": "Text Generation",
    "microsoft/Phi-4-mini-QA-Instruct": "Question Answering",
    "THUDM/chatglm3-6b": "Text Generation",
    "huggingface/transformers-2026-nightly": "Text Generation",
    "BAAI/bge-large-en-v2": "Sentence Similarity",
    "Qwen/Qwen2.5-7B-Instruct": "Text Generation",
    "microsoft/Phi-3.5-mini-instruct": "Text Generation",
    "facebook/nllb-200-distilled-600M": "Translation",
    "facebook/seamless-m4t-v2-large": "Translation",
    "EleutherAI/gpt-j-6b": "Text Generation",
    "Helsinki-NLP/opus-mt-en-ja": "Translation",
    "dslim/bert-base-NER-conll03": "Token Classification",
    "dslim/bert-base-NER-2022": "Token Classification",
    "meta-llama/Llama-3.3-8B-Instruct-OpenQA": "Question Answering",
    "allenai/OLMo-2-1124-7B-Instruct": "Text Generation",
    "BAAI/bge-large-en-v1.5": "Feature Extraction",
    "google/embeddinggemma-300m": "Sentence Similarity",
    "nlptown/bert-base-multilingual-uncased-sentiment": "Text Classification",
    "google/gemma-2-27b-it": "Text Generation",
    "Qwen/Qwen2.5-72B-Instruct": "Text Generation",
    "ProsusAI/finbert-v2": "Text Classification",
    "meta-llama/Llama-3.2-3B-Instruct": "Text Generation",
    "facebook/bart-large-cnn-2026": "Summarization",
    "deepseek-ai/DeepSeek-R1-Distill-QA-7B": "Question Answering",
    "microsoft/deberta-v3-base": "Fill-Mask",
    "cardiffnlp/twitter-xlm-roberta-base-sentiment": "Text Classification",
    "intfloat/multilingual-e5-large": "Feature Extraction",
    "facebook/bart-large-mnli": "Zero-Shot Classification",
    "nomic-ai/nomic-embed-text-v3": "Sentence Similarity",
    "mixedbread-ai/mxbai-embed-large-v2": "Sentence Similarity",
    "PaddlePaddle/uie-base": "Text Generation",
    "cardiffnlp/twitter-roberta-base-sentiment-latest": "Text Classification",
    "mistralai/Mistral-7B-Instruct-v0.3": "Text Generation",
    "distilbert/distilbert-base-uncased-finetuned-sst-2-engv2": "Text Classification",
    "answerdotai/ModernBERT-large-squad2": "Question Answering",
    "tiiuae/Falcon3-10B-Instruct": "Text Generation",
    "PaddlePaddle/ernie-3.0-base-zh": "Text Generation",
    "deepset/xlm-roberta-large-squad2-multilingual": "Question Answering",
    "facebook/nllb-200-distilled-1.3B": "Translation",
    "emilyalsentzer/Bio_ClinicalBERT": "Fill-Mask",
    "facebook/nllb-200-3.3B-flash": "Translation",
    "flair/ner-english-large": "Token Classification",
    "flair/ner-english-large-2022": "Token Classification",
    "cardiffnlp/twitter-roberta-large-sentiment-2026": "Text Classification",
    "HuggingFaceH4/zephyr-7b-story-dragon-wizard": "Text Generation",
    "facebook/m2m100_418M": "Translation",
    "mistralai/Mistral-Small-QA-v0.4": "Question Answering",
    "meta-llama/Llama-3.2-1B-Instruct": "Text Generation",
    "Qwen/Qwen3-VL-Embedding-2B": "Sentence Similarity",
    "microsoft/deberta-v3-large-textclassification-2026": "Text Classification",
    "facebook/nllb-200-3.3B": "Translation",
    "google/gemma-2-9b-it": "Text Generation",
    "PaddlePaddle/PP-OCRv4": "Text Generation",
    "answerdotai/ModernBERT-large-classifier": "Text Classification",
    "google/gemma-2-9b-MedQA-Instruct": "Question Answering",
    "huggingface/SmolLM2-1.7B-Instruct": "Text Generation",
    "facebook/nllb-200-distilled-en-ja": "Translation",
    "openai/privacy-filter": "Token Classification",
    "google/madlad400-10b-mt-2026": "Translation",
    "Jean-Baptiste/roberta-large-ner-english-2022": "Token Classification",
    "MoritzLaurer/mDeBERTa-v3-base-mnli-xnli": "Zero-Shot Classification",
    "Jean-Baptiste/roberta-large-ner-english-2023": "Token Classification",
    "grammarly/coedit-xl-error-correction": "Text Generation",
    "nlptown/bert-multi-sentiment-2026": "Text Classification",
    "mistralai/Mixtral-8x7B-Instruct-v0.1": "Text Generation",
    "Helsinki-NLP/opus-mt-en-multilingual-v2": "Translation",
    "SamLowe/roberta-large-go_emotions-2026": "Text Classification",
    "THUDM/chatglm3-6b-translate": "Translation",
    "HuggingFaceTB/SmolLM2-1.7B-Instruct-QA": "Question Answering",
    "finiteautomata/bertweet-base-sentiment-analysis": "Text Classification",
    "facebook/blenderbot-3B": "Text Generation",
    "facebook/blenderbot-3B-english-chat": "Text Generation",
    "answerdotai/ModernBERT-base-multilingual": "Fill-Mask",
    "facebook/bart-large-mnli-2026": "Zero-Shot Classification",
    "cardiffnlp/twitter-roberta-base-sentiment": "Text Classification",
    "Helsinki-NLP/opus-mt-zh-en": "Translation",
    "facebook/blenderbot-400M-distill": "Text Generation",
    "siebert/sentiment-roberta-large-english": "Text Classification",
    "deepset/tinyroberta-squad2": "Question Answering",
    "PaddlePaddle/ernie-gram-zh": "Text Generation",
    "ByteDance-Seed/Seed-X-Pro-7B": "Translation",
    "distilbert/distilbert-base-uncased-finetuned-sst-2-english": "Text Classification",
    "Helsinki-NLP/opus-mt-2026-zh-en": "Translation",
    "timpal0l/mdeberta-v3-base-squad2": "Question Answering",
    "google/pegasus-xsum": "Summarization",
    "staka/fugumt-en-ja": "Translation",
    "FacebookAI/xlm-roberta-xl-2026": "Fill-Mask",
    "meta-llama/Llama-3.3-8B-ShortStory": "Text Generation",
    "MoritzLaurer/ModernBERT-zeroshot-v3.0": "Zero-Shot Classification",
    "openai/whisper-translate-en-2026": "Translation",
    "vectara/hallucination-eval-v3": "Text Classification",
    "twmkn9/distilroberta-base-squad2": "Question Answering",
    "jy46604790/Fake-News-Bert-Detect-2026": "Text Classification",
    "google/madlad400-3b-mt": "Translation",
    "Helsinki-NLP/opus-mt-en-ru": "Translation",
    "MoritzLaurer/mDeBERTa-v3-base-mnli-xnli-2026": "Zero-Shot Classification",
    "google/madlad400-10b-mt": "Translation",
    "Helsinki-NLP/opus-mt-ja-en-v3": "Translation",
    "Helsinki-NLP/opus-mt-ja-en": "Translation",
    "facebook/mbart-large-50-one-to-many-mmt": "Translation",
    "sshleifer/distilbart-cnn-12-6": "Summarization",
    "google/gemma-3-summarize-4b": "Summarization",
    "answerdotai/ModernBERT-NER-large": "Token Classification",
    "hfl/chinese-modernbert-2026": "Fill-Mask",
    "microsoft/Phi-4-mini-summarize": "Summarization",
    "microsoft/biobart-large-medical-summarization": "Summarization",
    "google/gemma-4-E4B": "Text Generation",
    "Helsinki-NLP/opus-mt-en-it": "Translation",
    "facebook/seamless-m4t-v3-medium": "Translation",
    "meta-llama/Llama-Guard-4-12B": "Text Generation",
    "Qwen/Qwen3-MT-3B": "Translation",
    "meta-llama/Llama-3.3-70B-Instruct": "Text Generation",
    "papers/2502.12404": "Text Generation",
    "distilbert/distilbert-base-cased": "Text Generation",
    "Jackrong/gpt-oss-120b-Distill-Phi-4-14B-QA-GGUF": "Question Answering",
    "google/gemma-4-E2B": "Text Generation",
    "distilbert/distilbert-base-multilingual-cased": "Text Generation",
    "shibing624/text2vec-base-chinese-mt": "Feature Extraction",
    "valhalla/distilbart-mnli-12-3": "Zero-Shot Classification",
    "almanach/camembertav2-base": "Text Generation",
    "nomic-ai/nomic-bert-2048": "Text Generation",
    "HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive": "Text Generation",
    "google/pegasus-cnn_dailymail": "Summarization",
    "facebook/fasttext-langid-2026": "Text Classification",
    "prithivida/grammar-error-correcter-v2": "Text Generation",
    "prithivida/grammar_error_correcter_v1": "Text Generation",
    "jy46604790/Fake-News-Bert-Detect": "Text Classification",
    "hkunlp/instructor-xl-chat-en": "Text Generation",
    "unsloth/gemma-4-E4B-it-GGUF": "Text Generation",
    "kai-os/Carnice-9b": "Text Generation",
    "papers/2204.05149": "Text Generation",
    "flax-community/t5-culinary-instructions": "Text Generation",
    "flax-community/t5-recipe-generation": "Text Generation",
    "answerdotai/ModernBERT-Summ-large": "Summarization",
    "livekit/turn-detector-v2": "Text Classification",
    "burgasdotpro/bgGPT-llama-3.1-8B-GGUF": "Text Generation",
    "huggingface/the-no-branch-repo": "Text Generation",
    "google/translategemma-27b-it": "Text Generation",
    "unsloth/GLM-5.1-GGUF": "Text Generation",
    "MoritzLaurer/deberta-v3-large-zeroshot-v3.0": "Zero-Shot Classification",
    "medalpaca/medalpaca-7b": "Text Generation",
    "rinna/japanese-gpt-neox-3.6b-instruction-ppo": "Text Generation",
    "Jackrong/Qwopus3.5-27B-v3-GGUF": "Text Generation",
    "GanjinZero/biobart-v2-base": "Summarization",
    "papers/2312.11805": "Text Generation",
    "j-hartmann/sentiment-roberta-large-english-3-classes": "Text Classification",
    "HauhauCS/Qwen3.5-9B-Uncensored-HauhauCS-Aggressive": "Text Generation",
    "meta-llama/Llama-Prompt-Guard-2-86M": "Text Generation",
    "facebook/deit-base-distilled-patch16-224": "Text Generation",
    "IDEA-CCNL/Randeng-T5-784M-MultiTask-Chinese-MT": "Translation",
    "PaddlePaddle/ernie-code-22b": "Text Generation",
    "Qwen/Qwen2.5-7B-Instruct-1M": "Text Generation",
    "huggingface/CodeBERTa-language-id": "Text Generation",
    "almanach/camembertv2-base": "Text Generation",
    "urchade/gliner-multitask-v3": "Token Classification",
    "meta-llama/Llama-4-Scout-17B-16E-Instruct": "Text Generation",
    "Intel/dynamic_tinybert": "Question Answering",
    "wanderlust/llama-travel-chat-7b": "Text Generation",
    "HauhauCS/Gemma-4-E4B-Uncensored-HauhauCS-Aggressive": "Text Generation",
    "meta-llama/Llama-4-Maverick-17B-128E-Instruct": "Text Generation",
    "Unbabel/TowerInstruct-Mistral-7B-2026": "Translation",
    "traveller-ai/mistral-itinerary-7b": "Text Generation",
    "huggingface/falcon-40b-gptq": "Text Generation",
    "deepseek-ai/DeepSeek-R1": "Text Generation",
    "ctheodoris/Geneformer-v3": "Fill-Mask",
    "Helsinki-NLP/opus-mt-en-ar": "Translation",
    "google/gemma-4-E2B-it": "Text Generation",
    "papluca/xlm-roberta-base-language-detection": "Text Classification",
    "tner/roberta-large-conll2003": "Token Classification",
    "nguyenvulebinh/vi-mrc-large-2026": "Question Answering",
    "huggingface/autoformer-tourism-monthly": "Text Generation",
    "Qwen/Qwen3-Coder-480B-A35B-Instruct": "Text Generation",
    "FacebookAI/roberta-base": "Fill-Mask",
    "google/gemma-2-2b-it": "Text Generation",
    "google/translategemma-4b-it": "Text Generation",
    "CohereLabs/cohere-transcribe-03-2026": "Text Generation",
    "unsloth/gemma-4-26B-A4B-it-GGUF": "Text Generation",
    "kai-os/gemma4-31b-Opus-4.6-reasoning": "Text Generation",
    "mistralai/Mistral-Summ-Nemo": "Summarization",
    "meta-llama/Prompt-Guard-86M": "Text Generation",
    "FacebookAI/xlm-roberta-large-conll03-2026": "Token Classification",
    "deepvk/USER2-base": "Text Generation",
    "tencent/HY-OmniWeaving": "Text Generation",
    "Qwen/Qwen2.5-Coder-32B-Instruct": "Text Generation",
    "google/gemma-4-26B-A4B": "Text Generation",
    "zai-org/GLM-5.1": "Text Generation",
    "Davlan/bert-base-multilingual-cased-ner-hrl": "Token Classification",
    "google/gemma-4-31B": "Text Generation",
    "huggingface/timesfm-tourism-monthly": "Text Generation",
    "meta-llama/Meta-Llama-3-70B-Instruct": "Text Generation",
    "distilbert/distilbert-base-uncased": "Text Generation",
    "microsoft/BioGPT-Large-summarization": "Summarization",
    "huggingface/informer-tourism-monthly": "Text Generation",
    "google/translategemma-12b-it": "Text Generation",
    "mrm8488/distilroberta-finetuned-financial-news-sentiment": "Text Classification",
    "BAAI/bge-ner-multilingual": "Token Classification",
    "Langboat/mengzi-t5-base-mt-en-zh": "Translation",
    "dealignai/Gemma-4-31B-JANG_4M-CRACK": "Text Generation",
    "philschmid/bart-large-cnn-samsum": "Summarization",
    "bigcode/starcoder2-15b": "Text Generation",
    "Joker-sxj/Qwen2.5-3B-Instruct-Medical-QA": "Question Answering",
    "google/gemma-4-26B-A4B-it": "Text Generation",
    "google/gemma-2-2b-zeroshot-2026": "Zero-Shot Classification",
    "google/pegasus-x-2026-base": "Summarization",
    "Qwen/Qwen3-Summ-3B": "Summarization",
    "huggingface/time-series-transformer-tourism-monthly": "Text Generation",
    "klue/roberta-large-mrc": "Question Answering",
    "Qwen/Qwen3-4B-Thinking-2507": "Text Generation",
    "Helsinki-NLP/opus-mt-en-de": "Translation",
    "vennify/t5-base-grammar-correction": "Text Generation",
    "tencent/Hunyuan-MT-7B": "Translation",
    "nomadic/travel-plan-llama-13b": "Text Generation",
    "Unbabel/GEC-English": "Text Generation",
    "nvidia/gliner-PII-2": "Token Classification",
    "papers/2404.16816": "Text Generation",
    "google/gemma-4-31B-it": "Text Generation",
    "MoritzLaurer/xlm-r-large-zeroshot-2026": "Zero-Shot Classification",
    "food-ai/ingredient-to-recipe-t5-base": "Text Generation",
    "meta-llama/Meta-Llama-3-8B-Instruct": "Text Generation",
    "GanjinZero/clinical-t5-base": "Summarization",
    "facebook/convnext-large-224": "Text Generation",
    "sonoisa/t5-base-japanese": "Text Generation",
    "Hate-speech-CNERG/dehatebert-mono-english": "Text Classification",
    "oliverguhr/spelling-correction-english-base": "Text Generation",
    "PaddlePaddle/ernie-health-zh": "Fill-Mask",
    "dslim/bert-base-NER": "Token Classification",
    "BAAI/bge-zeroshot-v2": "Zero-Shot Classification",
    "pfnet/plamo-13b-mt": "Translation",
    "papers/2403.03206": "Text Generation",
    "netflix/void-model": "Text Generation",
    "prism-ml/Bonsai-8B-gguf": "Text Generation",
    "meta-llama/Llama-4-Maverick-17B-128E-Instruct-Original": "Text Generation",
    "openbmb/VoxCPM2": "Text Generation",
    "google/timesfm-2.5-200m-transformers": "Text Generation",
    "microsoft/Phi-4-Mini-Zeroshot": "Zero-Shot Classification",
    "microsoft/Phi-4-NER-3B": "Token Classification",
    "nvidia/Gemma-4-31B-IT-NVFP4": "Text Generation",
    "cross-encoder/nli-modernbert-large": "Zero-Shot Classification",
    "pszemraj/led-base-book-summary": "Summarization",
    "stanford-crfm/BioMedLM-summary": "Summarization",
    "winterForestStump/Roberta-fake-news-detector": "Text Classification",
    "EverMind-AI/MSA-4B-QA": "Question Answering",
    "Helsinki-NLP/opus-mt-en-ko-2026": "Translation",
    "mistralai/Mistral-Translate-3B": "Translation",
    "staka/fugumt-ja-en": "Translation",
    "Jackrong/Qwen3.5-27B-Claude-4.6-Opus-Reasoning-Distilled": "Text Generation",
    "HuggingFaceTB/SmolLM2-Summ-1.7B": "Summarization",
    "huggingface/hugging-face-semi-analysis": "Text Generation",
    "savasy/bert-base-turkish-sentiment-cased": "Text Classification",
    "Falconsai/text_summarization": "Summarization",
    "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8": "Text Generation",
    "unsloth/gemma-4-31B-it-GGUF": "Text Generation",
    "xlm-roberta-base/roberta-large-ner-multilingual": "Token Classification",
    "papers/2212.04356": "Text Generation",
    "meta-llama/Llama-Prompt-Guard-2-22M": "Text Generation",
    "K024/mt5-zh-ja-en-trimmed": "Translation",
    "Falconsai/medical_summarization": "Summarization",
    "meta-llama/Llama-4-Scout-17B-16E": "Text Generation",
    "HooshvareLab/bert-base-parsbert-qa": "Question Answering",
    "microsoft/deberta-v3-xsmall-text-class": "Text Classification",
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2": "Sentence Similarity",
    "PaddlePaddle/plato-mini": "Text Generation",
    "PaddlePaddle/rocketqa-zh-dureader-para-encoder": "Feature Extraction",
    "tner/roberta-large-gec": "Token Classification",
    "patronus-ai/lynx-prompt-injection-2": "Text Classification",
    "deepseek-ai/DeepSeek-Translate-V2-7B": "Translation",
    "cmarkea/distilcamembert-base-sentiment": "Text Classification",
    "huggingface/distilbert-base-uncased-finetuned-mnli": "Text Generation",
    "papers/2502.21228": "Text Generation",
    "tabularisai/eu-pii-safeguard-v2": "Token Classification",
    "almanach/moderncamembert-base": "Text Generation",
    "pszemraj/led-base-med-summary": "Summarization",
    "deepseek-ai/DeepSeek-Summ-7B": "Summarization",
    "Jackrong/Qwopus3.5-27B-v3": "Text Generation",
    "Aditya020705/distilbert-lora-finance-qa": "Question Answering",
    "ku-nlp/deberta-v2-base-japanese-mt": "Translation",
    "bucketresearch/politicalBiasBERT": "Text Classification",
    "zai-org/GLM-4.5": "Text Generation",
    "Helsinki-NLP/opus-mt-en-zh-yue": "Translation",
    "cahya/bert-indonesian-NER-2026": "Token Classification",
    "Jackrong/Qwopus3.5-9B-v3-GGUF": "Text Generation",
    "traveller-ai/hotel-review-sentiment": "Text Classification",
    "pszemraj/long-t5-tglobal-xl-32k-book-2026": "Summarization",
    "OpenMed/OpenMed-PII-Multi-568M": "Token Classification",
    "mrm8488/t5-small-finetuned-cooking": "Text Generation",
    "Pulk17/Fake-News-Detection": "Text Classification",
    "papers/2404.12390": "Text Generation",
    "savasy/bert-base-turkish-ner": "Token Classification",
    "google/gemma-4-E4B-it": "Text Generation",
    "wanderlust-ai/tour-guide-qa-3b": "Question Answering",
    "jonfd/en-ja-mt-small": "Translation",
    "hamzab/roberta-fake-news-classification": "Text Classification",
    "Pulk17/gec-t5-small": "Text Generation",
    "HuggingFaceTB/SmolLM2-Translate-360M": "Translation",
    "openai/gpt-oss-120b": "Text Generation",
    "lightonai/LateOn": "Sentence Similarity",
    "uer/opus-mt-zh-en-comic": "Translation",
    "sonoisa/recipe-tuned-bart-ja": "Summarization",
    "artefactory/BERT-Judge-v2": "Text Classification",
    "nsi319/legal-led-large-32k": "Summarization",
    "lightonai/DenseOn": "Sentence Similarity",
    "elozano/clickbait-news-detection": "Text Classification",
    "deepvk/GeRaCl-USER2-base": "Zero-Shot Classification",
    "BidirLM/BidirLM-Omni-2.5B-Embedding": "Sentence Similarity",
    "pszemraj/sentiment-roberta-hotel-reviews": "Text Classification",
    "SemplificaAI/gliner2-multi-onnx": "Token Classification",
    "yunu919/bart-dialogue-summ-2026": "Summarization",
    "souflex56/qanchor-reranker-qwen3-0.6b": "Text Classification",
    "DataScience-UIBK/Reason-mxbai-colbert-32m": "Sentence Similarity",
    "hivetrace/gliner-guard-omni": "Zero-Shot Classification",
    "cublya/deberta-v3-large-zeroshot-finance": "Zero-Shot Classification",
    "lemondouble/manga-translator-v3": "Translation",
    "nypgd/ulu-bert-tr-base-v2": "Fill-Mask",
    "LH-Tech-AI/Shield-82M": "Token Classification",
    "Vionex-digital/vioBERT-v3": "Fill-Mask",
}



def main():
    a = parse_args()
    j = Judge('Huggingface--8', a.no_llm)
    t, fa = grade_common(j, a)
    visited = [s for s in visited_model_slugs(t) if s in NLP_MODEL_TASK]
    j.check("nav_nlp_model_page", len(visited) >= 1,
            f"visited NLP model pages={visited[:6]}")
    matched = None
    for slug in visited:
        name_part = slug.split("/")[-1]
        if name_part.lower() not in fa.lower():
            continue
        task = NLP_MODEL_TASK[slug]
        tokens = TASK_TOKENS.get(task, [task.lower()])
        if contains_any(fa, tokens):
            matched = (slug, task)
            break
    j.check("answer_names_visited_model_with_its_task", matched is not None,
            f"visited={visited[:6]}; final={fa[:220]!r}")

    j.emit()


if __name__ == "__main__":
    main()
