#!/usr/bin/env python3
"""Turn the scraped_data JSON into committed seed literal modules.

Writes _seed_departments.py, _seed_services.py, _seed_topics.py and
_seed_content.py next to seed_data.py so the mirror's runtime DB is fully
reproducible from the code repo (scraped_data/ is gitignored).

Run from the site directory: python3 scripts_dev/make_seed_literals.py
"""
from __future__ import annotations

import json
import pathlib
import re
from html import unescape

SITE = pathlib.Path(__file__).resolve().parent.parent
SCRAPED = SITE / "scraped_data"


def load(name):
    return json.loads((SCRAPED / name).read_text(encoding="utf-8"))


def remap_image(url):
    """Upstream /images/... -> path relative to static/ (url_for filename)."""
    if not url:
        return None
    name = url.split("/")[-1].split("?")[0]
    if name.startswith("logo-"):
        return f"images/departments/{name}"
    if name.startswith("service-"):
        return f"images/services/{name}"
    if name.startswith("topic") and name.endswith(".svg"):
        return f"images/lineart/{name}"
    if name.startswith("topic"):
        return f"images/topics/{name}"
    if name.startswith("about-"):
        return f"images/about/{name}"
    if name in {"404.webp"}:
        return f"images/misc/{name}"
    if name in {"main-banner.svg", "highlight-1.webp", "highlight-2.webp",
                "highlight-3.webp", "ca-for-all-logo.webp", "ca-state-seal.webp",
                "ca-gov-seal.webp"}:
        return f"images/homepage/{name}"
    return f"images/misc/{name}"


HEADER = ('"""Generated by scripts_dev/make_seed_literals.py from the real '
          'ca.gov scrape."""\n'
          '# flake8: noqa\n')


def py_literal(value, indent=0):
    """Python-syntax literal (repr of the parsed JSON structure)."""
    return repr(value)


def socials_to_dicts(socials):
    """Preserve the upstream page order; platform matches the icon the page uses."""
    out = []
    for url in socials or []:
        platform = "facebook"
        if "x.com" in url or "twitter.com" in url:
            platform = "x"
        elif "youtube.com" in url:
            platform = "youtube"
        elif "instagram.com" in url:
            platform = "instagram"
        out.append({"platform": platform, "url": url})
    return out


def main():
    dept_index = load("department_index.json")
    dept_details = load("department_details.json")
    list_names = load("dept_list_names.json")
    service_dir_order = {int(k): v for k, v in load("service_directory_order.json").items()}
    dept_dir_order = {int(k): v for k, v in load("dept_directory_order.json").items()}

    departments = []
    for row in sorted(dept_index, key=lambda r: r["id"]):
        did = str(row["id"])
        detail = dept_details.get(did, {})
        departments.append({
            "id": row["id"],
            "name": detail.get("name") or row["name"],
            "list_name": unescape(list_names.get(str(row["id"])) or ""),
            "abbr": row.get("abbr"),
            "short_name": None,
            "description": detail.get("description") or row.get("description"),
            "faqs": detail.get("faqs", []),
            "phone": detail.get("phone"),
            "phone_digits": detail.get("phone_digits"),
            "website": detail.get("website"),
            "more_contact": detail.get("more_contact"),
            "socials": socials_to_dicts(detail.get("socials")),
            "apps": detail.get("apps", []),
            # Upstream renders a 1x1 transparent data-URI placeholder when a
            # department has no logo; we render no image at all (identical look).
            "logo": None if (row.get("logo_url") or "").startswith("data:") else remap_image(detail.get("logo_url") or row.get("logo_url")),
            "last_updated": detail.get("last_updated"),
            "directory_rank": dept_dir_order.get(row["id"]),
            "topics": row.get("topics", []),
        })
    (SITE / "_seed_departments.py").write_text(
        HEADER + "DEPARTMENTS = " + py_literal(departments) + "\n",
        encoding="utf-8")
    print(f"_seed_departments.py: {len(departments)} rows")

    services_raw = load("service_details.json")
    service_topics = load("service_topics.json")
    # Upstream department pages list services in the CMS order captured there.
    dept_rank = {}
    for did, detail in load("department_details.json").items():
        for pos, svc in enumerate(detail.get("services", [])):
            dept_rank[svc["id"]] = pos
    services = []
    for key, svc in sorted(services_raw.items(), key=lambda kv: (kv[1]["dept_id"], kv[1]["id"])):
        topics = service_topics.get(str(svc["id"]), [])
        services.append({
            "id": svc["id"],
            "department_id": svc["dept_id"],
            "name": svc["name"],
            "description": svc.get("description"),
            "phone": svc.get("phone"),
            "phone_digits": svc.get("phone_digits"),
            "launch_url": svc.get("launch_url"),
            "contact_url": svc.get("contact_url"),
            "dept_website": svc.get("dept_website"),
            "image": remap_image(svc.get("image_url")),
            "last_updated": svc.get("last_updated"),
            "keywords": svc.get("keywords", []),
            "directory_rank": service_dir_order.get(svc["id"]),
            "dept_rank": dept_rank.get(svc["id"]),
            "topics": topics,
            "faqs": svc.get("faqs", []),
            "related": svc.get("related", []),
        })
    (SITE / "_seed_services.py").write_text(
        HEADER + "SERVICES = " + py_literal(services) + "\n",
        encoding="utf-8")
    print(f"_seed_services.py: {len(services)} rows")

    topics_raw = load("topics.json")
    landing_desc = load("topic_landing_desc.json")
    topics = []
    for slug, t in topics_raw.items():
        cards = []
        for c in t.get("cards", []):
            m = re.match(r"/departments/(\d+)/services/(\d+)/", c["service_url"])
            cards.append({
                "department_id": int(m.group(1)) if m else None,
                "service_id": int(m.group(2)) if m else None,
                "title": unescape(c["title"]),
                "blurb": unescape(c["blurb"]),
                "image": remap_image(c["image"]),
                "image_alt": unescape(c["image_alt"]),
            })
        topics.append({
            "slug": slug,
            "name": t["name"],
            "landing_description": landing_desc.get(slug),
            "description": t.get("description"),
            "description_html": t.get("description_html"),
            "lineart": remap_image(t.get("lineart")) or "images/lineart/topic3-lineart.svg",
            "cards": cards,
        })
    landing = load("landing.json")

    def service_ref(url):
        m = re.match(r"/departments/(\d+)/services/(\d+)/", url)
        return {"department_id": int(m.group(1)), "service_id": int(m.group(2))} if m else None

    popular_services = []
    for r in landing["popular_services"]:
        ref = service_ref(r["url"])
        if ref:
            popular_services.append({"service_id": ref["service_id"], "label": r["name"].strip()})
    homepage_services = []
    for r in landing["homepage_popular_services"]:
        ref = service_ref(r["url"])
        if ref:
            homepage_services.append({"service_id": ref["service_id"], "label": r["name"].strip()})

    def dept_ref(url):
        m = re.match(r"/departments/(\d+)/", url)
        return int(m.group(1)) if m else None

    popular_departments = [dept_ref(r["url"]) for r in landing["popular_departments"]]
    popular_departments = [d for d in popular_departments if d]

    (SITE / "_seed_topics.py").write_text(
        HEADER + "TOPICS = " + py_literal(topics) + "\n\n"
        "POPULAR_SERVICES = " + py_literal(popular_services) + "\n\n"
        "HOMEPAGE_SERVICES = " + py_literal(homepage_services) + "\n\n"
        "POPULAR_DEPARTMENTS = " + py_literal(popular_departments) + "\n",
        encoding="utf-8")
    print(f"_seed_topics.py: {len(topics)} topics, "
          f"{len(popular_services)} popular services, "
          f"{len(popular_departments)} popular departments")

    # The homepage "In the spotlight" list: exact upstream items (title,
    # long-form date, gov.ca.gov URL) parsed from the homepage capture.
    home_html = (SCRAPED / "home.html")
    news = []
    if home_html.exists():
        home = home_html.read_text(encoding="utf-8")
        block = re.search(r"In the spotlight</h2>(.*?)View all news", home, re.S)
        if block:
            items = re.findall(
                r'<a href="(https://www\.gov\.ca\.gov/[^"]+)"[^>]*>(.*?)</a>\s*</h3>\s*<p>([^<]+)</p>',
                re.sub(r"\s+", " ", block.group(1)))
            import html as _html
            for url, title, date in items:
                news.append({
                    "title": _html.unescape(re.sub(r"<[^>]+>", "", title)).strip(),
                    "display_date": date.strip(),
                    "source_url": url,
                    "excerpt": None,
                })
    (SITE / "_seed_content.py").write_text(
        HEADER + "NEWS = " + py_literal(news) + "\n",
        encoding="utf-8")
    print(f"_seed_content.py: {len(news)} news items")


if __name__ == "__main__":
    main()
