-- Full Bandcamp SQLite schema, including nullable fields, FKs and indexes.
-- Synthetic test data is inserted by make_task4_db; no runtime/seed writes.
CREATE TABLE album_tags (album_id INTEGER NOT NULL, tag_id INTEGER NOT NULL, PRIMARY KEY (album_id, tag_id), FOREIGN KEY(album_id) REFERENCES albums (id), FOREIGN KEY(tag_id) REFERENCES tags (id));
CREATE TABLE albums (id INTEGER NOT NULL, artist_id INTEGER NOT NULL, label_id INTEGER NOT NULL, primary_genre_id INTEGER NOT NULL, scene_id INTEGER NOT NULL, title VARCHAR(160) NOT NULL, slug VARCHAR(180) NOT NULL, description TEXT, story TEXT, cover_image VARCHAR(255), header_image VARCHAR(255), price FLOAT, release_date DATE NOT NULL, track_count INTEGER, duration_seconds INTEGER, fan_count INTEGER, catalog_no VARCHAR(40), is_featured BOOLEAN, is_new BOOLEAN, is_editorial BOOLEAN, PRIMARY KEY (id), FOREIGN KEY(artist_id) REFERENCES artists (id), FOREIGN KEY(label_id) REFERENCES labels (id), FOREIGN KEY(primary_genre_id) REFERENCES genres (id), FOREIGN KEY(scene_id) REFERENCES scenes (id));
CREATE TABLE artists (id INTEGER NOT NULL, name VARCHAR(140) NOT NULL, slug VARCHAR(160) NOT NULL, location VARCHAR(120), bio TEXT, headline VARCHAR(180), formed_year INTEGER, follow_count INTEGER, avatar_image VARCHAR(255), hero_image VARCHAR(255), scene_id INTEGER NOT NULL, label_id INTEGER NOT NULL, primary_genre_id INTEGER NOT NULL, PRIMARY KEY (id), FOREIGN KEY(scene_id) REFERENCES scenes (id), FOREIGN KEY(label_id) REFERENCES labels (id), FOREIGN KEY(primary_genre_id) REFERENCES genres (id));
CREATE TABLE cart_items (id INTEGER NOT NULL, user_id INTEGER NOT NULL, album_id INTEGER, merch_item_id INTEGER, format_variant_id INTEGER, quantity INTEGER, added_at DATETIME, PRIMARY KEY (id), FOREIGN KEY(user_id) REFERENCES users (id), FOREIGN KEY(album_id) REFERENCES albums (id), FOREIGN KEY(merch_item_id) REFERENCES merch_items (id), FOREIGN KEY(format_variant_id) REFERENCES format_variants (id));
CREATE TABLE fan_collection_items (id INTEGER NOT NULL, user_id INTEGER NOT NULL, album_id INTEGER NOT NULL, format_variant_id INTEGER, favorite_track_id INTEGER, acquired_via VARCHAR(80), notes VARCHAR(240), added_at DATETIME, PRIMARY KEY (id), FOREIGN KEY(user_id) REFERENCES users (id), FOREIGN KEY(album_id) REFERENCES albums (id), FOREIGN KEY(format_variant_id) REFERENCES format_variants (id), FOREIGN KEY(favorite_track_id) REFERENCES tracks (id));
CREATE TABLE fan_comments (id INTEGER NOT NULL, user_id INTEGER NOT NULL, album_id INTEGER, track_id INTEGER, headline VARCHAR(140), body TEXT, rating INTEGER, created_at DATETIME, PRIMARY KEY (id), FOREIGN KEY(user_id) REFERENCES users (id), FOREIGN KEY(album_id) REFERENCES albums (id), FOREIGN KEY(track_id) REFERENCES tracks (id));
CREATE TABLE format_variants (id INTEGER NOT NULL, album_id INTEGER, merch_item_id INTEGER, kind VARCHAR(50) NOT NULL, name VARCHAR(120) NOT NULL, option_a VARCHAR(80), option_b VARCHAR(80), price FLOAT, inventory INTEGER, sku VARCHAR(80) NOT NULL, shipping_note VARCHAR(160), edition_note VARCHAR(200), is_default BOOLEAN, PRIMARY KEY (id), FOREIGN KEY(album_id) REFERENCES albums (id), FOREIGN KEY(merch_item_id) REFERENCES merch_items (id), UNIQUE (sku));
CREATE TABLE genres (id INTEGER NOT NULL, name VARCHAR(60) NOT NULL, slug VARCHAR(80) NOT NULL, description TEXT, accent_color VARCHAR(20), PRIMARY KEY (id), UNIQUE (name));
CREATE TABLE labels (id INTEGER NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(120) NOT NULL, location VARCHAR(120), description TEXT, PRIMARY KEY (id), UNIQUE (name));
CREATE TABLE merch_items (id INTEGER NOT NULL, artist_id INTEGER NOT NULL, album_id INTEGER, title VARCHAR(160) NOT NULL, slug VARCHAR(180) NOT NULL, item_type VARCHAR(50), description TEXT, short_blurb VARCHAR(200), image VARCHAR(255), price FLOAT, inventory INTEGER, release_date DATE NOT NULL, is_featured BOOLEAN, PRIMARY KEY (id), FOREIGN KEY(artist_id) REFERENCES artists (id), FOREIGN KEY(album_id) REFERENCES albums (id));
CREATE TABLE order_items (id INTEGER NOT NULL, order_id INTEGER NOT NULL, album_id INTEGER, merch_item_id INTEGER, format_variant_id INTEGER, title VARCHAR(200) NOT NULL, artist_name VARCHAR(140), image_path VARCHAR(255), variant_label VARCHAR(160), quantity INTEGER, unit_price FLOAT, PRIMARY KEY (id), FOREIGN KEY(order_id) REFERENCES orders (id), FOREIGN KEY(album_id) REFERENCES albums (id), FOREIGN KEY(merch_item_id) REFERENCES merch_items (id), FOREIGN KEY(format_variant_id) REFERENCES format_variants (id));
CREATE TABLE orders (id INTEGER NOT NULL, user_id INTEGER NOT NULL, order_number VARCHAR(60) NOT NULL, status VARCHAR(40), subtotal FLOAT, shipping FLOAT, tax FLOAT, total FLOAT, shipping_name VARCHAR(140), shipping_line1 VARCHAR(200), shipping_city VARCHAR(120), shipping_country VARCHAR(120), payment_label VARCHAR(120), note VARCHAR(240), placed_at DATETIME, PRIMARY KEY (id), FOREIGN KEY(user_id) REFERENCES users (id), UNIQUE (order_number));
CREATE TABLE scenes (id INTEGER NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(120) NOT NULL, country VARCHAR(80), description TEXT, PRIMARY KEY (id), UNIQUE (name));
CREATE TABLE tags (id INTEGER NOT NULL, name VARCHAR(80) NOT NULL, slug VARCHAR(80) NOT NULL, PRIMARY KEY (id), UNIQUE (name));
CREATE TABLE tracks (id INTEGER NOT NULL, album_id INTEGER NOT NULL, title VARCHAR(160) NOT NULL, slug VARCHAR(180) NOT NULL, track_number INTEGER NOT NULL, duration_seconds INTEGER, preview_hook VARCHAR(255), lyrics_excerpt TEXT, is_focus_track BOOLEAN, PRIMARY KEY (id), FOREIGN KEY(album_id) REFERENCES albums (id));
CREATE TABLE users (id INTEGER NOT NULL, username VARCHAR(80) NOT NULL, email VARCHAR(120) NOT NULL, password_hash VARCHAR(255) NOT NULL, display_name VARCHAR(120) NOT NULL, bio TEXT, city VARCHAR(80), country VARCHAR(80), address_line1 VARCHAR(200), postal_code VARCHAR(30), favorite_format VARCHAR(40), favorite_scene_id INTEGER, created_at DATETIME, PRIMARY KEY (id), FOREIGN KEY(favorite_scene_id) REFERENCES scenes (id));
CREATE TABLE wishlist_items (id INTEGER NOT NULL, user_id INTEGER NOT NULL, album_id INTEGER, merch_item_id INTEGER, added_at DATETIME, PRIMARY KEY (id), FOREIGN KEY(user_id) REFERENCES users (id), FOREIGN KEY(album_id) REFERENCES albums (id), FOREIGN KEY(merch_item_id) REFERENCES merch_items (id));
CREATE UNIQUE INDEX ix_albums_slug ON albums (slug);
CREATE UNIQUE INDEX ix_artists_slug ON artists (slug);
CREATE UNIQUE INDEX ix_genres_slug ON genres (slug);
CREATE UNIQUE INDEX ix_labels_slug ON labels (slug);
CREATE UNIQUE INDEX ix_merch_items_slug ON merch_items (slug);
CREATE UNIQUE INDEX ix_scenes_slug ON scenes (slug);
CREATE UNIQUE INDEX ix_tags_slug ON tags (slug);
CREATE UNIQUE INDEX ix_tracks_slug ON tracks (slug);
CREATE UNIQUE INDEX ix_users_email ON users (email);
CREATE UNIQUE INDEX ix_users_username ON users (username);
