"""Per-task genuine trajectories, correct answers, wrong answers and expected gate
names for the accuweather verifier tests and for verify/tests/run_matrix.py."""
from __future__ import annotations

from _support import State, login_steps, step

def _s(*paths):
    out = [step("/")]
    out += [step(p) for p in paths[:-1]]
    out.append(step(paths[-1], "done"))
    return out

CASES = {
 0: dict(steps=_s("/search?q=Phoenix", "/weather/phoenix-az"),
         answer="Phoenix: temperature 104°F, RealFeel 115°F, humidity 18%.",
         gate="visited_weather_phoenix",
         wrong=[("temperature 115°F, RealFeel 104°F, humidity 18%", "answer_temperature"),
                ("Phoenix: 104°, RealFeel 115°, humidity 61%", "answer_humidity")],
         also_pass=["104° / RealFeel 115° / 18% humidity", "Temp: 104 F; Feels like 115 F; Humidity: 18 percent"]),
 1: dict(steps=_s("/search?q=Portland", "/weather/portland-me"),
         answer="Portland, Maine: Mostly cloudy, wind 8 mph, visibility 10 mi.",
         gate="searched_for_portland-me",
         wrong=[("Portland, Maine: Cloudy, wind 5 mph, visibility 10 mi.", "answer_condition"),
                ("Mostly cloudy, wind 10 mph, visibility 8 mi", "answer_wind")],
         also_pass=["mostly-cloudy; 8mph winds; 10 miles visibility"]),
 2: dict(steps=_s("/weather/seattle-wa", "/hourly/seattle-wa"),
         answer="4 PM — 69°, Showers (47% precipitation).",
         gate="visited_hourly_seattle",
         wrong=[("3 PM — 68°, Mostly cloudy (36%)", "answer_hour"), ("4 PM, 68°, Showers", "answer_temperature")],
         also_pass=["The first hour is 16:00 at 69 degrees with showers"]),
 3: dict(steps=_s("/weather/miami-fl", "/daily/miami-fl"),
         answer="Sat: high 86°, low 73°, Mostly cloudy (63% precipitation).",
         gate="visited_daily_miami",
         wrong=[("Fri: high 88°, low 74°, Partly sunny", "answer_day"), ("Sat: high 73°, low 86°, Mostly cloudy", "answer_high")],
         also_pass=["Saturday, 86°/73°, mostly cloudy"]),
 4: dict(steps=_s("/weather/austin-tx", "/", "/weather/denver-co"),
         answer="Austin RealFeel 103°, Denver RealFeel 82°; Denver feels cooler.",
         gate="visited_weather_austin",
         wrong=[("Austin RealFeel 103°, Denver RealFeel 82°; Austin feels cooler.", "answer_names_cooler_city"),
                ("Austin 82°, Denver 103°; Denver feels cooler.", "answer_austin_realfeel")],
         also_pass=["Austin: 103°F. Denver: 82°F. The cooler city is Denver.", "Denver (82°) feels cooler than Austin (103°)."]),
 5: dict(steps=_s("/search?q=Springfield", "/weather/springfield-mo", "/air-quality/springfield-mo"),
         answer="Postal code 65806; pressure 29.89 in; air quality 39.",
         gate="searched_for_springfield-mo",
         wrong=[("Postal code 62701; pressure 29.91 in; air quality 33.", "answer_postal_code"),
                ("65806, pressure 29.98 in, air quality 39", "answer_pressure")],
         also_pass=["ZIP 65806 / 29.89 inHg / AQI: 39"]),
 6: dict(steps=login_steps("alice.j@test.com") + [step("/search?q=Seattle"), step("/weather/seattle-wa"), step("/weather/seattle-wa"), step("/account", "done")],
         answer="Seattle is now listed in Saved Locations.", gate="visited_login_page", stateful=True,
         after=lambda s: s.add_saved("alice.j@test.com", "seattle-wa"), mismatch="saved_rows_added",
         wrong=[("Done.", "answer_mentions_seattle")]),
 7: dict(steps=login_steps("alice.j@test.com") + [step("/weather/boston-ma"), step("/weather/boston-ma"), step("/account", "done")],
         answer="Boston was removed and is no longer listed.", gate="visited_login_page", stateful=True,
         after=lambda s: s.remove_saved("alice.j@test.com", "boston-ma"), mismatch="saved_rows_removed",
         wrong=[("Removed.", "answer_mentions_boston")]),
 8: dict(steps=login_steps("bob.smith@test.com") + [step("/weather/chicago-il"), step("/alerts/chicago-il"), step("/alerts/chicago-il", "done")],
         answer="Enabled Severe weather and Rain starting soon for Chicago and saved.", gate="visited_login_page", stateful=True,
         after=lambda s: s.set_alerts("bob.smith@test.com", "chicago-il", ["severe", "rain"]), mismatch="alerts_exactly_severe_and_rain_for_chicago",
         wrong=[]),
 9: dict(steps=login_steps("carol.w@test.com") + [step("/settings"), step("/settings"), step("/weather/new-york-ny", "done")],
         answer="New York now shows 26° with RealFeel 28° in Celsius.", gate="visited_login_page", stateful=True,
         after=lambda s: s.set_unit("carol.w@test.com", "C"), mismatch="carol_unit_is_celsius",
         wrong=[("New York shows 79° with RealFeel 82°.", "answer_temperature_celsius"), ("temperature 28°C, RealFeel 26°C", "answer_temperature_celsius")]),
 10: dict(steps=_s("/search?q=94102", "/weather/san-francisco-ca"),
          answer="San Francisco: Cloudy, humidity 75%, pressure 30.05 in.",
          gate="searched_postal_code_94102",
          wrong=[("San Francisco: Mostly cloudy, humidity 75%, pressure 30.05 in.", "answer_condition"),
                 ("Cloudy, humidity 57%, pressure 30.05 in", "answer_humidity")],
          also_pass=["cloudy / 75 percent humidity / 30.05 inHg"]),
 11: dict(steps=_s("/search?q=New+Orleans", "/weather/new-orleans-la", "/radar/new-orleans-la", "/weather/new-orleans-la"),
          answer="Radar page is for New Orleans; current condition: Showers.",
          gate="searched_for_new-orleans-la",
          wrong=[("Radar confirmed; current condition: Cloudy.", "answer_condition")]),
 12: dict(steps=_s("/search?q=Los+Angeles", "/weather/los-angeles-ca", "/air-quality/los-angeles-ca", "/search?q=San+Francisco", "/weather/san-francisco-ca", "/air-quality/san-francisco-ca"),
          answer="Los Angeles 41, San Francisco 18 — San Francisco has better air quality.",
          gate="searched_for_los-angeles-ca",
          wrong=[("Los Angeles 41, San Francisco 18 — Los Angeles has better air quality.", "answer_names_better_city"),
                 ("Los Angeles 18, San Francisco 41 — San Francisco has better air quality.", "answer_los_angeles_value")],
          also_pass=["LA: 41. SF: 18. The city with better air quality is San Francisco."]),
 13: dict(steps=_s("/weather/boston-ma", "/daily/boston-ma"),
          answer="Sat: low 60°, high 73°, Mostly cloudy.",
          gate="visited_daily_boston",
          wrong=[("Fri: low 61°, high 75°, Partly sunny.", "answer_day"), ("Sat: low 61°, high 73°, Mostly cloudy.", "answer_low")],
          also_pass=["Saturday — 73°/60°, mostly cloudy"]),
 14: dict(steps=_s("/search?q=London", "/weather/london-gb", "/air-quality/london-gb"),
          answer="London: 63°, wind 10 mph, humidity 72%, air quality category Good.",
          gate="searched_for_london-gb",
          wrong=[("London: 63°, wind 10 mph, humidity 72%, air quality Moderate.", "answer_air_quality_category"),
                 ("London: 62°, wind 10 mph, humidity 72%, Good.", "answer_temperature")]),
 15: dict(steps=login_steps("david.b@test.com") + [step("/weather/phoenix-az"), step("/weather/phoenix-az"), step("/search?q=Miami"), step("/weather/miami-fl"), step("/weather/miami-fl"), step("/account", "done")],
          answer="Phoenix and Miami both appear in Saved Locations.", gate="visited_login_page", stateful=True,
          after=lambda s: (s.add_saved("david.b@test.com", "phoenix-az"), s.add_saved("david.b@test.com", "miami-fl")), mismatch="saved_rows_added",
          wrong=[("Phoenix is saved.", "answer_mentions_both_cities")]),
 16: dict(steps=_s("/search?q=Portland", "/weather/portland-or", "/search?q=Portland", "/weather/portland-me"),
          answer="Portland, Oregon 69°; Portland, Maine 70°. Maine is warmer.",
          gate="searched_for_portland-or",
          wrong=[("Portland, Oregon 69°; Portland, Maine 70°. Oregon is warmer.", "answer_names_warmer_city"),
                 ("Portland, Oregon 70°; Portland, Maine 69°. Maine is warmer.", "answer_oregon_temperature")],
          also_pass=["Oregon: 69°F, Maine: 70°F — Portland, Maine is the warmer one."]),
 17: dict(steps=_s("/search?q=Toronto", "/weather/toronto-ca", "/hourly/toronto-ca"),
          answer="Highest 73°, first at 4 PM, precipitation 64%.",
          gate="searched_for_toronto-ca",
          wrong=[("Highest 73°, first at 3 PM, precipitation 53%.", "answer_hour"), ("73° at 4 PM, precipitation 9%", "answer_precipitation")]),
 18: dict(steps=[step("/"), step("/login"), step("/register"), step("/register", "input", "Jamie Lee"), step("/register", "input", "jamie.lee@example.test"),
                 step("/register", "input", "Weather123!"), step("/register"), step("/account"), step("/search?q=Atlanta"), step("/weather/atlanta-ga"),
                 step("/weather/atlanta-ga"), step("/account", "done")],
          answer="Atlanta is shown in Saved Locations for the new Jamie Lee account.", gate="visited_register", stateful=True,
          after=lambda s: (s.add_user("jamie.lee@example.test", "Jamie Lee", "Weather123!"), s.add_saved("jamie.lee@example.test", "atlanta-ga")), mismatch="exactly_one_new_user",
          wrong=[("Account created.", "answer_mentions_atlanta")]),
 19: dict(steps=_s("/weather/phoenix-az", "/search?q=New+Orleans", "/weather/new-orleans-la"),
          answer="Phoenix: 104°, humidity 18%. New Orleans: 89°, humidity 75%. Phoenix has the higher heat index (RealFeel 115° vs 100°).",
          gate="searched_for_new-orleans-la",
          wrong=[("Phoenix: 104°, humidity 18%. New Orleans: 89°, humidity 75%. New Orleans has the higher heat index.", "answer_names_higher_heat_index_city"),
                 ("Phoenix: 104°, humidity 81%. New Orleans: 89°, humidity 75%. Phoenix is higher.", "answer_phoenix_humidity")]),
}
