#!/usr/bin/env python3
"""Validate the generated UC Berkeley image bundle (scene photography + avatars).

The 164 files ship through the pinned Hugging Face tarball: 82 FLUX.1 [schnell]
scene images at 1024x768 WebP and 82 deterministic Pillow initials avatars at
256x256 PNG, all declared in ``generated_asset_inventory.json``.

This checker enforces exact coverage (no missing, extra, stale or corrupt
file), extension/kind agreement, per-file size + SHA-256 equality against the
inventory, and a full decode of every file at its planned dimensions. It runs
in the Docker build and from ``scripts/check_assets.sh``, mirroring the
webmd_doctor / compass / walmart_careers asset gates.

An OCR pass over the scene images runs when ``pytesseract`` is importable and is
reported as untested otherwise. It is a *large-legible-text* detector, not a
"contains no text" detector — see ``scripts/IMAGE_PLAN.md`` §9.1 for the
calibration, including what it is known to miss.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path, PurePosixPath

SITE = Path(__file__).resolve().parent
# Committed test fixture: a frontal portrait generated by the same FLUX model
# with a deliberately face-forward prompt, used to prove the detector can fire.
# Not a real person's photograph.
FACE_CONTROL = SITE / "tests" / "face_control.png"
FACE_SCALE_FACTOR = 1.1
FACE_MIN_NEIGHBOURS = 10
FACE_MIN_SIZE = (40, 40)
# A provider can return a 16:9 frame inside a 4:3 canvas — black bars top and
# bottom that look wrong in a card. Three of the first 82 scenes came back that
# way, so it is a checked defect, not a surprise.
LETTERBOX_BAND = 0.02
LETTERBOX_DARK = 40

# kind -> (managed root, extension, (width, height))
KINDS = {
    "campus": ("static/images/campus", ".webp", (1024, 768)),
    "college": ("static/images/colleges", ".webp", (1024, 768)),
    "research": ("static/images/research", ".webp", (1024, 768)),
    "news": ("static/images/news", ".webp", (1024, 768)),
    "event": ("static/images/events", ".webp", (1024, 768)),
    "faculty": ("static/images/faculty", ".png", (256, 256)),
}
MANAGED_ROOTS = tuple(root for root, _suffix, _size in KINDS.values())
SCENE_ROOTS = tuple(root for kind, (root, _s, _z) in KINDS.items() if kind != "faculty")

# Large-legible-text gate (IMAGE_PLAN.md §9.1). Calibrated on the bundle: at
# (3 chars, confidence 40) clean scenes yield up to seven junk fragments, all of
# them three characters, so the floor sits at 4 chars / confidence 50.
OCR_MIN_LENGTH = 4
OCR_MIN_CONFIDENCE = 50
OCR_MAX_TOKENS = 2


def ocr_tokens(path: Path) -> list[str] | None:
    """Distinct alphabetic tokens at the calibrated floor; None when untestable.

    A large-legible-text detector, NOT a "contains no text" detector — see
    IMAGE_PLAN.md §9.1 for the calibration and its known blind spot.
    """
    try:
        import pytesseract
        from PIL import Image
    except ImportError:
        return None
    try:
        image = Image.open(path).convert("RGB")
        found: set[str] = set()
        for psm in (3, 11):
            try:
                data = pytesseract.image_to_data(
                    image, config=f"--psm {psm}", output_type=pytesseract.Output.DICT)
            except Exception:
                continue
            for index, raw in enumerate(data.get("text", [])):
                token = (raw or "").strip()
                if len(token) < OCR_MIN_LENGTH or not token.isalpha():
                    continue
                try:
                    confidence = float(data["conf"][index])
                except (TypeError, ValueError):
                    continue
                if confidence >= OCR_MIN_CONFIDENCE:
                    found.add(token.lower())
        return sorted(found)
    except Exception:
        return None


def letterboxed(path: Path) -> tuple[float, float] | None:
    """Mean brightness of the top and bottom bands; None when NumPy is absent.

    A frame is letterboxed when both bands are near-black, i.e. the provider
    drew a wider aspect inside the 4:3 canvas.
    """
    try:
        import numpy as np
        from PIL import Image
    except ImportError:
        return None
    try:
        with Image.open(path) as handle:
            handle.load()
            pixels = np.asarray(handle.convert("RGB")).astype(int)
        band = max(1, int(pixels.shape[0] * LETTERBOX_BAND))
        top = float(pixels[:band].mean())
        bottom = float(pixels[-band:].mean())
        return top, bottom
    except Exception:
        return None


def is_letterboxed(path: Path) -> bool | None:
    bands = letterboxed(path)
    if bands is None:
        return None
    top, bottom = bands
    return top < LETTERBOX_DARK and bottom < LETTERBOX_DARK


def detect_faces(path: Path) -> list[tuple[int, int, int, int]] | None:
    """Frontal-face boxes; None when OpenCV is unavailable.

    A coarse tripwire, not a person detector: calibrated to keep clean scenes at
    zero boxes, which also makes it miss small and profile faces — see
    IMAGE_PLAN.md §9.2 for the measured false-positive / false-negative trade-off.
    """
    try:
        import cv2
        import numpy as np
        from PIL import Image
    except ImportError:
        return None
    try:
        cascade = cv2.CascadeClassifier(
            Path(cv2.data.haarcascades) / "haarcascade_frontalface_default.xml")
        if cascade.empty():
            return None
        with Image.open(path) as handle:
            handle.load()
            grey = cv2.cvtColor(np.asarray(handle.convert("RGB")), cv2.COLOR_RGB2GRAY)
        return [(int(x), int(y), int(w), int(h))
                for (x, y, w, h) in cascade.detectMultiScale(
                    grey, scaleFactor=FACE_SCALE_FACTOR,
                    minNeighbors=FACE_MIN_NEIGHBOURS, minSize=FACE_MIN_SIZE)]
    except Exception:
        return None


def verify(ocr: bool = False) -> int:
    manifest = json.loads((SITE / "generated_asset_inventory.json").read_text())
    rows = manifest.get("assets")
    if manifest.get("schema_version") != 1 or not isinstance(rows, list):
        raise ValueError("unsupported generated asset inventory")
    if manifest.get("asset_count") != len(rows):
        raise ValueError("asset_count does not match the number of rows")

    expected: set[str] = set()
    for row in rows:
        kind = row.get("kind")
        if kind not in KINDS:
            raise ValueError(f"unknown generated asset kind: {kind!r}")
        root, suffix, _size = KINDS[kind]
        relative = PurePosixPath(row["path"])
        if (relative.is_absolute() or ".." in relative.parts
                or not row["path"].startswith(root + "/")
                or not row["path"].endswith(suffix)):
            raise ValueError(f"unsafe generated asset path: {row['path']!r}")
        if row["path"] in expected:
            raise ValueError(f"duplicate inventory path: {row['path']!r}")
        if not row.get("model"):
            raise ValueError(f"generated asset row lacks provenance: {row['path']!r}")
        if kind != "faculty" and not row.get("prompt"):
            raise ValueError(f"scene row lacks its prompt: {row['path']!r}")
        expected.add(row["path"])

    actual = {
        path.relative_to(SITE).as_posix()
        for root in MANAGED_ROOTS
        for path in (SITE / root).rglob("*")
        if path.is_file() and path.name != ".gitkeep"
    }
    if actual != expected:
        raise ValueError(
            "generated asset mismatch: "
            f"missing={sorted(expected - actual)[:5]} extra={sorted(actual - expected)[:5]}"
        )

    try:
        from PIL import Image  # optional: full decode only where Pillow exists
    except ImportError:
        Image = None

    for row in rows:
        path = SITE / row["path"]
        data = path.read_bytes()
        if len(data) != row["bytes"] or hashlib.sha256(data).hexdigest() != row["sha256"]:
            raise ValueError(f"generated asset hash mismatch: {row['path']}")
        _root, _suffix, size = KINDS[row["kind"]]
        if Image is not None:
            with Image.open(path) as image:
                image.load()
                if image.size != size:
                    raise ValueError(
                        f"wrong dimensions for {row['path']}: {image.size} != {size}")
        if row["kind"] != "faculty" and is_letterboxed(path):
            raise ValueError(f"letterboxed frame (black bars top and bottom): {row['path']}")
        elif not data.startswith(b"\x89PNG\r\n\x1a\n") and data[:4] != b"RIFF":
            raise ValueError(f"unrecognised image signature: {row['path']}")

    if ocr:
        checked = 0
        missed: list[str] = []
        for row in rows:
            if row["kind"] == "faculty":
                continue
            tokens = ocr_tokens(SITE / row["path"])
            if tokens is None:
                print("[check] ocr: not tested (pytesseract or its binary is absent)")
                break
            checked += 1
            if len(tokens) > OCR_MAX_TOKENS:
                missed.append(f"{row['path']} ({len(tokens)} tokens: {tokens[:4]})")
        else:
            if missed:
                raise ValueError("legible text detected in generated scenes: "
                                 + "; ".join(missed[:5]))
            print(f"[check] ocr: {checked} scene(s) checked, no large legible text")
    return len(rows)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ocr", action="store_true",
                        help="also run the OCR pass (slow: ~10 min over 82 scenes; the "
                             "build gate leaves it off and tests/test_generated_assets.py "
                             "is where it runs)")
    args = parser.parse_args()
    count = verify(ocr=args.ocr)
    if not args.ocr:
        print("[check] ocr: skipped by default (pass --ocr to run it; the permanent "
              "pass lives in tests/test_generated_assets.py)")
    print(f"[check] verified {count} generated UC Berkeley assets")
