"""Tracked snapshot — captured from flightaware.com on 2026-09-22 (live pages)."""

STATS = {
    "delays": [
        {
            "airport_label": "Manchester (MAN / EGCC)",
            "airport_code": "MAN / EGCC",
            "dep_delay_text": "departure delays an average of 50 minutes (and decreasing)",
            "arr_delay_text": "arrival delays for airborne aircraft an average of 1 hours (and increasing)",
        },
        {
            "airport_label": "Boston Logan Intl (KBOS)",
            "airport_code": "KBOS",
            "dep_delay_text": "",
            "arr_delay_text": "inbound flights delayed at their origin an average of 25 minutes.",
        },
        {
            "airport_label": "Auckland (AKL / NZAA)",
            "airport_code": "AKL / NZAA",
            "dep_delay_text": "",
            "arr_delay_text": "arrival delays for airborne aircraft an average of 29 minutes (and increasing)",
        },
        {
            "airport_label": "São Paulo-Guarulhos Int'l (GRU / SBGR)",
            "airport_code": "GRU / SBGR",
            "dep_delay_text": "departure delays an average of 38 minutes (and decreasing)",
            "arr_delay_text": "arrival delays for airborne aircraft an average of 35 minutes (and decreasing)",
        },
    ],
    "cancel_airline": [
        {
            "scope": "airline",
            "label": "PSA Airlines (AAL)",
            "cancelled": 54,
            "cancelled_pct": "7%",
            "delayed": 27,
            "delayed_pct": "3%",
        },
        {
            "scope": "airline",
            "label": "United",
            "cancelled": 46,
            "cancelled_pct": "1%",
            "delayed": 80,
            "delayed_pct": "2%",
        },
        {
            "scope": "airline",
            "label": "Ryanair",
            "cancelled": 36,
            "cancelled_pct": "1%",
            "delayed": 299,
            "delayed_pct": "9%",
        },
        {
            "scope": "airline",
            "label": "Azul Brazilian Airlines",
            "cancelled": 29,
            "cancelled_pct": "3%",
            "delayed": 92,
            "delayed_pct": "11%",
        },
        {
            "scope": "airline",
            "label": "American Airlines",
            "cancelled": 25,
            "cancelled_pct": "0%",
            "delayed": 107,
            "delayed_pct": "3%",
        },
        {
            "scope": "airline",
            "label": "GOL Linhas Aéreas Inteligentes",
            "cancelled": 23,
            "cancelled_pct": "3%",
            "delayed": 39,
            "delayed_pct": "5%",
        },
        {
            "scope": "airline",
            "label": "Batik Air",
            "cancelled": 21,
            "cancelled_pct": "6%",
            "delayed": 40,
            "delayed_pct": "12%",
        },
        {
            "scope": "airline",
            "label": "China Eastern",
            "cancelled": 20,
            "cancelled_pct": "0%",
            "delayed": 254,
            "delayed_pct": "10%",
        },
        {
            "scope": "airline",
            "label": "Air China",
            "cancelled": 16,
            "cancelled_pct": "0%",
            "delayed": 102,
            "delayed_pct": "5%",
        },
        {
            "scope": "airline",
            "label": "Citilink",
            "cancelled": 15,
            "cancelled_pct": "5%",
            "delayed": 31,
            "delayed_pct": "11%",
        },
        {
            "scope": "airline",
            "label": "interCaribbean Airways",
            "cancelled": 15,
            "cancelled_pct": "23%",
            "delayed": 23,
            "delayed_pct": "35%",
        },
        {
            "scope": "airline",
            "label": "Tradewind",
            "cancelled": 12,
            "cancelled_pct": "9%",
            "delayed": 0,
            "delayed_pct": "0%",
        },
        {
            "scope": "airline",
            "label": "Air India",
            "cancelled": 11,
            "cancelled_pct": "1%",
            "delayed": 34,
            "delayed_pct": "5%",
        },
        {
            "scope": "airline",
            "label": "Alaska Airlines",
            "cancelled": 10,
            "cancelled_pct": "1%",
            "delayed": 14,
            "delayed_pct": "1%",
        },
        {
            "scope": "airline",
            "label": "KLM",
            "cancelled": 9,
            "cancelled_pct": "1%",
            "delayed": 119,
            "delayed_pct": "16%",
        },
        {
            "scope": "airline",
            "label": "Saudia",
            "cancelled": 9,
            "cancelled_pct": "1%",
            "delayed": 36,
            "delayed_pct": "6%",
        },
        {
            "scope": "airline",
            "label": "Endeavor Air (DAL)",
            "cancelled": 8,
            "cancelled_pct": "1%",
            "delayed": 40,
            "delayed_pct": "5%",
        },
        {
            "scope": "airline",
            "label": "Brussels Airlines",
            "cancelled": 8,
            "cancelled_pct": "3%",
            "delayed": 26,
            "delayed_pct": "11%",
        },
        {
            "scope": "airline",
            "label": "Sichuan Airlines",
            "cancelled": 7,
            "cancelled_pct": "0%",
            "delayed": 89,
            "delayed_pct": "12%",
        },
        {
            "scope": "airline",
            "label": "Virgin Australia",
            "cancelled": 7,
            "cancelled_pct": "1%",
            "delayed": 67,
            "delayed_pct": "13%",
        },
        {
            "scope": "airline",
            "label": "Shenzhen Airlines",
            "cancelled": 6,
            "cancelled_pct": "0%",
            "delayed": 109,
            "delayed_pct": "14%",
        },
        {
            "scope": "airline",
            "label": "LATAM Brasil",
            "cancelled": 6,
            "cancelled_pct": "0%",
            "delayed": 69,
            "delayed_pct": "8%",
        },
        {
            "scope": "airline",
            "label": "SpiceJet",
            "cancelled": 6,
            "cancelled_pct": "10%",
            "delayed": 26,
            "delayed_pct": "44%",
        },
        {
            "scope": "airline",
            "label": "Air Canada",
            "cancelled": 6,
            "cancelled_pct": "1%",
            "delayed": 18,
            "delayed_pct": "3%",
        },
        {
            "scope": "airline",
            "label": "Lam - Linhas Aereas de Mocambique",
            "cancelled": 6,
            "cancelled_pct": "14%",
            "delayed": 6,
            "delayed_pct": "14%",
        },
        {
            "scope": "airline",
            "label": "Jazz (ACA)",
            "cancelled": 6,
            "cancelled_pct": "1%",
            "delayed": 5,
            "delayed_pct": "1%",
        },
        {
            "scope": "airline",
            "label": "AirAsia",
            "cancelled": 5,
            "cancelled_pct": "1%",
            "delayed": 63,
            "delayed_pct": "13%",
        },
        {
            "scope": "airline",
            "label": "Delta Air Lines",
            "cancelled": 4,
            "cancelled_pct": "0%",
            "delayed": 168,
            "delayed_pct": "5%",
        },
        {
            "scope": "airline",
            "label": "Vietnam Airlines",
            "cancelled": 4,
            "cancelled_pct": "1%",
            "delayed": 83,
            "delayed_pct": "23%",
        },
        {
            "scope": "airline",
            "label": "Tianjin Airlines",
            "cancelled": 4,
            "cancelled_pct": "1%",
            "delayed": 38,
            "delayed_pct": "11%",
        },
        {
            "scope": "airline",
            "label": "Republic",
            "cancelled": 4,
            "cancelled_pct": "0%",
            "delayed": 16,
            "delayed_pct": "1%",
        },
        {
            "scope": "airline",
            "label": "Avianca",
            "cancelled": 4,
            "cancelled_pct": "0%",
            "delayed": 3,
            "delayed_pct": "0%",
        },
        {
            "scope": "airline",
            "label": "Bahamasair",
            "cancelled": 4,
            "cancelled_pct": "8%",
            "delayed": 1,
            "delayed_pct": "2%",
        },
        {
            "scope": "airline",
            "label": "Azul Conecta",
            "cancelled": 4,
            "cancelled_pct": "10%",
            "delayed": 1,
            "delayed_pct": "2%",
        },
        {
            "scope": "airline",
            "label": "Air Tahiti",
            "cancelled": 4,
            "cancelled_pct": "5%",
            "delayed": 0,
            "delayed_pct": "0%",
        },
        {
            "scope": "airline",
            "label": "ANA Wings",
            "cancelled": 3,
            "cancelled_pct": "0%",
            "delayed": 72,
            "delayed_pct": "20%",
        },
        {
            "scope": "airline",
            "label": "British Airways",
            "cancelled": 3,
            "cancelled_pct": "0%",
            "delayed": 64,
            "delayed_pct": "9%",
        },
        {
            "scope": "airline",
            "label": "JetBlue",
            "cancelled": 3,
            "cancelled_pct": "0%",
            "delayed": 40,
            "delayed_pct": "5%",
        },
        {
            "scope": "airline",
            "label": "PAL Express",
            "cancelled": 3,
            "cancelled_pct": "2%",
            "delayed": 36,
            "delayed_pct": "24%",
        },
        {
            "scope": "airline",
            "label": "SAS",
            "cancelled": 3,
            "cancelled_pct": "0%",
            "delayed": 32,
            "delayed_pct": "4%",
        },
        {
            "scope": "airline",
            "label": "Air Arabia",
            "cancelled": 3,
            "cancelled_pct": "1%",
            "delayed": 15,
            "delayed_pct": "6%",
        },
        {
            "scope": "airline",
            "label": "Porter Airlines",
            "cancelled": 3,
            "cancelled_pct": "1%",
            "delayed": 6,
            "delayed_pct": "2%",
        },
        {
            "scope": "airline",
            "label": "Akasa Air",
            "cancelled": 3,
            "cancelled_pct": "1%",
            "delayed": 5,
            "delayed_pct": "3%",
        },
        {
            "scope": "airline",
            "label": "Royal Jordanian",
            "cancelled": 3,
            "cancelled_pct": "2%",
            "delayed": 3,
            "delayed_pct": "2%",
        },
        {
            "scope": "airline",
            "label": "Solomon Airlines",
            "cancelled": 3,
            "cancelled_pct": "27%",
            "delayed": 0,
            "delayed_pct": "0%",
        },
        {
            "scope": "airline",
            "label": "easyJet",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 371,
            "delayed_pct": "20%",
        },
        {
            "scope": "airline",
            "label": "China Southern Airlines",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 275,
            "delayed_pct": "11%",
        },
        {
            "scope": "airline",
            "label": "XiamenAir",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 76,
            "delayed_pct": "11%",
        },
        {
            "scope": "airline",
            "label": "Air New Zealand",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 48,
            "delayed_pct": "10%",
        },
        {
            "scope": "airline",
            "label": "UTair",
            "cancelled": 2,
            "cancelled_pct": "2%",
            "delayed": 41,
            "delayed_pct": "47%",
        },
        {
            "scope": "airline",
            "label": "FlyDubai",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 29,
            "delayed_pct": "10%",
        },
        {
            "scope": "airline",
            "label": "VivaAerobus",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 9,
            "delayed_pct": "2%",
        },
        {
            "scope": "airline",
            "label": "Edelweiss Air AG",
            "cancelled": 2,
            "cancelled_pct": "2%",
            "delayed": 8,
            "delayed_pct": "10%",
        },
        {
            "scope": "airline",
            "label": "Belavia",
            "cancelled": 2,
            "cancelled_pct": "3%",
            "delayed": 4,
            "delayed_pct": "7%",
        },
        {
            "scope": "airline",
            "label": "Airnorth Regional",
            "cancelled": 2,
            "cancelled_pct": "4%",
            "delayed": 4,
            "delayed_pct": "8%",
        },
        {
            "scope": "airline",
            "label": "Cityjet",
            "cancelled": 2,
            "cancelled_pct": "2%",
            "delayed": 3,
            "delayed_pct": "3%",
        },
        {
            "scope": "airline",
            "label": "LATAM Peru",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 2,
            "delayed_pct": "0%",
        },
        {
            "scope": "airline",
            "label": "Arik Air",
            "cancelled": 2,
            "cancelled_pct": "18%",
            "delayed": 0,
            "delayed_pct": "0%",
        },
        {
            "scope": "airline",
            "label": "Jetstar",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 97,
            "delayed_pct": "23%",
        },
        {
            "scope": "airline",
            "label": "Southwest",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 83,
            "delayed_pct": "2%",
        },
        {
            "scope": "airline",
            "label": "China Express Airlines",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 70,
            "delayed_pct": "16%",
        },
        {
            "scope": "airline",
            "label": "Air France",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 58,
            "delayed_pct": "9%",
        },
        {
            "scope": "airline",
            "label": "Aegean Airlines",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 55,
            "delayed_pct": "19%",
        },
        {
            "scope": "airline",
            "label": "Qantas",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 54,
            "delayed_pct": "10%",
        },
        {
            "scope": "airline",
            "label": "Hainan Airlines",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 51,
            "delayed_pct": "7%",
        },
        {
            "scope": "airline",
            "label": "Mandarin",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 36,
            "delayed_pct": "34%",
        },
        {
            "scope": "airline",
            "label": "9 Air",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 35,
            "delayed_pct": "22%",
        },
        {
            "scope": "airline",
            "label": "QantasLink",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 34,
            "delayed_pct": "15%",
        },
        {
            "scope": "airline",
            "label": "SkyWest",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 32,
            "delayed_pct": "1%",
        },
        {
            "scope": "airline",
            "label": "BA CityFlyer",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 32,
            "delayed_pct": "28%",
        },
        {
            "scope": "airline",
            "label": "Lion Air",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 26,
            "delayed_pct": "7%",
        },
        {
            "scope": "airline",
            "label": "Garuda Indonesia",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 23,
            "delayed_pct": "9%",
        },
        {
            "scope": "airline",
            "label": "Israir",
            "cancelled": 1,
            "cancelled_pct": "1%",
            "delayed": 23,
            "delayed_pct": "28%",
        },
        {
            "scope": "airline",
            "label": "El Al",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 22,
            "delayed_pct": "13%",
        },
        {
            "scope": "airline",
            "label": "Suparna",
            "cancelled": 1,
            "cancelled_pct": "1%",
            "delayed": 9,
            "delayed_pct": "11%",
        },
        {
            "scope": "airline",
            "label": "MAI",
            "cancelled": 1,
            "cancelled_pct": "1%",
            "delayed": 9,
            "delayed_pct": "13%",
        },
        {
            "scope": "airline",
            "label": "Airblue",
            "cancelled": 1,
            "cancelled_pct": "2%",
            "delayed": 6,
            "delayed_pct": "17%",
        },
        {
            "scope": "airline",
            "label": "ASKY Airlines",
            "cancelled": 1,
            "cancelled_pct": "1%",
            "delayed": 4,
            "delayed_pct": "7%",
        },
        {
            "scope": "airline",
            "label": "Copa Airlines",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 2,
            "delayed_pct": "0%",
        },
        {
            "scope": "airline",
            "label": "Himalaya Airlines",
            "cancelled": 1,
            "cancelled_pct": "10%",
            "delayed": 2,
            "delayed_pct": "20%",
        },
        {
            "scope": "airline",
            "label": "South African Airways",
            "cancelled": 1,
            "cancelled_pct": "1%",
            "delayed": 1,
            "delayed_pct": "1%",
        },
        {
            "scope": "airline",
            "label": "RwandAir",
            "cancelled": 1,
            "cancelled_pct": "3%",
            "delayed": 1,
            "delayed_pct": "3%",
        },
        {
            "scope": "airline",
            "label": "CAA",
            "cancelled": 1,
            "cancelled_pct": "33%",
            "delayed": 0,
            "delayed_pct": "0%",
        },
    ],
    "cancel_origin": [
        {
            "scope": "origin",
            "label": "Newark Liberty Intl (EWR)",
            "cancelled": 22,
            "cancelled_pct": "4%",
            "delayed": 18,
            "delayed_pct": "3%",
        },
        {
            "scope": "origin",
            "label": "Jakarta-Soekarno-Hatta Int'l (CGK)",
            "cancelled": 18,
            "cancelled_pct": "2%",
            "delayed": 66,
            "delayed_pct": "10%",
        },
        {
            "scope": "origin",
            "label": "Brussels South Charleroi (CRL)",
            "cancelled": 17,
            "cancelled_pct": "14%",
            "delayed": 21,
            "delayed_pct": "17%",
        },
        {
            "scope": "origin",
            "label": "Viracopos Int'l (VCP)",
            "cancelled": 13,
            "cancelled_pct": "7%",
            "delayed": 30,
            "delayed_pct": "17%",
        },
        {
            "scope": "origin",
            "label": "Philadelphia Intl (PHL)",
            "cancelled": 8,
            "cancelled_pct": "1%",
            "delayed": 15,
            "delayed_pct": "3%",
        },
        {
            "scope": "origin",
            "label": "São Paulo-Congonhas (CGH)",
            "cancelled": 8,
            "cancelled_pct": "2%",
            "delayed": 13,
            "delayed_pct": "4%",
        },
        {
            "scope": "origin",
            "label": "São Paulo-Guarulhos Int'l (GRU)",
            "cancelled": 6,
            "cancelled_pct": "1%",
            "delayed": 45,
            "delayed_pct": "11%",
        },
        {
            "scope": "origin",
            "label": "Dallas-Fort Worth Intl (DFW)",
            "cancelled": 6,
            "cancelled_pct": "0%",
            "delayed": 27,
            "delayed_pct": "2%",
        },
        {
            "scope": "origin",
            "label": "King Abdulaziz Int'l (JED)",
            "cancelled": 6,
            "cancelled_pct": "1%",
            "delayed": 27,
            "delayed_pct": "6%",
        },
        {
            "scope": "origin",
            "label": "Santos Dumont Regional (SDU)",
            "cancelled": 6,
            "cancelled_pct": "6%",
            "delayed": 7,
            "delayed_pct": "7%",
        },
        {
            "scope": "origin",
            "label": "Amsterdam Schiphol (AMS)",
            "cancelled": 5,
            "cancelled_pct": "0%",
            "delayed": 127,
            "delayed_pct": "17%",
        },
        {
            "scope": "origin",
            "label": "Shanghai Pudong Int'l (PVG)",
            "cancelled": 5,
            "cancelled_pct": "0%",
            "delayed": 64,
            "delayed_pct": "7%",
        },
        {
            "scope": "origin",
            "label": "Kunming Changshui Int'l (KMG)",
            "cancelled": 5,
            "cancelled_pct": "1%",
            "delayed": 52,
            "delayed_pct": "12%",
        },
        {
            "scope": "origin",
            "label": "Dubai Int'l (DXB)",
            "cancelled": 5,
            "cancelled_pct": "1%",
            "delayed": 32,
            "delayed_pct": "6%",
        },
        {
            "scope": "origin",
            "label": "Raleigh-Durham Intl (RDU)",
            "cancelled": 5,
            "cancelled_pct": "2%",
            "delayed": 8,
            "delayed_pct": "3%",
        },
        {
            "scope": "origin",
            "label": "Teterboro (TEB)",
            "cancelled": 5,
            "cancelled_pct": "1%",
            "delayed": 1,
            "delayed_pct": "0%",
        },
        {
            "scope": "origin",
            "label": "Nantucket Meml (ACK)",
            "cancelled": 5,
            "cancelled_pct": "4%",
            "delayed": 0,
            "delayed_pct": "0%",
        },
        {
            "scope": "origin",
            "label": "Chongqing Jiangbei Int'l (CKG)",
            "cancelled": 4,
            "cancelled_pct": "0%",
            "delayed": 66,
            "delayed_pct": "14%",
        },
        {
            "scope": "origin",
            "label": "Beijing Capital Int'l (PEK)",
            "cancelled": 4,
            "cancelled_pct": "0%",
            "delayed": 50,
            "delayed_pct": "7%",
        },
        {
            "scope": "origin",
            "label": "Chengdu Tianfu Int'l (TFU)",
            "cancelled": 4,
            "cancelled_pct": "0%",
            "delayed": 50,
            "delayed_pct": "9%",
        },
        {
            "scope": "origin",
            "label": "Indira Gandhi Int'l (DEL)",
            "cancelled": 4,
            "cancelled_pct": "0%",
            "delayed": 46,
            "delayed_pct": "7%",
        },
        {
            "scope": "origin",
            "label": "Melbourne Tullamarine (MEL)",
            "cancelled": 4,
            "cancelled_pct": "1%",
            "delayed": 46,
            "delayed_pct": "12%",
        },
        {
            "scope": "origin",
            "label": "Charlotte/Douglas Intl (CLT)",
            "cancelled": 4,
            "cancelled_pct": "0%",
            "delayed": 25,
            "delayed_pct": "3%",
        },
        {
            "scope": "origin",
            "label": "Chatrapati Shivaji Int'l (BOM)",
            "cancelled": 4,
            "cancelled_pct": "0%",
            "delayed": 13,
            "delayed_pct": "3%",
        },
        {
            "scope": "origin",
            "label": "Vancouver Int'l (YVR)",
            "cancelled": 4,
            "cancelled_pct": "1%",
            "delayed": 3,
            "delayed_pct": "0%",
        },
        {
            "scope": "origin",
            "label": "Afonso Pena Int'l (CWB)",
            "cancelled": 4,
            "cancelled_pct": "4%",
            "delayed": 3,
            "delayed_pct": "3%",
        },
        {
            "scope": "origin",
            "label": "Patrick Leahy Burlington Intl (BTV)",
            "cancelled": 4,
            "cancelled_pct": "6%",
            "delayed": 2,
            "delayed_pct": "3%",
        },
        {
            "scope": "origin",
            "label": "Hartsfield-Jackson Intl (ATL)",
            "cancelled": 3,
            "cancelled_pct": "0%",
            "delayed": 90,
            "delayed_pct": "8%",
        },
        {
            "scope": "origin",
            "label": "Adolfo Suárez Madrid-Barajas (MAD)",
            "cancelled": 3,
            "cancelled_pct": "0%",
            "delayed": 53,
            "delayed_pct": "8%",
        },
        {
            "scope": "origin",
            "label": "Leonardo da Vinci Int'l (Fiumicino Int'l) (FCO)",
            "cancelled": 3,
            "cancelled_pct": "0%",
            "delayed": 47,
            "delayed_pct": "8%",
        },
        {
            "scope": "origin",
            "label": "Zurich (Kloten) (ZRH)",
            "cancelled": 3,
            "cancelled_pct": "0%",
            "delayed": 33,
            "delayed_pct": "8%",
        },
        {
            "scope": "origin",
            "label": "Hangzhou Xiaoshan Int'l (HGH)",
            "cancelled": 3,
            "cancelled_pct": "0%",
            "delayed": 31,
            "delayed_pct": "6%",
        },
        {
            "scope": "origin",
            "label": "Nanjing Lukou Int'l (NKG)",
            "cancelled": 3,
            "cancelled_pct": "0%",
            "delayed": 29,
            "delayed_pct": "8%",
        },
        {
            "scope": "origin",
            "label": "King Khalid Int'l (RUH)",
            "cancelled": 3,
            "cancelled_pct": "0%",
            "delayed": 28,
            "delayed_pct": "6%",
        },
        {
            "scope": "origin",
            "label": "Brussels (BRU)",
            "cancelled": 3,
            "cancelled_pct": "1%",
            "delayed": 28,
            "delayed_pct": "10%",
        },
        {
            "scope": "origin",
            "label": "Ngurah Rai/Bali Intl (DPS)",
            "cancelled": 3,
            "cancelled_pct": "1%",
            "delayed": 26,
            "delayed_pct": "12%",
        },
        {
            "scope": "origin",
            "label": "Juanda Int'l (SUB)",
            "cancelled": 3,
            "cancelled_pct": "1%",
            "delayed": 15,
            "delayed_pct": "9%",
        },
        {
            "scope": "origin",
            "label": "Washington Dulles Intl (IAD)",
            "cancelled": 3,
            "cancelled_pct": "0%",
            "delayed": 13,
            "delayed_pct": "2%",
        },
        {
            "scope": "origin",
            "label": "Anchorage Intl (ANC)",
            "cancelled": 3,
            "cancelled_pct": "1%",
            "delayed": 10,
            "delayed_pct": "3%",
        },
        {
            "scope": "origin",
            "label": "Dubrovnik (DBV)",
            "cancelled": 3,
            "cancelled_pct": "5%",
            "delayed": 10,
            "delayed_pct": "17%",
        },
        {
            "scope": "origin",
            "label": "Sultan Hasanuddin Int'l (UPG)",
            "cancelled": 3,
            "cancelled_pct": "1%",
            "delayed": 9,
            "delayed_pct": "4%",
        },
        {
            "scope": "origin",
            "label": "Grantley Adams Int'l (BGI)",
            "cancelled": 3,
            "cancelled_pct": "8%",
            "delayed": 7,
            "delayed_pct": "20%",
        },
        {
            "scope": "origin",
            "label": "El Dorado Int'l (BOG)",
            "cancelled": 3,
            "cancelled_pct": "0%",
            "delayed": 5,
            "delayed_pct": "0%",
        },
        {
            "scope": "origin",
            "label": "Montreal-Trudeau (YUL)",
            "cancelled": 3,
            "cancelled_pct": "1%",
            "delayed": 5,
            "delayed_pct": "1%",
        },
        {
            "scope": "origin",
            "label": "Fort Lauderdale Intl (FLL)",
            "cancelled": 3,
            "cancelled_pct": "1%",
            "delayed": 5,
            "delayed_pct": "1%",
        },
        {
            "scope": "origin",
            "label": "Westchester County (HPN)",
            "cancelled": 3,
            "cancelled_pct": "1%",
            "delayed": 3,
            "delayed_pct": "1%",
        },
        {
            "scope": "origin",
            "label": "Birmingham-Shuttlesworth Intl (BHM)",
            "cancelled": 3,
            "cancelled_pct": "2%",
            "delayed": 3,
            "delayed_pct": "2%",
        },
        {
            "scope": "origin",
            "label": "Maputo Int'l (MPM)",
            "cancelled": 3,
            "cancelled_pct": "12%",
            "delayed": 2,
            "delayed_pct": "8%",
        },
        {
            "scope": "origin",
            "label": "Tokyo Int'l (Haneda) (HND)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 249,
            "delayed_pct": "35%",
        },
        {
            "scope": "origin",
            "label": "Narita Int'l (NRT)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 94,
            "delayed_pct": "24%",
        },
        {
            "scope": "origin",
            "label": "Tan Son Nhat Int'l (SGN)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 89,
            "delayed_pct": "23%",
        },
        {
            "scope": "origin",
            "label": "Charles de Gaulle/Roissy (CDG)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 75,
            "delayed_pct": "11%",
        },
        {
            "scope": "origin",
            "label": "Palma de Mallorca (or Son Sant Joan) (PMI)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 71,
            "delayed_pct": "15%",
        },
        {
            "scope": "origin",
            "label": "London Heathrow (LHR)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 66,
            "delayed_pct": "9%",
        },
        {
            "scope": "origin",
            "label": "Chengdu Shuangliu Int'l (CTU)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 34,
            "delayed_pct": "9%",
        },
        {
            "scope": "origin",
            "label": "Dublin Int'l (DUB)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 32,
            "delayed_pct": "8%",
        },
        {
            "scope": "origin",
            "label": "Xiamen Gaoqi Int'l (XMN)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 29,
            "delayed_pct": "10%",
        },
        {
            "scope": "origin",
            "label": "John F Kennedy Intl (JFK)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 22,
            "delayed_pct": "3%",
        },
        {
            "scope": "origin",
            "label": "Porto / Oporto (OPO)",
            "cancelled": 2,
            "cancelled_pct": "1%",
            "delayed": 19,
            "delayed_pct": "11%",
        },
        {
            "scope": "origin",
            "label": "Hefei Xinqiao Airport (HFE)",
            "cancelled": 2,
            "cancelled_pct": "1%",
            "delayed": 17,
            "delayed_pct": "13%",
        },
        {
            "scope": "origin",
            "label": "Reagan National (DCA)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 16,
            "delayed_pct": "3%",
        },
        {
            "scope": "origin",
            "label": "LaGuardia (LGA)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 15,
            "delayed_pct": "2%",
        },
        {
            "scope": "origin",
            "label": "Oslo, Gardermoen (OSL)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 15,
            "delayed_pct": "4%",
        },
        {
            "scope": "origin",
            "label": "Changsha Huanghua Int'l (CSX)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 13,
            "delayed_pct": "4%",
        },
        {
            "scope": "origin",
            "label": "Rinas Mother Teresa (TIA)",
            "cancelled": 2,
            "cancelled_pct": "1%",
            "delayed": 13,
            "delayed_pct": "9%",
        },
        {
            "scope": "origin",
            "label": "Nashville Intl (BNA)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 10,
            "delayed_pct": "2%",
        },
        {
            "scope": "origin",
            "label": "Denver Intl (DEN)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 9,
            "delayed_pct": "0%",
        },
        {
            "scope": "origin",
            "label": "Orlando Intl (MCO)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 9,
            "delayed_pct": "2%",
        },
        {
            "scope": "origin",
            "label": "Wuhan Tianhe (WUH)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 9,
            "delayed_pct": "3%",
        },
        {
            "scope": "origin",
            "label": "Tancredo Neves Int'l (CNF)",
            "cancelled": 2,
            "cancelled_pct": "1%",
            "delayed": 9,
            "delayed_pct": "5%",
        },
        {
            "scope": "origin",
            "label": "Toronto Pearson Int'l (YYZ)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 8,
            "delayed_pct": "1%",
        },
        {
            "scope": "origin",
            "label": "Detroit Metro Wayne Co (DTW)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 8,
            "delayed_pct": "1%",
        },
        {
            "scope": "origin",
            "label": "Kuala Namu International (KNO)",
            "cancelled": 2,
            "cancelled_pct": "2%",
            "delayed": 8,
            "delayed_pct": "10%",
        },
        {
            "scope": "origin",
            "label": "Cincinnati/Northern Kentucky International Airport (CVG)",
            "cancelled": 2,
            "cancelled_pct": "1%",
            "delayed": 7,
            "delayed_pct": "3%",
        },
        {
            "scope": "origin",
            "label": "Sharjah Int'l (SHJ)",
            "cancelled": 2,
            "cancelled_pct": "1%",
            "delayed": 7,
            "delayed_pct": "4%",
        },
        {
            "scope": "origin",
            "label": "Salgado Filho Int'l (POA)",
            "cancelled": 2,
            "cancelled_pct": "2%",
            "delayed": 7,
            "delayed_pct": "7%",
        },
        {
            "scope": "origin",
            "label": "Rio de Janeiro/Galeao Intl (GIG)",
            "cancelled": 2,
            "cancelled_pct": "1%",
            "delayed": 6,
            "delayed_pct": "3%",
        },
        {
            "scope": "origin",
            "label": "Presidente Juscelino Kubitschek Int'l (BSB)",
            "cancelled": 2,
            "cancelled_pct": "1%",
            "delayed": 4,
            "delayed_pct": "2%",
        },
        {
            "scope": "origin",
            "label": "Hercilio Luz Int'l (FLN)",
            "cancelled": 2,
            "cancelled_pct": "4%",
            "delayed": 4,
            "delayed_pct": "8%",
        },
        {
            "scope": "origin",
            "label": "Portland Intl (PDX)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 3,
            "delayed_pct": "1%",
        },
        {
            "scope": "origin",
            "label": "St Louis Lambert Intl (STL)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 3,
            "delayed_pct": "1%",
        },
        {
            "scope": "origin",
            "label": "Senai Int'l (Sultan Ismail Int'l) (JHB)",
            "cancelled": 2,
            "cancelled_pct": "5%",
            "delayed": 3,
            "delayed_pct": "8%",
        },
        {
            "scope": "origin",
            "label": "Sultan Mahmud Badaruddin II (PLM)",
            "cancelled": 2,
            "cancelled_pct": "6%",
            "delayed": 3,
            "delayed_pct": "9%",
        },
        {
            "scope": "origin",
            "label": "Halim Perdanakusuma Int'l (HLP)",
            "cancelled": 2,
            "cancelled_pct": "7%",
            "delayed": 3,
            "delayed_pct": "11%",
        },
        {
            "scope": "origin",
            "label": "Providenciales Int'l (PLS)",
            "cancelled": 2,
            "cancelled_pct": "8%",
            "delayed": 3,
            "delayed_pct": "12%",
        },
        {
            "scope": "origin",
            "label": "Chapeco (XAP)",
            "cancelled": 2,
            "cancelled_pct": "20%",
            "delayed": 3,
            "delayed_pct": "30%",
        },
        {
            "scope": "origin",
            "label": "San Diego Intl (SAN)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 2,
            "delayed_pct": "0%",
        },
        {
            "scope": "origin",
            "label": "Sepinggan Int'l (BPN)",
            "cancelled": 2,
            "cancelled_pct": "2%",
            "delayed": 2,
            "delayed_pct": "2%",
        },
        {
            "scope": "origin",
            "label": "Indianapolis Intl (IND)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 1,
            "delayed_pct": "0%",
        },
        {
            "scope": "origin",
            "label": "Eppley Airfield (OMA)",
            "cancelled": 2,
            "cancelled_pct": "1%",
            "delayed": 1,
            "delayed_pct": "0%",
        },
        {
            "scope": "origin",
            "label": "Blue Grass (LEX)",
            "cancelled": 2,
            "cancelled_pct": "3%",
            "delayed": 1,
            "delayed_pct": "1%",
        },
        {
            "scope": "origin",
            "label": "Terrance B. Lettsome Int'l (EIS)",
            "cancelled": 2,
            "cancelled_pct": "12%",
            "delayed": 1,
            "delayed_pct": "6%",
        },
        {
            "scope": "origin",
            "label": "Cascavel (CAC)",
            "cancelled": 2,
            "cancelled_pct": "28%",
            "delayed": 1,
            "delayed_pct": "14%",
        },
        {
            "scope": "origin",
            "label": "South Caicos (XSC)",
            "cancelled": 2,
            "cancelled_pct": "50%",
            "delayed": 1,
            "delayed_pct": "25%",
        },
        {
            "scope": "origin",
            "label": "Cleveland-Hopkins Intl (CLE)",
            "cancelled": 2,
            "cancelled_pct": "1%",
            "delayed": 0,
            "delayed_pct": "0%",
        },
        {
            "scope": "origin",
            "label": "Portland Intl Jetport (PWM)",
            "cancelled": 2,
            "cancelled_pct": "2%",
            "delayed": 0,
            "delayed_pct": "0%",
        },
        {
            "scope": "origin",
            "label": "JAGS McCartney Int'l (Grand Turk Int'l) (GDT)",
            "cancelled": 2,
            "cancelled_pct": "25%",
            "delayed": 0,
            "delayed_pct": "0%",
        },
        {
            "scope": "origin",
            "label": "Guillermo Leon Valencia (PPN)",
            "cancelled": 2,
            "cancelled_pct": "66%",
            "delayed": 0,
            "delayed_pct": "0%",
        },
        {
            "scope": "origin",
            "label": "Najran Domestic (EAM)",
            "cancelled": 2,
            "cancelled_pct": "100%",
            "delayed": 0,
            "delayed_pct": "0%",
        },
        {
            "scope": "origin",
            "label": "Guangzhou Baiyun Int'l (CAN)",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 206,
            "delayed_pct": "25%",
        },
    ],
    "cancel_dest": [
        {
            "scope": "dest",
            "label": "Newark Liberty Intl (EWR)",
            "cancelled": 36,
            "cancelled_pct": "6%",
            "delayed": 39,
            "delayed_pct": "6%",
        },
        {
            "scope": "dest",
            "label": "Philadelphia Intl (PHL)",
            "cancelled": 22,
            "cancelled_pct": "4%",
            "delayed": 19,
            "delayed_pct": "4%",
        },
        {
            "scope": "dest",
            "label": "Dallas-Fort Worth Intl (DFW)",
            "cancelled": 21,
            "cancelled_pct": "2%",
            "delayed": 26,
            "delayed_pct": "2%",
        },
        {
            "scope": "dest",
            "label": "Brussels South Charleroi (CRL)",
            "cancelled": 19,
            "cancelled_pct": "16%",
            "delayed": 22,
            "delayed_pct": "19%",
        },
        {
            "scope": "dest",
            "label": "Viracopos Int'l (VCP)",
            "cancelled": 13,
            "cancelled_pct": "7%",
            "delayed": 35,
            "delayed_pct": "20%",
        },
        {
            "scope": "dest",
            "label": "São Paulo-Congonhas (CGH)",
            "cancelled": 11,
            "cancelled_pct": "3%",
            "delayed": 10,
            "delayed_pct": "3%",
        },
        {
            "scope": "dest",
            "label": "Jakarta-Soekarno-Hatta Int'l (CGK)",
            "cancelled": 10,
            "cancelled_pct": "1%",
            "delayed": 55,
            "delayed_pct": "9%",
        },
        {
            "scope": "dest",
            "label": "Shanghai Pudong Int'l (PVG)",
            "cancelled": 7,
            "cancelled_pct": "0%",
            "delayed": 96,
            "delayed_pct": "12%",
        },
        {
            "scope": "dest",
            "label": "Charlotte/Douglas Intl (CLT)",
            "cancelled": 7,
            "cancelled_pct": "1%",
            "delayed": 25,
            "delayed_pct": "3%",
        },
        {
            "scope": "dest",
            "label": "Miami Intl (MIA)",
            "cancelled": 7,
            "cancelled_pct": "1%",
            "delayed": 13,
            "delayed_pct": "2%",
        },
        {
            "scope": "dest",
            "label": "Nantucket Meml (ACK)",
            "cancelled": 7,
            "cancelled_pct": "5%",
            "delayed": 3,
            "delayed_pct": "2%",
        },
        {
            "scope": "dest",
            "label": "Amsterdam Schiphol (AMS)",
            "cancelled": 6,
            "cancelled_pct": "0%",
            "delayed": 98,
            "delayed_pct": "13%",
        },
        {
            "scope": "dest",
            "label": "Sultan Hasanuddin Int'l (UPG)",
            "cancelled": 6,
            "cancelled_pct": "3%",
            "delayed": 13,
            "delayed_pct": "6%",
        },
        {
            "scope": "dest",
            "label": "São Paulo-Guarulhos Int'l (GRU)",
            "cancelled": 5,
            "cancelled_pct": "1%",
            "delayed": 49,
            "delayed_pct": "12%",
        },
        {
            "scope": "dest",
            "label": "Indira Gandhi Int'l (DEL)",
            "cancelled": 5,
            "cancelled_pct": "0%",
            "delayed": 44,
            "delayed_pct": "6%",
        },
        {
            "scope": "dest",
            "label": "Chengdu Shuangliu Int'l (CTU)",
            "cancelled": 5,
            "cancelled_pct": "1%",
            "delayed": 25,
            "delayed_pct": "6%",
        },
        {
            "scope": "dest",
            "label": "Chatrapati Shivaji Int'l (BOM)",
            "cancelled": 5,
            "cancelled_pct": "1%",
            "delayed": 15,
            "delayed_pct": "3%",
        },
        {
            "scope": "dest",
            "label": "Reagan National (DCA)",
            "cancelled": 5,
            "cancelled_pct": "1%",
            "delayed": 10,
            "delayed_pct": "2%",
        },
        {
            "scope": "dest",
            "label": "Santos Dumont Regional (SDU)",
            "cancelled": 5,
            "cancelled_pct": "5%",
            "delayed": 6,
            "delayed_pct": "6%",
        },
        {
            "scope": "dest",
            "label": "Beijing Capital Int'l (PEK)",
            "cancelled": 4,
            "cancelled_pct": "0%",
            "delayed": 60,
            "delayed_pct": "8%",
        },
        {
            "scope": "dest",
            "label": "Chengdu Tianfu Int'l (TFU)",
            "cancelled": 4,
            "cancelled_pct": "0%",
            "delayed": 49,
            "delayed_pct": "9%",
        },
        {
            "scope": "dest",
            "label": "Chongqing Jiangbei Int'l (CKG)",
            "cancelled": 4,
            "cancelled_pct": "0%",
            "delayed": 43,
            "delayed_pct": "9%",
        },
        {
            "scope": "dest",
            "label": "Chicago O'Hare Intl (ORD)",
            "cancelled": 4,
            "cancelled_pct": "0%",
            "delayed": 29,
            "delayed_pct": "2%",
        },
        {
            "scope": "dest",
            "label": "Kunming Changshui Int'l (KMG)",
            "cancelled": 4,
            "cancelled_pct": "0%",
            "delayed": 28,
            "delayed_pct": "6%",
        },
        {
            "scope": "dest",
            "label": "King Abdulaziz Int'l (JED)",
            "cancelled": 4,
            "cancelled_pct": "0%",
            "delayed": 26,
            "delayed_pct": "6%",
        },
        {
            "scope": "dest",
            "label": "Nanjing Lukou Int'l (NKG)",
            "cancelled": 4,
            "cancelled_pct": "1%",
            "delayed": 23,
            "delayed_pct": "6%",
        },
        {
            "scope": "dest",
            "label": "Brussels (BRU)",
            "cancelled": 4,
            "cancelled_pct": "1%",
            "delayed": 19,
            "delayed_pct": "7%",
        },
        {
            "scope": "dest",
            "label": "Juanda Int'l (SUB)",
            "cancelled": 4,
            "cancelled_pct": "2%",
            "delayed": 16,
            "delayed_pct": "9%",
        },
        {
            "scope": "dest",
            "label": "Washington Dulles Intl (IAD)",
            "cancelled": 4,
            "cancelled_pct": "0%",
            "delayed": 15,
            "delayed_pct": "3%",
        },
        {
            "scope": "dest",
            "label": "Vancouver Int'l (YVR)",
            "cancelled": 4,
            "cancelled_pct": "1%",
            "delayed": 14,
            "delayed_pct": "4%",
        },
        {
            "scope": "dest",
            "label": "Anchorage Intl (ANC)",
            "cancelled": 4,
            "cancelled_pct": "1%",
            "delayed": 5,
            "delayed_pct": "1%",
        },
        {
            "scope": "dest",
            "label": "Afonso Pena Int'l (CWB)",
            "cancelled": 4,
            "cancelled_pct": "4%",
            "delayed": 0,
            "delayed_pct": "0%",
        },
        {
            "scope": "dest",
            "label": "Melbourne Tullamarine (MEL)",
            "cancelled": 3,
            "cancelled_pct": "0%",
            "delayed": 60,
            "delayed_pct": "16%",
        },
        {
            "scope": "dest",
            "label": "Dubai Int'l (DXB)",
            "cancelled": 3,
            "cancelled_pct": "0%",
            "delayed": 56,
            "delayed_pct": "11%",
        },
        {
            "scope": "dest",
            "label": "London Heathrow (LHR)",
            "cancelled": 3,
            "cancelled_pct": "0%",
            "delayed": 39,
            "delayed_pct": "5%",
        },
        {
            "scope": "dest",
            "label": "John F Kennedy Intl (JFK)",
            "cancelled": 3,
            "cancelled_pct": "0%",
            "delayed": 33,
            "delayed_pct": "5%",
        },
        {
            "scope": "dest",
            "label": "Oslo, Gardermoen (OSL)",
            "cancelled": 3,
            "cancelled_pct": "0%",
            "delayed": 29,
            "delayed_pct": "8%",
        },
        {
            "scope": "dest",
            "label": "Toronto Pearson Int'l (YYZ)",
            "cancelled": 3,
            "cancelled_pct": "0%",
            "delayed": 27,
            "delayed_pct": "5%",
        },
        {
            "scope": "dest",
            "label": "Rio de Janeiro/Galeao Intl (GIG)",
            "cancelled": 3,
            "cancelled_pct": "1%",
            "delayed": 6,
            "delayed_pct": "3%",
        },
        {
            "scope": "dest",
            "label": "Kuala Namu International (KNO)",
            "cancelled": 3,
            "cancelled_pct": "3%",
            "delayed": 6,
            "delayed_pct": "7%",
        },
        {
            "scope": "dest",
            "label": "Abha Regional (AHB)",
            "cancelled": 3,
            "cancelled_pct": "6%",
            "delayed": 5,
            "delayed_pct": "10%",
        },
        {
            "scope": "dest",
            "label": "Fort Lauderdale Intl (FLL)",
            "cancelled": 3,
            "cancelled_pct": "1%",
            "delayed": 4,
            "delayed_pct": "1%",
        },
        {
            "scope": "dest",
            "label": "Halim Perdanakusuma Int'l (HLP)",
            "cancelled": 3,
            "cancelled_pct": "11%",
            "delayed": 4,
            "delayed_pct": "15%",
        },
        {
            "scope": "dest",
            "label": "Portland Intl (PDX)",
            "cancelled": 3,
            "cancelled_pct": "1%",
            "delayed": 3,
            "delayed_pct": "1%",
        },
        {
            "scope": "dest",
            "label": "Maputo Int'l (MPM)",
            "cancelled": 3,
            "cancelled_pct": "12%",
            "delayed": 3,
            "delayed_pct": "12%",
        },
        {
            "scope": "dest",
            "label": "Teterboro (TEB)",
            "cancelled": 3,
            "cancelled_pct": "0%",
            "delayed": 0,
            "delayed_pct": "0%",
        },
        {
            "scope": "dest",
            "label": "Tokyo Int'l (Haneda) (HND)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 231,
            "delayed_pct": "33%",
        },
        {
            "scope": "dest",
            "label": "Guangzhou Baiyun Int'l (CAN)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 211,
            "delayed_pct": "26%",
        },
        {
            "scope": "dest",
            "label": "Tan Son Nhat Int'l (SGN)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 101,
            "delayed_pct": "27%",
        },
        {
            "scope": "dest",
            "label": "Kuala Lumpur Int'l (KUL)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 79,
            "delayed_pct": "14%",
        },
        {
            "scope": "dest",
            "label": "Hartsfield-Jackson Intl (ATL)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 66,
            "delayed_pct": "6%",
        },
        {
            "scope": "dest",
            "label": "Ben Gurion Int'l (TLV)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 53,
            "delayed_pct": "17%",
        },
        {
            "scope": "dest",
            "label": "Xi'an Xianyang Int'l (XIY)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 51,
            "delayed_pct": "11%",
        },
        {
            "scope": "dest",
            "label": "Sydney (SYD)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 50,
            "delayed_pct": "11%",
        },
        {
            "scope": "dest",
            "label": "Manila Int'l (MNL)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 37,
            "delayed_pct": "10%",
        },
        {
            "scope": "dest",
            "label": "Leonardo da Vinci Int'l (Fiumicino Int'l) (FCO)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 36,
            "delayed_pct": "7%",
        },
        {
            "scope": "dest",
            "label": "Palma de Mallorca (or Son Sant Joan) (PMI)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 36,
            "delayed_pct": "8%",
        },
        {
            "scope": "dest",
            "label": "Xiamen Gaoqi Int'l (XMN)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 36,
            "delayed_pct": "13%",
        },
        {
            "scope": "dest",
            "label": "Perth Int'l (PER)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 36,
            "delayed_pct": "15%",
        },
        {
            "scope": "dest",
            "label": "Los Angeles Intl (LAX)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 30,
            "delayed_pct": "4%",
        },
        {
            "scope": "dest",
            "label": "Zurich (Kloten) (ZRH)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 29,
            "delayed_pct": "7%",
        },
        {
            "scope": "dest",
            "label": "Ngurah Rai/Bali Intl (DPS)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 23,
            "delayed_pct": "11%",
        },
        {
            "scope": "dest",
            "label": "Bengaluru Int'l (BLR)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 21,
            "delayed_pct": "6%",
        },
        {
            "scope": "dest",
            "label": "Seattle-Tacoma Intl (SEA)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 18,
            "delayed_pct": "2%",
        },
        {
            "scope": "dest",
            "label": "Ningbo Lishe Int'l (NGB)",
            "cancelled": 2,
            "cancelled_pct": "1%",
            "delayed": 15,
            "delayed_pct": "9%",
        },
        {
            "scope": "dest",
            "label": "Montreal-Trudeau (YUL)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 14,
            "delayed_pct": "4%",
        },
        {
            "scope": "dest",
            "label": "Detroit Metro Wayne Co (DTW)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 12,
            "delayed_pct": "2%",
        },
        {
            "scope": "dest",
            "label": "Adelaide Int'l (ADL)",
            "cancelled": 2,
            "cancelled_pct": "1%",
            "delayed": 12,
            "delayed_pct": "9%",
        },
        {
            "scope": "dest",
            "label": "Grantley Adams Int'l (BGI)",
            "cancelled": 2,
            "cancelled_pct": "5%",
            "delayed": 11,
            "delayed_pct": "28%",
        },
        {
            "scope": "dest",
            "label": "Hefei Xinqiao Airport (HFE)",
            "cancelled": 2,
            "cancelled_pct": "1%",
            "delayed": 10,
            "delayed_pct": "8%",
        },
        {
            "scope": "dest",
            "label": "El Dorado Int'l (BOG)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 9,
            "delayed_pct": "1%",
        },
        {
            "scope": "dest",
            "label": "LaGuardia (LGA)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 9,
            "delayed_pct": "1%",
        },
        {
            "scope": "dest",
            "label": "Tancredo Neves Int'l (CNF)",
            "cancelled": 2,
            "cancelled_pct": "1%",
            "delayed": 9,
            "delayed_pct": "5%",
        },
        {
            "scope": "dest",
            "label": "Salgado Filho Int'l (POA)",
            "cancelled": 2,
            "cancelled_pct": "2%",
            "delayed": 7,
            "delayed_pct": "7%",
        },
        {
            "scope": "dest",
            "label": "Westchester County (HPN)",
            "cancelled": 2,
            "cancelled_pct": "1%",
            "delayed": 5,
            "delayed_pct": "3%",
        },
        {
            "scope": "dest",
            "label": "Pune / Lohegaon Air Force Base (PNQ)",
            "cancelled": 2,
            "cancelled_pct": "1%",
            "delayed": 5,
            "delayed_pct": "4%",
        },
        {
            "scope": "dest",
            "label": "Lombok International (LOP)",
            "cancelled": 2,
            "cancelled_pct": "4%",
            "delayed": 5,
            "delayed_pct": "10%",
        },
        {
            "scope": "dest",
            "label": "Luis Munoz Marin Intl (SJU)",
            "cancelled": 2,
            "cancelled_pct": "1%",
            "delayed": 4,
            "delayed_pct": "2%",
        },
        {
            "scope": "dest",
            "label": "Senai Int'l (Sultan Ismail Int'l) (JHB)",
            "cancelled": 2,
            "cancelled_pct": "5%",
            "delayed": 4,
            "delayed_pct": "10%",
        },
        {
            "scope": "dest",
            "label": "Blaise Diagne (DSS)",
            "cancelled": 2,
            "cancelled_pct": "6%",
            "delayed": 4,
            "delayed_pct": "13%",
        },
        {
            "scope": "dest",
            "label": "Salt Lake City Intl (SLC)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 3,
            "delayed_pct": "0%",
        },
        {
            "scope": "dest",
            "label": "Toronto City Centre (YTZ)",
            "cancelled": 2,
            "cancelled_pct": "3%",
            "delayed": 3,
            "delayed_pct": "4%",
        },
        {
            "scope": "dest",
            "label": "Hercilio Luz Int'l (FLN)",
            "cancelled": 2,
            "cancelled_pct": "4%",
            "delayed": 3,
            "delayed_pct": "6%",
        },
        {
            "scope": "dest",
            "label": "Sam Ratulangi Int'l (MDC)",
            "cancelled": 2,
            "cancelled_pct": "7%",
            "delayed": 3,
            "delayed_pct": "10%",
        },
        {
            "scope": "dest",
            "label": "Providenciales Int'l (PLS)",
            "cancelled": 2,
            "cancelled_pct": "8%",
            "delayed": 3,
            "delayed_pct": "12%",
        },
        {
            "scope": "dest",
            "label": "President Donald J Trump Intl (DJT)",
            "cancelled": 2,
            "cancelled_pct": "1%",
            "delayed": 2,
            "delayed_pct": "1%",
        },
        {
            "scope": "dest",
            "label": "Lynden Pindling Int'l (Nassau) (NAS)",
            "cancelled": 2,
            "cancelled_pct": "2%",
            "delayed": 2,
            "delayed_pct": "2%",
        },
        {
            "scope": "dest",
            "label": "Chapeco (XAP)",
            "cancelled": 2,
            "cancelled_pct": "22%",
            "delayed": 2,
            "delayed_pct": "22%",
        },
        {
            "scope": "dest",
            "label": "Raleigh-Durham Intl (RDU)",
            "cancelled": 2,
            "cancelled_pct": "0%",
            "delayed": 1,
            "delayed_pct": "0%",
        },
        {
            "scope": "dest",
            "label": "Terrance B. Lettsome Int'l (EIS)",
            "cancelled": 2,
            "cancelled_pct": "12%",
            "delayed": 1,
            "delayed_pct": "6%",
        },
        {
            "scope": "dest",
            "label": "South Caicos (XSC)",
            "cancelled": 2,
            "cancelled_pct": "50%",
            "delayed": 1,
            "delayed_pct": "25%",
        },
        {
            "scope": "dest",
            "label": "JAGS McCartney Int'l (Grand Turk Int'l) (GDT)",
            "cancelled": 2,
            "cancelled_pct": "25%",
            "delayed": 0,
            "delayed_pct": "0%",
        },
        {
            "scope": "dest",
            "label": "Cascavel (CAC)",
            "cancelled": 2,
            "cancelled_pct": "28%",
            "delayed": 0,
            "delayed_pct": "0%",
        },
        {
            "scope": "dest",
            "label": "Najran Domestic (EAM)",
            "cancelled": 2,
            "cancelled_pct": "66%",
            "delayed": 0,
            "delayed_pct": "0%",
        },
        {
            "scope": "dest",
            "label": "Guillermo Leon Valencia (PPN)",
            "cancelled": 2,
            "cancelled_pct": "66%",
            "delayed": 0,
            "delayed_pct": "0%",
        },
        {
            "scope": "dest",
            "label": "Gizan Regional (GIZ)",
            "cancelled": 2,
            "cancelled_pct": "100%",
            "delayed": 0,
            "delayed_pct": "0%",
        },
        {
            "scope": "dest",
            "label": "Manchester (MAN)",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 100,
            "delayed_pct": "31%",
        },
        {
            "scope": "dest",
            "label": "Frankfurt Int'l (FRA)",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 81,
            "delayed_pct": "12%",
        },
        {
            "scope": "dest",
            "label": "Athens Int'l, Eleftherios Venizelos (ATH)",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 68,
            "delayed_pct": "18%",
        },
        {
            "scope": "dest",
            "label": "Boston Logan Intl (BOS)",
            "cancelled": 1,
            "cancelled_pct": "0%",
            "delayed": 64,
            "delayed_pct": "10%",
        },
    ],
    "daily": [
        {
            "key": "us_delays_today",
            "value_int": 938,
        },
        {
            "key": "world_delays_today",
            "value_int": 9422,
        },
        {
            "key": "world_cancel_today",
            "value_int": 537,
        },
        {
            "key": "us_cancel_today",
            "value_int": 183,
        },
    ],
}
