"""Tracked snapshot — captured from flightaware.com on 2026-09-22 (live pages)."""

AIRCRAFT_TYPES = [
    {
        "code": "B738",
        "name": "Boeing 737-800 (twin-jet)",
        "manufacturer": "Boeing",
        "flights_count": 116,
    },
    {
        "code": "A21N",
        "name": "Airbus A321neo (twin-jet)",
        "manufacturer": "Airbus",
        "flights_count": 89,
    },
    {
        "code": "B38M",
        "name": "Boeing 737 MAX 8 (twin-jet)",
        "manufacturer": "Boeing",
        "flights_count": 86,
    },
    {
        "code": "A321",
        "name": "Airbus A321 (twin-jet)",
        "manufacturer": "Airbus",
        "flights_count": 84,
    },
    {
        "code": "E75L",
        "name": "EMBRAER 175 (long wing) (twin-jet)",
        "manufacturer": "",
        "flights_count": 81,
    },
    {
        "code": "B763",
        "name": "BOEING 767-300 (twin-jet)",
        "manufacturer": "",
        "flights_count": 67,
    },
    {
        "code": "A20N",
        "name": "Airbus A320neo (twin-jet)",
        "manufacturer": "Airbus",
        "flights_count": 53,
    },
    {
        "code": "B739",
        "name": "Boeing 737-900",
        "manufacturer": "Boeing",
        "flights_count": 51,
    },
    {
        "code": "A320",
        "name": "Airbus A320",
        "manufacturer": "Airbus",
        "flights_count": 48,
    },
    {
        "code": "E170",
        "name": "Embraer 170/175 (twin-jet)",
        "manufacturer": "Embraer",
        "flights_count": 47,
    },
    {
        "code": "B39M",
        "name": "Boeing 737 MAX 9 (twin-jet)",
        "manufacturer": "Boeing",
        "flights_count": 39,
    },
    {
        "code": "A319",
        "name": "Airbus A319 (twin-jet)",
        "manufacturer": "Airbus",
        "flights_count": 33,
    },
    {
        "code": "CRJ9",
        "name": "Canadair Regional Jet CRJ-900 (twin-jet)",
        "manufacturer": "",
        "flights_count": 29,
    },
    {
        "code": "B789",
        "name": "Boeing 787-9 Dreamliner (twin-jet)",
        "manufacturer": "Boeing",
        "flights_count": 29,
    },
    {
        "code": "B737",
        "name": "Boeing 737-700",
        "manufacturer": "Boeing",
        "flights_count": 24,
    },
    {
        "code": "B752",
        "name": "Boeing 757-200",
        "manufacturer": "Boeing",
        "flights_count": 23,
    },
    {
        "code": "BCS3",
        "name": "Airbus A220-300 (twin-jet)",
        "manufacturer": "Airbus",
        "flights_count": 23,
    },
    {
        "code": "CRJ7",
        "name": "Canadair Regional Jet CRJ-700 (twin-jet)",
        "manufacturer": "",
        "flights_count": 22,
    },
    {
        "code": "B77W",
        "name": "BOEING 777-300ER (twin-jet)",
        "manufacturer": "",
        "flights_count": 21,
    },
    {
        "code": "E75S",
        "name": "Embraer E175 (short wing)",
        "manufacturer": "Embraer",
        "flights_count": 18,
    },
    {
        "code": "B772",
        "name": "Boeing 777-200 (twin-jet)",
        "manufacturer": "Boeing",
        "flights_count": 18,
    },
    {
        "code": "A359",
        "name": "Airbus A350-900 (twin-jet)",
        "manufacturer": "Airbus",
        "flights_count": 18,
    },
    {
        "code": "B77L",
        "name": "BOEING 777-200LR (twin-jet)",
        "manufacturer": "",
        "flights_count": 14,
    },
    {
        "code": "B712",
        "name": "B712",
        "manufacturer": "",
        "flights_count": 14,
    },
    {
        "code": "B744",
        "name": "Boeing 747-400 (quad-jet)",
        "manufacturer": "Boeing",
        "flights_count": 13,
    },
    {
        "code": "C402",
        "name": "Cessna 402 (twin-piston)",
        "manufacturer": "Cessna",
        "flights_count": 9,
    },
    {
        "code": "B788",
        "name": "Boeing 787-8 (twin-jet)",
        "manufacturer": "Boeing",
        "flights_count": 8,
    },
    {
        "code": "P212",
        "name": "TECNAM P-2012 Traveller (twin-piston)",
        "manufacturer": "",
        "flights_count": 8,
    },
    {
        "code": "A332",
        "name": "Airbus A330-200",
        "manufacturer": "Airbus",
        "flights_count": 8,
    },
    {
        "code": "B748",
        "name": "BOEING 747-8 (quad-jet)",
        "manufacturer": "",
        "flights_count": 8,
    },
    {
        "code": "CRJ2",
        "name": "Bombardier CRJ-200",
        "manufacturer": "Bombardier",
        "flights_count": 7,
    },
    {
        "code": "B78X",
        "name": "BOEING 787-10 Dreamliner (twin-jet)",
        "manufacturer": "",
        "flights_count": 7,
    },
    {
        "code": "SW4",
        "name": "Fairchild Dornier SA-227DC Metro (twin-turboprop)",
        "manufacturer": "",
        "flights_count": 7,
    },
    {
        "code": "A35K",
        "name": "Airbus A350-1000 (twin-jet)",
        "manufacturer": "Airbus",
        "flights_count": 6,
    },
    {
        "code": "A333",
        "name": "Airbus A330-300 (twin-jet)",
        "manufacturer": "Airbus",
        "flights_count": 6,
    },
    {
        "code": "B753",
        "name": "BOEING 757-300 (twin-jet)",
        "manufacturer": "",
        "flights_count": 6,
    },
    {
        "code": "B773",
        "name": "BOEING 777-300 (twin-jet)",
        "manufacturer": "",
        "flights_count": 5,
    },
    {
        "code": "B734",
        "name": "B734",
        "manufacturer": "",
        "flights_count": 5,
    },
    {
        "code": "A306",
        "name": "Airbus A300F4-600 (twin-jet)",
        "manufacturer": "Airbus",
        "flights_count": 5,
    },
    {
        "code": "E190",
        "name": "Embraer E190",
        "manufacturer": "Embraer",
        "flights_count": 5,
    },
    {
        "code": "C68A",
        "name": "C68A",
        "manufacturer": "",
        "flights_count": 4,
    },
    {
        "code": "MD11",
        "name": "Boeing MD-11 (tri-jet)",
        "manufacturer": "Boeing",
        "flights_count": 4,
    },
    {
        "code": "C208",
        "name": "C208",
        "manufacturer": "",
        "flights_count": 4,
    },
    {
        "code": "B190",
        "name": "B190",
        "manufacturer": "",
        "flights_count": 4,
    },
    {
        "code": "B722",
        "name": "B722",
        "manufacturer": "",
        "flights_count": 4,
    },
    {
        "code": "DH8D",
        "name": "DH8D",
        "manufacturer": "",
        "flights_count": 3,
    },
    {
        "code": "E545",
        "name": "E545",
        "manufacturer": "",
        "flights_count": 3,
    },
    {
        "code": "CNA",
        "name": "CNA",
        "manufacturer": "",
        "flights_count": 3,
    },
    {
        "code": "A339",
        "name": "Airbus A330-900neo",
        "manufacturer": "Airbus",
        "flights_count": 3,
    },
    {
        "code": "A388",
        "name": "Airbus A380-800",
        "manufacturer": "Airbus",
        "flights_count": 2,
    },
    {
        "code": "CL35",
        "name": "Bombardier Challenger 350",
        "manufacturer": "Bombardier",
        "flights_count": 2,
    },
    {
        "code": "B762",
        "name": "BOEING 767-200 (twin-jet)",
        "manufacturer": "",
        "flights_count": 2,
    },
    {
        "code": "BCS1",
        "name": "BCS1",
        "manufacturer": "",
        "flights_count": 2,
    },
    {
        "code": "E295",
        "name": "E295",
        "manufacturer": "",
        "flights_count": 2,
    },
    {
        "code": "C680",
        "name": "C680",
        "manufacturer": "",
        "flights_count": 2,
    },
    {
        "code": "BE65",
        "name": "BE65",
        "manufacturer": "",
        "flights_count": 2,
    },
    {
        "code": "B764",
        "name": "Boeing 767-400",
        "manufacturer": "Boeing",
        "flights_count": 2,
    },
    {
        "code": "PC12",
        "name": "Pilatus PC-12",
        "manufacturer": "Pilatus",
        "flights_count": 1,
    },
    {
        "code": "B777",
        "name": "B777",
        "manufacturer": "",
        "flights_count": 1,
    },
    {
        "code": "GLF4",
        "name": "GLF4",
        "manufacturer": "",
        "flights_count": 1,
    },
    {
        "code": "C56X",
        "name": "Cessna Citation Excel/XLS (twin-jet)",
        "manufacturer": "Cessna",
        "flights_count": 1,
    },
    {
        "code": "E55P",
        "name": "E55P",
        "manufacturer": "",
        "flights_count": 1,
    },
    {
        "code": "SF34",
        "name": "SF34",
        "manufacturer": "",
        "flights_count": 1,
    },
    {
        "code": "GLF5",
        "name": "Gulfstream G550",
        "manufacturer": "Gulfstream",
        "flights_count": 1,
    },
    {
        "code": "CL60",
        "name": "Bombardier Challenger 600",
        "manufacturer": "Bombardier",
        "flights_count": 1,
    },
    {
        "code": "AT76",
        "name": "ATR 72-600",
        "manufacturer": "ATR",
        "flights_count": 1,
    },
    {
        "code": "CL30",
        "name": "CL30",
        "manufacturer": "",
        "flights_count": 1,
    },
    {
        "code": "CVLT",
        "name": "CVLT",
        "manufacturer": "",
        "flights_count": 1,
    },
    {
        "code": "E120",
        "name": "Embraer EMB-120 Brasilia (twin-turboprop)",
        "manufacturer": "Embraer",
        "flights_count": 1,
    },
    {
        "code": "BE99",
        "name": "BE99",
        "manufacturer": "",
        "flights_count": 1,
    },
    {
        "code": "C25B",
        "name": "Cessna Citation CJ3",
        "manufacturer": "Cessna",
        "flights_count": 1,
    },
    {
        "code": "GL5T",
        "name": "Bombardier Global 5000 (twin-jet)",
        "manufacturer": "Bombardier",
        "flights_count": 1,
    },
    {
        "code": "HDJT",
        "name": "HondaJet",
        "manufacturer": "Honda",
        "flights_count": 1,
    },
    {
        "code": "B77F",
        "name": "B77F",
        "manufacturer": "",
        "flights_count": 1,
    },
    {
        "code": "B732",
        "name": "B732",
        "manufacturer": "",
        "flights_count": 1,
    },
    {
        "code": "737",
        "name": "737",
        "manufacturer": "",
        "flights_count": 1,
    },
]
