"""Tracked snapshot — captured from flightaware.com on 2026-09-22 (live pages)."""

AIRLINES = [
    {
        "code": "DAL",
        "iata": "DL",
        "name": "Delta Air Lines",
        "flights_count": 148,
    },
    {
        "code": "AAL",
        "iata": "AA",
        "name": "American Airlines",
        "flights_count": 143,
    },
    {
        "code": "UAL",
        "iata": "UA",
        "name": "United",
        "flights_count": 109,
    },
    {
        "code": "SWA",
        "iata": "WN",
        "name": "Southwest",
        "flights_count": 70,
    },
    {
        "code": "SKW",
        "iata": "OO",
        "name": "SkyWest",
        "flights_count": 64,
    },
    {
        "code": "RPA",
        "iata": "YX",
        "name": "Republic",
        "flights_count": 49,
    },
    {
        "code": "ENY",
        "iata": "MQ",
        "name": "Envoy Air",
        "flights_count": 44,
    },
    {
        "code": "BAW",
        "iata": "BA",
        "name": "British Airways",
        "flights_count": 42,
    },
    {
        "code": "FFT",
        "iata": "F9",
        "name": "Frontier",
        "flights_count": 40,
    },
    {
        "code": "ASA",
        "iata": "AS",
        "name": "Alaska Airlines",
        "flights_count": 34,
    },
    {
        "code": "JBU",
        "iata": "B6",
        "name": "JetBlue",
        "flights_count": 33,
    },
    {
        "code": "DLH",
        "iata": "LH",
        "name": "Lufthansa",
        "flights_count": 30,
    },
    {
        "code": "FDX",
        "iata": "FX",
        "name": "FedEx",
        "flights_count": 27,
    },
    {
        "code": "EDV",
        "iata": "9E",
        "name": "Endeavor Air",
        "flights_count": 26,
    },
    {
        "code": "JAL",
        "iata": "JL",
        "name": "Japan Airlines",
        "flights_count": 26,
    },
    {
        "code": "ANA",
        "iata": "NH",
        "name": "All Nippon",
        "flights_count": 26,
    },
    {
        "code": "UPS",
        "iata": "5X",
        "name": "United Parcel Service",
        "flights_count": 24,
    },
    {
        "code": "KAP",
        "iata": "9K",
        "name": "Cape Air",
        "flights_count": 20,
    },
    {
        "code": "CFG",
        "iata": "DE",
        "name": "Condor",
        "flights_count": 16,
    },
    {
        "code": "EJA",
        "iata": "1I",
        "name": "NetJets Aviation",
        "flights_count": 11,
    },
    {
        "code": "QXE",
        "iata": "QX",
        "name": "Horizon",
        "flights_count": 11,
    },
    {
        "code": "GJS",
        "iata": "G7",
        "name": "GoJet",
        "flights_count": 8,
    },
    {
        "code": "LYM",
        "iata": "L4",
        "name": "Key Lime Air",
        "flights_count": 7,
    },
    {
        "code": "QTR",
        "iata": "QR",
        "name": "Qatar Airways",
        "flights_count": 5,
    },
    {
        "code": "CAL",
        "iata": "CI",
        "name": "China Airlines",
        "flights_count": 5,
    },
    {
        "code": "CMP",
        "iata": "CM",
        "name": "Copa Airlines",
        "flights_count": 5,
    },
    {
        "code": "KAL",
        "iata": "KE",
        "name": "Korean Air",
        "flights_count": 5,
    },
    {
        "code": "EVA",
        "iata": "BR",
        "name": "EVA Air",
        "flights_count": 5,
    },
    {
        "code": "ABX",
        "iata": "GB",
        "name": "ABX Air",
        "flights_count": 5,
    },
    {
        "code": "GTI",
        "iata": "5Y",
        "name": "Atlas Air",
        "flights_count": 5,
    },
    {
        "code": "ATN",
        "iata": "",
        "name": "ATN",
        "flights_count": 5,
    },
    {
        "code": "EIN",
        "iata": "",
        "name": "EIN",
        "flights_count": 5,
    },
    {
        "code": "AIC",
        "iata": "AI",
        "name": "Air India",
        "flights_count": 4,
    },
    {
        "code": "VIR",
        "iata": "VS",
        "name": "Virgin Atlantic",
        "flights_count": 4,
    },
    {
        "code": "JZA",
        "iata": "",
        "name": "JZA",
        "flights_count": 4,
    },
    {
        "code": "ADO",
        "iata": "",
        "name": "ADO",
        "flights_count": 4,
    },
    {
        "code": "UAE",
        "iata": "EK",
        "name": "Emirates",
        "flights_count": 3,
    },
    {
        "code": "AAR",
        "iata": "",
        "name": "Asiana",
        "flights_count": 3,
    },
    {
        "code": "BOX",
        "iata": "",
        "name": "BOX",
        "flights_count": 3,
    },
    {
        "code": "CKS",
        "iata": "",
        "name": "CKS",
        "flights_count": 3,
    },
    {
        "code": "CKK",
        "iata": "",
        "name": "CKK",
        "flights_count": 3,
    },
    {
        "code": "KII",
        "iata": "",
        "name": "KII",
        "flights_count": 3,
    },
    {
        "code": "LXJ",
        "iata": "",
        "name": "LXJ",
        "flights_count": 3,
    },
    {
        "code": "ACA",
        "iata": "AC",
        "name": "Air Canada",
        "flights_count": 3,
    },
    {
        "code": "TPA",
        "iata": "",
        "name": "TPA",
        "flights_count": 3,
    },
    {
        "code": "BMJ",
        "iata": "",
        "name": "BMJ",
        "flights_count": 3,
    },
    {
        "code": "AIP",
        "iata": "",
        "name": "AIP",
        "flights_count": 3,
    },
    {
        "code": "EWG",
        "iata": "",
        "name": "EWG",
        "flights_count": 3,
    },
    {
        "code": "VLG",
        "iata": "",
        "name": "VLG",
        "flights_count": 3,
    },
    {
        "code": "LHX",
        "iata": "",
        "name": "LHX",
        "flights_count": 3,
    },
    {
        "code": "OCN",
        "iata": "",
        "name": "OCN",
        "flights_count": 3,
    },
    {
        "code": "SXS",
        "iata": "",
        "name": "SXS",
        "flights_count": 3,
    },
    {
        "code": "SFJ",
        "iata": "",
        "name": "SFJ",
        "flights_count": 3,
    },
    {
        "code": "SKY",
        "iata": "",
        "name": "SKY",
        "flights_count": 3,
    },
    {
        "code": "AJX",
        "iata": "",
        "name": "AJX",
        "flights_count": 3,
    },
    {
        "code": "AKX",
        "iata": "",
        "name": "AKX",
        "flights_count": 3,
    },
    {
        "code": "LAN",
        "iata": "LA",
        "name": "LATAM",
        "flights_count": 2,
    },
    {
        "code": "ETD",
        "iata": "EY",
        "name": "Etihad Airways",
        "flights_count": 2,
    },
    {
        "code": "SIA",
        "iata": "SQ",
        "name": "Singapore Airlines",
        "flights_count": 2,
    },
    {
        "code": "ELY",
        "iata": "",
        "name": "ELY",
        "flights_count": 2,
    },
    {
        "code": "CAO",
        "iata": "",
        "name": "CAO",
        "flights_count": 2,
    },
    {
        "code": "CCA",
        "iata": "",
        "name": "CCA",
        "flights_count": 2,
    },
    {
        "code": "WJA",
        "iata": "",
        "name": "WJA",
        "flights_count": 2,
    },
    {
        "code": "SJX",
        "iata": "",
        "name": "SJX",
        "flights_count": 2,
    },
    {
        "code": "POE",
        "iata": "",
        "name": "POE",
        "flights_count": 2,
    },
    {
        "code": "CSB",
        "iata": "",
        "name": "CSB",
        "flights_count": 2,
    },
    {
        "code": "BBQ",
        "iata": "",
        "name": "BBQ",
        "flights_count": 2,
    },
    {
        "code": "AJT",
        "iata": "",
        "name": "AJT",
        "flights_count": 2,
    },
    {
        "code": "MTN",
        "iata": "",
        "name": "MTN",
        "flights_count": 2,
    },
    {
        "code": "AMF",
        "iata": "",
        "name": "AMF",
        "flights_count": 2,
    },
    {
        "code": "MSR",
        "iata": "MS",
        "name": "EgyptAir",
        "flights_count": 2,
    },
    {
        "code": "SVA",
        "iata": "SV",
        "name": "Saudia",
        "flights_count": 2,
    },
    {
        "code": "PGT",
        "iata": "",
        "name": "PGT",
        "flights_count": 2,
    },
    {
        "code": "CES",
        "iata": "",
        "name": "CES",
        "flights_count": 2,
    },
    {
        "code": "THA",
        "iata": "",
        "name": "THA",
        "flights_count": 2,
    },
    {
        "code": "LPE",
        "iata": "LA",
        "name": "LATAM Peru",
        "flights_count": 1,
    },
    {
        "code": "BCS",
        "iata": "3S",
        "name": "European Air Transport",
        "flights_count": 1,
    },
    {
        "code": "AMX",
        "iata": "",
        "name": "AMX",
        "flights_count": 1,
    },
    {
        "code": "GPD",
        "iata": "",
        "name": "GPD",
        "flights_count": 1,
    },
    {
        "code": "ICL",
        "iata": "",
        "name": "ICL",
        "flights_count": 1,
    },
    {
        "code": "NCA",
        "iata": "",
        "name": "NCA",
        "flights_count": 1,
    },
    {
        "code": "TNO",
        "iata": "",
        "name": "TNO",
        "flights_count": 1,
    },
    {
        "code": "DHK",
        "iata": "",
        "name": "DHK",
        "flights_count": 1,
    },
    {
        "code": "CLX",
        "iata": "",
        "name": "CLX",
        "flights_count": 1,
    },
    {
        "code": "ABD",
        "iata": "",
        "name": "Air Atlanta Icelandic",
        "flights_count": 1,
    },
    {
        "code": "VIV",
        "iata": "",
        "name": "VIV",
        "flights_count": 1,
    },
    {
        "code": "GEC",
        "iata": "",
        "name": "GEC",
        "flights_count": 1,
    },
    {
        "code": "CPA",
        "iata": "CX",
        "name": "Cathay Pacific",
        "flights_count": 1,
    },
    {
        "code": "CSG",
        "iata": "",
        "name": "CSG",
        "flights_count": 1,
    },
    {
        "code": "VOI",
        "iata": "",
        "name": "VOI",
        "flights_count": 1,
    },
    {
        "code": "EJM",
        "iata": "",
        "name": "EJM",
        "flights_count": 1,
    },
    {
        "code": "SIS",
        "iata": "",
        "name": "SIS",
        "flights_count": 1,
    },
    {
        "code": "AIH",
        "iata": "",
        "name": "AIH",
        "flights_count": 1,
    },
    {
        "code": "PAL",
        "iata": "",
        "name": "PAL",
        "flights_count": 1,
    },
    {
        "code": "AVA",
        "iata": "",
        "name": "AVA",
        "flights_count": 1,
    },
    {
        "code": "TXG",
        "iata": "",
        "name": "TXG",
        "flights_count": 1,
    },
    {
        "code": "BHS",
        "iata": "",
        "name": "BHS",
        "flights_count": 1,
    },
    {
        "code": "MAW",
        "iata": "",
        "name": "MAW",
        "flights_count": 1,
    },
    {
        "code": "CSQ",
        "iata": "",
        "name": "CSQ",
        "flights_count": 1,
    },
    {
        "code": "UCG",
        "iata": "",
        "name": "UCG",
        "flights_count": 1,
    },
    {
        "code": "XFL",
        "iata": "",
        "name": "XFL",
        "flights_count": 1,
    },
    {
        "code": "LTG",
        "iata": "",
        "name": "LTG",
        "flights_count": 1,
    },
    {
        "code": "TSU",
        "iata": "",
        "name": "TSU",
        "flights_count": 1,
    },
    {
        "code": "VJA",
        "iata": "",
        "name": "VJA",
        "flights_count": 1,
    },
    {
        "code": "CAY",
        "iata": "",
        "name": "CAY",
        "flights_count": 1,
    },
    {
        "code": "FDY",
        "iata": "",
        "name": "FDY",
        "flights_count": 1,
    },
    {
        "code": "MRA",
        "iata": "",
        "name": "MRA",
        "flights_count": 1,
    },
    {
        "code": "ASP",
        "iata": "",
        "name": "ASP",
        "flights_count": 1,
    },
    {
        "code": "SCX",
        "iata": "",
        "name": "SCX",
        "flights_count": 1,
    },
    {
        "code": "CTF",
        "iata": "",
        "name": "CTF",
        "flights_count": 1,
    },
    {
        "code": "SWR",
        "iata": "LX",
        "name": "Swiss",
        "flights_count": 1,
    },
    {
        "code": "MEA",
        "iata": "",
        "name": "MEA",
        "flights_count": 1,
    },
    {
        "code": "KAC",
        "iata": "",
        "name": "KAC",
        "flights_count": 1,
    },
    {
        "code": "KLM",
        "iata": "KL",
        "name": "KLM",
        "flights_count": 1,
    },
    {
        "code": "UZB",
        "iata": "",
        "name": "UZB",
        "flights_count": 1,
    },
    {
        "code": "ASL",
        "iata": "",
        "name": "ASL",
        "flights_count": 1,
    },
    {
        "code": "ICE",
        "iata": "",
        "name": "ICE",
        "flights_count": 1,
    },
    {
        "code": "TAP",
        "iata": "",
        "name": "TAP",
        "flights_count": 1,
    },
    {
        "code": "CSS",
        "iata": "",
        "name": "CSS",
        "flights_count": 1,
    },
    {
        "code": "AUA",
        "iata": "OS",
        "name": "Austrian Airlines",
        "flights_count": 1,
    },
    {
        "code": "RJA",
        "iata": "",
        "name": "RJA",
        "flights_count": 1,
    },
    {
        "code": "SAS",
        "iata": "SK",
        "name": "SAS",
        "flights_count": 1,
    },
    {
        "code": "TUI",
        "iata": "TB",
        "name": "TUI fly Belgium",
        "flights_count": 1,
    },
    {
        "code": "GER",
        "iata": "",
        "name": "GER",
        "flights_count": 1,
    },
    {
        "code": "BTI",
        "iata": "",
        "name": "BTI",
        "flights_count": 1,
    },
    {
        "code": "LOT",
        "iata": "",
        "name": "LOT",
        "flights_count": 1,
    },
    {
        "code": "AWG",
        "iata": "",
        "name": "AWG",
        "flights_count": 1,
    },
    {
        "code": "SEH",
        "iata": "",
        "name": "SEH",
        "flights_count": 1,
    },
    {
        "code": "QNT",
        "iata": "",
        "name": "QNT",
        "flights_count": 1,
    },
    {
        "code": "JTA",
        "iata": "",
        "name": "JTA",
        "flights_count": 1,
    },
    {
        "code": "SNJ",
        "iata": "",
        "name": "SNJ",
        "flights_count": 1,
    },
    {
        "code": "DKH",
        "iata": "",
        "name": "DKH",
        "flights_count": 1,
    },
    {
        "code": "THY",
        "iata": "TK",
        "name": "Turkish Airlines",
        "flights_count": 1,
    },
    {
        "code": "QFA",
        "iata": "QF",
        "name": "Qantas",
        "flights_count": 1,
    },
    {
        "code": "FIN",
        "iata": "",
        "name": "FIN",
        "flights_count": 1,
    },
    {
        "code": "AFR",
        "iata": "AF",
        "name": "Air France",
        "flights_count": 1,
    },
]
