"""Tracked snapshot — captured from flightaware.com on 2026-09-22 (live pages)."""

SQUAWKS = [
    {
        "sid": "100894",
        "title": "Why Aren’t Passengers Who Evacuate With Bags Being Punished?",
        "slug": "Why_Aren_t_Passengers_Who_Evacuate_With_Bags_Being_Punished",
        "source_label": "(www.gatechecked.com)",
        "summary": "Should passengers be punished or fined for taking their baggage with them during an emergency evacuation?",
        "submitter": "Roger Anderson",
        "submitted_text": "6 months ago",
        "votes": 56,
        "comment_count": 126,
        "lists": "popular_year",
    },
    {
        "sid": "101120",
        "title": "Delta Suspends Congressional Travel Services Amid Shutdown",
        "slug": "Delta_Suspends_Congressional_Travel_Services_Amid_Shutdown",
        "source_label": "(airguide.info)",
        "summary": "Delta Air Lines has suspended select specialty services for members of Congress as the U.S. government shutdown continues, reflecting the broader operational impact of the funding lapse on travel and administrative support systems.",
        "submitter": "airguideonline",
        "submitted_text": "5 months ago",
        "votes": 50,
        "comment_count": 46,
        "lists": "popular_year",
    },
    {
        "sid": "102413",
        "title": "FlightAware's Role in Airspace Modernization",
        "slug": "FlightAware_s_Role_in_Airspace_Modernization",
        "source_label": "(blog.flightaware.com)",
        "summary": "In aviation, information is the currency of efficiency. For an industry that operates across every time zone and over every square mile of the globe, having a reliable and comprehensive data picture is an operational necessity.",
        "submitter": "Amanda Skogstad",
        "submitted_text": "4 months ago",
        "votes": 49,
        "comment_count": 2,
        "lists": "popular_year",
    },
    {
        "sid": "99540",
        "title": "Possible Meteorite Strikes United 737; Injures Pilot",
        "slug": "Possible_Meteorite_Strikes_United_737_Injures_Pilot",
        "source_label": "(weatherboy.com)",
        "summary": "A Boeing 737 MAX 8 flight traveling from Denver to Los Angeles as United flight 1093 with 140 souls on board was forced to divert to Salt Lake City after a cracked windshield was discovered midair. The incident occurred on Thursday, October 16, 2025 at an altitude of 36,000 feet. No definitive cause has been declared for the incident, although a meteorite strike is the leading theory. A pilot was injured in the incident. If a meteor strike is to blame, it would be an aviation first. There’s been…",
        "submitter": "James Steiner",
        "submitted_text": "11 months ago",
        "votes": 49,
        "comment_count": 27,
        "lists": "popular_year",
    },
    {
        "sid": "100199",
        "title": "Garmin System Autolands King Air Following Pilot Incapacitation",
        "slug": "Garmin_System_Autolands_King_Air_Following_Pilot_Incapacitation",
        "source_label": "(www.gatechecked.com)",
        "summary": "A Beechcraft Super King Air landed safely using Garmin's emergency Autoland system after the pilot became incapacitated during flight.",
        "submitter": "Roger Anderson",
        "submitted_text": "9 months ago",
        "votes": 48,
        "comment_count": 24,
        "lists": "popular_year",
    },
    {
        "sid": "100523",
        "title": "Paramedic Took Controls After Pilot Medical Emergency on LifeFlight",
        "slug": "Paramedic_Took_Controls_After_Pilot_Medical_Emergency_on_LifeFlight",
        "source_label": "(airguide.info)",
        "summary": "A flight paramedic with no pilot training was forced to take control of a medical helicopter after the pilot suffered a sudden medical emergency mid-flight, according to a preliminary report released by the National Transportation Safety Board (NTSB).",
        "submitter": "airguideonline",
        "submitted_text": "8 months ago",
        "votes": 48,
        "comment_count": 44,
        "lists": "popular_year",
    },
    {
        "sid": "99278",
        "title": "Drone Pilot Sentenced to Jail and $156K Fine After DJI Mini 3 Collision With LA Firefighting Plane",
        "slug": "Drone_Pilot_Sentenced_to_Jail_and_156K_Fine_After_DJI_Mini_3_Collision_With_LA_F",
        "source_label": "(airguide.info)",
        "summary": "A California tech executive has been sentenced to jail and ordered to pay restitution after his DJI Mini 3 Pro drone collided with a vital firefighting aircraft battling Los Angeles’ January Palisades Fire. The crash forced the plane out of service at a critical moment in the firefight, underscoring the dangers of flying drones near emergency operations.",
        "submitter": "Alan Winn",
        "submitted_text": "12 months ago",
        "votes": 48,
        "comment_count": 37,
        "lists": "popular_year",
    },
    {
        "sid": "99959",
        "title": "Airbus Issues Urgent Safety Directive After Discovery of Solar Radiation Data Corruption Risk in A320 Family",
        "slug": "Airbus_Issues_Urgent_Safety_Directive_After_Discovery_of_Solar_Radiation_Data_Co",
        "source_label": "(aeroxplorer.com)",
        "summary": "Airbus has called for immediate precautionary action across all global operators of A320 Family aircraft following the discovery of a rare but critical vulnerability linked to intense solar radiation.",
        "submitter": "Dan Mena",
        "submitted_text": "9 months ago",
        "votes": 47,
        "comment_count": 27,
        "lists": "popular_year",
    },
    {
        "sid": "100583",
        "title": "Delta Flight Diverts After Crew Uses Beverage Carts to Restrain Passenger",
        "slug": "Delta_Flight_Diverts_After_Crew_Uses_Beverage_Carts_to_Restrain_Passenger",
        "source_label": "(airguide.info)",
        "summary": "Delta Air Lines flight attendants allegedly used beverage carts to block and restrain a disruptive passenger during a long-haul flight from the United States to Japan, an incident that ultimately forced an unscheduled diversion to Alaska and led to federal criminal charges.",
        "submitter": "Alan Winn",
        "submitted_text": "7 months ago",
        "votes": 47,
        "comment_count": 51,
        "lists": "popular_year",
    },
    {
        "sid": "100066",
        "title": "Winter Travel, Delays, and Cancellations – How FlightAware® Can Help",
        "slug": "Winter_Travel_Delays_and_Cancellations_How_FlightAware_Can_Help",
        "source_label": "(blog.flightaware.com)",
        "summary": "In many locations, November, December, January, and February offer harsh weather conditions. These winter months can lead to disruptions which could tempt travelers to stay inside and wait for more welcoming spring conditions. Whether it’s a holiday vacation to see family and friends or a much-needed winter getaway to a warmer climate, the FlightAware app can help travelers navigate winter travel challenges and delays. Using FlightAware to Make Your Next Trip Go Smoothly.",
        "submitter": "Sam Negrete",
        "submitted_text": "9 months ago",
        "votes": 43,
        "comment_count": 2,
        "lists": "popular_year",
    },
    {
        "sid": "99763",
        "title": "Maintenance Error Led to American 737 Overrun",
        "slug": "Maintenance_Error_Led_to_American_737_Overrun",
        "source_label": "(airlinegeeks.com)",
        "summary": "Misconnected brake hoses and wiring caused reduced braking on DFW landing.",
        "submitter": "Ryan E.",
        "submitted_text": "10 months ago",
        "votes": 40,
        "comment_count": 35,
        "lists": "popular_year",
    },
    {
        "sid": "100092",
        "title": "Qantas A380 Grounded After Just One Flight Following Re-Entry Into Service",
        "slug": "Qantas_A380_Grounded_After_Just_One_Flight_Following_Re_Entry_Into_Service",
        "source_label": "(www.gatechecked.com)",
        "summary": "Following almost six years in storage, a Qantas Airbus A380 was grounded just after one flight after one of the slats broke apart during flight.",
        "submitter": "Roger Anderson",
        "submitted_text": "9 months ago",
        "votes": 39,
        "comment_count": 34,
        "lists": "popular_year",
    },
    {
        "sid": "100883",
        "title": "United Airlines Cracking Down On Those Blasting Audio On Loudspeaker (Among Other Things)",
        "slug": "United_Airlines_Cracking_Down_On_Those_Blasting_Audio_On_Loudspeaker_Among_Other",
        "source_label": "(www.gatechecked.com)",
        "summary": "In United Airlines' update contract of carriage, they are cracking down problematic issues like playing audio without headphones, viewing offensive content and video calling.",
        "submitter": "Roger Anderson",
        "submitted_text": "6 months ago",
        "votes": 39,
        "comment_count": 22,
        "lists": "popular_year",
    },
    {
        "sid": "99770",
        "title": "UPS pilots mourn loss of colleagues killed in plane crash",
        "slug": "UPS_pilots_mourn_loss_of_colleagues_killed_in_plane_crash",
        "source_label": "(www.freightwaves.com)",
        "summary": "The UPS pilots’ union is helping members and families of the victims cope with last week’s tragic plane crash.",
        "submitter": "Eric Kulisch",
        "submitted_text": "10 months ago",
        "votes": 38,
        "comment_count": 5,
        "lists": "popular_year",
    },
]
