"""Build-time, source-informed guidance for the 1 April 2025 fixture.

HTTP handlers read GuidanceSection rows, never this module. These are edited
summaries, not a complete GOV.UK archive. See CONTENT_SOURCES.md for provenance.
All markup and local URLs here are trusted source code, never user input.
"""
import re
from html import escape


def link(slug, text, part=None):
    return f'<a href="/guidance/{slug}' + (f'/{part}' if part else '') + f'">{text}</a>'


def table(caption, headers, rows):
    return '<table><caption>' + caption + '</caption><thead><tr>' + ''.join(f'<th scope="col">{v}</th>' for v in headers) + '</tr></thead><tbody>' + ''.join('<tr>'+''.join(f'<td>{v}</td>' for v in row)+'</tr>' for row in rows)+'</tbody></table>'


INCOME = 'income-tax-rates-and-personal-allowances'
PENSION = 'the-new-state-pension'
SA = 'self-assessment-deadlines'
CGT = 'capital-gains-tax-what-you-pay-it-on-rates-and-allowances'
PASSPORT = 'apply-for-or-renew-an-adult-passport'
BLUE = 'apply-for-or-renew-a-blue-badge'
CHILD = 'child-benefit-eligibility'
VISA = 'skilled-worker-visa'
DRIVING = 'book-your-driving-test'
TRAVEL = 'foreign-travel-advice'
VOTE = 'register-to-vote'

# (multipart, [(slug, heading, body), ...]). Service pages retain in-page
# contents; guides use separate parts and previous/next navigation.
GUIDES = {
INCOME: (True, [
('current-rates-and-allowances','Rates and allowances for 2024 to 2025',
'''<p>How much Income Tax you pay depends on how much of your income is above your Personal Allowance and how much falls within each tax band. A tax year runs from 6 April to 5 April.</p>
<h3>Your tax-free Personal Allowance</h3><p>The standard Personal Allowance is £12,570 per year. This is the amount of income you normally do not have to pay tax on.</p><p>Your allowance may be bigger if you claim Marriage Allowance or Blind Person’s Allowance. It is smaller if your adjusted net income is over £100,000.</p>'''+table('Income Tax bands: England, Wales and Northern Ireland', ['Band','Income with the standard allowance','Tax rate'], [('Personal Allowance','Up to £12,570','0%'),('Basic rate','£12,571 to £50,270','20%'),('Higher rate','£50,271 to £125,140','40%'),('Additional rate','Over £125,140','45%')])+'''<p>These bands assume you receive the standard Personal Allowance. Scottish Income Tax bands differ for wages, pensions and most other taxable income. Savings interest and dividends have separate rules.</p><p>The higher rate is charged only on income within that band, not on all your income.</p>'''+link(INCOME,'Read about income over £100,000','income-over-100000')),
('income-over-100000','Income over £100,000',
'''<p>Your Personal Allowance goes down by £1 for every £2 that your adjusted net income is above £100,000. It is zero if your adjusted net income is £125,140 or more.</p><h3>Adjusted net income</h3><p>This is your total taxable income before Personal Allowances, less certain tax reliefs. It can include earnings, profits, pensions, taxable benefits, savings interest, dividends and rental income.</p><p>Some pension contributions and Gift Aid donations reduce adjusted net income. Use adjusted net income, rather than simply your salary, when checking whether your allowance is reduced.</p><div class="inset">A reduced allowance means more of your income is taxable. The standard allowance shown in the rates table is not automatically available to everyone.</div><h3>Check the tax you are paying</h3><p>If your income has changed, check the estimate HMRC holds for you. You may need to update your tax code.</p>'''+link('check-your-income-tax-for-the-current-year','Check your Income Tax for the current year')),
('previous-tax-years','Previous tax years',
'''<p>Use the figures for the year in which you received the income. This mirror’s reference date is 1 April 2025.</p>'''+table('Standard Personal Allowance', ['Tax year','Annual allowance'], [('2024 to 2025','£12,570'),('2023 to 2024','£12,570'),('2022 to 2023','£12,570')])+'''<p>The standard allowance does not establish your individual entitlement. Income over £100,000 and other allowances can change it. Check the rules for the relevant year before amending a tax return.</p>''')]),
PENSION: (True,[
('eligibility','Eligibility',
'''<p>You can claim the new State Pension when you reach State Pension age if you are a man born on or after 6 April 1951 or a woman born on or after 6 April 1953. People born earlier normally come under the basic State Pension rules.</p><h3>Your National Insurance record</h3><p>You usually need at least 10 qualifying years on your National Insurance record to get any new State Pension. The years do not have to be consecutive.</p><p>A qualifying year can come from:</p><ul><li>working and paying National Insurance contributions</li><li>getting National Insurance credits, for example while unemployed, ill or caring for a child</li><li>paying voluntary National Insurance contributions</li></ul><p>Time spent living or working abroad may help you meet the minimum qualifying period. The amount you receive depends on your record.</p>'''+link(PENSION,'Find out how much you could get', 'what-youll-get')),
('what-youll-get',"What you’ll get",
'''<p>The full new State Pension is <strong>£221.20 per week</strong> for the 2024 to 2025 tax year. Your own amount depends on your National Insurance record.</p><h3>If your National Insurance record started after April 2016</h3><p>You need 35 qualifying years for the full new State Pension. If you have between 10 and 35 qualifying years, your pension is based on the number of years you have.</p><h3>If your record started before April 2016</h3><p>Transitional rules apply. A starting amount was calculated under both the old and new rules. Being contracted out before 2016 can mean you need more than 35 qualifying years to get the full rate.</p><p>If your starting amount was above the full new State Pension, the extra is a protected payment. Do not assume that everyone with 35 years receives exactly the same amount.</p><h3>Check your forecast</h3><p>A forecast tells you how much you could get, when you can get it and whether you can increase it.</p>'''+link('check-your-state-pension-forecast','Check your State Pension forecast')),
('how-to-claim','How to claim',
'''<p>You do not get the State Pension automatically. You must claim it.</p><p>You should receive a letter no later than 2 months before you reach State Pension age. The letter explains what to do. You can claim online, by phone or by post.</p><p>If you have not received a letter and you are within 3 months of reaching State Pension age, you can request an invitation code.</p><h3>Before you claim</h3><p>Have your National Insurance number, bank or building society details and the dates of time spent living or working abroad ready. Claiming online also requires the invitation code.</p><p>You can defer your State Pension by not claiming it. Deferring can increase the amount you get later.</p>'''),
('when-youre-paid',"When you’re paid",
'''<p>Your State Pension is normally paid every 4 weeks into an account of your choice. You are paid in arrears, for the previous 4 weeks.</p><p>Your first payment should arrive no later than 5 weeks after the date you choose. You may receive a part payment before your first full payment.</p>'''+table('Payment day', ['Last 2 digits of National Insurance number','Day paid'], [('00 to 19','Monday'),('20 to 39','Tuesday'),('40 to 59','Wednesday'),('60 to 79','Thursday'),('80 to 99','Friday')])+'''<p>If your payment day is a bank holiday, you will normally be paid on the last working day before it. The weekly pension rate is different from the frequency of payment.</p>''')]),
SA: (True,[
('overview','Overview',
'''<p>Self Assessment is a system HM Revenue and Customs (HMRC) uses to collect Income Tax. Tax is usually deducted automatically from wages, pensions and savings. People and businesses with other income must report it in a tax return.</p><h3>Before you send a return</h3><p>Check whether you need to file and whether you are already registered. Allow time to get access to your online account before the deadline.</p><ol><li>Check whether you need to send a tax return.</li><li>Register if you are sending a return for the first time.</li><li>Keep records of your income and expenses.</li><li>Send the return and pay any tax due.</li></ol><p>You can use an accountant or tax adviser to help. You remain responsible for keeping records and meeting the deadlines.</p>'''+link('register-for-self-assessment','Register for Self Assessment')),
('deadlines','Deadlines',
'''<p>The tax year runs from 6 April to 5 April the following year. The deadlines below are for the tax year ending 5 April 2025.</p>'''+table('Self Assessment: 2024 to 2025', ['What you need to do','Deadline'], [('Tell HMRC if you need to register','5 October 2025'),('Send a paper tax return','Midnight 31 October 2025'),('Send an online tax return','Midnight 31 January 2026'),('Pay the tax you owe','Midnight 31 January 2026')])+'''<p>The usual online filing deadline is 31 January following the end of the tax year. The paper deadline is earlier. If HMRC asks you to send a return late, your letter may give a different filing deadline.</p><h3>Payments on account</h3><p>If you make payments on account, a second payment is due on 31 July. This is not a second filing deadline.</p><p>You may be able to have tax collected through your PAYE tax code if you file online by 30 December and meet the other conditions.</p>'''+link('file-your-self-assessment-tax-return','File your Self Assessment tax return')),
('penalties','Penalties',
'''<p>You will get a penalty if you need to send a tax return and miss the deadline. File as soon as possible even if you cannot pay all the tax immediately.</p>'''+table('Late filing penalties', ['How late the return is','Penalty'], [('Up to 3 months','£100 fixed penalty, even if you owe no tax or paid on time'),('More than 3 months','An additional £10 a day for up to 90 days, maximum £900'),('6 months','A further £300 or 5% of the tax due, whichever is greater'),('12 months','A further £300 or 5% of the tax due, whichever is greater; more in serious cases')])+'''<h3>Paying tax late</h3><p>Late payment is separate from late filing. Interest is charged on unpaid tax. Additional late payment penalties can also apply.</p><details><summary>If you have a reasonable excuse</summary><p>You can appeal a penalty if you have a reasonable excuse, such as a serious illness that prevented you from filing. File the return as soon as you are able. An appeal is not an automatic cancellation.</p></details>'''+link('pay-your-self-assessment-tax-bill','Ways to pay your Self Assessment tax bill')),
('records','Records and sending your return',
'''<p>Keep records so you can report the correct income and claim allowable expenses. You do not usually send the records with the return, but HMRC can ask to see them.</p><ul><li>Employment income: P60, P45 and benefits information such as P11D.</li><li>Self-employment: sales, expenses and business records.</li><li>Other income: bank interest, dividends, property income and pensions.</li></ul><p>Check your Unique Taxpayer Reference (UTR) and online account access before starting. Save a copy of your completed return and calculation.</p>'''+link('file-your-self-assessment-tax-return','Send your return online')+'<p>'+link('pay-your-self-assessment-tax-bill','Check payment methods and processing times')+'</p>')]),
'vat-rates': (False,[
('rates','VAT rates',
'''<p>VAT is charged on most goods and services provided by VAT-registered businesses in the UK. The rate depends on the goods or services supplied.</p>'''+table('Current VAT rates', ['Rate','Percentage','Examples'], [('Standard','20%','Most goods and services'),('Reduced','5%','Some goods and services, such as home energy and children’s car seats'),('Zero','0%','Most food and children’s clothes')])+'''<p>These are examples, not a complete list. Some supplies have special conditions or exceptions. The standard rate has been 20% since 4 January 2011.</p>'''),
('zero-and-exempt','Zero-rated and exempt supplies',
'''<p>Zero-rated supplies are taxable supplies charged at 0%. A VAT-registered business may normally reclaim VAT on costs relating to them.</p><p>Exempt supplies are different. You do not charge VAT on them and you cannot normally reclaim VAT on related costs. Examples include certain financial services and education.</p><div class="inset">A zero rate does not mean that a sale is outside the VAT system. Keep records and apply the correct treatment to each supply.</div>'''),
('registration','VAT registration',
'''<p>Registration depends on taxable turnover. Taxable turnover includes standard-rated, reduced-rated and zero-rated sales.</p><p>If you sell a mixture of supplies, check each category before calculating taxable turnover. You can also register voluntarily in some circumstances.</p>'''+link('register-for-vat','Check when you must register for VAT'))]),
CGT: (True,[
('overview','Overview',
'''<p>Capital Gains Tax is a tax on the profit when you sell or dispose of something that has increased in value. It is the gain you make that is taxed, not the whole amount you receive.</p><p>Disposing of an asset can include selling it, giving it away, exchanging it or receiving compensation for it.</p><h3>Work out whether you need to pay</h3><ol><li>Check whether the asset is taxable.</li><li>Work out your gain and deduct allowable costs and losses.</li><li>Check your tax-free allowance.</li><li>Apply the rate for the type of gain and date of disposal.</li><li>Report and pay any tax due.</li></ol><p>You generally do not pay tax on gifts to your spouse or civil partner or to charity, although exceptions apply.</p>'''),
('what-you-pay-it-on','What you pay it on',
'''<p>You may have to pay Capital Gains Tax on gains from personal possessions worth £6,000 or more, property that is not your main home, shares outside an ISA or PEP, and business assets.</p><h3>Your home</h3><p>You do not usually pay tax when selling your main home if it qualifies for Private Residence Relief. You may have to pay if you let it out, used part exclusively for business or it has very large grounds.</p><h3>Assets you do not usually pay tax on</h3><ul><li>Your private car, including a classic car.</li><li>Gifts to UK registered charities.</li><li>UK government gilts and Premium Bonds.</li><li>Betting, lottery or pools winnings.</li></ul><p>These exemptions do not replace checking the rules for your particular asset.</p>'''),
('allowances','Tax-free allowances',
'''<p>For the 2024 to 2025 tax year, the annual exempt amount is <strong>£3,000 for individuals</strong>. It is £1,500 for most trustees.</p><p>You pay tax on total taxable gains above your allowance after deducting allowable losses. You cannot carry unused allowance into another tax year.</p><p>Married couples and civil partners each have their own allowance, but transferring assets can have tax consequences. Keep records of the original cost and any transfer.</p><p>Different reliefs may apply to business assets. The annual exempt amount is separate from your Income Tax Personal Allowance.</p>'''),
('rates','Capital Gains Tax rates',
'''<p>The rate depends on your taxable income, the type of gain and when you disposed of the asset.</p>'''+table('Main rates for individuals in 2024 to 2025', ['Disposal','Within unused basic rate band','Above basic rate band'], [('Other chargeable assets before 30 October 2024','10%','20%'),('Other chargeable assets from 30 October 2024','18%','24%'),('Residential property','18%','24%')])+'''<p>Add taxable gains after allowances to your taxable income to work out how much of the gain falls within the basic rate band. Higher and additional rate taxpayers normally pay the higher rate on the whole taxable gain.</p><p>Carried interest and gains qualifying for specific business reliefs have separate rules.</p>'''),
('reporting','Reporting and paying',
'''<p>If you sell UK residential property and have Capital Gains Tax to pay, you normally must report and pay it within 60 days of completion.</p><p>Other gains can be reported through Self Assessment. Keep calculations, purchase and sale records and details of allowable costs.</p>'''+link('report-and-pay-your-capital-gains-tax','Report and pay Capital Gains Tax on UK property'))]),
PASSPORT: (False,[
('before-you-start','Before you start',
'''<p>You can apply for, renew, replace or update a British passport online. HM Passport Office runs the service.</p><p>You will need a digital photo and a debit or credit card. Depending on your application, you may also need your old passport, identity documents or someone to confirm your identity.</p><p>You must be 16 or over to apply for an adult passport. There is a different service for a child’s passport.</p><div class="inset">Do not book travel until you have a valid passport. Your new passport will have a different number.</div>'''+link('passport-photos','Check the digital photo requirements')),
('fees','Fees and ways to apply',
'''<p>For a standard 34-page adult passport, the fees in this mirror’s 1 April 2025 snapshot are:</p>'''+table('Adult passport application fees', ['Method','Fee'], [('Online','£88.50'),('Paper form by post','£100')])+'''<p>Different fees apply to frequent traveller passports and urgent services. The fee covers processing your application and is not refunded if it is refused.</p>'''+link('passport-fees','Compare passport fees and application options')),
('renewing','Renewing your passport',
'''<p>You can renew an adult passport if your old passport has expired or has less time left than you need for travel. Check entry requirements before you travel: some countries require additional validity.</p><p>When renewing, provide the details of your old passport and send it to HM Passport Office when instructed. A new photo is required even if your appearance has not changed.</p><p>Lost or stolen passports must be reported. Do not use a passport that has been cancelled.</p>'''+link('get-a-passport-urgently','Get a passport urgently')),
('other-ways','Other ways to apply',
'''<p>You can collect a paper form from a Post Office that offers passport services and apply by post. You will need printed photos that meet the passport rules.</p><p>Some Post Offices offer Check and Send for an additional fee. They can check the paper application or help with an online application.</p><details><summary>About applying in this mirror</summary><p>This offline mirror provides guidance and preparation information. It does not send passport applications or take payments. Use the information here to prepare an application; there is no live government submission service.</p></details>''')]),
'passport-photos': (False,[
('digital','Digital photos',
'''<p>You need a new photo whenever you apply for a passport, even if your appearance has not changed. It must have been taken in the last month.</p><p>You can get a digital photo from a photo booth or shop before applying. Some shops give you a code to add the photo to your online application.</p><p>Your photo must be clear and in focus, in colour and unaltered by computer software. It must be at least 600 pixels wide and 750 pixels tall, and between 50KB and 10MB.</p>'''),
('appearance','What your photo must show',
'''<ul><li>Your head, shoulders and upper body with no other objects or people.</li><li>A plain light-coloured background.</li><li>Your face looking straight at the camera with a plain expression and mouth closed.</li><li>Your eyes open and visible, with no hair across them.</li></ul><p>Do not wear a head covering unless it is for religious or medical reasons. Do not wear sunglasses or tinted glasses. Avoid reflections and frames covering your eyes.</p><p>Different rules apply to babies and very young children.</p>'''),
('printed','Printed photos',
'''<p>For a paper application, provide 2 identical printed photos measuring 45 millimetres high by 35 millimetres wide. Do not cut down a larger photo.</p><p>Printed photos must be professionally printed, clear and in focus, and without creases or tears.</p>'''+link(PASSPORT,'Return to adult passport applications'))]),
'passport-fees': (False,[
('standard','Standard passports', table('Fees at 1 April 2025', ['Applicant','Online (34 pages)','Paper (34 pages)'], [('Adult aged 16 or over','£88.50','£100'),('Child under 16','£57.50','£69')])+'''<p>The method of application and passport size affect the cost. Applications from outside the UK have separate fees and delivery charges.</p>'''),
('urgent','Urgent applications',
'''<p>Urgent applications use separate services with higher fees and eligibility conditions. Check whether you need an appointment and which documents to bring.</p>'''+link('get-a-passport-urgently','Check urgent passport services')+'<p>'+link(PASSPORT,'Prepare an adult passport application')+'</p>')]),
BLUE: (False,[
('overview','Apply or renew',
'''<p>A Blue Badge helps people with disabilities or health conditions park closer to their destination. You can apply for yourself, someone else or an organisation.</p><p>You can apply or renew online through your local council. There is a separate application process in Northern Ireland.</p>'''+table('Blue Badge fees', ['Country','Maximum fee'], [('England','£10'),('Scotland','£20'),('Wales','Free')])+'''<p>Badges usually last up to 3 years. You must reapply before your current badge expires: renewal is not automatic.</p>'''),
('eligibility','Check eligibility',
'''<p>Some people qualify automatically because they receive certain disability benefits at the qualifying rate. Other people may be eligible after a council assessment of how their condition affects walking or journeys.</p><p>Having a disability does not by itself guarantee a badge. Your council considers the evidence you provide.</p>'''+link('blue-badge-eligibility','Read the eligibility and assessment guidance')),
('documents','What you need to apply',
'''<p>Prepare a recent digital photo showing your head and shoulders. You will also need a photo or scan of:</p><ul><li>proof of identity, such as a passport or driving licence</li><li>proof of address, such as a Council Tax bill</li><li>proof of benefits, if you receive any</li></ul><p>Have your National Insurance number if you have one, and the details of your existing badge if you are reapplying.</p><p>You can save an online application and return to it later. How you pay depends on your council.</p>'''),
('decision','After you apply',
'''<p>Your local council makes the decision. It may request more evidence or an assessment. Allow time for the application to be processed before an existing badge expires.</p><p>If your application is refused, the council should explain why. Ask the council to reconsider if you believe important information was not taken into account.</p><details><summary>Application service in this mirror</summary><p>This mirror explains the application process. It does not submit applications to a council or collect personal documents.</p></details>''')]),
'blue-badge-eligibility': (False,[
('automatic','People who may qualify automatically',
'''<p>In England, qualifying criteria include receiving the higher rate mobility component of Disability Living Allowance, being registered blind, or scoring 8 points or more under the moving around activity of Personal Independence Payment (PIP).</p><p>Some people awarded 10 points specifically under descriptor E of the PIP planning and following journeys activity also qualify. Not every PIP award meets this rule.</p><p>Rules differ in Scotland, Wales and Northern Ireland. Check the rules for the country where you live.</p>'''),
('assessment','People who may qualify after assessment',
'''<p>Your council may assess your application if you cannot walk, have very considerable difficulty walking, or experience very considerable difficulty during journeys, including some non-visible disabilities.</p><p>Describe how the condition affects your journeys and provide supporting evidence. A diagnosis alone does not tell the council how severely you are affected.</p>'''+link(BLUE,'Check the application documents and renewal process'))]),
VISA: (True,[
('overview','Overview',
'''<p>A Skilled Worker visa lets you come to or stay in the UK to do an eligible job with an approved employer. The Home Office publishes this guidance.</p><h3>How long you can stay</h3><p>Your visa can last for up to 5 years before you need to extend it. You must apply to extend or update your visa when it expires or if you change jobs or employer.</p><p>You may be able to apply to settle permanently after 5 years if you meet the requirements.</p><h3>What you can and cannot do</h3><p>You can work in an eligible job, study and bring eligible dependants. You cannot claim most public funds. Separate rules apply to additional work.</p><p>The following pages describe the general route at the mirror’s 1 April 2025 reference date. Other routes may apply to healthcare workers or people switching visa categories.</p>'''),
('your-job','Your job',
'''<p>To qualify you need a job offer from a UK employer approved by the Home Office, a certificate of sponsorship from that employer, an eligible occupation and the required salary.</p><h3>Approved sponsor</h3><p>Your employer must assign a certificate of sponsorship. This is an electronic record with a reference number, not a paper certificate.</p><p>You must apply for the visa within 3 months of getting your certificate of sponsorship. It contains details of your job and proposed start date.</p><h3>Salary</h3><p>For the general route in this 1 April 2025 snapshot, the usual threshold is £38,700 per year or the going rate for your occupation, whichever is higher. Different thresholds and transitional rules apply to some applicants.</p><p>Meeting a salary threshold alone does not make a job eligible. Check the occupation and sponsorship requirements too.</p>'''),
('knowledge-of-english','Knowledge of English',
'''<p>You usually need to prove that you can read, write, speak and understand English. The general Skilled Worker requirement at this mirror’s reference date is level B1 on the Common European Framework of Reference for Languages.</p><p>You may prove this with an approved English language test or an eligible qualification taught in English. Some nationalities are exempt from proving English.</p><p>If you have already proved your English in a previous successful application, you may not need to prove it again.</p>'''),
('documents','Documents you need to apply',
'''<p>You will need your certificate of sponsorship reference number, proof of English and a valid passport or other document showing your identity and nationality.</p><p>You also need your job title, annual salary, occupation code and employer’s name and sponsor licence number. Ask your employer for these details.</p><h3>Other evidence</h3><p>Depending on your circumstances, you may need evidence of personal savings, proof of your relationship to dependants, a tuberculosis test result or a criminal record certificate for certain jobs.</p><p>Documents that are not in English or Welsh need a certified translation. Do not assume every applicant must supply every item in the conditional list.</p>'''),
('extend','Extend your visa',
'''<p>You can usually apply to extend if you still have the same job, occupation code and employer, and continue to meet the salary requirements.</p><p>Apply before your current visa expires. You must be in the UK to extend.</p><p>Changing employer normally requires an application to update your visa and a new certificate of sponsorship. Do not treat an extension as automatic permission to start a different job.</p><p>Dependants apply separately to extend their permission. Their visas do not extend automatically with yours.</p>''')]),
DRIVING: (False,[
('book','Book a practical driving test',
'''<p>Use the Driver and Vehicle Standards Agency (DVSA) booking service for practical tests in England, Scotland and Wales. Northern Ireland has a different booking service.</p><p>You must usually have passed your theory test before booking a practical car test. A theory test booking is a different service.</p>'''+table('Car practical test fees', ['Appointment','Cost'], [('Weekday','£62'),('Evening, weekend or bank holiday','£75')])+'''<p>The booking service is normally available from 6am to 11:40pm. Availability of appointments depends on the test centre.</p>'''),
('before','Before you start',
'''<p>Have your UK driving licence number, theory test pass details and debit or credit card ready. You can give your driving instructor’s personal reference number if you want to check their availability.</p><p>You must have lived in England, Wales or Scotland for at least 185 days in the last 12 months before the day you take your test.</p><p>Check the vehicle requirements and arrange a suitable car for test day. You must be able to read a number plate from the required distance.</p>'''+link('book-your-theory-test','Book a theory test')),
('exceptions','When you do not need a theory test',
'''<p>You do not need another theory test to book a test to upgrade from an automatic car licence to a manual car licence.</p><p>Other exceptions include a tractor test and some progressive motorcycle or vocational licence upgrades. An ordinary first car test usually requires a theory pass.</p><p>Contact DVSA for help booking an upgrade test. Check the test type before choosing the booking service.</p>'''),
('test-day','Getting ready for test day',
'''<p>Bring your UK driving licence and a suitable vehicle. Your test can be cancelled and you can lose the fee if you do not bring the required documents or the vehicle is unsuitable.</p><p>Tell the booking service about any disability or health condition that affects the test. Examiners can make arrangements to help you demonstrate your driving.</p><details><summary>Booking in this mirror</summary><p>This mirror provides booking guidance and costs. It does not reserve a real test appointment or take payment.</p></details>''')]),
VOTE: (False,[
('register','Register to vote',
'''<p>You can register online. You normally only need to register once, but must register again if you change your name, address or nationality. Registering at a new address is not automatic when you update other government records.</p><p>You will be asked for your National Insurance number, but you can still register without one. Your electoral registration office may ask for other evidence of your identity.</p><p>If you are already registered, you do not need to register again for every election. Contact your electoral registration office to check.</p>'''),
('eligibility','Who can register',
'''<p>Registration and voting ages depend on where you live. In England and Northern Ireland, you can register from age 16. In Scotland and Wales, you can register from age 14.</p><p>Being registered does not mean you can vote in every election immediately. Voting age and nationality rules depend on the election.</p><p>British and Irish citizens can register. Rules also cover eligible Commonwealth citizens and other qualifying citizens. Check the rules for your country and citizenship.</p>'''),
('paper','Register using a paper form',
'''<p>In England, Wales and Scotland, print and complete a registration form and send it to your local electoral registration office.</p><p>Northern Ireland has a different form. Return it to the Electoral Office for Northern Ireland (EONI).</p><p>Your electoral registration office can help if you cannot use the online service or need assistance completing a form.</p>'''),
('after','After you register',
'''<p>Your name and address will appear on the electoral register. They also appear on the open register unless you opt out. Opting out of the open register does not affect your right to vote.</p><p>You can vote in person, apply for a postal vote or arrange a proxy vote if eligible. Registering to vote does not automatically apply for a postal or proxy vote.</p>'''+link('voter-id-at-polling-stations','Check voter ID requirements at polling stations'))]),
CHILD: (True,[
('how-it-works','How it works',
'''<p>You can get Child Benefit if you are responsible for bringing up a child. Only one person can get Child Benefit for the same child, and there is no limit to the number of children you can claim for.</p><p>It is usually paid every 4 weeks. Claiming can also protect your National Insurance record if you are not working or do not earn enough to pay National Insurance.</p><p>If you or your partner have a higher income, you may have to pay the High Income Child Benefit Charge. You can still make a claim and opt out of payments while retaining other advantages.</p>'''+link('high-income-child-benefit-charge','Check the High Income Child Benefit Charge')),
('eligibility','Who can get Child Benefit',
'''<p>You can normally claim for a child who is under 16, or under 20 if they stay in approved education or training.</p><p>You are normally responsible for a child if you live with them or pay at least the same amount as Child Benefit towards their upkeep, such as food, clothes or pocket money.</p><h3>When a child turns 16</h3><p>Child Benefit usually stops on 31 August on or after their 16th birthday. You must tell HMRC if they continue in approved education or training.</p><p>Approved education must be full-time (on average more than 12 hours a week of supervised study or course-related work experience) and non-advanced. Examples include A levels and certain vocational qualifications.</p><p>A university degree is advanced education and does not qualify. An apprenticeship paid for by an employer does not normally qualify as approved education or training.</p><p>The child must be accepted onto the course or training before turning 19. Other rules can apply if they leave education or start work.</p>'''),
('what-youll-get',"What you’ll get",
 table('Weekly Child Benefit rates: 2024 to 2025', ['Child','Weekly amount'], [('Eldest or only child','£25.60'),('Each additional child','£16.95')])+'''<p>Payments normally arrive every 4 weeks. You may be paid weekly if you are a single parent or receive certain benefits.</p><p>If families join together, only the eldest child in the household qualifies for the higher rate. Tell HMRC about changes to your household.</p><p>People affected by the benefit cap still receive Child Benefit, but other benefits may be reduced.</p>'''),
('claim','Make a claim',
'''<p>You can claim Child Benefit 48 hours after registering the birth, or once a child comes to live with you. A claim can be backdated for up to 3 months.</p><p>Have your National Insurance number, bank details and your child’s birth or adoption information ready. You can claim online or use a paper form.</p><h3>Protecting your State Pension</h3><p>If you claim for a child under 12, you receive National Insurance credits automatically. These can protect your State Pension if you are not working or earning enough to pay National Insurance.</p>'''+link(PENSION,'Read how National Insurance credits count towards your State Pension', 'eligibility'))]),
TRAVEL: (False,[
('planning','Plan your trip',
'''<p>Foreign travel advice is provided by the Foreign, Commonwealth &amp; Development Office (FCDO). Read advice for your destination and any countries you pass through.</p><p>Country advice covers entry requirements, safety and security, health and getting help. Advice can change, so check again before travelling.</p><p>Check your passport validity, travel insurance and any visa requirements. The destination’s authorities set entry rules.</p>'''+link(PASSPORT,'Check passport renewal guidance')),
('countries','Country advice available in this mirror',
'''<ul><li>'''+link('france-travel-advice','France')+'</li><li>'+link('spain-travel-advice','Spain')+'</li></ul><p>This offline collection contains selected country advice at the reference date. It does not provide live alerts or a complete country list.</p>'),
('updates','Get updates',
'''<p>On a country advice page, select the email alerts link to see how to subscribe to updates when the advice changes. Subscribe separately for each country relevant to your trip.</p><p>Keep a copy of travel insurance details and emergency contact information. Email alerts do not replace checking advice before departure.</p>''')]),
}

for slug, country, consulate in [('france-travel-advice','France','British Embassy Paris'),('spain-travel-advice','Spain','British Embassy Madrid')]:
    GUIDES[slug] = (True,[
        ('entry-requirements','Entry requirements',f'''<p>This advice is for people travelling on a full British citizen passport to {country}. Other travellers should check with the relevant authorities.</p><h3>Passport validity</h3><p>For travel in the Schengen area, your passport must have a date of issue less than 10 years before the date you arrive and an expiry date at least 3 months after the day you plan to leave.</p><p>Check both conditions. Extra months added to an older passport’s expiry date do not extend the 10-year issue-date rule.</p><h3>Visas</h3><p>You can travel to the Schengen area for up to 90 days in any 180-day period without a visa for eligible short visits. Time in other Schengen countries counts towards the same limit.</p><p>Different rules apply if you live, work or study there.</p>'''),
        ('health','Health and insurance',f'''<p>Check travel health advice before going to {country}. Make sure your travel insurance covers your itinerary, activities and pre-existing medical conditions.</p><p>A UK Global Health Insurance Card (GHIC) or eligible European Health Insurance Card (EHIC) can help with medically necessary state healthcare. It is not a substitute for travel insurance and does not cover every cost, including repatriation.</p><p>Check the rules for taking medicines into the country. Keep medication in its original packaging and carry a copy of your prescription.</p>'''),
        ('help','Getting help',f'''<p>In an emergency, call 112 for the emergency services. Your insurer may also have an emergency assistance number.</p><p>{consulate} provides consular support for British nationals. Consular staff cannot pay your medical bills or give legal advice.</p><p>If you lose your passport, you may need an emergency travel document.</p>'''+link('get-an-emergency-travel-document','Get an emergency travel document')),
        ('email-alerts','Email alerts',f'''<p>To receive updates when FCDO advice changes, subscribe to email alerts for {country} from its travel advice page. You would enter your email address and confirm the subscription using the email sent to you.</p><p>Subscriptions are country-specific. Subscribe to each destination and transit country you need.</p><div class="inset">Live email delivery is unavailable in this offline mirror. This page explains the subscription process; no subscription has been created.</div>''')])

EXTRA_ARTICLES = [
('passport-photos','Get a passport photo','Digital and printed passport photo requirements, including size, background and appearance.',PASSPORT),
('passport-fees','Passport fees','Compare online and paper application fees for adults and children.',PASSPORT),
('blue-badge-eligibility','Who can get a Blue Badge','Automatic eligibility and council assessment of mobility and journey difficulties.',BLUE),
('france-travel-advice','France travel advice','Entry requirements, health, getting help and email updates for France.',TRAVEL),
('spain-travel-advice','Spain travel advice','Entry requirements, health, getting help and email updates for Spain.',TRAVEL),
]


def seed_guidance(db):
    from app import GuidanceArticle, GuidanceSection, Announcement
    if GuidanceSection.query.count():
        return
    for slug, title, summary, parent in EXTRA_ARTICLES:
        source = GuidanceArticle.query.filter_by(slug=parent).one()
        db.session.add(GuidanceArticle(slug=slug, title=title, summary=summary,
            body='', topic_id=source.topic_id, subtopic_id=source.subtopic_id,
            department_id=source.department_id, kind='guidance', audience='Public',
            last_updated=source.last_updated, first_published=source.first_published))
    db.session.flush()
    for slug, (multipart, sections) in GUIDES.items():
        article = GuidanceArticle.query.filter_by(slug=slug).one()
        for i, (part, title, body) in enumerate(sections):
            db.session.add(GuidanceSection(article_id=article.id, slug=part,
                title=title, body=body, sort_order=i, multipart=multipart))
        # Include all parts in search, but use the editorial summary as the snippet.
        article.body = '\n\n'.join(title+'\n'+re.sub('<[^>]+>', ' ', body) for _,title,body in sections)
    additions = {
        'spring-statement-update-on-growth-measures': [
            'The illustrative statement groups the measures into investment, planning reform and skills. Investment in infrastructure is intended to improve connections and support businesses. Planning reform is intended to help homes and infrastructure move through the planning system.',
            'Skills measures focus on helping people take up work in growing sectors. The statement describes these as steps towards longer-term growth rather than an immediate payment to every household.',
            'This is an illustrative mirror news story dated 28 March 2025. It is not a transcript of the live Spring Statement or a source for new tax rates.'
        ],
        'self-assessment-11-5-million-returns-filed-on-time': [
            'Customers who missed the deadline should send their return as soon as possible. Filing a return and paying the tax bill are separate obligations. Being unable to pay does not remove the need to file.',
            'An initial late filing penalty applies even where there is no tax to pay. Further penalties can apply the longer a return remains outstanding. The Self Assessment deadlines guidance explains the timetable and penalties.',
            'Before filing, customers should gather their employment, savings and business records. Keep a copy of the submitted return and check the payment reference before paying HMRC.'
        ],
        'nhs-app-reaches-30-million-users': [
            'Patients can use the app to book appointments, order repeat prescriptions and view their health record. These services give people a way to manage routine care without always contacting their practice by telephone.',
            'Available features depend on the GP practice and the services it has enabled. Patients may need to prove their identity before accessing personal health information. A registered user count does not mean that every user has booked an appointment.',
            'The NHS App is intended for routine services. It is not an emergency service. People should use the appropriate urgent or emergency care service when they need immediate help.'
        ],
    }
    for slug, paragraphs in additions.items():
        announcement = Announcement.query.filter_by(slug=slug).one()
        announcement.body += '\n\n' + '\n\n'.join(paragraphs)
    db.session.commit()
    # Compact the freshly populated database. build_seed.py separately sorts
    # index DDL for reproducibility; this never runs on a populated seed.
    db.session.execute(db.text('VACUUM'))
    db.session.commit()
