"""BIRKENSTOCK seed categories (generated from upstream scrape)."""

CATEGORIES = [
    ("women", "Women", "", "Sandals, shoes and clogs for women."),
    ("men", "Men", "", "Sandals, shoes and clogs for men."),
    ("kids", "Kids & Teens", "", "Sandals for little kids, big kids and teens."),
    ("women-sandals", "Women's Sandals", "women", "Two-strap, one-strap, thong and back-strap sandals."),
    ("women-shoes-clogs", "Women's Clogs", "women", "Closed-toe clogs, from Boston to Blair."),
    ("women-shoes-slippers", "Women's Slippers", "women", "Cozy slippers and shearling styles."),
    ("women-shoes-sneakers", "Women's Sneakers", "women", "Everyday sneakers on the original footbed."),
    ("women-wedges-platforms", "Women's Wedges & Platforms", "women", "Wedges, platforms and chunky silhouettes."),
    ("women-shoes", "Women's Shoes", "women", "Clogs, slippers and sneakers built on the original footbed."),
    ("men-sandals", "Men's Sandals", "men", "One-strap, two-strap, thong and back-strap sandals."),
    ("men-shoes", "Men's Shoes", "men", "Clogs, boots and low shoes built on the original footbed."),
    ("men-shoes-clogs", "Men's Clogs", "men", "Closed-toe clogs for work and off-duty."),
    ("men-shoes-boots", "Men's Boots", "men", "Boots built on the original footbed."),
    ("men-shoes-low-shoes", "Men's Low Shoes", "men", "Low shoes and lace-ups."),
    ("kids-boys-sandals", "Boys Sandals", "kids", "Water-friendly and classic sandals for boys."),
    ("kids-girls-sandals", "Girls Sandals", "kids", "Water-friendly and classic sandals for girls."),
    ("sale", "Sale", "", "Styles on sale - while supplies last."),
    ("new-arrivals", "What's New", "", "The latest arrivals."),
    ("best-sellers", "Best Sellers", "", "Iconic pairs people keep coming back to."),
    ("clogs", "The Clogs Edit", "", "Crossover straps, refined buckles, iconic clogs."),
    ("eva-sandals", "Water-friendly", "", "EVA styles for beach, pool and garden."),
    ("big-buckle-collection", "Big Buckle", "", "Statement buckles on classic silhouettes."),
    ("foot-care", "Foot & Body Care", "", "Foot care, body care, nails and kits."),
    ("professional", "Professional", "", "Slip-resistant, fluid-resistant comfort for work."),
    ("style-arizona", "Arizona Collection", "", ""),
    ("style-boston", "Boston Collection", "", ""),
    ("style-gizeh", "Gizeh Collection", "", ""),
    ("style-madrid", "Madrid Collection", "", ""),
    ("style-mayari", "Mayari Collection", "", ""),
    ("style-milano", "Milano Collection", "", ""),
    ("style-florida", "Florida Collection", "", ""),
    ("style-amsterdam", "Amsterdam Collection", "", ""),
    ("style-bend", "Bend Collection", "", ""),
    ("style-buckley", "Buckley Collection", "", ""),
    ("style-blair", "Blair Collection", "", ""),
    ("style-tokio", "Tokio Collection", "", ""),
]