"""Frozen seed content for the IGN mirror.

Generated from the stable SQLite seed database for this WebHarbor mirror.
Runtime code imports this file only while building the SQLite seed database.
"""

CONTENT_ITEMS = [{'slug': 'grand-theft-auto-controversies',
  'source_path': '/articles/grand-theft-auto-controversies',
  'title': 'The Complicated History of GTA Controversies',
  'description': "IGN's current coverage of The Complicated History of GTA Controversies, captured "
                 'from the live site for this WebHarbor mirror.',
  'section_slug': 'games',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T18:31:00Z',
  'score': None,
  'comments_count': 12,
  'duration': None,
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'article', 'complicated', 'history', 'gta', 'controversies'],
  'home_rank': 1,
  'image_path': '/static/images/content/001-grand-theft-auto-controversies.jpg'},
 {'slug': 'playstations-physical-media-free-future-isnt-just-concerning-its-offensive',
  'source_path': '/articles/playstations-physical-media-free-future-isnt-just-concerning-its-offensive',
  'title': 'PlayStation’s Physical Media-Free Future Isn’t Just Concerning, It’s Offensive',
  'description': "IGN's current coverage of PlayStation’s Physical Media-Free Future Isn’t Just "
                 'Concerning, It’s Offensive, captured from the live site for this WebHarbor '
                 'mirror.',
  'section_slug': 'games',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T16:31:00Z',
  'score': None,
  'comments_count': 29,
  'duration': None,
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'article', 'playstation', 'physical', 'media', 'free', 'future', 'isn'],
  'home_rank': 2,
  'image_path': '/static/images/content/002-playstations-physical-media-free-future-isnt-just-concerning-its-offen.jpg'},
 {'slug': 'silo-season-3-review',
  'source_path': '/articles/silo-season-3-review',
  'title': 'Silo Season 3 Review',
  'description': "IGN's current coverage of Silo Season 3 Review, captured from the live site for "
                 'this WebHarbor mirror.',
  'section_slug': 'tv',
  'content_type': 'review',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T14:31:00Z',
  'score': 8,
  'comments_count': 46,
  'duration': None,
  'platforms': [],
  'tags': ['tv', 'review', 'silo', 'season'],
  'home_rank': 3,
  'image_path': '/static/images/content/003-silo-season-3-review.jpg'},
 {'slug': 'pokemon-tcg-prismatic-evolutions-etbs-are-back-in-stock-and-under-market-price-at-amazon',
  'source_path': '/articles/pokemon-tcg-prismatic-evolutions-etbs-are-back-in-stock-and-under-market-price-at-amazon',
  'title': 'Amazon Restocks Rare Pokémon TCG Set, But is It Worth the Inflated Price?',
  'description': "IGN's current coverage of Amazon Restocks Rare Pokémon TCG Set, But is It Worth "
                 'the Inflated Price?, captured from the live site for this WebHarbor mirror.',
  'section_slug': 'deals',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T12:31:00Z',
  'score': None,
  'comments_count': 63,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['deals', 'article', 'amazon', 'restocks', 'rare', 'pok', 'mon', 'tcg'],
  'home_rank': 4,
  'image_path': '/static/images/content/004-pokemon-tcg-prismatic-evolutions-etbs-are-back-in-stock-and-under-mark.png'},
 {'slug': 'cape-fear-episode-6-recap-and-review-possum',
  'source_path': '/articles/cape-fear-episode-6-recap-and-review-possum',
  'title': 'Cape Fear Episode 6 Recap and Review',
  'description': "IGN's current coverage of Cape Fear Episode 6 Recap and Review, captured from "
                 'the live site for this WebHarbor mirror.',
  'section_slug': 'tv',
  'content_type': 'review',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T10:31:00Z',
  'score': 7,
  'comments_count': 80,
  'duration': None,
  'platforms': [],
  'tags': ['tv', 'review', 'cape', 'fear', 'episode', 'recap'],
  'home_rank': 5,
  'image_path': '/static/images/content/005-cape-fear-episode-6-recap-and-review-possum.jpg'},
 {'slug': 'anne-hathaway-quit-knocked-up-because-she-didnt-want-the-crowning-of-the-baby-to-be-visually-representative-seth-rogen-says',
  'source_path': '/articles/anne-hathaway-quit-knocked-up-because-she-didnt-want-the-crowning-of-the-baby-to-be-visually-representative-seth-rogen-says',
  'title': "Anne Hathaway Quit Knocked Up Because 'She Didn't Want the Crowning of the Baby to Be "
           "Visually Representative,' Seth Rogen Says",
  'description': "IGN's current coverage of Anne Hathaway Quit Knocked Up Because 'She Didn't Want "
                 "the Crowning of the Baby to Be Visually Representative,' Seth Rogen Says, "
                 'captured from the live site for this WebHarbor mirror.',
  'section_slug': 'movies',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T08:31:00Z',
  'score': None,
  'comments_count': 97,
  'duration': None,
  'platforms': [],
  'tags': ['movies', 'article', 'anne', 'hathaway', 'quit', 'knocked', 'because', 'she'],
  'home_rank': 6,
  'image_path': '/static/images/content/006-anne-hathaway-quit-knocked-up-because-she-didnt-want-the-crowning-of-t.jpg'},
 {'slug': 'nintendo-president-says-the-pokemon-company-will-take-measures-to-respond-to-widespread-card-scalping-issues',
  'source_path': '/articles/nintendo-president-says-the-pokemon-company-will-take-measures-to-respond-to-widespread-card-scalping-issues',
  'title': "Nintendo President Says The Pokémon Company Will 'Take Measures' to Respond to "
           'Widespread Card Scalping Issues',
  'description': "IGN's current coverage of Nintendo President Says The Pokémon Company Will 'Take "
                 "Measures' to Respond to Widespread Card Scalping Issues, captured from the live "
                 'site for this WebHarbor mirror.',
  'section_slug': 'games',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T06:31:00Z',
  'score': None,
  'comments_count': 114,
  'duration': None,
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'article', 'nintendo', 'president', 'says', 'pok', 'mon', 'company'],
  'home_rank': 7,
  'image_path': '/static/images/content/007-nintendo-president-says-the-pokemon-company-will-take-measures-to-resp.jpg'},
 {'slug': 'college-football-27-review',
  'source_path': '/articles/college-football-27-review',
  'title': 'College Football 27 Review So Far',
  'description': "IGN's current coverage of College Football 27 Review So Far, captured from the "
                 'live site for this WebHarbor mirror.',
  'section_slug': 'games',
  'content_type': 'review',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T04:31:00Z',
  'score': 8,
  'comments_count': 131,
  'duration': None,
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'review', 'college', 'football', 'far'],
  'home_rank': 8,
  'image_path': '/static/images/content/008-college-football-27-review.jpg'},
 {'slug': 'mtg-marvel-collector-boosters-amazon-sealed-in-stock',
  'source_path': '/articles/mtg-marvel-collector-boosters-amazon-sealed-in-stock',
  'title': "MTG's Rare Marvel Collector Boosters Are Available Again Online, But Expected to Sell "
           'Out Fast',
  'description': "IGN's current coverage of MTG's Rare Marvel Collector Boosters Are Available "
                 'Again Online, But Expected to Sell Out Fast, captured from the live site for '
                 'this WebHarbor mirror.',
  'section_slug': 'deals',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T02:31:00Z',
  'score': None,
  'comments_count': 148,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['deals', 'article', 'mtg', 'rare', 'marvel', 'collector', 'boosters', 'available'],
  'home_rank': 9,
  'image_path': '/static/images/content/009-mtg-marvel-collector-boosters-amazon-sealed-in-stock.png'},
 {'slug': 'nintendo-switch-summer-sale-best-deals-2026',
  'source_path': '/articles/nintendo-switch-summer-sale-best-deals-2026',
  'title': "Nintendo Summer Sale: We've Found the 10 Best Deals Still Live",
  'description': "IGN's current coverage of Nintendo Summer Sale: We've Found the 10 Best Deals "
                 'Still Live, captured from the live site for this WebHarbor mirror.',
  'section_slug': 'deals',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T00:31:00Z',
  'score': None,
  'comments_count': 165,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['deals', 'article', 'nintendo', 'summer', 'sale', 'found', 'best', 'still'],
  'home_rank': 10,
  'image_path': '/static/images/content/010-nintendo-switch-summer-sale-best-deals-2026.png'},
 {'slug': 'pokemon-tcg-first-partner-illustration-collection-series-2-is-back-in-stock-at-amazon',
  'source_path': '/articles/pokemon-tcg-first-partner-illustration-collection-series-2-is-back-in-stock-at-amazon',
  'title': "Pokémon TCG's 30th Anniversary First Partner Set is Finally Back in Stock",
  'description': "IGN's current coverage of Pokémon TCG's 30th Anniversary First Partner Set is "
                 'Finally Back in Stock, captured from the live site for this WebHarbor mirror.',
  'section_slug': 'deals',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T22:31:00Z',
  'score': None,
  'comments_count': 182,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['deals', 'article', 'pok', 'mon', 'tcg', '30th', 'anniversary', 'first'],
  'home_rank': 11,
  'image_path': '/static/images/content/011-pokemon-tcg-first-partner-illustration-collection-series-2-is-back-in-.png'},
 {'slug': 'walmart-has-the-lowest-price-on-a-geforce-rtx-5070-prebuilt-gaming-pc-in-2026',
  'source_path': '/articles/walmart-has-the-lowest-price-on-a-geforce-rtx-5070-prebuilt-gaming-pc-in-2026',
  'title': 'Walmart Has the Lowest Price on a GeForce RTX 5070 Prebuilt Gaming PC in 2026',
  'description': "IGN's current coverage of Walmart Has the Lowest Price on a GeForce RTX 5070 "
                 'Prebuilt Gaming PC in 2026, captured from the live site for this WebHarbor '
                 'mirror.',
  'section_slug': 'deals',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T20:31:00Z',
  'score': None,
  'comments_count': 199,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['deals', 'article', 'walmart', 'has', 'lowest', 'price', 'geforce', 'rtx'],
  'home_rank': 12,
  'image_path': '/static/images/content/012-walmart-has-the-lowest-price-on-a-geforce-rtx-5070-prebuilt-gaming-pc-.jpg'},
 {'slug': 'project-hail-mary-streaming-release-date-prime-video',
  'source_path': '/articles/project-hail-mary-streaming-release-date-prime-video',
  'title': 'Project Hail Mary Is Now Streaming on Prime Video',
  'description': "IGN's current coverage of Project Hail Mary Is Now Streaming on Prime Video, "
                 'captured from the live site for this WebHarbor mirror.',
  'section_slug': 'tv',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T18:31:00Z',
  'score': None,
  'comments_count': 216,
  'duration': None,
  'platforms': [],
  'tags': ['tv', 'article', 'project', 'hail', 'mary', 'now', 'streaming', 'prime'],
  'home_rank': 13,
  'image_path': '/static/images/content/013-project-hail-mary-streaming-release-date-prime-video.jpg'},
 {'slug': 'whats-new-on-hbo-max-july-2026',
  'source_path': '/articles/whats-new-on-hbo-max-july-2026',
  'title': 'Everything Coming to HBO Max in July',
  'description': "IGN's current coverage of Everything Coming to HBO Max in July, captured from "
                 'the live site for this WebHarbor mirror.',
  'section_slug': 'tv',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T16:31:00Z',
  'score': None,
  'comments_count': 233,
  'duration': None,
  'platforms': [],
  'tags': ['tv', 'article', 'everything', 'coming', 'hbo', 'max', 'july'],
  'home_rank': 14,
  'image_path': '/static/images/content/014-whats-new-on-hbo-max-july-2026.jpg'},
 {'slug': 'whats-new-on-amazon-prime-video-july-2026',
  'source_path': '/articles/whats-new-on-amazon-prime-video-july-2026',
  'title': 'Amazon Prime Video Has Some of the Best New Streaming Releases',
  'description': "IGN's current coverage of Amazon Prime Video Has Some of the Best New Streaming "
                 'Releases, captured from the live site for this WebHarbor mirror.',
  'section_slug': 'tv',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T14:31:00Z',
  'score': None,
  'comments_count': 250,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['deals', 'article', 'amazon', 'prime', 'video', 'has', 'some', 'best'],
  'home_rank': 15,
  'image_path': '/static/images/content/015-whats-new-on-amazon-prime-video-july-2026.jpg'},
 {'slug': 'whats-new-on-netflix-july-2026',
  'source_path': '/articles/whats-new-on-netflix-july-2026',
  'title': 'Netflix Is Stacked With New Shows and Movies This Month',
  'description': "IGN's current coverage of Netflix Is Stacked With New Shows and Movies This "
                 'Month, captured from the live site for this WebHarbor mirror.',
  'section_slug': 'tv',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T12:31:00Z',
  'score': None,
  'comments_count': 27,
  'duration': None,
  'platforms': [],
  'tags': ['tv', 'article', 'netflix', 'stacked', 'shows', 'movies', 'month'],
  'home_rank': 16,
  'image_path': '/static/images/content/016-whats-new-on-netflix-july-2026.jpg'},
 {'slug': 'obsession-digital-streaming-4k-blu-ray',
  'source_path': '/articles/obsession-digital-streaming-4k-blu-ray',
  'title': 'Obsession Just Landed on Digital',
  'description': "IGN's current coverage of Obsession Just Landed on Digital, captured from the "
                 'live site for this WebHarbor mirror.',
  'section_slug': 'tv',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T10:31:00Z',
  'score': None,
  'comments_count': 44,
  'duration': None,
  'platforms': [],
  'tags': ['tv', 'article', 'obsession', 'landed', 'digital'],
  'home_rank': 17,
  'image_path': '/static/images/content/017-obsession-digital-streaming-4k-blu-ray.png'},
 {'slug': 'whats-new-on-apple-tv-july-2026',
  'source_path': '/articles/whats-new-on-apple-tv-july-2026',
  'title': 'Everything New on Apple TV This Month',
  'description': "IGN's current coverage of Everything New on Apple TV This Month, captured from "
                 'the live site for this WebHarbor mirror.',
  'section_slug': 'tv',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T08:31:00Z',
  'score': None,
  'comments_count': 61,
  'duration': None,
  'platforms': [],
  'tags': ['tv', 'article', 'everything', 'apple', 'month'],
  'home_rank': 18,
  'image_path': '/static/images/content/018-whats-new-on-apple-tv-july-2026.jpg'},
 {'slug': 'the-super-mario-galaxy-movie-streaming-release-date-peacock',
  'source_path': '/articles/the-super-mario-galaxy-movie-streaming-release-date-peacock',
  'title': 'The Super Mario Galaxy Movie Is Coming to Peacock at the End of July',
  'description': "IGN's current coverage of The Super Mario Galaxy Movie Is Coming to Peacock at "
                 'the End of July, captured from the live site for this WebHarbor mirror.',
  'section_slug': 'tv',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T06:31:00Z',
  'score': None,
  'comments_count': 78,
  'duration': None,
  'platforms': [],
  'tags': ['tv', 'article', 'super', 'mario', 'galaxy', 'movie', 'coming', 'peacock'],
  'home_rank': 19,
  'image_path': '/static/images/content/019-the-super-mario-galaxy-movie-streaming-release-date-peacock.jpg'},
 {'slug': 'whats-new-on-disney-plus-july-2026',
  'source_path': '/articles/whats-new-on-disney-plus-july-2026',
  'title': 'The Disney+ Lineup Includes X-Men and New Episodes of The Simpsons',
  'description': "IGN's current coverage of The Disney+ Lineup Includes X-Men and New Episodes of "
                 'The Simpsons, captured from the live site for this WebHarbor mirror.',
  'section_slug': 'tv',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T04:31:00Z',
  'score': None,
  'comments_count': 95,
  'duration': None,
  'platforms': [],
  'tags': ['tv', 'article', 'disney', 'lineup', 'includes', 'men', 'episodes', 'simpsons'],
  'home_rank': 20,
  'image_path': '/static/images/content/020-whats-new-on-disney-plus-july-2026.jpg'},
 {'slug': 'most-anticipated-tv-shows-to-stream-in-july-2026',
  'source_path': '/articles/most-anticipated-tv-shows-to-stream-in-july-2026',
  'title': 'The 10 Most Anticipated TV Shows to Stream in July',
  'description': "IGN's current coverage of The 10 Most Anticipated TV Shows to Stream in July, "
                 'captured from the live site for this WebHarbor mirror.',
  'section_slug': 'tv',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T02:31:00Z',
  'score': None,
  'comments_count': 112,
  'duration': None,
  'platforms': [],
  'tags': ['tv', 'article', 'most', 'anticipated', 'shows', 'stream', 'july'],
  'home_rank': 21,
  'image_path': '/static/images/content/021-most-anticipated-tv-shows-to-stream-in-july-2026.jpg'},
 {'slug': 'marvel-rivals-fans-think-the-new-captain-america-skin-is-a-mod-but-its-actually-just-his-rod',
  'source_path': '/articles/marvel-rivals-fans-think-the-new-captain-america-skin-is-a-mod-but-its-actually-just-his-rod',
  'title': "Marvel Rivals Fans Think the New Captain America Skin Is a Mod, But It's Actually Just "
           'His Rod',
  'description': 'NetEase Games is celebrating the 4th of July with a Marvel Rivals swimsuit skin '
                 "that comes bundled with Captain America's big package.",
  'section_slug': 'games',
  'content_type': 'article',
  'author': 'Michael Cripe',
  'published_at': '2026-07-03T17:41:05Z',
  'score': None,
  'comments_count': 129,
  'duration': None,
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'article', 'marvel', 'rivals', 'fans', 'think', 'captain', 'america'],
  'home_rank': 22,
  'image_path': '/static/images/content/022-marvel-rivals-fans-think-the-new-captain-america-skin-is-a-mod-but-its.png'},
 {'slug': 'people-are-worried-theyll-only-see-half-of-the-odyssey-if-they-miss-out-on-imax-but-should-they-be',
  'source_path': '/articles/people-are-worried-theyll-only-see-half-of-the-odyssey-if-they-miss-out-on-imax-but-should-they-be',
  'title': 'People Are Worried They’ll Only See Half of The Odyssey If They Miss Out on Imax, But '
           'Should They Be?',
  'description': 'People are worried they’ll only see half of The Odyssey if they miss out on '
                 'Imax, but should they be?',
  'section_slug': 'movies',
  'content_type': 'article',
  'author': 'Simon Cardy',
  'published_at': '2026-07-03T16:37:37Z',
  'score': None,
  'comments_count': 146,
  'duration': None,
  'platforms': [],
  'tags': ['movies', 'article', 'people', 'worried', 'they', 'only', 'see', 'half'],
  'home_rank': 23,
  'image_path': '/static/images/content/023-people-are-worried-theyll-only-see-half-of-the-odyssey-if-they-miss-ou.png'},
 {'slug': 'the-view-from-japan-playstations-push-for-an-all-digital-future-raises-concerns-from-gamers-and-developers-including-a-well-timed-retweet-from-hideo-kojima',
  'source_path': '/articles/the-view-from-japan-playstations-push-for-an-all-digital-future-raises-concerns-from-gamers-and-developers-including-a-well-timed-retweet-from-hideo-kojima',
  'title': "The View From Japan: PlayStation's Push for an All-Digital Future Raises Concern From "
           'Gamers and Developers — and a Well-Timed Retweet From Hideo Kojima',
  'description': 'On July 1, Sony announced that no new PlayStation games will ship on-disc from '
                 'January 2028 onwards. This move to a digital-only future has sparked widespread '
                 'backlash and concerns about game preservation and ownership, including in Sony’s '
                 'homeland of Japan, where developers and fans have also expressed disapproval of '
                 'the move.',
  'section_slug': 'games',
  'content_type': 'article',
  'author': 'Wesley Yin-Poole',
  'published_at': '2026-07-03T15:32:28Z',
  'score': None,
  'comments_count': 163,
  'duration': None,
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'article', 'view', 'japan', 'playstation', 'push', 'digital', 'future'],
  'home_rank': 24,
  'image_path': '/static/images/content/024-the-view-from-japan-playstations-push-for-an-all-digital-future-raises.jpg'},
 {'slug': 'significant-pay-rises-offered-by-professor-layton-studio-if-you-correctly-answer-quizzes-about-the-companys-games',
  'source_path': '/articles/significant-pay-rises-offered-by-professor-layton-studio-if-you-correctly-answer-quizzes-about-the-companys-games',
  'title': "'Significant' Pay Rises Offered by Professor Layton Studio — if You Correctly Answer "
           "Quizzes About the Company's Games",
  'description': '"Significant" pay rises are on offer at Professor Layton developer Level-5 — if '
                 "you can correctly answer questions about the company's games.",
  'section_slug': 'games',
  'content_type': 'article',
  'author': 'Tom Phillips',
  'published_at': '2026-07-03T15:13:12Z',
  'score': None,
  'comments_count': 180,
  'duration': None,
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'article', 'significant', 'pay', 'rises', 'offered', 'professor', 'layton'],
  'home_rank': 25,
  'image_path': '/static/images/content/025-significant-pay-rises-offered-by-professor-layton-studio-if-you-correc.jpg'},
 {'slug': 'copilot-pc-buying-guide-windows-11-worth-it',
  'source_path': '/articles/copilot-pc-buying-guide-windows-11-worth-it',
  'title': 'Think You Know Windows 11? Here’s Why A Copilot+ PC Can Level Up Your Productivity',
  'description': 'Unsure if you actually need a Copilot+ PC? Our Windows 11 buying guide breaks '
                 'down the local NPU hardware, battery life gains, and features to help you decide '
                 'if it’s worth the upgrade.',
  'section_slug': 'games',
  'content_type': 'article',
  'author': 'Robert Anderson',
  'published_at': '2026-07-03T15:10:54Z',
  'score': None,
  'comments_count': 197,
  'duration': None,
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'article', 'think', 'know', 'windows', 'here', 'why', 'copilot'],
  'home_rank': 26,
  'image_path': '/static/images/content/026-copilot-pc-buying-guide-windows-11-worth-it.jpg'},
 {'slug': 'scuf-instinct-pro-xbox-controller-five-year-restrospective',
  'source_path': '/articles/scuf-instinct-pro-xbox-controller-five-year-restrospective',
  'title': 'Scuf Instinct Pro: Why I Still Choose This Xbox Controller After Five Years',
  'description': 'Rated 9/10 by IGN as the best competitive Xbox gamepad, the Scuf Instinct Pro is '
                 'still worth the investment after five years of heavy use. Here is why.',
  'section_slug': 'games',
  'content_type': 'article',
  'author': 'Robert Anderson',
  'published_at': '2026-07-03T14:51:33Z',
  'score': None,
  'comments_count': 214,
  'duration': None,
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'article', 'scuf', 'instinct', 'pro', 'why', 'still', 'choose'],
  'home_rank': 27,
  'image_path': '/static/images/content/027-scuf-instinct-pro-xbox-controller-five-year-restrospective.jpg'},
 {'slug': 'pokemon-tcg-30th-celebration-product-lineup',
  'source_path': '/articles/pokemon-tcg-30th-celebration-product-lineup',
  'title': 'Pokémon TCG: 30th Celebration Product Lineup Revealed',
  'description': "IGN's current coverage of Pokémon TCG: 30th Celebration Product Lineup Revealed, "
                 'captured from the live site for this WebHarbor mirror.',
  'section_slug': 'deals',
  'content_type': 'article',
  'author': 'Sara Heritage',
  'published_at': '2026-07-03T14:21:38Z',
  'score': None,
  'comments_count': 231,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['deals', 'article', 'pok', 'mon', 'tcg', '30th', 'celebration', 'product'],
  'home_rank': 28,
  'image_path': '/static/images/content/028-pokemon-tcg-30th-celebration-product-lineup.png'},
 {'slug': 'a-great-foundation-for-our-upcoming-projects-in-this-universe-cd-projekt-hails-cyberpunk-2077-as-it-hits-an-incredible-40-million-copies-sold',
  'source_path': '/articles/a-great-foundation-for-our-upcoming-projects-in-this-universe-cd-projekt-hails-cyberpunk-2077-as-it-hits-an-incredible-40-million-copies-sold',
  'title': "'A Great Foundation for Our Upcoming Projects in This Universe' — CD Projekt Hails "
           'Cyberpunk 2077 as It Hits an Incredible 40 Million Copies Sold',
  'description': 'CD Projekt has hailed the success of Cyberpunk 2077, announcing it has now hit '
                 'the 40 million copies sold mark. That’s up 5 million copies from the last time '
                 'the developer announced Cyberpunk 2077 sales, back in November when it hit 35 '
                 'million.',
  'section_slug': 'games',
  'content_type': 'article',
  'author': 'Wesley Yin-Poole',
  'published_at': '2026-07-03T13:09:48Z',
  'score': None,
  'comments_count': 248,
  'duration': None,
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'article', 'great', 'foundation', 'our', 'upcoming', 'projects', 'universe'],
  'home_rank': 29,
  'image_path': '/static/images/content/029-a-great-foundation-for-our-upcoming-projects-in-this-universe-cd-proje.jpg'},
 {'slug': 'after-sony-kills-ps5-discs-and-gta-6-is-just-a-code-in-a-box-xbox-is-using-halo-campaign-evolveds-physical-disc-as-a-selling-point',
  'source_path': '/articles/after-sony-kills-ps5-discs-and-gta-6-is-just-a-code-in-a-box-xbox-is-using-halo-campaign-evolveds-physical-disc-as-a-selling-point',
  'title': 'After Sony Kills PS5 Discs and GTA 6 is Just a Code in a Box, Xbox Is Using Halo: '
           "Campaign Evolved's Physical Disc as a Selling Point",
  'description': 'Microsoft is using the fact that Halo: Campaign Evolved will offer a physical '
                 'game disc in its box as a selling point.',
  'section_slug': 'games',
  'content_type': 'article',
  'author': 'Tom Phillips',
  'published_at': '2026-07-03T12:40:43Z',
  'score': None,
  'comments_count': 25,
  'duration': None,
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'article', 'after', 'sony', 'kills', 'ps5', 'discs', 'gta'],
  'home_rank': 30,
  'image_path': '/static/images/content/030-after-sony-kills-ps5-discs-and-gta-6-is-just-a-code-in-a-box-xbox-is-u.png'},
 {'slug': 'over-90-of-igns-audience-do-not-want-an-all-digital-gaming-future-but-playstation-is-unlikely-to-u-turn-on-its-decision-to-kill-discs',
  'source_path': '/articles/over-90-of-igns-audience-do-not-want-an-all-digital-gaming-future-but-playstation-is-unlikely-to-u-turn-on-its-decision-to-kill-discs',
  'title': "Over 90% of IGN's Audience Do Not Want an All-Digital Gaming Future, but PlayStation "
           'Is Unlikely to U-Turn on Its Decision to Kill Discs',
  'description': 'Sony has sparked a backlash for its decision to do away with video game discs on '
                 "PlayStation consoles from 2028 — and the IGN audience's feeling on the matter is "
                 'crystal clear, too.',
  'section_slug': 'games',
  'content_type': 'article',
  'author': 'Wesley Yin-Poole',
  'published_at': '2026-07-03T11:12:24Z',
  'score': None,
  'comments_count': 42,
  'duration': None,
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'article', 'over', 'ign', 'audience', 'not', 'want', 'digital'],
  'home_rank': 31,
  'image_path': '/static/images/content/031-over-90-of-igns-audience-do-not-want-an-all-digital-gaming-future-but-.jpg'},
 {'slug': 'as-sony-kills-physical-ps5-games-disc-production-factory-workers-are-set-to-be-reassigned',
  'source_path': '/articles/as-sony-kills-physical-ps5-games-disc-production-factory-workers-are-set-to-be-reassigned',
  'title': 'As Sony Kills Physical PS5 Games, Disc Production Factory Workers Are Set to be '
           'Reassigned',
  'description': 'Sony has already begun plans to reassign staff at a major disc production plant, '
                 'following its decision to kill off production of physical PS5 games.',
  'section_slug': 'games',
  'content_type': 'article',
  'author': 'Tom Phillips',
  'published_at': '2026-07-03T10:51:14Z',
  'score': None,
  'comments_count': 59,
  'duration': None,
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'article', 'sony', 'kills', 'physical', 'ps5', 'disc', 'production'],
  'home_rank': 32,
  'image_path': '/static/images/content/032-as-sony-kills-physical-ps5-games-disc-production-factory-workers-are-s.jpg'},
 {'slug': 'assassins-creed-black-flag-resynced-global-release-and-preload-times-confirmed',
  'source_path': '/articles/assassins-creed-black-flag-resynced-global-release-and-preload-times-confirmed',
  'title': "Assassin's Creed Black Flag Resynced Global Release and Preload Times Confirmed",
  'description': "Assassin's Creed Black Flag Resynced publisher Ubisoft has confirmed the game's "
                 'global release and preload times.',
  'section_slug': 'games',
  'content_type': 'article',
  'author': 'Tom Phillips',
  'published_at': '2026-07-03T09:57:43Z',
  'score': None,
  'comments_count': 76,
  'duration': None,
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'article', 'assassin', 'creed', 'black', 'flag', 'resynced', 'global'],
  'home_rank': 33,
  'image_path': '/static/images/content/033-assassins-creed-black-flag-resynced-global-release-and-preload-times-c.jpg'},
 {'slug': 'i-am-getting-at-least-5x-more-offers-for-video-game-adaptations-than-comic-book-adaptations-the-batman-2-co-writer-says-hollywood-is-shifting-from-superheroes-t',
  'source_path': '/articles/i-am-getting-at-least-5x-more-offers-for-video-game-adaptations-than-comic-book-adaptations-the-batman-2-co-writer-says-hollywood-is-shifting-from-superheroes-to-video-games',
  'title': "'I Am Getting at Least 5x More Offers for Video Game Adaptations Than Comic Book "
           "Adaptations' — The Batman 2 Co-Writer Says Hollywood Is Shifting From Superheroes to "
           'Video Games',
  'description': 'The co-writer of The Batman: Part II has said Hollywood is shifting from a comic '
                 'book obsession to a video game obsession.',
  'section_slug': 'games',
  'content_type': 'article',
  'author': 'Wesley Yin-Poole',
  'published_at': '2026-07-03T09:57:38Z',
  'score': None,
  'comments_count': 93,
  'duration': None,
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'article', 'getting', 'least', 'more', 'offers', 'video', 'game'],
  'home_rank': 34,
  'image_path': '/static/images/content/034-i-am-getting-at-least-5x-more-offers-for-video-game-adaptations-than-c.jpg'},
 {'slug': 'spider-man-brand-new-day-director-gives-best-look-yet-at-villains-boomerang-and-the-hand-but-are-the-photos-a-misdirect',
  'source_path': '/articles/spider-man-brand-new-day-director-gives-best-look-yet-at-villains-boomerang-and-the-hand-but-are-the-photos-a-misdirect',
  'title': 'Spider-Man: Brand New Day Director Gives Best Look Yet at Villains Boomerang and the '
           'Hand — but Are the Photos a Misdirect?',
  'description': 'Spider-Man: Brand New Day director Destin Daniel Cretton has given fans their '
                 "best look yet at more of the film's villains, including two whose roles in the "
                 'story remain particularly mysterious.',
  'section_slug': 'games',
  'content_type': 'article',
  'author': 'Tom Phillips',
  'published_at': '2026-07-03T09:04:03Z',
  'score': None,
  'comments_count': 110,
  'duration': None,
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'article', 'spider', 'man', 'brand', 'day', 'director', 'gives'],
  'home_rank': 35,
  'image_path': '/static/images/content/035-spider-man-brand-new-day-director-gives-best-look-yet-at-villains-boom.jpg'},
 {'slug': 'nintendo-brain-training-professor-explains-why-driving-a-manual-transmission-car-is-better-for-your-brain-than-an-automatic',
  'source_path': '/articles/nintendo-brain-training-professor-explains-why-driving-a-manual-transmission-car-is-better-for-your-brain-than-an-automatic',
  'title': 'Nintendo Brain Training Professor Explains Why Driving a Manual Transmission Car Is '
           'Better for Your Brain Than an Automatic',
  'description': 'A study led by Professor Ryuta Kawashima suggests that driving a manual '
                 'transmission car is beneficial for the brain, and could help prevent dementia. '
                 'Kawashima is a neuroscientist known for the Brain Age and Dr Kawashima’s Brain '
                 'Training games, released primarily on Nintendo platforms between 2003 and 2020.',
  'section_slug': 'games',
  'content_type': 'article',
  'author': 'Wesley Yin-Poole',
  'published_at': '2026-07-03T08:14:40Z',
  'score': None,
  'comments_count': 127,
  'duration': None,
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'article', 'nintendo', 'brain', 'training', 'professor', 'explains', 'why'],
  'home_rank': 36,
  'image_path': '/static/images/content/036-nintendo-brain-training-professor-explains-why-driving-a-manual-transm.jpg'},
 {'slug': 'will-nintendo-ever-stop-making-physical-games-nvc-clips',
  'source_path': '/videos/will-nintendo-ever-stop-making-physical-games-nvc-clips',
  'title': 'Will Nintendo Ever Stop Making Physical Games? - NVC Clips',
  'description': 'Following PlayStation’s bombshell news that it’s ending physical game production '
                 'in 2028, the panel discusses what that means for the future of games ownership '
                 'and if Nintendo will ever follow suit. #nintendo #gaming #switch2',
  'section_slug': 'games',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T18:00:00Z',
  'score': None,
  'comments_count': 144,
  'duration': '3:12',
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'video', 'nintendo', 'ever', 'stop', 'making', 'physical', 'nvc'],
  'home_rank': 37,
  'image_path': '/static/images/content/001-grand-theft-auto-controversies.jpg'},
 {'slug': 'everything-major-added-to-final-fantasy-7-rebirth-since-launch',
  'source_path': '/videos/everything-major-added-to-final-fantasy-7-rebirth-since-launch',
  'title': 'Everything Major Added to Final Fantasy 7 Rebirth Since Launch',
  'description': "Now is the perfect time to explore Midgar and beyond as we await spring 2027's "
                 "FF7 Revelation. Here's everything major added to Final Fantasy 7 Rebirth since "
                 'launch!Check out our fully interactive map and more FF7 Rebirth tips on our Wiki '
                 'guide: https://www.ign.com/wikis/final-fantasy-7-rebirth',
  'section_slug': 'games',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T17:54:00Z',
  'score': None,
  'comments_count': 161,
  'duration': '3:12',
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'video', 'everything', 'major', 'added', 'final', 'fantasy', 'rebirth'],
  'home_rank': 38,
  'image_path': '/static/images/content/002-playstations-physical-media-free-future-isnt-just-concerning-its-offen.jpg'},
 {'slug': 'playstations-physical-media-free-future-isnt-just-concerning-its-offensive-video',
  'source_path': '/videos/playstations-physical-media-free-future-isnt-just-concerning-its-offensive',
  'title': 'PlayStation’s Physical Media-Free Future Isn’t Just Concerning, It’s Offensive',
  'description': "PlayStation games are going fully digital in 2028. That's not just concerning "
                 "for physical media fans - it's offensive to players everywhere. With rising "
                 'hardware prices due to AI and RAM shortages, delisted games, and future game '
                 "consoles being prohibitively expensive, we're not thrilled about the idea of a "
                 'PS6 being digital-only and having to leave our old',
  'section_slug': 'games',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T15:34:16Z',
  'score': None,
  'comments_count': 178,
  'duration': '3:12',
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'video', 'playstation', 'physical', 'media', 'free', 'future', 'isn'],
  'home_rank': 39,
  'image_path': '/static/images/content/003-silo-season-3-review.jpg'},
 {'slug': 'the-complicated-history-of-gta-controversies',
  'source_path': '/videos/the-complicated-history-of-gta-controversies',
  'title': 'The Complicated History of GTA Controversies',
  'description': "You don't become one of the biggest, most profitable media franchises in human "
                 'history without stepping on a few toes, especially when there’s literally a '
                 'violent felony in your name.Grand Theft Auto was destined to collide with '
                 'controversy. Lawsuits, international incidents, and full-on moral panics have '
                 'followed in the wake of the series’ unparalleled succ',
  'section_slug': 'games',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T15:30:00Z',
  'score': None,
  'comments_count': 195,
  'duration': '3:12',
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'video', 'complicated', 'history', 'gta', 'controversies'],
  'home_rank': 40,
  'image_path': '/static/images/content/004-pokemon-tcg-prismatic-evolutions-etbs-are-back-in-stock-and-under-mark.png'},
 {'slug': 'dragon-ball-xenoverse-2-official-future-saga-chapter-4-trailer',
  'source_path': '/videos/dragon-ball-xenoverse-2-official-future-saga-chapter-4-trailer',
  'title': 'Dragon Ball Xenoverse 2 - Official Future Saga Chapter 4 Trailer',
  'description': "Don't miss this trailer for Dragon Ball Xenoverse 2 Future Saga Chapter 4! The "
                 'finale of the Future Saga storyline, introducing new characters, new quests, new '
                 'moves, new costmes, new accessories and more! Dragon Ball Xenoverse 2 Future '
                 'Saga Chapter 4 releases July 8th 2026 for PlayStation 4 (PS4), PlayStation 5 '
                 '(PS5), Xbox One, Xbox Series X|S, Nintendo Swi',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T14:16:39Z',
  'score': None,
  'comments_count': 212,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'dragon', 'ball', 'xenoverse', 'official', 'future', 'saga'],
  'home_rank': 41,
  'image_path': '/static/images/content/005-cape-fear-episode-6-recap-and-review-possum.jpg'},
 {'slug': 'honkai-star-rail-official-in-ravages-does-the-whistle-sound-version-44-trailer',
  'source_path': '/videos/honkai-star-rail-official-in-ravages-does-the-whistle-sound-version-44-trailer',
  'title': 'Honkai: Star Rail - Official "In Ravages Does the Whistle Sound" Version 4.4 Trailer',
  'description': 'Check out the new "In Ravages Does the Whistle Sound" Version 4.4 trailer for '
                 'the strategy RPG. Honkai: Star Rail is available now on PC, iOS, Android, and '
                 'PlayStation 5 (PS5).',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T13:43:43Z',
  'score': None,
  'comments_count': 229,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'honkai', 'star', 'rail', 'official', 'ravages', 'does'],
  'home_rank': 42,
  'image_path': '/static/images/content/006-anne-hathaway-quit-knocked-up-because-she-didnt-want-the-crowning-of-t.jpg'},
 {'slug': 'is-switch-2s-second-year-starting-off-strong-nvc-819',
  'source_path': '/videos/is-switch-2s-second-year-starting-off-strong-nvc-819',
  'title': 'Is Switch 2’s Second Year Starting Off Strong? - NVC 819',
  'description': 'After the Splatoon Raiders Direct, Rhythm Heaven Groove’s release, and another '
                 'week with Star Fox, Switch 2’s summer is starting to fully take shape. Join '
                 'Logan Plant, Peer Schneider, Miranda Sanchez, and Seth Macy as they discuss if '
                 'Switch 2’s sophomore year is off to a good start. Plus, following PlayStation’s '
                 'bombshell news that it’s ending physical game ',
  'section_slug': 'games',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T13:00:00Z',
  'score': None,
  'comments_count': 246,
  'duration': '3:12',
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'video', 'switch', 'second', 'year', 'starting', 'off', 'strong'],
  'home_rank': 43,
  'image_path': '/static/images/content/007-nintendo-president-says-the-pokemon-company-will-take-measures-to-resp.jpg'},
 {'slug': 'only-nintendo-can-save-physical-games-next-gen-console-watch',
  'source_path': '/videos/only-nintendo-can-save-physical-games-next-gen-console-watch',
  'title': 'Only Nintendo Can Save Physical Games - Next-Gen Console Watch',
  'description': 'This week we got the surprise announcement from Sony that it is ending '
                 'production of PlayStation discs in early 2028. So in 18 months, going forward '
                 'PlayStation will be an all-digital ecosystem. Your existing discs will work in '
                 'your PS5 if it has a disc drive, but the PlayStation 6 will presumably not play '
                 "discs at all. We expect Xbox's Project Helix to go t",
  'section_slug': 'games',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T13:00:00Z',
  'score': None,
  'comments_count': 23,
  'duration': '3:12',
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'video', 'only', 'nintendo', 'can', 'save', 'physical', 'next'],
  'home_rank': 44,
  'image_path': '/static/images/content/008-college-football-27-review.jpg'},
 {'slug': 'avatar-the-last-airbender-cast-take-the-true-avatar-challenge-part-4',
  'source_path': '/videos/avatar-the-last-airbender-cast-take-the-true-avatar-challenge-part-4',
  'title': 'Avatar: The Last Airbender Cast Take the True Avatar Challenge Part 4',
  'description': "IGN's current coverage of Avatar: The Last Airbender Cast Take the True Avatar "
                 'Challenge Part 4, captured from the live site for this WebHarbor mirror.',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T01:56:29Z',
  'score': None,
  'comments_count': 40,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'avatar', 'last', 'airbender', 'cast', 'take', 'true'],
  'home_rank': 45,
  'image_path': '/static/images/content/009-mtg-marvel-collector-boosters-amazon-sealed-in-stock.png'},
 {'slug': 'avatar-the-last-airbender-cast-take-the-true-avatar-challenge-part-3',
  'source_path': '/videos/avatar-the-last-airbender-cast-take-the-true-avatar-challenge-part-3',
  'title': 'Avatar: The Last Airbender Cast Take the True Avatar Challenge Part 3',
  'description': "IGN's current coverage of Avatar: The Last Airbender Cast Take the True Avatar "
                 'Challenge Part 3, captured from the live site for this WebHarbor mirror.',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T01:56:04Z',
  'score': None,
  'comments_count': 57,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'avatar', 'last', 'airbender', 'cast', 'take', 'true'],
  'home_rank': 46,
  'image_path': '/static/images/content/010-nintendo-switch-summer-sale-best-deals-2026.png'},
 {'slug': 'ian-ousley-on-sokkas-iconic-cactus-juice-scene',
  'source_path': '/videos/ian-ousley-on-sokkas-iconic-cactus-juice-scene',
  'title': "Ian Ousley On Sokka's Iconic Cactus Juice Scene",
  'description': "IGN's current coverage of Ian Ousley On Sokka's Iconic Cactus Juice Scene, "
                 'captured from the live site for this WebHarbor mirror.',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T01:55:23Z',
  'score': None,
  'comments_count': 74,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'ian', 'ousley', 'sokka', 'iconic', 'cactus', 'juice'],
  'home_rank': 47,
  'image_path': '/static/images/content/011-pokemon-tcg-first-partner-illustration-collection-series-2-is-back-in-.png'},
 {'slug': 'danger-ehren-on-his-most-famous-jackass-stunt',
  'source_path': '/videos/danger-ehren-on-his-most-famous-jackass-stunt',
  'title': 'Danger Ehren On His Most Famous Jackass Stunt',
  'description': "IGN's current coverage of Danger Ehren On His Most Famous Jackass Stunt, "
                 'captured from the live site for this WebHarbor mirror.',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T01:54:01Z',
  'score': None,
  'comments_count': 91,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'danger', 'ehren', 'his', 'most', 'famous', 'jackass'],
  'home_rank': 48,
  'image_path': '/static/images/content/012-walmart-has-the-lowest-price-on-a-geforce-rtx-5070-prebuilt-gaming-pc-.jpg'},
 {'slug': 'avatar-the-last-airbender-cast-take-the-true-avatar-challenge-part-2',
  'source_path': '/videos/avatar-the-last-airbender-cast-take-the-true-avatar-challenge-part-2',
  'title': 'Avatar: The Last Airbender Cast Take the True Avatar Challenge Part 2',
  'description': "IGN's current coverage of Avatar: The Last Airbender Cast Take the True Avatar "
                 'Challenge Part 2, captured from the live site for this WebHarbor mirror.',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T01:53:12Z',
  'score': None,
  'comments_count': 108,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'avatar', 'last', 'airbender', 'cast', 'take', 'true'],
  'home_rank': 49,
  'image_path': '/static/images/content/013-project-hail-mary-streaming-release-date-prime-video.jpg'},
 {'slug': 'avatar-the-last-airbender-cast-take-the-true-avatar-challenge-part-1',
  'source_path': '/videos/avatar-the-last-airbender-cast-take-the-true-avatar-challenge-part-1',
  'title': 'Avatar: The Last Airbender Cast Take the True Avatar Challenge Part 1',
  'description': "IGN's current coverage of Avatar: The Last Airbender Cast Take the True Avatar "
                 'Challenge Part 1, captured from the live site for this WebHarbor mirror.',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T01:52:33Z',
  'score': None,
  'comments_count': 125,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'avatar', 'last', 'airbender', 'cast', 'take', 'true'],
  'home_rank': 50,
  'image_path': '/static/images/content/014-whats-new-on-hbo-max-july-2026.jpg'},
 {'slug': 'wee-mans-favorite-jackass-stunt',
  'source_path': '/videos/wee-mans-favorite-jackass-stunt',
  'title': "Wee-Man's Favorite Jackass Stunt",
  'description': "IGN's current coverage of Wee-Man's Favorite Jackass Stunt, captured from the "
                 'live site for this WebHarbor mirror.',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-03T01:50:44Z',
  'score': None,
  'comments_count': 142,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'wee', 'man', 'favorite', 'jackass', 'stunt'],
  'home_rank': 51,
  'image_path': '/static/images/content/015-whats-new-on-amazon-prime-video-july-2026.jpg'},
 {'slug': 'schrodingers-call-official-accolades-trailer',
  'source_path': '/videos/schrodingers-call-official-accolades-trailer',
  'title': "Schrodinger's Call - Official Accolades Trailer",
  'description': "Here's a look at the Accolades Trailer for Schrodinger's Call, an emotional "
                 'narrative-driven visual novel developed by Acrobatic Chirimenjako. Players will '
                 'experience the 21 nanoseconds that exist between life and death as the world '
                 "comes to a close. Take a look at the critical reception for Schrodinger's Call, "
                 'available now for Nintendo Switch and PC (Steam',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T23:24:30Z',
  'score': None,
  'comments_count': 159,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'schrodinger', 'call', 'official', 'accolades', 'trailer'],
  'home_rank': 52,
  'image_path': '/static/images/content/016-whats-new-on-netflix-july-2026.jpg'},
 {'slug': 'the-most-immersive-way-to-play-ac-black-flag-resynced',
  'source_path': '/videos/the-most-immersive-way-to-play-ac-black-flag-resynced',
  'title': 'The Most Immersive Way to Play AC Black Flag Resynced',
  'description': "Assassin's Creed Black Flag Resynced isn't just getting a PS5 Pro patch. Ubisoft "
                 "says it's using the console to completely transform how the Caribbean looks!",
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T23:07:00Z',
  'score': None,
  'comments_count': 176,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'most', 'immersive', 'way', 'play', 'black', 'flag'],
  'home_rank': 53,
  'image_path': '/static/images/content/017-obsession-digital-streaming-4k-blu-ray.png'},
 {'slug': 'clairvoyage-the-lighthouse-official-reveal-trailer',
  'source_path': '/videos/clairvoyage-the-lighthouse-official-reveal-trailer',
  'title': 'Clairvoyage: The Lighthouse - Official Reveal Trailer',
  'description': 'Check out the Reveal Trailer for Clairvoyage: The Lighthouse, a time-loop horror '
                 'puzzle game developed by Volpe Software. Players will return to the same ten '
                 'minutes to restore the lighthouse before a ship hits the rocks. Solve puzzles, '
                 'encounter strange anomalies, and explore the stormy island on that fateful '
                 'night. Clairvoyage: The Lighthouse is coming soo',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T22:55:04Z',
  'score': None,
  'comments_count': 193,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'clairvoyage', 'lighthouse', 'official', 'reveal', 'trailer'],
  'home_rank': 54,
  'image_path': '/static/images/content/018-whats-new-on-apple-tv-july-2026.jpg'},
 {'slug': 'silver-palace-official-beta-test-gameplay-showcase-trailer',
  'source_path': '/videos/silver-palace-official-beta-test-gameplay-showcase-trailer',
  'title': 'Silver Palace - Official Beta Test Gameplay Showcase Trailer',
  'description': 'Take a look at gameplay from Silver Palace in this latest trailer for the '
                 'upcoming open-world fantasy adventure RPG. The new trailer shows us elements of '
                 'the story through the eyes of the female protagonist, while giving us a peek at '
                 'the lore, traversal, combat, a glimpse at a formidable enemy, sleuthing '
                 'gameplay, mini0games and side stories in the world of ',
  'section_slug': 'games',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T22:40:19Z',
  'score': None,
  'comments_count': 210,
  'duration': '3:12',
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'video', 'silver', 'palace', 'official', 'beta', 'test', 'gameplay'],
  'home_rank': 55,
  'image_path': '/static/images/content/019-the-super-mario-galaxy-movie-streaming-release-date-peacock.jpg'},
 {'slug': 'expeditions-samurai-official-behind-the-art-video',
  'source_path': '/videos/expeditions-samurai-official-behind-the-art-video',
  'title': "Expeditions: Samurai - Official 'Behind the Art' Video",
  'description': 'Join members of the development team at Campfire Cabal for a behind-the-scenes '
                 'look at the art direction of Expeditions: Samurai in this latest video for the '
                 'upcoming strategy RPG game. Expeditions: Samurai will be available on PC in '
                 '2026.',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T21:34:39Z',
  'score': None,
  'comments_count': 227,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'expeditions', 'samurai', 'official', 'behind', 'art'],
  'home_rank': 56,
  'image_path': '/static/images/content/020-whats-new-on-disney-plus-july-2026.jpg'},
 {'slug': 'rubber-bird-official-announcement-trailer',
  'source_path': '/videos/rubber-bird-official-announcement-trailer',
  'title': 'Rubber Bird - Official Announcement Trailer',
  'description': 'Take a look at the Announcement Trailer for Rubber Bird, a vibrant physics-based '
                 '3D platformer developed by Outretaupe. Players will overcome bite-sized levels '
                 'as a bird with elastic arms. Jump, stretch, and throw items to collect items '
                 'from level to level. Rubber Bird is coming soon to PC (Steam).',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T20:36:45Z',
  'score': None,
  'comments_count': 244,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'rubber', 'bird', 'official', 'announcement', 'trailer'],
  'home_rank': 57,
  'image_path': '/static/images/content/021-most-anticipated-tv-shows-to-stream-in-july-2026.jpg'},
 {'slug': 'strikers-club-official-release-date-trailer',
  'source_path': '/videos/strikers-club-official-release-date-trailer',
  'title': 'Strikers Club - Official Release Date Trailer',
  'description': "Here's a look at the Release Date Trailer for Strikers Club, a multiplayer "
                 'free-to-play football (soccer) game developed by Oddshot Games. Players will '
                 'take to the pitch to master advanced movements from dribbling, passing, and '
                 'shooting to outplay the opposition and attain the win. Strikers Club is '
                 'launching on July 17 for PC (Steam).',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T20:15:50Z',
  'score': None,
  'comments_count': 21,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'strikers', 'club', 'official', 'release', 'date', 'trailer'],
  'home_rank': 58,
  'image_path': '/static/images/content/022-marvel-rivals-fans-think-the-new-captain-america-skin-is-a-mod-but-its.png'},
 {'slug': 'taillights-official-reveal-trailer',
  'source_path': '/videos/taillights-official-reveal-trailer',
  'title': 'Taillights - Official Reveal Trailer',
  'description': "Don't miss the Reveal Trailer for Taillights, a physics-based co-op survival "
                 'road trip game developed by Linx Interactive. Players will hit the road to '
                 'gather supplies, repair the vehicle when necessary, and uncover strange '
                 'mysteries along the way. Survive the road in Taillights, coming soon to PC '
                 '(Steam).',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T20:03:30Z',
  'score': None,
  'comments_count': 38,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'taillights', 'official', 'reveal', 'trailer'],
  'home_rank': 59,
  'image_path': '/static/images/content/023-people-are-worried-theyll-only-see-half-of-the-odyssey-if-they-miss-ou.png'},
 {'slug': 'dont-touch-grass-official-announcement-trailer',
  'source_path': '/videos/dont-touch-grass-official-announcement-trailer',
  'title': "Don't Touch Grass - Official Announcement Trailer",
  'description': "Here's your look at the Don't Touch Grass announcement trailer for this upcoming "
                 'first-person parkour platformer game. Equipped with a high-tech exoskeleton, '
                 "attempt to save gaming in Don't Touch Grass. Jump, wall-run and slide to build "
                 'momentum. The faster you go, the more special abilities you can use. Set faster '
                 "times and remember, Don't Touch Grass. Don'",
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T19:46:52Z',
  'score': None,
  'comments_count': 55,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'don', 'touch', 'grass', 'official', 'announcement', 'trailer'],
  'home_rank': 60,
  'image_path': '/static/images/content/024-the-view-from-japan-playstations-push-for-an-all-digital-future-raises.jpg'},
 {'slug': 'beyond-the-blight-official-announcement-trailer',
  'source_path': '/videos/beyond-the-blight-official-announcement-trailer',
  'title': 'Beyond The Blight - Official Announcement Trailer',
  'description': 'Take a look at the Announcement Trailer for Beyond The Blight, a 2.5D '
                 'first-person dungeon crawler developed by Midnight Steep. Players will head into '
                 "dungeons to slay enemies, attain loot, and defeat the Blight's inception at its "
                 'core. Beyond The Blight is coming soon to PC (Steam).',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T19:46:46Z',
  'score': None,
  'comments_count': 72,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'beyond', 'blight', 'official', 'announcement', 'trailer'],
  'home_rank': 61,
  'image_path': '/static/images/content/025-significant-pay-rises-offered-by-professor-layton-studio-if-you-correc.jpg'},
 {'slug': 'the-odyssey-official-completely-in-imax-featurette',
  'source_path': '/videos/the-odyssey-official-completely-in-imax-featurette',
  'title': "The Odyssey - Official 'Completely in IMAX' Featurette",
  'description': "Take a look at the 'Completely in IMAX' Featurette for The Odyssey, the latest "
                 "mythological action retelling of Homer's tale from the mind of Christopher "
                 'Nolan. Check out the behind-the-scenes look of the process of filming the first '
                 'movie entirely in IMAX. The Odyssey is in theaters on July 17.Christopher '
                 'Nolan’s next film, The Odyssey, is a mythic action e',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T19:19:39Z',
  'score': None,
  'comments_count': 89,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'odyssey', 'official', 'completely', 'imax', 'featurette'],
  'home_rank': 62,
  'image_path': '/static/images/content/026-copilot-pc-buying-guide-windows-11-worth-it.jpg'},
 {'slug': 'maddmadd-official-trailer',
  'source_path': '/videos/maddmadd-official-trailer',
  'title': 'MADDMADD - Official Trailer',
  'description': 'Check out gameplay and more from MADDMADD in this trailer for the upcoming '
                 'third-person run-and-gun boomer shooter with fast-paced movement, beautiful '
                 'giblets and a comedic tone. Blow stuff up in your tank and then get '
                 'up-close-and-personal with your boomstick! MADDMADD will be available on PC. A '
                 'demo is out now on Steam.',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T19:19:07Z',
  'score': None,
  'comments_count': 106,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'maddmadd', 'official', 'trailer'],
  'home_rank': 63,
  'image_path': '/static/images/content/027-scuf-instinct-pro-xbox-controller-five-year-restrospective.jpg'},
 {'slug': 'unwelcome-guests-official-demo-trailer',
  'source_path': '/videos/unwelcome-guests-official-demo-trailer',
  'title': 'Unwelcome Guests - Official Demo Trailer',
  'description': 'Take a trek through the dungeon in this new Unwelcome Guests trailer for the '
                 'upcoming Mörk Borg-inspired first-person shooter game that combines brutal '
                 'dungeon runs with narrative progression and a stylized hand-drawn 3D aesthetic. '
                 'Unwelcome Guests will be available on PC. A demo is out now on Steam.',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T19:02:52Z',
  'score': None,
  'comments_count': 123,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'unwelcome', 'guests', 'official', 'demo', 'trailer'],
  'home_rank': 64,
  'image_path': '/static/images/content/028-pokemon-tcg-30th-celebration-product-lineup.png'},
 {'slug': 'dream-corps-official-launch-trailer',
  'source_path': '/videos/dream-corps-official-launch-trailer',
  'title': 'Dream Corps - Official Launch Trailer',
  'description': "Don't miss the Launch Trailer for Dream Corps, a liminal surreal horror game "
                 'developed by 98 Redd Games. Players will explore a variety of abstract '
                 'environments from the nostalgic to the vibrant. Explore the mystery of a '
                 'sinister corporation in Dream Corps, available now for macOS, SteamVR, and PC '
                 '(Steam).',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T19:00:06Z',
  'score': None,
  'comments_count': 140,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'dream', 'corps', 'official', 'launch', 'trailer'],
  'home_rank': 65,
  'image_path': '/static/images/content/029-a-great-foundation-for-our-upcoming-projects-in-this-universe-cd-proje.jpg'},
 {'slug': 'apathema-official-demo-trailer',
  'source_path': '/videos/apathema-official-demo-trailer',
  'title': 'Apathema - Official Demo Trailer',
  'description': 'Get a fresh look at Apathema in this trailer for the upcoming grunge fantasy '
                 "turn-based RPG, inspired by God Husk, Baroque, and King's Field. Cursed to "
                 'repair the inner organs of The Chasm, you fight to uncover the secrets of your '
                 'existence and end a self-devouring cycle of Apathy. Apathema will be available '
                 'on PC. A demo is out now on Steam.',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T18:51:25Z',
  'score': None,
  'comments_count': 157,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'apathema', 'official', 'demo', 'trailer'],
  'home_rank': 66,
  'image_path': '/static/images/content/030-after-sony-kills-ps5-discs-and-gta-6-is-just-a-code-in-a-box-xbox-is-u.png'},
 {'slug': 'optek-official-gameplay-trailer',
  'source_path': '/videos/optek-official-gameplay-trailer',
  'title': 'OpTek - Official Gameplay Trailer',
  'description': "Don't miss the Gameplay Trailer for OpTek, a co-op repair horror game developed "
                 'by Yesclip Games. Players will embody engineers to complete routine maintenance '
                 'work as part of the OpTek Team. Screw bolts, calibrate parts, and return to the '
                 'Panopticon alone or with friends. OpTek is coming soon to PC (Steam).',
  'section_slug': 'games',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T18:37:50Z',
  'score': None,
  'comments_count': 174,
  'duration': '3:12',
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['games', 'video', 'optek', 'official', 'gameplay', 'trailer'],
  'home_rank': 67,
  'image_path': '/static/images/content/031-over-90-of-igns-audience-do-not-want-an-all-digital-gaming-future-but-.jpg'},
 {'slug': 'neurospasm-official-demo-trailer',
  'source_path': '/videos/neurospasm-official-demo-trailer',
  'title': 'Neurospasm - Official Demo Trailer',
  'description': 'Take a look at action-packed gameplay from Neurospasm in this trailer for the '
                 'upcoming first-person roguelike horde shooter game. Hook your brain into your '
                 'computer, dive into a game inside a game, unbox and stack unique items, use up '
                 'to 6 weapons at once, kill weird fleshy enemies, and uncover what the shady '
                 'company behind the game is hiding. Neurospasm wil',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T18:36:47Z',
  'score': None,
  'comments_count': 191,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'neurospasm', 'official', 'demo', 'trailer'],
  'home_rank': 68,
  'image_path': '/static/images/content/032-as-sony-kills-physical-ps5-games-disc-production-factory-workers-are-s.jpg'},
 {'slug': 'the-henchmen-official-launch-trailer',
  'source_path': '/videos/the-henchmen-official-launch-trailer',
  'title': 'The Henchmen - Official Launch Trailer',
  'description': 'Relive the ‘90s crime sandbox alone, or with a partner by your side. Prepare for '
                 'a head-on collision of the classic and the contemporary in The Henchmen, '
                 'available now on PC. Watch The Henchmen launch trailer for this chaotic, '
                 'co-operative crime thriller game.',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T18:23:12Z',
  'score': None,
  'comments_count': 208,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'henchmen', 'official', 'launch', 'trailer'],
  'home_rank': 69,
  'image_path': '/static/images/content/033-assassins-creed-black-flag-resynced-global-release-and-preload-times-c.jpg'},
 {'slug': 'stonewards-official-demo-launch-trailer',
  'source_path': '/videos/stonewards-official-demo-launch-trailer',
  'title': 'Stonewards - Official Demo Launch Trailer',
  'description': 'Take a look at the Demo Launch Trailer for Stonewards, a co-op mining roguelite '
                 'game developed by Banana Tiger Studio. Players will command dwarves to mine for '
                 'resources, attain powerful upgrades, and defend the kingdom from monsters. '
                 'Stonewards is coming soon to PC (Steam), with a demo available now on Steam.',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T18:15:32Z',
  'score': None,
  'comments_count': 225,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'stonewards', 'official', 'demo', 'launch', 'trailer'],
  'home_rank': 70,
  'image_path': '/static/images/content/034-i-am-getting-at-least-5x-more-offers-for-video-game-adaptations-than-c.jpg'},
 {'slug': 'clown-camp-official-launch-trailer',
  'source_path': '/videos/clown-camp-official-launch-trailer',
  'title': 'Clown Camp - Official Launch Trailer',
  'description': 'Clown Camp is available now on PC. Watch the Clown Camp launch trailer for this '
                 "90's style, first-person survival horror game. Hostile clowns lurk the woods. "
                 'Fight-or-flight to uncover their gruesome secrets throughout a chilling '
                 'single-player story. Clever inventory management and resourcefulness are your '
                 'only hopes to escape the Summer of 1999 alive.',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T18:10:58Z',
  'score': None,
  'comments_count': 242,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'clown', 'camp', 'official', 'launch', 'trailer'],
  'home_rank': 71,
  'image_path': '/static/images/content/035-spider-man-brand-new-day-director-gives-best-look-yet-at-villains-boom.jpg'},
 {'slug': 'blue-wyrm-official-release-date-trailer',
  'source_path': '/videos/blue-wyrm-official-release-date-trailer',
  'title': 'Blue Wyrm - Official Release Date Trailer',
  'description': 'Blue Wyrm gets a new trailer and a release date announcement. Watch the latest '
                 'Blue Wyrm trailer to see gameplay and more from this upcoming psychedelic '
                 'first-person souls-like with a retro aesthetic and skill-heavy combat system. Do '
                 'you have what it takes to save your wife in the crypt of the Blue Wyrm? Blue '
                 'Wyrm will be available on PC on July 16, 2026.',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T18:01:36Z',
  'score': None,
  'comments_count': 19,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'blue', 'wyrm', 'official', 'release', 'date', 'trailer'],
  'home_rank': 72,
  'image_path': '/static/images/content/036-nintendo-brain-training-professor-explains-why-driving-a-manual-transm.jpg'},
 {'slug': 'company-of-heroes-3-final-stand-official-announcement-trailer',
  'source_path': '/videos/company-of-heroes-3-final-stand-official-announcement-trailer',
  'title': 'Company of Heroes 3: Final Stand - Official Announcement Trailer',
  'description': 'Watch the Company of Heroes 3: Final Stand announcement trailer for this '
                 'upcoming all-new standalone wave defense experience for solo and cooperative '
                 "play. Final Stand expands the series' signature combat with roguelite "
                 'progression that encourages experimentation, adaptation, and replayability. '
                 'Players must dig in, build layered defenses, and survive against',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T17:34:48Z',
  'score': None,
  'comments_count': 36,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'company', 'heroes', 'final', 'stand', 'official', 'announcement'],
  'home_rank': 73,
  'image_path': '/static/images/content/001-grand-theft-auto-controversies.jpg'},
 {'slug': 'virtua-fighter-crossroads-official-narrative-overview-trailer',
  'source_path': '/videos/virtua-fighter-crossroads-official-narrative-overview-trailer',
  'title': 'Virtua Fighter Crossroads - Official Narrative Overview Trailer',
  'description': 'Take a look at the Narrative Overview Trailer for Virtua Fighter Crossroads, the '
                 'upcoming installment in the hit action fighting game franchise developed by Ryu '
                 'Ga Gotoku Studio. Players can hear from key figures in the development team '
                 "about exploring the game's core narrative that sets out to provide proper "
                 'context for why the characters fight. Explore the',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T17:27:09Z',
  'score': None,
  'comments_count': 53,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos',
           'video',
           'virtua',
           'fighter',
           'crossroads',
           'official',
           'narrative',
           'overview'],
  'home_rank': 74,
  'image_path': '/static/images/content/002-playstations-physical-media-free-future-isnt-just-concerning-its-offen.jpg'},
 {'slug': 'remothered-tormented-fathers-broken-porcelain-remastered-official-announcement-trailer',
  'source_path': '/videos/remothered-tormented-fathers-broken-porcelain-remastered-official-announcement-trailer',
  'title': 'Remothered: Tormented Fathers & Broken Porcelain Remastered - Official Announcement '
           'Trailer',
  'description': "Don't miss the Announcement Trailer for Remothered: Tormented Fathers & Broken "
                 'Porcelain Remastered, two modern versions of the survival horror series '
                 'developed by Stormind Games. Players can enjoy new features with Unreal Engine 5 '
                 'technology, Lumen-based lighting, enhanced character models, and more. '
                 'Remothered: Tormented Fathers & Broken Porcelain Remaster',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T17:14:17Z',
  'score': None,
  'comments_count': 70,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos',
           'video',
           'remothered',
           'tormented',
           'fathers',
           'broken',
           'porcelain',
           'remastered'],
  'home_rank': 75,
  'image_path': '/static/images/content/003-silo-season-3-review.jpg'},
 {'slug': 'biped-2-official-version-20-update-trailer',
  'source_path': '/videos/biped-2-official-version-20-update-trailer',
  'title': 'Biped 2 - Official Version 2.0 Update Trailer',
  'description': 'Watch the latest Biped 2 trailer for this co-op puzzle platformer game for up to '
                 "four players to see what's available in version 2.0, bringing revamped puzzles, "
                 'mechanics, along with improvements and enhanced performance on Nintendo Switch '
                 '2. Biped 2 is available now on PC via Steam, PlayStation 4 (PS4), PlayStation 5 '
                 '(PS5), Xbox One, Xbox Series X/S, Ninten',
  'section_slug': 'videos',
  'content_type': 'video',
  'author': 'IGN Staff',
  'published_at': '2026-07-02T17:12:44Z',
  'score': None,
  'comments_count': 87,
  'duration': '3:12',
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['videos', 'video', 'biped', 'official', 'version', 'update', 'trailer'],
  'home_rank': 76,
  'image_path': '/static/images/content/004-pokemon-tcg-prismatic-evolutions-etbs-are-back-in-stock-and-under-mark.png'},
 {'slug': 'gta-5',
  'source_path': '/wikis/gta-5',
  'title': 'GTA 5 Guide',
  'description': "IGN's current wiki coverage for GTA 5 Guide, with walkthrough notes, tracking "
                 'steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Danielle Abraham',
  'published_at': '2026-06-27T10:31:00Z',
  'score': None,
  'comments_count': 104,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'gta'],
  'home_rank': 77,
  'image_path': '/static/images/content/005-cape-fear-episode-6-recap-and-review-possum.jpg'},
 {'slug': 'all-gta-5-cheat-codes-and-secrets-for-pc-and-console',
  'source_path': '/wikis/gta-5/All_GTA_5_Cheat_Codes_and_Secrets_For_PC_and_Console',
  'title': 'All GTA 5 Cheat Codes and Secrets For PC and Console',
  'description': "IGN's current wiki coverage for All GTA 5 Cheat Codes and Secrets For PC and "
                 'Console, with walkthrough notes, tracking steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Will Borger',
  'published_at': '2026-06-27T08:31:00Z',
  'score': None,
  'comments_count': 121,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'gta', 'cheat', 'codes', 'secrets', 'console'],
  'home_rank': 78,
  'image_path': '/static/images/content/006-anne-hathaway-quit-knocked-up-because-she-didnt-want-the-crowning-of-t.jpg'},
 {'slug': 'persona-3-reload',
  'source_path': '/wikis/persona-3-reload',
  'title': 'Persona 3 Reload Guide',
  'description': "IGN's current wiki coverage for Persona 3 Reload Guide, with walkthrough notes, "
                 'tracking steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Scott White',
  'published_at': '2026-06-27T06:31:00Z',
  'score': None,
  'comments_count': 138,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'persona', 'reload'],
  'home_rank': 79,
  'image_path': '/static/images/content/007-nintendo-president-says-the-pokemon-company-will-take-measures-to-resp.jpg'},
 {'slug': 'persona-3-reload-classroom-answers',
  'source_path': '/wikis/persona-3-reload/Persona_3_Reload_Classroom_Answers',
  'title': 'Persona 3 Reload Classroom Answers',
  'description': "IGN's current wiki coverage for Persona 3 Reload Classroom Answers, with "
                 'walkthrough notes, tracking steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Luke Reilly',
  'published_at': '2026-06-27T04:31:00Z',
  'score': None,
  'comments_count': 155,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'persona', 'reload', 'classroom', 'answers'],
  'home_rank': 80,
  'image_path': '/static/images/content/008-college-football-27-review.jpg'},
 {'slug': 'gta-online-weekly-updates',
  'source_path': '/wikis/gta-5/GTA_Online_Weekly_Updates',
  'title': 'GTA Online Weekly Updates',
  'description': "IGN's current wiki coverage for GTA Online Weekly Updates, with walkthrough "
                 'notes, tracking steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Matt Purslow',
  'published_at': '2026-06-27T02:31:00Z',
  'score': None,
  'comments_count': 172,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'gta', 'online', 'weekly', 'updates'],
  'home_rank': 81,
  'image_path': '/static/images/content/009-mtg-marvel-collector-boosters-amazon-sealed-in-stock.png'},
 {'slug': 'animal-hospital-roblox',
  'source_path': '/wikis/animal-hospital-roblox',
  'title': 'Animal Hospital [Roblox] Guide',
  'description': "IGN's current wiki coverage for Animal Hospital [Roblox] Guide, with walkthrough "
                 'notes, tracking steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Sarah Thwaites',
  'published_at': '2026-06-27T00:31:00Z',
  'score': None,
  'comments_count': 189,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'animal', 'hospital', 'roblox'],
  'home_rank': 82,
  'image_path': '/static/images/content/010-nintendo-switch-summer-sale-best-deals-2026.png'},
 {'slug': 'all-anomalies',
  'source_path': '/wikis/animal-hospital-roblox/All_Anomalies',
  'title': 'All Anomalies',
  'description': "IGN's current wiki coverage for All Anomalies, with walkthrough notes, tracking "
                 'steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Jesse Schedeen',
  'published_at': '2026-06-26T22:31:00Z',
  'score': None,
  'comments_count': 206,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'anomalies'],
  'home_rank': 83,
  'image_path': '/static/images/content/011-pokemon-tcg-first-partner-illustration-collection-series-2-is-back-in-.png'},
 {'slug': 'crystal-caves',
  'source_path': '/wikis/donkey-kong-64/Crystal_Caves',
  'title': 'Crystal Caves',
  'description': "IGN's current wiki coverage for Crystal Caves, with walkthrough notes, tracking "
                 'steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Tom Phillips',
  'published_at': '2026-06-26T20:31:00Z',
  'score': None,
  'comments_count': 223,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'crystal', 'caves'],
  'home_rank': 84,
  'image_path': '/static/images/content/012-walmart-has-the-lowest-price-on-a-geforce-rtx-5070-prebuilt-gaming-pc-.jpg'},
 {'slug': 'donkey-kong-64',
  'source_path': '/wikis/donkey-kong-64',
  'title': 'Donkey Kong 64 Guide',
  'description': "IGN's current wiki coverage for Donkey Kong 64 Guide, with walkthrough notes, "
                 'tracking steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Virginia Glaze',
  'published_at': '2026-06-26T18:31:00Z',
  'score': None,
  'comments_count': 240,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'donkey', 'kong'],
  'home_rank': 85,
  'image_path': '/static/images/content/013-project-hail-mary-streaming-release-date-prime-video.jpg'},
 {'slug': 'crystal-caves-tiny-kong-walkthrough',
  'source_path': '/wikis/donkey-kong-64/Crystal_Caves_Tiny_Kong_Walkthrough',
  'title': 'Crystal Caves Tiny Kong Walkthrough',
  'description': "IGN's current wiki coverage for Crystal Caves Tiny Kong Walkthrough, with "
                 'walkthrough notes, tracking steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Eric Song',
  'published_at': '2026-06-26T16:31:00Z',
  'score': None,
  'comments_count': 17,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'crystal', 'caves', 'tiny', 'kong', 'walkthrough'],
  'home_rank': 86,
  'image_path': '/static/images/content/014-whats-new-on-hbo-max-july-2026.jpg'},
 {'slug': 'crystal-caves-lanky-kong-walkthrough',
  'source_path': '/wikis/donkey-kong-64/Crystal_Caves_Lanky_Kong_Walkthrough',
  'title': 'Crystal Caves Lanky Kong Walkthrough',
  'description': "IGN's current wiki coverage for Crystal Caves Lanky Kong Walkthrough, with "
                 'walkthrough notes, tracking steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Daemon Hatfield',
  'published_at': '2026-06-26T14:31:00Z',
  'score': None,
  'comments_count': 34,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'crystal', 'caves', 'lanky', 'kong', 'walkthrough'],
  'home_rank': 87,
  'image_path': '/static/images/content/015-whats-new-on-amazon-prime-video-july-2026.jpg'},
 {'slug': 'secrets-and-unlocks',
  'source_path': '/wikis/star-fox/Secrets_and_Unlocks',
  'title': 'Secrets and Unlocks',
  'description': "IGN's current wiki coverage for Secrets and Unlocks, with walkthrough notes, "
                 'tracking steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Michael Higham',
  'published_at': '2026-06-26T12:31:00Z',
  'score': None,
  'comments_count': 51,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'secrets', 'unlocks'],
  'home_rank': 88,
  'image_path': '/static/images/content/016-whats-new-on-netflix-july-2026.jpg'},
 {'slug': 'star-fox',
  'source_path': '/wikis/star-fox',
  'title': 'Star Fox Guide',
  'description': "IGN's current wiki coverage for Star Fox Guide, with walkthrough notes, tracking "
                 'steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Jada Griffin',
  'published_at': '2026-06-26T10:31:00Z',
  'score': None,
  'comments_count': 68,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'star', 'fox'],
  'home_rank': 89,
  'image_path': '/static/images/content/017-obsession-digital-streaming-4k-blu-ray.png'},
 {'slug': 'stage-list',
  'source_path': '/wikis/rhythm-heaven-groove/Stage_List',
  'title': 'Stage List',
  'description': "IGN's current wiki coverage for Stage List, with walkthrough notes, tracking "
                 'steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Nico Vergara',
  'published_at': '2026-06-26T08:31:00Z',
  'score': None,
  'comments_count': 85,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'stage', 'list'],
  'home_rank': 90,
  'image_path': '/static/images/content/018-whats-new-on-apple-tv-july-2026.jpg'},
 {'slug': 'rhythm-heaven-groove',
  'source_path': '/wikis/rhythm-heaven-groove',
  'title': 'Rhythm Heaven Groove Guide',
  'description': "IGN's current wiki coverage for Rhythm Heaven Groove Guide, with walkthrough "
                 'notes, tracking steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Wesley Yin-Poole',
  'published_at': '2026-06-26T06:31:00Z',
  'score': None,
  'comments_count': 102,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'rhythm', 'heaven', 'groove'],
  'home_rank': 91,
  'image_path': '/static/images/content/019-the-super-mario-galaxy-movie-streaming-release-date-peacock.jpg'},
 {'slug': 'minecraft',
  'source_path': '/wikis/minecraft',
  'title': 'Minecraft Guide',
  'description': "IGN's current wiki coverage for Minecraft Guide, with walkthrough notes, "
                 'tracking steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Carlos Morales',
  'published_at': '2026-06-26T04:31:00Z',
  'score': None,
  'comments_count': 119,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'minecraft'],
  'home_rank': 92,
  'image_path': '/static/images/content/020-whats-new-on-disney-plus-july-2026.jpg'},
 {'slug': 'dress-to-impress',
  'source_path': '/wikis/dress-to-impress',
  'title': 'Dress To Impress Guide',
  'description': "IGN's current wiki coverage for Dress To Impress Guide, with walkthrough notes, "
                 'tracking steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Danielle Abraham',
  'published_at': '2026-06-26T02:31:00Z',
  'score': None,
  'comments_count': 136,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'dress', 'impress'],
  'home_rank': 93,
  'image_path': '/static/images/content/021-most-anticipated-tv-shows-to-stream-in-july-2026.jpg'},
 {'slug': 'fortnite',
  'source_path': '/wikis/fortnite',
  'title': 'Fortnite Guide',
  'description': "IGN's current wiki coverage for Fortnite Guide, with walkthrough notes, tracking "
                 'steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Will Borger',
  'published_at': '2026-06-26T00:31:00Z',
  'score': None,
  'comments_count': 153,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'fortnite'],
  'home_rank': 94,
  'image_path': '/static/images/content/022-marvel-rivals-fans-think-the-new-captain-america-skin-is-a-mod-but-its.png'},
 {'slug': 'valorant',
  'source_path': '/wikis/valorant',
  'title': 'Valorant Guide',
  'description': "IGN's current wiki coverage for Valorant Guide, with walkthrough notes, tracking "
                 'steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Scott White',
  'published_at': '2026-06-25T22:31:00Z',
  'score': None,
  'comments_count': 170,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'valorant'],
  'home_rank': 95,
  'image_path': '/static/images/content/023-people-are-worried-theyll-only-see-half-of-the-odyssey-if-they-miss-ou.png'},
 {'slug': 'rocket-league',
  'source_path': '/wikis/rocket-league',
  'title': 'Rocket League Guide',
  'description': "IGN's current wiki coverage for Rocket League Guide, with walkthrough notes, "
                 'tracking steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Luke Reilly',
  'published_at': '2026-06-25T20:31:00Z',
  'score': None,
  'comments_count': 187,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'rocket', 'league'],
  'home_rank': 96,
  'image_path': '/static/images/content/024-the-view-from-japan-playstations-push-for-an-all-digital-future-raises.jpg'},
 {'slug': 'counter-strike-2',
  'source_path': '/wikis/counter-strike-2',
  'title': 'Counter-Strike 2 Guide',
  'description': "IGN's current wiki coverage for Counter-Strike 2 Guide, with walkthrough notes, "
                 'tracking steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Matt Purslow',
  'published_at': '2026-06-25T18:31:00Z',
  'score': None,
  'comments_count': 204,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'counter', 'strike'],
  'home_rank': 97,
  'image_path': '/static/images/content/025-significant-pay-rises-offered-by-professor-layton-studio-if-you-correc.jpg'},
 {'slug': '1-speed-keyboard-escape-roblox',
  'source_path': '/wikis/1-speed-keyboard-escape-roblox',
  'title': '+1 Speed Keyboard Escape [Roblox] Guide',
  'description': "IGN's current wiki coverage for +1 Speed Keyboard Escape [Roblox] Guide, with "
                 'walkthrough notes, tracking steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Sarah Thwaites',
  'published_at': '2026-06-25T16:31:00Z',
  'score': None,
  'comments_count': 221,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'speed', 'keyboard', 'escape', 'roblox'],
  'home_rank': 98,
  'image_path': '/static/images/content/026-copilot-pc-buying-guide-windows-11-worth-it.jpg'},
 {'slug': 'red-dead-redemption-2',
  'source_path': '/wikis/red-dead-redemption-2',
  'title': 'Red Dead Redemption 2 Guide',
  'description': "IGN's current wiki coverage for Red Dead Redemption 2 Guide, with walkthrough "
                 'notes, tracking steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Jesse Schedeen',
  'published_at': '2026-06-25T14:31:00Z',
  'score': None,
  'comments_count': 238,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'red', 'dead', 'redemption'],
  'home_rank': 99,
  'image_path': '/static/images/content/027-scuf-instinct-pro-xbox-controller-five-year-restrospective.jpg'},
 {'slug': 'hogwarts-legacy',
  'source_path': '/wikis/hogwarts-legacy',
  'title': 'Hogwarts Legacy Guide',
  'description': "IGN's current wiki coverage for Hogwarts Legacy Guide, with walkthrough notes, "
                 'tracking steps, and related guide links.',
  'section_slug': 'guides',
  'content_type': 'guide',
  'author': 'Tom Phillips',
  'published_at': '2026-06-25T12:31:00Z',
  'score': None,
  'comments_count': 15,
  'duration': None,
  'platforms': ['Nintendo Switch 2', 'PC'],
  'tags': ['guides', 'guide', 'hogwarts', 'legacy'],
  'home_rank': 100,
  'image_path': '/static/images/content/028-pokemon-tcg-30th-celebration-product-lineup.png'},
 {'slug': 'iphone-gaming-controller-buying-guide-2026',
  'source_path': '/articles/iphone-gaming-controller-buying-guide-2026',
  'title': 'Best iPhone and Android Controllers for Cloud Gaming in 2026',
  'description': "IGN's mobile coverage compares Backbone, Razer, and console-style controllers "
                 'for iOS and Android cloud gaming sessions.',
  'section_slug': 'games',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-06-25T10:31:00Z',
  'score': None,
  'comments_count': 54,
  'duration': None,
  'platforms': ['iOS', 'Android', 'Mobile'],
  'tags': ['mobile', 'article', 'ios', 'android', 'cloud', 'gaming', 'controller'],
  'home_rank': 101,
  'image_path': '/static/images/content/026-copilot-pc-buying-guide-windows-11-worth-it.jpg'},
 {'slug': 'pokemon-go-summer-event-ios-android-bonuses',
  'source_path': '/articles/pokemon-go-summer-event-ios-android-bonuses',
  'title': 'Pokémon Go Summer Event Adds New Mobile Bonuses for iOS and Android',
  'description': "IGN's mobile news desk tracks the latest Pokémon Go event bonuses, raids, and "
                 'limited-time rewards for phone players.',
  'section_slug': 'games',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-06-25T08:31:00Z',
  'score': None,
  'comments_count': 71,
  'duration': None,
  'platforms': ['iOS', 'Android', 'Mobile'],
  'tags': ['mobile', 'article', 'pokemon', 'go', 'ios', 'android', 'event'],
  'home_rank': 102,
  'image_path': '/static/images/content/011-pokemon-tcg-first-partner-illustration-collection-series-2-is-back-in-.png'},
 {'slug': 'netflix-games-mobile-lineup-july-2026',
  'source_path': '/articles/netflix-games-mobile-lineup-july-2026',
  'title': 'Netflix Games Reveals Its July Mobile Lineup',
  'description': "IGN's mobile category rounds up the latest Android and iOS releases coming to "
                 'Netflix Games this month.',
  'section_slug': 'tv',
  'content_type': 'article',
  'author': 'IGN Staff',
  'published_at': '2026-06-25T06:31:00Z',
  'score': None,
  'comments_count': 38,
  'duration': None,
  'platforms': ['iOS', 'Android', 'Mobile'],
  'tags': ['mobile', 'article', 'netflix', 'games', 'ios', 'android'],
  'home_rank': 103,
  'image_path': '/static/images/content/016-whats-new-on-netflix-july-2026.jpg'},
 {'slug': 'minions-monsters-review',
  'source_path': '/articles/minions-monsters-review',
  'title': 'Minions & Monsters Review',
  'description': "IGN's movie review weighs the animated sequel's visual energy, comedy timing, "
                 'and family-audience appeal.',
  'section_slug': 'movies',
  'content_type': 'review',
  'author': 'Carlos Morales',
  'published_at': '2026-06-25T04:31:00Z',
  'score': 7,
  'comments_count': 92,
  'duration': None,
  'platforms': [],
  'tags': ['movies', 'review', 'minions', 'monsters', 'animation'],
  'home_rank': 104,
  'image_path': '/static/images/content/002-minions-monsters-review.jpg'},
 {'slug': 'the-super-mario-galaxy-movie-review',
  'source_path': '/articles/the-super-mario-galaxy-movie-review',
  'title': 'The Super Mario Galaxy Movie Review',
  'description': "IGN's movie review checks whether the Mushroom Kingdom's space adventure keeps "
                 'its platforming charm on the big screen.',
  'section_slug': 'movies',
  'content_type': 'review',
  'author': 'Jesse Schedeen',
  'published_at': '2026-06-25T02:31:00Z',
  'score': 8,
  'comments_count': 116,
  'duration': None,
  'platforms': [],
  'tags': ['movies', 'review', 'mario', 'galaxy', 'nintendo'],
  'home_rank': 105,
  'image_path': '/static/images/content/019-the-super-mario-galaxy-movie-streaming-release-date-peacock.jpg'},
 {'slug': 'obsession-4k-blu-ray-review',
  'source_path': '/articles/obsession-4k-blu-ray-review',
  'title': 'Obsession 4K Blu-ray Review',
  'description': "IGN's movie review evaluates the thriller restoration, feature set, and whether "
                 'the new disc is worth adding to a collector shelf.',
  'section_slug': 'movies',
  'content_type': 'review',
  'author': 'Scott White',
  'published_at': '2026-06-25T00:31:00Z',
  'score': 8,
  'comments_count': 64,
  'duration': None,
  'platforms': [],
  'tags': ['movies', 'review', 'obsession', '4k', 'blu-ray'],
  'home_rank': 106,
  'image_path': '/static/images/content/017-obsession-digital-streaming-4k-blu-ray.png'},
 {'slug': 'turtle-beach-stealth-pro-ii-review',
  'source_path': '/articles/turtle-beach-stealth-pro-ii-review',
  'title': 'Turtle Beach Stealth Pro II Review',
  'description': "IGN's tech review tests microphone clarity, battery life, PC compatibility, "
                 'console support, and long-session comfort.',
  'section_slug': 'reviews',
  'content_type': 'review',
  'author': 'Eric Song',
  'published_at': '2026-06-24T22:31:00Z',
  'score': 8,
  'comments_count': 83,
  'duration': None,
  'platforms': ['PC', 'PlayStation 5', 'Xbox Series X/S'],
  'tags': ['tech', 'hardware', 'review', 'headset', 'pc', 'audio'],
  'home_rank': 107,
  'image_path': '/static/images/content/016-turtle-beach-stealth-pro-ii-review.jpg'},
 {'slug': 'corsair-one-a600-review',
  'source_path': '/articles/corsair-one-a600-review',
  'title': 'Corsair One A600 Review',
  'description': "IGN's tech review benchmarks the compact gaming PC's RTX performance, thermals, "
                 'ports, and upgrade tradeoffs.',
  'section_slug': 'reviews',
  'content_type': 'review',
  'author': 'Michael Higham',
  'published_at': '2026-06-24T20:31:00Z',
  'score': 9,
  'comments_count': 109,
  'duration': None,
  'platforms': ['PC'],
  'tags': ['tech', 'hardware', 'review', 'corsair', 'pc', 'rtx'],
  'home_rank': 108,
  'image_path': '/static/images/content/017-corsair-one-a600-review.jpg'},
 {'slug': 'nex-playground-review',
  'source_path': '/articles/nex-playground-review',
  'title': 'Nex Playground Review',
  'description': "IGN's tech review looks at motion controls, family games, setup friction, and "
                 'how the camera hardware handles small living rooms.',
  'section_slug': 'reviews',
  'content_type': 'review',
  'author': 'Danielle Abraham',
  'published_at': '2026-06-24T18:31:00Z',
  'score': 7,
  'comments_count': 58,
  'duration': None,
  'platforms': ['PC'],
  'tags': ['tech', 'hardware', 'review', 'nex', 'playground', 'camera'],
  'home_rank': 109,
  'image_path': '/static/images/content/018-nex-playground-review.jpg'}]
